### ISSUE TITLE
[LLVM 15] Getting invalid-symbol-name-offset while linking with LLD

### ISSUE THREAD

**Issue by Panchajanya1999** [ClangBuiltLinux/linux#1578] opened 2022-02-03 19:12 UTC
Error -

```
LTO     vmlinux.o
ld.lld: error: built-in.o(arch/arm64/lib/lib-ksyms.o): invalid symbol name offset
```

Kernel Source - https://github.com/Panchajanya1999/msm-4.14
LLVM tip - https://github.com/llvm/llvm-project/commit/36c36c1e

Build command -
```
MAKE+=(
			CROSS_COMPILE=aarch64-linux-gnu- \
			CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
			CC=clang \
			AR=llvm-ar \
			OBJDUMP=llvm-objdump \
			STRIP=llvm-strip \
			NM=llvm-nm \
			OBJCOPY=llvm-objcopy \
			LD=ld.lld
)
make -kj8 O=out \
		V=0 \
		"${MAKE[@]}"
```
Full log is available at - https://cloud.drone.io/Panchajanya1999/msm-4.14/388/1/2

**Comment by nathanchance** [comment] 2022-02-03 19:34
Can confirm.

```
$ make -skj"$(nproc)" AR=llvm-ar ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LD=ld.lld NM=llvm-nm O=build OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip mrproper vendor/violet-perf_defconfig all
...
ld.lld: error: built-in.o(arch/arm64/lib/lib-ksyms.o): invalid symbol name offset
...

$ clang --version | head -1
ClangBuiltLinux clang version 15.0.0 (https://github.com/llvm/llvm-project 4a6c9b56866517cb001bc4837c8470f090881f45)
```

This reproduces without `CONFIG_LTO_CLANG=y`.

I don't see this at https://github.com/llvm/llvm-project/commit/e64feaf00fd3b42c5820da556e60dd575f98cbe5.

I'll bisect LLVM once I am done investigating another issue.

**Comment by nickdesaulniers** [comment] 2022-02-03 19:35
cc @MaskRay 

https://github.com/llvm/llvm-project/blob/607ffa5515b9cd9c9c951dacbe4c403b52aa6bdb/lld/ELF/InputFiles.cpp#L1056-L1057

It sounds like someone is producing a bad object file (arch/arm64/lib/lib-ksyms.o) that has a symbol with whose name isn't in the symbol table.

@Panchajanya1999 do you have `CONFIG_TRIM_UNUSED_KSYMS` set?

**Comment by Panchajanya1999** [comment] 2022-02-03 19:51
> cc @MaskRay
> 
> https://github.com/llvm/llvm-project/blob/607ffa5515b9cd9c9c951dacbe4c403b52aa6bdb/lld/ELF/InputFiles.cpp#L1056-L1057
> 
> It sounds like someone is producing a bad object file (arch/arm64/lib/lib-ksyms.o) that has a symbol with whose name isn't in the symbol table.
> 
> @Panchajanya1999 do you have `CONFIG_TRIM_UNUSED_KSYMS` set?

I don't have this config.

**Comment by nathanchance** [comment] 2022-02-03 22:01
```
0c3704fdbd901e5f51acf11a85278bf9214ae7b2 is the first bad commit
commit 0c3704fdbd901e5f51acf11a85278bf9214ae7b2
Author: Fangrui Song <i@maskray.me>
Date:   Tue Feb 1 10:10:22 2022 -0800

    [ELF] Deduplicate names of local symbols only with -O2

    The deduplication requires a DenseMap of the same size of the local part of
    .strtab . I optimized it in e20544543478b259eb09fa0a253d4fb1a5525d9e but it is
    still quite slow.

    For Release build of clang, deduplication makes .strtab 1.1% smaller and makes the link 3% slower.
    For chrome, deduplication makes .strtab 0.1% smaller and makes the link 6% slower.

    I suggest that we only perform the optimization with -O2 (default is -O1).
    Not deduplicating local symbol names will simplify parallel symbol table write.

    Reviewed By: peter.smith

    Differential Revision: https://reviews.llvm.org/D118577

 lld/ELF/SyntheticSections.cpp |  7 +++++--
 lld/docs/ReleaseNotes.rst     |  3 +++
 lld/test/ELF/strtab-dedup.s   | 33 +++++++++++++++++++++++++++++++++
 3 files changed, 41 insertions(+), 2 deletions(-)
 create mode 100644 lld/test/ELF/strtab-dedup.s
```

https://github.com/llvm/llvm-project/commit/0c3704fdbd901e5f51acf11a85278bf9214ae7b2

**Comment by nickdesaulniers** [comment] 2022-02-03 22:22
Is `-O2` being passed to the linker? :P (ie. an out of tree patch, @Panchajanya1999 )

**Comment by nathanchance** [comment] 2022-02-03 22:32
> Is `-O2` being passed to the linker? :P (ie. an out of tree patch, @Panchajanya1999 )

;)

https://github.com/Panchajanya1999/msm-4.14/commit/4a4ea24df22cf8419006f5f65745f12b5fcdace0

but in that case, shouldn't the above change be a no-op?

**Comment by nathanchance** [comment] 2022-02-03 22:42
I see `-O2` is added to all the `ld.lld` invocations... So I am a little confused as to why that change would make any difference here unless maybe there are some places on msm-4.14 where `clang` is being used for linking, which means we might need `-Wl,-O2` somewhere?

**Comment by nathanchance** [comment] 2022-02-03 22:49
Reverting that change fixes it for me at least:

```diff
diff --git a/Makefile b/Makefile
index c2a65e221..67629ff42 100644
--- a/Makefile
+++ b/Makefile
@@ -797,7 +797,6 @@ KBUILD_CFLAGS += $(call cc-disable-warning, unused-but-set-variable)
 endif

 ifeq ($(ld-name),lld)
-LDFLAGS += -O2
 LDFLAGS += -z norelro
 endif

```

**Comment by Panchajanya1999** [comment] 2022-02-04 05:36
> Reverting that change fixes it for me at least:
> 
> ```diff
> diff --git a/Makefile b/Makefile
> index c2a65e221..67629ff42 100644
> --- a/Makefile
> +++ b/Makefile
> @@ -797,7 +797,6 @@ KBUILD_CFLAGS += $(call cc-disable-warning, unused-but-set-variable)
>  endif
> 
>  ifeq ($(ld-name),lld)
> -LDFLAGS += -O2
>  LDFLAGS += -z norelro
>  endif
> ```

Someone on tg confirmed passing `--lto-O3` fixes it too. 

[edit] @dakkshesh just confirmed the same on k4.9 with full-LTO and `LDFLAGS += -O3`. He says thin-LTO is totally fine with `-O3` and he hasnt tried thinLTO with `-O2` yet.

**Comment by Panchajanya1999** [comment] 2022-02-04 06:13
I am thinking to setup LDFLAGS like this-
```
diff --git a/Makefile b/Makefile
index c2a65e221447..7e3005e4df73 100644
--- a/Makefile
+++ b/Makefile
@@ -797,7 +797,11 @@ KBUILD_CFLAGS += $(call cc-disable-warning, unused-but-set-variable)
 endif

 ifeq ($(ld-name),lld)
+ifdef CONFIG_LTO_CLANG
+LDFLAGS += --lto-O2
+else
 LDFLAGS += -O2
+endif
 LDFLAGS += -z norelro
 endif
```

**Comment by Panchajanya1999** [comment] 2022-02-04 09:11
This commit fixes this issue.
https://github.com/Panchajanya1999/msm-4.14/commit/d0110f4b86536b08e6c7567c2e8558b5284214ee

Cc @nathanchance @nickdesaulniers

**Comment by nathanchance** [comment] 2022-02-04 16:50
> This commit fixes this issue. [Panchajanya1999/msm-4.14@d0110f4](https://github.com/Panchajanya1999/msm-4.14/commit/d0110f4b86536b08e6c7567c2e8558b5284214ee)

> Non-LTO isn't affected by this error.

I was able to reproduce this without LTO.

```diff
$ git diff HEAD
diff --git a/arch/arm64/configs/vendor/violet-perf_defconfig b/arch/arm64/configs/vendor/violet-perf_defconfig
index e1d45b73b..d4ab032e5 100644
--- a/arch/arm64/configs/vendor/violet-perf_defconfig
+++ b/arch/arm64/configs/vendor/violet-perf_defconfig
@@ -271,16 +271,11 @@ CONFIG_CC_STACKPROTECTOR=y
 # CONFIG_CC_STACKPROTECTOR_REGULAR is not set
 CONFIG_CC_STACKPROTECTOR_STRONG=y
 CONFIG_THIN_ARCHIVES=y
-CONFIG_LTO=y
+# CONFIG_LTO is not set
 CONFIG_ARCH_SUPPORTS_LTO_CLANG=y
 CONFIG_ARCH_SUPPORTS_THINLTO=y
-# CONFIG_THINLTO is not set
-# CONFIG_LTO_NONE is not set
-CONFIG_LTO_CLANG=y
-CONFIG_CFI=y
-# CONFIG_CFI_PERMISSIVE is not set
-CONFIG_CFI_CLANG=y
-# CONFIG_CFI_CLANG_SHADOW is not set
+CONFIG_LTO_NONE=y
+# CONFIG_LTO_CLANG is not set
 CONFIG_ARCH_SUPPORTS_SHADOW_CALL_STACK=y
 # CONFIG_ROP_PROTECTION_NONE is not set
 CONFIG_SHADOW_CALL_STACK=y
@@ -681,6 +676,7 @@ CONFIG_ARM64_UAO=y
 # CONFIG_ARM64_PMEM is not set
 CONFIG_RELOCATABLE=y
 CONFIG_RANDOMIZE_BASE=y
+CONFIG_RANDOMIZE_MODULE_REGION_FULL=y

 #
 # Boot options

$ make -skj"$(nproc)" AR=llvm-ar ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LD=ld.lld NM=llvm-nm O=build OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip vendor/violet-perf_defconfig all
...
ld.lld: error: built-in.o(arch/arm64/lib/lib-ksyms.o): invalid symbol name offset
...
```

**Comment by MaskRay** [comment] 2022-02-04 17:31
The linker option -O2 is different from the compiler driver option -O2. (https://maskray.me/blog/2020-11-15-explain-gnu-linker-options#o)

Using -O2 for ld.lld is not recommended. It just makes the link quite slow while decreasing the size only a tiny bit. -O2 does not change the LTO optimization level. It is different from --lto-O2.

Failures in the absence of local symbol name deduplicating is just outright wrong and should be fixed.

**Comment by nathanchance** [comment] 2022-02-05 04:38
CI is now hitting this for [the `android-4.14` builds](https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/1797865035). [The `android-4.19` builds](https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/1797872551) are fine.

As far as I can tell, it does not look like `android-4.19` has [the `-O2` linker patch](https://android.googlesource.com/kernel/common/+/4a4ea24df22cf8419006f5f65745f12b5fcdace0) that I mentioned above. I'll double check that reverting that change fixes both broken Android builds on Monday. Given Fangrui's comment above and the fact that it is not present in later Android branches nor upstream, should we just revert that patch if it resolves the issue?

**Comment by nathanchance** [comment] 2022-02-05 17:10
I can confirm that reverting https://android.googlesource.com/kernel/common/+/4a4ea24df22cf8419006f5f65745f12b5fcdace0 fixes the issues seen in CI.

**Comment by Panchajanya1999** [comment] 2022-02-05 17:30
> I can confirm that reverting https://android.googlesource.com/kernel/common/+/4a4ea24df22cf8419006f5f65745f12b5fcdace0 fixes the issues seen in CI.

Yeah, reverting it just passed here too (locally).

**Comment by nathanchance** [comment] 2022-02-10 22:50
> Failures in the absence of local symbol name deduplicating is just outright wrong and should be fixed.

@MaskRay This particular kernel branch links with `-O2`, so shouldn't https://github.com/llvm/llvm-project/commit/0c3704fdbd901e5f51acf11a85278bf9214ae7b2 just be a no-op for it? It clearly isn't, which I assume means that it has something to do with the first two hunks of that commit, right?

```diff
diff --git a/lld/ELF/SyntheticSections.cpp b/lld/ELF/SyntheticSections.cpp
index 36a226c20576..75fb51eb33f5 100644
--- a/lld/ELF/SyntheticSections.cpp
+++ b/lld/ELF/SyntheticSections.cpp
@@ -1230,7 +1230,8 @@ StringTableSection::StringTableSection(StringRef name, bool dynamic)
     : SyntheticSection(dynamic ? (uint64_t)SHF_ALLOC : 0, SHT_STRTAB, 1, name),
       dynamic(dynamic) {
   // ELF string tables start with a NUL byte.
-  addString("");
+  strings.push_back("");
+  size = 1;
 }

 // Adds a string to the string table. If `hashIt` is true we hash and check for
@@ -1243,6 +1244,8 @@ unsigned StringTableSection::addString(StringRef s, bool hashIt) {
     if (!r.second)
       return r.first->second;
   }
+  if (s.empty())
+    return 0;
   unsigned ret = this->size;
   this->size = this->size + s.size() + 1;
   strings.push_back(s);
```

Other kernels do not have a problem, as they link with the default of `-O1`, which presumably means that the above diff is safe for `-O1` but not `-O2`.

I can trivially reproduce this:

```
$ cat lib-ksyms.o.lds
EXTERN(clear_page_rep)
EXTERN(clear_page_orig)
EXTERN(clear_page_erms)
EXTERN(copy_page)
EXTERN(copy_user_generic_unrolled)
EXTERN(copy_user_generic_string)
EXTERN(copy_user_enhanced_fast_string)
EXTERN(__copy_user_nocache)
EXTERN(x86_family)
EXTERN(x86_model)
EXTERN(x86_stepping)
EXTERN(csum_partial)
EXTERN(ip_compute_csum)
EXTERN(csum_partial_copy_from_user)
EXTERN(csum_partial_copy_to_user)
EXTERN(csum_partial_copy_nocheck)
EXTERN(csum_ipv6_magic)
EXTERN(__delay)
EXTERN(__const_udelay)
EXTERN(__udelay)
EXTERN(__ndelay)
EXTERN(__get_user_1)
EXTERN(__get_user_2)
EXTERN(__get_user_4)
EXTERN(__get_user_8)
EXTERN(memcpy)
EXTERN(__memcpy)
EXTERN(memcpy_mcsafe_unrolled)
EXTERN(__memmove)
EXTERN(memmove)
EXTERN(memset)
EXTERN(__memset)
EXTERN(__put_user_1)
EXTERN(__put_user_2)
EXTERN(__put_user_4)
EXTERN(__put_user_8)
EXTERN(__x86_indirect_thunk_rax)
EXTERN(__x86_indirect_thunk_rbx)
EXTERN(__x86_indirect_thunk_rcx)
EXTERN(__x86_indirect_thunk_rdx)
EXTERN(__x86_indirect_thunk_rsi)
EXTERN(__x86_indirect_thunk_rdi)
EXTERN(__x86_indirect_thunk_rbp)
EXTERN(__x86_indirect_thunk_r8)
EXTERN(__x86_indirect_thunk_r9)
EXTERN(__x86_indirect_thunk_r10)
EXTERN(__x86_indirect_thunk_r11)
EXTERN(__x86_indirect_thunk_r12)
EXTERN(__x86_indirect_thunk_r13)
EXTERN(__x86_indirect_thunk_r14)
EXTERN(__x86_indirect_thunk_r15)
EXTERN(copy_from_user_nmi)
EXTERN(__clear_user)
EXTERN(clear_user)
EXTERN(arch_wb_cache_pmem)
EXTERN(memcpy_flushcache)

$ echo | clang -no-integrated-as -fno-PIE -m64 -Wa,-gdwarf-2 -c -o lib_exports.o -x assembler -

$ ld.lld -m elf_x86_64 -z max-page-size=0x200000 -O2 -r -o lib-ksyms.o -T lib-ksyms.o.lds lib_exports.o

$ ld.lld -m elf_x86_64 -z max-page-size=0x200000 -O2 -r -o vmlinux.o --whole-archive lib-ksyms.o
ld.lld: error: lib-ksyms.o: invalid symbol name offset
```

The whole EXTERN thing comes from https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/scripts/Makefile.build?h=linux-5.4.y#n411, which was eliminated in 5.7 by https://git.kernel.org/linus/7273ad2b08f8ac9563579d16a3cf528857b26f49, in response to https://github.com/ClangBuiltLinux/linux/issues/515.

**Closed as completed** 2022-02-18 22:54 UTC
Labels: [ARCH] arm64, [TOOL] lld, [BUG] llvm (main), [FIXED][LLVM] main

**Comment by MaskRay** [comment] 2022-02-18 23:38
Sorry for the belated response. The  .symtab deduplication regression in -r links was due to https://reviews.llvm.org/D118577
 `addString("");`. It has been fixed in main branch.

release/14.x has llvm/llvm-project@42a797ef011bd920bb7b781a752b925362b9754c to fix it.

**Comment by nathanchance** [comment] 2022-02-18 23:51
Thanks a lot!
