### ISSUE TITLE
arm32 allyesconfig build fails to link

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#288] opened 2018-12-10 21:30 UTC
```
arm-linux-gnueabi-ld: arch/arm/kernel/irq.o: in function `arch_show_interrupts':
irq.c:(.text+0x14): undefined reference to `mcount'
arm-linux-gnueabi-ld: arch/arm/kernel/irq.o: in function `handle_IRQ':
irq.c:(.text+0x7c): undefined reference to `mcount'
arm-linux-gnueabi-ld: arch/arm/kernel/irq.o: in function `migrate_irqs':
irq.c:(.text+0xa8): undefined reference to `mcount'
arm-linux-gnueabi-ld: arch/arm/kernel/irq.o: in function `migrate_one_irq':
irq.c:(.text+0x208): undefined reference to `mcount'
arm-linux-gnueabi-ld: arch/arm/kernel/irq.o: in function `asm_do_IRQ':
irq.c:(.irqentry.text+0x10): undefined reference to `mcount'
arm-linux-gnueabi-ld: arch/arm/kernel/irq.o:irq.c:(.init.text+0x8): more undefined references to `mcount' follow
make: *** [Makefile:1047: vmlinux] Error 1
```

Disabling `CONFIG_FTRACE` allows the kernel to link successfully, I haven't done any more triage than that.

**Comment by nickdesaulniers** [comment] 2018-12-10 22:39
dupe of #35

**Closed by nickdesaulniers** 2018-12-10 22:39 UTC
Labels: [ARCH] arm32, [BUG] Untriaged

**Comment by nathanchance** [comment] 2018-12-10 22:50
Whoops, thank you!
