### ISSUE TITLE
clang crash compiling binder.o for 32b x86

### ISSUE THREAD

**Issue by cwhuang** [ClangBuiltLinux/linux#22] opened 2018-06-26 07:30 UTC
I'm trying to build 32-bit x86 kernel from android-4.14 branch of AOSP
https://android.googlesource.com/kernel/common with
AOSP's prebuilt clang-4053586 (in the Oreo release):

make CC=clang HOSTCC=clang CLANG_TRIPLE=x86_64-linux-gnu- CROSS_COMPILE=x86_64-linux-androidkernel- bzImage modules

 I saw the errors. Not sure what it means.
....
  CC      kernel/events/core.o
  CC [M]  fs/cifs/netmisc.o
  CC      mm/frame_vector.o
  CC      mm/usercopy.o
/home/cwhuang/git/android-x86-8.1/kernel/kernel/events/core.c:520:16: error: invalid output size for constraint '=q'
        running_len = __this_cpu_read(running_sample_length);
                      ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:433:2: note: expanded from macro '__this_cpu_read'
        raw_cpu_read(pcp);                                              \
        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:407:28: note: expanded from macro 'raw_cpu_read'
#define raw_cpu_read(pcp)               __pcpu_size_call_return(raw_cpu_read_, pcp)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:308:23: note: expanded from macro '__pcpu_size_call_return'
        case 1: pscr_ret__ = stem##1(variable); break;                  \
                             ^
<scratch space>:262:1: note: expanded from here
raw_cpu_read_1
^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:394:30: note: expanded from macro 'raw_cpu_read_1'
#define raw_cpu_read_1(pcp)             percpu_from_op("mov", pcp)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:189:15: note: expanded from macro 'percpu_from_op'
                    : "=q" (pfo_ret__)                  \
                            ^
/home/cwhuang/git/android-x86-8.1/kernel/kernel/events/core.c:520:16: error: invalid output size for constraint '=q'
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:433:2: note: expanded from macro '__this_cpu_read'
        raw_cpu_read(pcp);                                              \
        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:407:28: note: expanded from macro 'raw_cpu_read'
#define raw_cpu_read(pcp)               __pcpu_size_call_return(raw_cpu_read_, pcp)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:309:23: note: expanded from macro '__pcpu_size_call_return'
        case 2: pscr_ret__ = stem##2(variable); break;                  \
                             ^
<scratch space>:264:1: note: expanded from here
raw_cpu_read_2
^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:395:30: note: expanded from macro 'raw_cpu_read_2'
#define raw_cpu_read_2(pcp)             percpu_from_op("mov", pcp)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:189:15: note: expanded from macro 'percpu_from_op'
                    : "=q" (pfo_ret__)                  \
                            ^
/home/cwhuang/git/android-x86-8.1/kernel/kernel/events/core.c:520:16: error: invalid output size for constraint '=q'
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:433:2: note: expanded from macro '__this_cpu_read'
        raw_cpu_read(pcp);                                              \
        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:407:28: note: expanded from macro 'raw_cpu_read'
#define raw_cpu_read(pcp)               __pcpu_size_call_return(raw_cpu_read_, pcp)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:310:23: note: expanded from macro '__pcpu_size_call_return'
        case 4: pscr_ret__ = stem##4(variable); break;                  \
                             ^
<scratch space>:264:1: note: expanded from here
raw_cpu_read_4
^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:396:30: note: expanded from macro 'raw_cpu_read_4'
#define raw_cpu_read_4(pcp)             percpu_from_op("mov", pcp)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:189:15: note: expanded from macro 'percpu_from_op'
                    : "=q" (pfo_ret__)                  \
                            ^
/home/cwhuang/git/android-x86-8.1/kernel/kernel/events/core.c:523:2: error: invalid input size for constraint 'qi'
        __this_cpu_write(running_sample_length, running_len);
        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:439:2: note: expanded from macro '__this_cpu_write'
        raw_cpu_write(pcp, val);                                        \
        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:408:34: note: expanded from macro 'raw_cpu_write'
#define raw_cpu_write(pcp, val)         __pcpu_size_call(raw_cpu_write_, pcp, val)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:364:11: note: expanded from macro '__pcpu_size_call'
                case 1: stem##1(variable, __VA_ARGS__);break;           \
                        ^
<scratch space>:264:1: note: expanded from here
raw_cpu_write_1
^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:398:35: note: expanded from macro 'raw_cpu_write_1'
#define raw_cpu_write_1(pcp, val)       percpu_to_op("mov", (pcp), val)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:102:15: note: expanded from macro 'percpu_to_op'
                    : "qi" ((pto_T__)(val)));           \
                            ^
/home/cwhuang/git/android-x86-8.1/kernel/kernel/events/core.c:523:2: error: invalid input size for constraint 'qi'
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:439:2: note: expanded from macro '__this_cpu_write'
        raw_cpu_write(pcp, val);                                        \
        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:408:34: note: expanded from macro 'raw_cpu_write'
#define raw_cpu_write(pcp, val)         __pcpu_size_call(raw_cpu_write_, pcp, val)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:365:11: note: expanded from macro '__pcpu_size_call'
                case 2: stem##2(variable, __VA_ARGS__);break;           \
                        ^
<scratch space>:264:1: note: expanded from here
raw_cpu_write_2
^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:399:35: note: expanded from macro 'raw_cpu_write_2'
#define raw_cpu_write_2(pcp, val)       percpu_to_op("mov", (pcp), val)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:102:15: note: expanded from macro 'percpu_to_op'
                    : "qi" ((pto_T__)(val)));           \
                            ^
/home/cwhuang/git/android-x86-8.1/kernel/kernel/events/core.c:523:2: error: invalid input size for constraint 'qi'
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:439:2: note: expanded from macro '__this_cpu_write'
        raw_cpu_write(pcp, val);                                        \
        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:408:34: note: expanded from macro 'raw_cpu_write'
#define raw_cpu_write(pcp, val)         __pcpu_size_call(raw_cpu_write_, pcp, val)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:366:11: note: expanded from macro '__pcpu_size_call'
                case 4: stem##4(variable, __VA_ARGS__);break;           \
                        ^
<scratch space>:264:1: note: expanded from here
raw_cpu_write_4
^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:400:35: note: expanded from macro 'raw_cpu_write_4'
#define raw_cpu_write_4(pcp, val)       percpu_to_op("mov", (pcp), val)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:102:15: note: expanded from macro 'percpu_to_op'
                    : "qi" ((pto_T__)(val)));           \
                            ^
/home/cwhuang/git/android-x86-8.1/kernel/kernel/events/core.c:3570:2: error: invalid input size for constraint 'qi'
        __this_cpu_inc(perf_throttled_seq);
        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:484:30: note: expanded from macro '__this_cpu_inc'
#define __this_cpu_inc(pcp)             __this_cpu_add(pcp, 1)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:445:2: note: expanded from macro '__this_cpu_add'
        raw_cpu_add(pcp, val);                                          \
        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:409:32: note: expanded from macro 'raw_cpu_add'
#define raw_cpu_add(pcp, val)           __pcpu_size_call(raw_cpu_add_, pcp, val)
                                        ^
note: (skipping 1 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
<scratch space>:185:1: note: expanded from here
raw_cpu_add_1
^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:401:34: note: expanded from macro 'raw_cpu_add_1'
#define raw_cpu_add_1(pcp, val)         percpu_add_op((pcp), val)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:147:16: note: expanded from macro 'percpu_add_op'
                            : "qi" ((pao_T__)(val)));                   \
                                    ^
/home/cwhuang/git/android-x86-8.1/kernel/kernel/events/core.c:3570:2: error: invalid input size for constraint 'qi'
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:484:30: note: expanded from macro '__this_cpu_inc'
#define __this_cpu_inc(pcp)             __this_cpu_add(pcp, 1)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:445:2: note: expanded from macro '__this_cpu_add'
        raw_cpu_add(pcp, val);                                          \
        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:409:32: note: expanded from macro 'raw_cpu_add'
#define raw_cpu_add(pcp, val)           __pcpu_size_call(raw_cpu_add_, pcp, val)
                                        ^
note: (skipping 1 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
<scratch space>:191:1: note: expanded from here
raw_cpu_add_2
^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:402:34: note: expanded from macro 'raw_cpu_add_2'
#define raw_cpu_add_2(pcp, val)         percpu_add_op((pcp), val)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:147:16: note: expanded from macro 'percpu_add_op'
                            : "qi" ((pao_T__)(val)));                   \
                                    ^
/home/cwhuang/git/android-x86-8.1/kernel/kernel/events/core.c:3570:2: error: invalid input size for constraint 'qi'
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:484:30: note: expanded from macro '__this_cpu_inc'
#define __this_cpu_inc(pcp)             __this_cpu_add(pcp, 1)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:445:2: note: expanded from macro '__this_cpu_add'
        raw_cpu_add(pcp, val);                                          \
        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:409:32: note: expanded from macro 'raw_cpu_add'
#define raw_cpu_add(pcp, val)           __pcpu_size_call(raw_cpu_add_, pcp, val)
                                        ^
note: (skipping 1 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
<scratch space>:191:1: note: expanded from here
raw_cpu_add_4
^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:403:34: note: expanded from macro 'raw_cpu_add_4'
#define raw_cpu_add_4(pcp, val)         percpu_add_op((pcp), val)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:147:16: note: expanded from macro 'percpu_add_op'
                            : "qi" ((pao_T__)(val)));                   \
                                    ^
  CC [M]  fs/btrfs/transaction.o
  CC      kernel/events/ring_buffer.o
/home/cwhuang/git/android-x86-8.1/kernel/kernel/events/core.c:7433:8: error: invalid output size for constraint '=q'
        seq = __this_cpu_read(perf_throttled_seq);
              ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:433:2: note: expanded from macro '__this_cpu_read'
        raw_cpu_read(pcp);                                              \
        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:407:28: note: expanded from macro 'raw_cpu_read'
#define raw_cpu_read(pcp)               __pcpu_size_call_return(raw_cpu_read_, pcp)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:308:23: note: expanded from macro '__pcpu_size_call_return'
        case 1: pscr_ret__ = stem##1(variable); break;                  \
                             ^
<scratch space>:11:1: note: expanded from here
raw_cpu_read_1
^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:394:30: note: expanded from macro 'raw_cpu_read_1'
#define raw_cpu_read_1(pcp)             percpu_from_op("mov", pcp)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:189:15: note: expanded from macro 'percpu_from_op'
                    : "=q" (pfo_ret__)                  \
                            ^
/home/cwhuang/git/android-x86-8.1/kernel/kernel/events/core.c:7433:8: error: invalid output size for constraint '=q'
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:433:2: note: expanded from macro '__this_cpu_read'
        raw_cpu_read(pcp);                                              \
        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:407:28: note: expanded from macro 'raw_cpu_read'
#define raw_cpu_read(pcp)               __pcpu_size_call_return(raw_cpu_read_, pcp)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:309:23: note: expanded from macro '__pcpu_size_call_return'
        case 2: pscr_ret__ = stem##2(variable); break;                  \
                             ^
<scratch space>:13:1: note: expanded from here
raw_cpu_read_2
^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:395:30: note: expanded from macro 'raw_cpu_read_2'
#define raw_cpu_read_2(pcp)             percpu_from_op("mov", pcp)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:189:15: note: expanded from macro 'percpu_from_op'
                    : "=q" (pfo_ret__)                  \
                            ^
/home/cwhuang/git/android-x86-8.1/kernel/kernel/events/core.c:7433:8: error: invalid output size for constraint '=q'
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:433:2: note: expanded from macro '__this_cpu_read'
        raw_cpu_read(pcp);                                              \
        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:407:28: note: expanded from macro 'raw_cpu_read'
#define raw_cpu_read(pcp)               __pcpu_size_call_return(raw_cpu_read_, pcp)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/include/linux/percpu-defs.h:310:23: note: expanded from macro '__pcpu_size_call_return'
        case 4: pscr_ret__ = stem##4(variable); break;                  \
                             ^
<scratch space>:13:1: note: expanded from here
raw_cpu_read_4
^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:396:30: note: expanded from macro 'raw_cpu_read_4'
#define raw_cpu_read_4(pcp)             percpu_from_op("mov", pcp)
                                        ^
/home/cwhuang/git/android-x86-8.1/kernel/arch/x86/include/asm/percpu.h:189:15: note: expanded from macro 'percpu_from_op'
                    : "=q" (pfo_ret__)                  \
                            ^
12 errors generated.

**Comment by gwelymernans** [comment] 2018-06-26 07:54
Could this be related to https://github.com/ClangBuiltLinux/linux/issues/3 ?

**Comment by cwhuang** [comment] 2018-06-26 09:07
Ah! Thank you. Yes, it seems to be the same bug as https://llvm.org/pr33587

**Comment by cwhuang** [comment] 2018-06-26 09:42
After applied the workaround patch from https://llvm.org/pr33587, it built further.
But it still failed:

[ 20% 2/10] /bin/bash -c "make -j4 -j\$(nproc) -l\$((\$(nproc)+2)) -C kernel O=/home/cwhuang/git/android-x86-8.1/out/target/product/x86/obj/kernel ARCH=x86 CROSS_COMPILE=\" x86_64-linux-androidkernel-\"  CC=clang HOSTCC=clang CLANG_TRIPLE=x86_64-linux-gnu- PATH=/home/cwhuang/git/android-x86-8.1/prebuilts/clang/host/linux-x86/clang-4053586/bin:\$PATH bzImage modules"
FAILED: /home/cwhuang/git/android-x86-8.1/out/target/product/x86/obj/kernel/arch/x86/boot/bzImage 
/bin/bash -c "make -j4 -j\$(nproc) -l\$((\$(nproc)+2)) -C kernel O=/home/cwhuang/git/android-x86-8.1/out/target/product/x86/obj/kernel ARCH=x86 CROSS_COMPILE=\" x86_64-linux-androidkernel-\"  CC=clang HOSTCC=clang CLANG_TRIPLE=x86_64-linux-gnu- PATH=/home/cwhuang/git/android-x86-8.1/prebuilts/clang/host/linux-x86/clang-4053586/bin:\$PATH bzImage modules"
make: Entering directory '/home/cwhuang/git/android-x86-8.1/kernel'
make[1]: Entering directory '/home/cwhuang/git/android-x86-8.1/out/target/product/x86/obj/kernel'
  CHK     include/config/kernel.release
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     scripts/mod/devicetable-offsets.h
  Using /home/cwhuang/git/android-x86-8.1/kernel as source for kernel
  CHK     include/generated/utsrelease.h
  CHK     include/generated/timeconst.h
  CHK     include/generated/bounds.h
  CHK     include/generated/asm-offsets.h
  CALL    /home/cwhuang/git/android-x86-8.1/kernel/scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  CHK     kernel/config_data.h
  CC      drivers/android/binder.o
  AR      drivers/auxdisplay/built-in.o
  CC [M]  drivers/auxdisplay/charlcd.o
  CC [M]  drivers/auxdisplay/panel.o
  CC      drivers/base/component.o
  AR      drivers/bcma/built-in.o
  CC [M]  drivers/bcma/main.o
  CC [M]  drivers/bcma/scan.o
  CC [M]  drivers/bcma/core.o
  CC      drivers/base/core.o
  CC [M]  drivers/bcma/sprom.o
clang.real: error: unable to execute command: Segmentation fault (core dumped)
clang.real: error: clang frontend command failed due to signal (use -v to see invocation)
Android clang version 5.0.300080  (based on LLVM 5.0.300080)
Target: i386--linux-gnu
Thread model: posix
InstalledDir: /home/cwhuang/git/android-x86-8.1/prebuilts/clang/host/linux-x86/clang-4053586/bin
clang.real: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
  CC [M]  drivers/bcma/driver_chipcommon.o
clang.real: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang.real: note: diagnostic msg: /tmp/binder-770459.c
clang.real: note: diagnostic msg: /tmp/binder-770459.sh
clang.real: note: diagnostic msg: 

********************
make[3]: *** [/home/cwhuang/git/android-x86-8.1/kernel/scripts/Makefile.build:358: drivers/android/binder.o] Error 254
make[2]: *** [/home/cwhuang/git/android-x86-8.1/kernel/scripts/Makefile.build:673: drivers/android] Error 2
make[2]: *** Waiting for unfinished jobs....
[binder-770459.c.txt](https://github.com/ClangBuiltLinux/linux/files/2136567/binder-770459.c.txt)
[binder-770459.sh.txt](https://github.com/ClangBuiltLinux/linux/files/2136568/binder-770459.sh.txt)

**Comment by nickdesaulniers** [comment] 2018-07-14 15:47
heh, yes @gwelymernans correctly identified that your first comment is a duplicate of issue #3.  Your second issue looks like clang itself is segfaulting (bad!).  I think it's crashing trying to compile drivers/bcma/sprom.o, but since you're compiling with `-j4`, I don't trust the output.

@cwhuang , can you please try just:

```sh
make <your special  flags> drivers/bcma/sprom.o
```

so just kbuild that one object file and see if that can reliably crash clang?

**Comment by nickdesaulniers** [comment] 2018-07-17 20:38
Sorry, looks like the crash is: `drivers/android/binder.o`?

**Comment by nickdesaulniers** [comment] 2018-07-17 20:44
Was there a backtrace, too?

**Comment by cwhuang** [comment] 2018-07-25 12:08
Sorry to reply late. I'm busy on other stuff recently.

Yes, the crash is drivers/android/binder.o. I made that file directly and it crashed every time.

**Comment by nickdesaulniers** [comment] 2018-08-27 23:12
Does not repro with 64b.

STR:
```
CONFIG_ANDROID=y
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDER_DEVICES="binder,hwbinder,vndbinder"
CONFIG_X86_32=y

$ make CC=clang -j46 drivers/android/binder.o
```

Filed llvm bug: https://llvm.org/pr38730

**Comment by nickdesaulniers** [comment] 2018-08-29 23:48
Besides clang crashing for extremely poorly defined input, it seems that no one is defining `BINDER_IPC_32BIT` for a 32b build.  Will look more into that later.

**Comment by nickdesaulniers** [comment] 2018-08-30 16:55
Note that commit 1190b4e38f97 ("ANDROID: binder: remove 32-bit binder interface.") partially removed support for 32b binder.  I will send a cleanup to remove `BINDER_IPC_32BIT`, and talk to maco@ about support.

**Comment by niravhdave** [comment] 2018-08-30 19:27
https://reviews.llvm.org/D51502

**Comment by nickdesaulniers** [comment] 2018-08-30 20:20
@cwhuang , can you please try enabling `ANDROID_BINDER_IPC_32BIT`? Note that it was removed in Linux `v4.18-rc1`.  I would also recommend reading the commit message to 1190b4e ("ANDROID: binder: remove 32-bit binder interface.") to understand the implications for Android P.

I think there's still an issue with `get_user` in `arch/x86/include/asm/uaccess.h` for 32b x86 with Clang, but am unsure of the correct fix.  The llvm bug filed shows that Clang is not happy with:

```c
register long long foo asm("edx");
```

My current understanding of the above is to "create a 64b variable, `foo`, that occupies at least the 32b register `edx` (and implicitly `ecx` for the upper 32b).  If that's correct, it sounds horribly poorly specified.  Clang should not crash, but we care less about poorly specified code.

GCC produces an unnamed (an thus non-disable-able) warning, but does produce working code: https://godbolt.org/z/uKQG0s

commit f69fa9a91f60 ("x86, doc: Update uaccess.h comment to reflect clang changes") and commit bdfc017eead9 ("x86, asm: Fix a compilation issue with clang") seem relevant.

Maybe, in the kernel, we might be able to do:
```diff
-         register __inttype(*(ptr)) __val_gu asm("%"_ASM_DX);            \       
+         register __inttype(*(ptr)) __val_gu;            \    
```

But I'm not sure if `edx` is part of the calling convention of `__get_user_%P4` or just a scratch or output register.

**Comment by cwhuang** [comment] 2018-09-05 09:16
@nickdesaulniers Thank you! I'm building LTS kernel 4.14.x. In 4.14.5x with ANDROID_BINDER_IPC_32BIT=y, it's buildable indeed. However, the commit "ANDROID: binder: remove 32-bit binder interface." has been picked to latest 4.14.x so the workaround is not applicable now.

**Comment by nickdesaulniers** [comment] 2018-09-05 23:36
It sounds like the 32b binder interface is no longer supported, so we will have to support the 64b interface, even on 32b hosts.

**Comment by nickdesaulniers** [comment] 2018-09-05 23:39
Commits 3578baaed and ff52c3b02b3f7 are also interesting for historical context.

**Comment by nickdesaulniers** [comment] 2018-09-13 20:56
Thanks @niravhdave ! https://reviews.llvm.org/rL342175

**Closed by nickdesaulniers** 2018-09-13 20:56 UTC
Labels: [BUG] llvm, [PATCH] Exists
