### ISSUE TITLE
undefined reference to __divdi3

### ISSUE THREAD

**Issue by bulwahn** [ClangBuiltLinux/linux#186] opened 2018-10-02 21:17 UTC
clang fails to properly link the kernel build with tinyconfig:

```
LD      vmlinux
ld: kernel/events/core.o: in function `perf_adjust_period':
core.c:(.text+0x5bb9): undefined reference to `__divdi3'
ld: mm/filemap.o: in function `filemap_fault':
filemap.c:(.text+0x1d25): undefined reference to `__divdi3'
ld: filemap.c:(.text+0x1f25): undefined reference to `__divdi3'
ld: mm/filemap.o: in function `filemap_map_pages':
filemap.c:(.text+0x213f): undefined reference to `__divdi3'
ld: mm/page-writeback.o: in function `balance_dirty_pages_ratelimited':
page-writeback.c:(.text+0xaf3): undefined reference to `__divdi3'
make: *** [Makefile:1037: vmlinux] Error 1
```

I tested it with clang-7 and the recent version of clang-8 (clang version 8.0.0-svn343562-1~exp1+0~20181002091440.2051~1.gbp47b1b6 (trunk)).

To get to this point of compiling and linking the kernel (tag: next-20181002 from linux-next), I applied three hacky patches:

```
hack around to make it compile with clang
compiler.h: give up __compiletime_assert_fallback()
Make clang hate percpu.h less in 32-bit mode 
```

I provide the three patches in this repository here:

https://github.com/bulwahn/linux-kernel-analysis/tree/clang-patches/clang/next/next-20181002/patches

**Comment by nickdesaulniers** [comment] 2018-10-03 07:59
I *think* `__divdi3` should [come from libgcc](https://gcc.gnu.org/onlinedocs/gccint/Integer-library-routines.html)? `perf_adjust_period` is [very clearly performing signed division and using the quotient](https://elixir.bootlin.com/linux/v4.19-rc6/source/kernel/events/core.c#L3562).  I don't understand why those functions would be pulled from glibc.

Curious too that these occur *after* `LD vmlinux`.  Did you have `HOSTCC=` set?

**Comment by bulwahn** [comment] 2018-10-04 22:30
I bisected between allnoconfig (which was good) and tinyconfig (which was bad) and this resulted in config-bisect.pl to report:
```
Hmm, can't make any more changes without making good == bad?
Difference between good (+) and bad (-)
 CC_OPTIMIZE_FOR_SIZE n -> y
 CC_OPTIMIZE_FOR_PERFORMANCE y -> n
```

**Comment by pirama-arumuga-nainar** [comment] 2018-10-04 23:44
IIUC ` CC_OPTIMIZE_FOR_PERFORMANCE y -> n` builds with `-O0` or similar?  If so that *may* cause Clang to use a library call instead of lowering to instructions.

But I'm pretty sure both clang_rt and libgcc provide this function.  Do you happen to get the link command that failed?  If you add `-v`, you should be able to see if libgcc or libclang_rt is getting used.

**Comment by nickdesaulniers** [comment] 2018-10-04 23:46
Thank you for taking the time to bisect, it is always painful.

Right, so those flags are mutually exclusive and change whether we compile with `-O2` (performance) vs `-Os` (`-Oz` for Clang)(size).

kernel/configs/tiny.config sets `CONFIG_CC_OPTIMIZE_FOR_SIZE=y`.  I was not able to go from `make defconfig`, then using `make menuconfig` to set `CONFIG_CC_OPTIMIZE_FOR_SIZE=y` then reproduce.  So that flag alone is not the problem.

**Comment by nathanchance** [comment] 2018-10-05 04:35
Somewhat interesting...

```bash
make -j8 CC=clang HOSTCC=clang defconfig tiny.config
make -j8 CC=clang HOSTCC=clang
```

links just fine for me (I have the same hacky patches that you do for x86). Is that the right command to reproduce this failure? I'm on Arch Linux with the following versions:

```bash
$ clang --version
clang version 7.0.0 (tags/RELEASE_700/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
$ gcc --version
gcc (GCC) 8.2.1 20180831
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by bulwahn** [comment] 2018-10-05 04:36
With a bit of bisecting and educating guessing, I could boil it down to:

allnoconfig works!
allnoconfig + OPTIMIZE_FOR_SIZE fails!
allnoconfig + OPTIMIZE_FOR_SIZE + "64-bit kernel" works!
allnoconfig + "64-bit kernel" works!

defconfig + OPTIMIZE_FOR_SIZE works!
defconfig + OPTIMIZE_FOR_SIZE - "64-bit kernel" fails! (with the reported issue and even more other linking problems)
defconfig - "64-bit kernel" is strange:
  - does not fail with linking problem above
  - but fails with:
```
  LD      vmlinux.o
  MODPOST vmlinux.o
ld: drivers/gpu/drm/i915/i915_params.o: in function `i915_params_dump':
i915_params.c:(.text+0x56): undefined reference to `__compiletime_assert_191'
ld: i915_params.c:(.text+0xed): undefined reference to `__compiletime_assert_191'
ld: i915_params.c:(.text+0x188): undefined reference to `__compiletime_assert_191'
ld: i915_params.c:(.text+0x223): undefined reference to `__compiletime_assert_191'
ld: i915_params.c:(.text+0x2be): undefined reference to `__compiletime_assert_191'
ld: drivers/gpu/drm/i915/i915_params.o:i915_params.c:(.text+0x359): more undefined references to `__compiletime_assert_191' follow
make: *** [Makefile:1037: vmlinux] Error 1
```

Conclusion:
- OPTIMIZE_FOR_SIZE and no "64-bit kernel" seems to be the issue.
- there is another issue with defconfig and no "64-bit kernel"

**Comment by bulwahn** [comment] 2018-10-05 04:46
@nathanchance I can confirm that these two commands link just fine on my machine as well: 
```
make -j8 CC=clang-8 HOSTCC=clang-8 defconfig tiny.config
make -j8 CC=clang-8 HOSTCC=clang-8
```

**Comment by bulwahn** [comment] 2018-10-05 04:50
@nathanchance Just to be clear, these commands show the linking issue:
```
make -j8 CC=clang-8 HOSTCC=clang-8 tinyconfig
make -j8 CC=clang-8 HOSTCC=clang-8
```

I guess this fits well into the other observations above.

**Comment by nathanchance** [comment] 2018-10-05 04:56
Ah thanks. I didn't try just `tinyconfig`, today I learned that's a thing :P

Looks like `tinyconfig` = `allnoconfig` + `tiny.config`, which certainly aligns with what you said. I can reproduce the failure here as well, I'll start digging in to see what is up.

**Comment by bulwahn** [comment] 2018-10-05 05:05
Well, it is the "64-bit kernel" option between defconfig and allnoconfig that makes the crucial difference.

**Comment by nathanchance** [comment] 2018-10-05 05:12
Moving from `-Oz` to `-Os` fixes this for me:

```diff
diff --git a/Makefile b/Makefile
index 4f08e99c267c..22916c188419 100644
--- a/Makefile
+++ b/Makefile
@@ -663,7 +663,7 @@ KBUILD_CFLAGS       += $(call cc-disable-warning, format-overflow)
 KBUILD_CFLAGS  += $(call cc-disable-warning, int-in-bool-context)
 
 ifdef CONFIG_CC_OPTIMIZE_FOR_SIZE
-KBUILD_CFLAGS  += $(call cc-option,-Oz,-Os)
+KBUILD_CFLAGS  += -Os
 KBUILD_CFLAGS  += $(call cc-disable-warning,maybe-uninitialized,)
 else
 ifdef CONFIG_PROFILE_ALL_BRANCHES
```

Time to find out why.

**Comment by tpimh** [comment] 2018-10-05 07:06
Yes, tinyconfig is x86 by default. I never succeeded building an x86 kernel. I only did build with `make ARCH=x86_64 tinyconfig`. Perhaps, it should be labeled `[ARCH] x86`.

**Comment by nickdesaulniers** [comment] 2018-10-05 15:38
So 32b x86 -Oz fails to link cause of those missing symbols. That other
link failure is a build bug on failure (they look ugly with clang).

**Comment by nickdesaulniers** [comment] 2018-10-05 23:00
Looks like Clang and GCC can emit `__divdi3` when doing divisions of `uint64_t`s.  There seems to be disagreement about whether `-ffreestanding` should prevent the emission of this symbol.

**Comment by nathanchance** [comment] 2018-10-17 04:54
Interesting comment in [arch/x86/mm/numa_emulation.c](https://github.com/ClangBuiltLinux/linux/blob/master/arch/x86/mm/numa_emulation.c#L101-L106)

```
	/*
	 * Calculate target node size.  x86_32 freaks on __udivdi3() so do
	 * the division in ulong number of pages and convert back.
	 */
	size = max_addr - addr - mem_hole_size(addr, max_addr);
	size = PFN_PHYS((unsigned long)(size >> PAGE_SHIFT) / nr_nodes);
```

**Comment by nickdesaulniers** [comment] 2018-10-17 05:30
IIRC, I think grepping for `__udivdi3` I saw a comment somewhere else that said "do <wacky code here> to avoid GCC generating `__udivdi3`."

**Comment by nathanchance** [comment] 2018-10-17 20:38
Similar error after commit 49116f2081ee ("x86/vdso: Introduce and use vgtod_ts") in -next: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=49116f2081eeaf75316956705d46602b7eb735cc

```
ld: arch/x86/entry/vsyscall/vsyscall_gtod.o: in function `update_vsyscall':
vsyscall_gtod.c:(.text+0x232): undefined reference to `__udivdi3'
make: *** [Makefile:1030: vmlinux] Error 1
```

**Comment by nickdesaulniers** [comment] 2019-01-24 19:09
AMD is reporting similar issues for CrOS.  Will open a new bug.

**Comment by nickdesaulniers** [comment] 2019-03-22 05:12
I suspect once 

Revert "kbuild: use -Oz instead of -Os when using clang"

[1] https://lore.kernel.org/patchwork/patch/1051932/

hits mainline & stable, this will no longer be reproducible.

**Comment by nathanchance** [comment] 2019-04-09 03:42
Merged into mainline: https://git.kernel.org/linus/a75bb4eb9e565b9f5115e2e8c07377ce32cbe69a

**Closed by nathanchance** 2019-04-09 03:42 UTC
Labels: [ARCH] x86, [BUG] linux, [PATCH] Accepted, low priority
