### ISSUE TITLE
arm allyesconfig fails after r366523

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#615] opened 2019-07-19 05:12 UTC
After [r366523](https://github.com/llvm/llvm-project/commit/ccbffefccaff42b0d094c9ef0f49fc3e8c8456ea), arm allyesconfig fails with:

```
  LD      vmlinux.o
  MODPOST vmlinux.o
  MODINFO modules.builtin.modinfo
ld.lld: error: undefined symbol: .LBB6_54
>>> referenced by nozomi.c
>>>               tty/nozomi.o:(__jump_table+0xB8) in archive drivers/built-in.a
```

I haven't worked down a simpler set of configs that triggers this; however, I did throw it through `creduce` with the following interestingness test:

```bash
#!/bin/bash

/home/nathan/toolchains/gcc/9.1.0/bin/arm-linux-gnueabi-gcc -O2 -c -o nozomi.o nozomi.i || exit 1

/home/nathan/cbl/usr/bin/clang -O2 -no-integrated-as --target=arm-linux-gnueabi --prefix=/home/nathan/cbl/usr/bin/ --gcc-toolchain=/home/nathan/cbl/usr -c -o nozomi.o nozomi.i && nm nozomi.o | grep LBB
```

and it spits out:

```c
enum { a, b };
struct c {};
debug;
d() {
  _Bool branch;
  struct c *e = 0;
  asm goto("1:\n\t.word b, %l[l_yes], %c0\n\t" : : "i"(&e[branch]) : : l_yes);
  return a;
l_yes:
  return b;
}
f() {
  if (1 & debug)
    if (({
          _Bool branch = !d();
          __builtin_expect(branch, 1);
        }))
      g();
  if (1 & debug)
    asm goto("" : : : : l_yes);
l_yes:;
}
```

cc @gwelymernans

**Comment by nathanchance** [comment] 2019-07-19 07:06
x86 allyesconfig also fails, I assume it is related (if not, I can file another issue).

```
  LD      vmlinux.o
  MODPOST vmlinux.o
  MODINFO modules.builtin.modinfo
ld.lld: error: undefined symbol: .LBB2_2
>>> referenced by dca.c
>>>               dma/ioat/dca.o:(__jump_table+0x24) in archive drivers/built-in.a
```

`creduce` test and result:

```bash
#!/bin/bash

gcc -O2 -c -o dca.o dca.i || exit 1

/home/nathan/cbl/usr/bin/clang -O2 -no-integrated-as -c -o dca.o dca.i && nm dca.o | grep LBB
```

```c
a() {
  if (b())
    return c();
  asm goto("1:.long b - ., %l[l_yes] - . \n\t" : : : : l_yes);
l_yes:
  return 0;
}
d() {
  if (a())
    e();
}
```

**Comment by nickdesaulniers** [comment] 2019-07-19 07:30
dupe of #614 and #500 (regression from r366523) cc @gwelymernans

**Comment by nickdesaulniers** [comment] 2019-07-19 09:31
@gwelymernans has posted https://reviews.llvm.org/D64982, we should verify if that's a fix.

**Comment by nathanchance** [comment] 2019-07-19 16:53
The arm32 error is fixed with that patch. The x86 one is not. I am testing #614 now.

**Comment by nickdesaulniers** [comment] 2019-07-19 17:50
> The x86 one is not. I am testing #614 now.

That's problematic. I'm going to suggest a revert.

**Comment by nickdesaulniers** [comment] 2019-07-19 18:17
Reverted in r366600.

**Comment by nickdesaulniers** [comment] 2019-08-23 17:00
I can no longer reproduce @nathanchance 's [reproducer](https://github.com/ClangBuiltLinux/linux/issues/615#issuecomment-513118516)

**Closed by nickdesaulniers** 2019-08-23 17:00 UTC
Labels: [ARCH] arm32, [BUG] llvm, asm goto
