### ISSUE TITLE
-Wgnu-variable-sized-type-not-at-end in include/linux/cgroup-defs.h

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#113] opened 2018-09-18 18:16 UTC
```
./include/linux/cgroup-defs.h:463:16: warning: field 'cgrp' with variable sized type 'struct cgroup' not at the end of a struct or class is
      a GNU extension [-Wgnu-variable-sized-type-not-at-end]
        struct cgroup cgrp;
                      ^
```

**Comment by tpimh** [comment] 2018-09-19 13:33
```
In file included from drivers/firmware/efi/libstub/efi-stub-helper.c:14:
In file included from ./arch/x86/include/asm/efi.h:8:
In file included from ./arch/x86/include/asm/tlb.h:17:
In file included from ./include/asm-generic/tlb.h:19:
In file included from ./include/linux/swap.h:9:
In file included from ./include/linux/memcontrol.h:22:
In file included from ./include/linux/cgroup.h:28:
```

**Comment by nickdesaulniers** [comment] 2018-09-24 01:07
Guilty: drivers/firmware/efi/libstub/Makefile. Looks like they just get steamrolled for x86 (32b and 64b), but lines 8-27 should be rewritten.

**Comment by nickdesaulniers** [comment] 2018-09-24 01:09
root cause is a duplicate of https://github.com/ClangBuiltLinux/linux/issues/112.

**Comment by gwelymernans** [comment] 2019-05-09 06:10
I'm still seeing this occurring, but now for AArch64:

```
clang -Wp,-MD,arch/arm64/kernel/.asm-offsets.s.d  -nostdinc -isystem /google/src/files/246902398/depot/google3/third_party/crosstool/v18/llvm_unstable/installs/llvm/lib/clang/google3-trunk/include -I./arch/arm64/include -I./arch/arm64/include/generated  -I./include -I./arch/arm64/include/uapi -I./arch/arm64/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 --target=aarch64-grtev4-linux-gnu --gcc-toolchain=/sandbox/morbo/prodkernel/gbuild-obj/obj_arm64_smp-5a711e570e2843690026bbc80407197dba94286b/wrappers/18-arm64-clang --prefix=/sandbox/morbo/prodkernel/gbuild-obj/obj_arm64_smp-5a711e570e2843690026bbc80407197dba94286b/wrappers/18-arm64-clang/b6993799ec31688dfc01f457b172dc5ad2ffb729/ -no-integrated-as -fno-PIE -DARCH_DIORITE_ACC -march=armv8.2-a+fp16+dotprod+simd -mgeneral-regs-only -DCONFIG_BROKEN_GAS_INST=1 -fno-asynchronous-unwind-tables -O2 -fstack-protector-strong -fno-omit-frame-pointer -fno-optimize-sibling-calls -g -pg -Werror -ffreestanding -fdebug-prefix-map=/sandbox/morbo/prodkernel=.    -DKBUILD_BASENAME='"asm_offsets"' -DKBUILD_MODNAME='"asm_offsets"'  -fverbose-asm -S -o arch/arm64/kernel/asm-offsets.s arch/arm64/kernel/asm-offsets.c
In file included from arch/arm64/kernel/asm-offsets.c:25:
In file included from ./include/linux/kvm_host.h:38:
In file included from ./arch/arm64/include/asm/kvm_host.h:42:
In file included from ./include/kvm/arm_pmu.h:21:
In file included from ./include/linux/perf_event.h:57:
In file included from ./include/linux/cgroup.h:28:
./include/linux/cgroup-defs.h:464:16: error: field 'cgrp' with variable sized type 'struct cgroup' not at the end of a struct or class is a GNU extension [-Werror,-Wgnu-variable-sized-type-not-at-end]
        struct cgroup cgrp;
                      ^
1 error generated.
Kbuild:56: recipe for target 'arch/arm64/kernel/asm-offsets.s' failed
make[2]: *** [arch/arm64/kernel/asm-offsets.s] Error 1
Makefile:1102: recipe for target 'prepare0' failed
make[1]: *** [prepare0] Error 2
make[1]: Leaving directory '/sandbox/morbo/prodkernel'
make: *** [gb_binaries] Error 2
/sandbox/morbo/prodkernel/gbuild/main.makefile:663: recipe for target 'gb_binaries' failed
```

**Comment by nathanchance** [comment] 2019-05-09 06:23
Hmmm where are the clang specific `-Wno-*` flags?

https://github.com/ClangBuiltLinux/linux/blob/master/Makefile#L691

This seems oddly familiar to my comment here with regards to `-Waddress-of-packed-member`: https://github.com/ClangBuiltLinux/continuous-integration/issues/152#issuecomment-489287093

**Comment by gwelymernans** [comment] 2019-05-09 07:00
Weird. It looks like none of those flags are being picked up in the `KBUILD_CFLAGS` var. It might be an issue with the command line....

**Comment by gwelymernans** [comment] 2019-05-09 07:10
I think I know what's happening. The compile is failing for another reason and it's assuming that the flags aren't acceptable. PEBCAK.

**Closed by gwelymernans** 2019-05-09 07:10 UTC
Labels: duplicate

**Comment by nathanchance** [comment] 2019-05-09 11:19
Just as an FYI, Masahiro sent a patch that unconditionally adds these flags to `KBUILD_CFLAGS` because they are for certain supported by clang: https://lore.kernel.org/lkml/20190509064455.1173-1-yamada.masahiro@socionext.com/
