### ISSUE TITLE
warning: objtool: can't find jump dest instruction

### ISSUE THREAD

**Issue by samitolvanen** [ClangBuiltLinux/linux#1435] opened 2021-08-05 21:20 UTC
I'm seeing a "can't find jump dest instruction" objtool warning when building allyesconfig with LTO and CFI, which I narrowed down to [`drivers/net/ethernet/stmicro/stmmac/dwmac-ipq806x.c:ipq806x_gmac_probe`](https://elixir.bootlin.com/linux/v5.14-rc4/source/drivers/net/ethernet/stmicro/stmmac/dwmac-ipq806x.c#L245).

After a quick `cvise` run, I ended up with the following reproducer:
```C
enum { PHY_INTERFACE_MODE_RGMII } ipq806x_gmac_probe_gmac_0;
ipq806x_gmac_probe() {
  switch (ipq806x_gmac_probe_gmac_0)
  case PHY_INTERFACE_MODE_RGMII: {
    asm("");
    __builtin_unreachable();
  }
}
```

And I can trivially reproduce the issue without LTO or CFI as well:
```
$ clang -O2 -c -o dwmac-ipq806x.o dwmac-ipq806x.i
$ ./tools/objtool/objtool check --module dwmac-ipq806x.o
dwmac-ipq806x.o: warning: objtool: ipq806x_gmac_probe()+0x7: can't find jump dest instruction at .text+0xa
```

Looking at the object file, we really do seem to end up with a jump beyond the `.text` section here:
```objdump
$ llvm-objdump -d -r dwmac-ipq806x.o

dwmac-ipq806x.o:        file format elf64-x86-64

Disassembly of section .text:

0000000000000000 <ipq806x_gmac_probe>:
       0: 83 3d 00 00 00 00 00          cmpl    $0, (%rip)              # 0x7 <ipq806x_gmac_probe+0x7>
                0000000000000002:  R_X86_64_PC32        ipq806x_gmac_probe_gmac_0-0x5
       7: 74 01                         je      0xa <ipq806x_gmac_probe+0xa>
       9: c3                            retq
```
@nickdesaulniers @nathanchance Thoughts?

Edit: ThinLTO, not full...

**Comment by nathanchance** [comment] 2021-08-05 21:37
```c
static int ipq806x_gmac_probe(struct platform_device *pdev)
{
	struct plat_stmmacenet_data *plat_dat;
	struct stmmac_resources stmmac_res;
	struct device *dev = &pdev->dev;
	struct ipq806x_gmac *gmac;
	int val;
	int err;

	val = stmmac_get_platform_resources(pdev, &stmmac_res);
	if (val)
		return val;

	plat_dat = stmmac_probe_config_dt(pdev, stmmac_res.mac);
	if (IS_ERR(plat_dat))
		return PTR_ERR(plat_dat);

	gmac = devm_kzalloc(dev, sizeof(*gmac), GFP_KERNEL);
	if (!gmac) {
		err = -ENOMEM;
		goto err_remove_config_dt;
	}

	gmac->pdev = pdev;

	err = ipq806x_gmac_of_parse(gmac);
	if (err) {
		dev_err(dev, "device tree parsing error\n");
		goto err_remove_config_dt;
	}

	regmap_write(gmac->qsgmii_csr, QSGMII_PCS_CAL_LCKDT_CTL,
		     QSGMII_PCS_CAL_LCKDT_CTL_RST);

	/* Inter frame gap is set to 12 */
	val = 12 << NSS_COMMON_GMAC_CTL_IFG_OFFSET |
	      12 << NSS_COMMON_GMAC_CTL_IFG_LIMIT_OFFSET;
	/* We also initiate an AXI low power exit request */
	val |= NSS_COMMON_GMAC_CTL_CSYS_REQ;
	switch (gmac->phy_mode) {
	case PHY_INTERFACE_MODE_RGMII:
		val |= NSS_COMMON_GMAC_CTL_PHY_IFACE_SEL;
		break;
	case PHY_INTERFACE_MODE_SGMII:
		val &= ~NSS_COMMON_GMAC_CTL_PHY_IFACE_SEL;
		break;
	default:
		dev_err(&pdev->dev, "Unsupported PHY mode: \"%s\"\n",
			phy_modes(gmac->phy_mode));
		err = -EINVAL;
		goto err_remove_config_dt;
	}
	regmap_write(gmac->nss_common, NSS_COMMON_GMAC_CTL(gmac->id), val);

	/* Configure the clock src according to the mode */
	regmap_read(gmac->nss_common, NSS_COMMON_CLK_SRC_CTRL, &val);
	val &= ~(1 << NSS_COMMON_CLK_SRC_CTRL_OFFSET(gmac->id));
	switch (gmac->phy_mode) {
	case PHY_INTERFACE_MODE_RGMII:
		val |= NSS_COMMON_CLK_SRC_CTRL_RGMII(gmac->id) <<
			NSS_COMMON_CLK_SRC_CTRL_OFFSET(gmac->id);
		break;
	case PHY_INTERFACE_MODE_SGMII:
		val |= NSS_COMMON_CLK_SRC_CTRL_SGMII(gmac->id) <<
			NSS_COMMON_CLK_SRC_CTRL_OFFSET(gmac->id);
		break;
	default:
		dev_err(&pdev->dev, "Unsupported PHY mode: \"%s\"\n",
			phy_modes(gmac->phy_mode));
		err = -EINVAL;
		goto err_remove_config_dt;
	}
	regmap_write(gmac->nss_common, NSS_COMMON_CLK_SRC_CTRL, val);

	/* Enable PTP clock */
	regmap_read(gmac->nss_common, NSS_COMMON_CLK_GATE, &val);
	val |= NSS_COMMON_CLK_GATE_PTP_EN(gmac->id);
	switch (gmac->phy_mode) {
	case PHY_INTERFACE_MODE_RGMII:
		val |= NSS_COMMON_CLK_GATE_RGMII_RX_EN(gmac->id) |
			NSS_COMMON_CLK_GATE_RGMII_TX_EN(gmac->id);
		break;
	case PHY_INTERFACE_MODE_SGMII:
		val |= NSS_COMMON_CLK_GATE_GMII_RX_EN(gmac->id) |
				NSS_COMMON_CLK_GATE_GMII_TX_EN(gmac->id);
		break;
	default:
		/* We don't get here; the switch above will have errored out */
		unreachable();
	}
	regmap_write(gmac->nss_common, NSS_COMMON_CLK_GATE, val);

	if (gmac->phy_mode == PHY_INTERFACE_MODE_SGMII) {
		regmap_write(gmac->qsgmii_csr, QSGMII_PHY_SGMII_CTL(gmac->id),
			     QSGMII_PHY_CDR_EN |
			     QSGMII_PHY_RX_FRONT_EN |
			     QSGMII_PHY_RX_SIGNAL_DETECT_EN |
			     QSGMII_PHY_TX_DRIVER_EN |
			     QSGMII_PHY_QSGMII_EN |
			     0x4ul << QSGMII_PHY_PHASE_LOOP_GAIN_OFFSET |
			     0x3ul << QSGMII_PHY_RX_DC_BIAS_OFFSET |
			     0x1ul << QSGMII_PHY_RX_INPUT_EQU_OFFSET |
			     0x2ul << QSGMII_PHY_CDR_PI_SLEW_OFFSET |
			     0xCul << QSGMII_PHY_TX_DRV_AMP_OFFSET);
	}

	plat_dat->has_gmac = true;
	plat_dat->bsp_priv = gmac;
	plat_dat->fix_mac_speed = ipq806x_gmac_fix_mac_speed;
	plat_dat->multicast_filter_bins = 0;
	plat_dat->tx_fifo_size = 8192;
	plat_dat->rx_fifo_size = 8192;

	err = stmmac_dvr_probe(&pdev->dev, plat_dat, &stmmac_res);
	if (err)
		goto err_remove_config_dt;

	return 0;

err_remove_config_dt:
	stmmac_remove_config_dt(pdev, plat_dat);

	return err;
}
```

I guess LLVM could not figure out that if `gmac->phy_mode` was neither `PHY_INTERFACE_MODE_RGMII` nor `PHY_INTERFACE_MODE_SGMII`, we will not get to the `unreacahable()` call because of the `default` case of the previous statement, so it leaves the `unreachable()` annotation in and we go off into the weeds.

Not sure why we cannot just copy and paste the previous default case here, given that it exists twice already? This matches what has been done in certain other cases such as:

https://git.kernel.org/linus/e50989527faeafb79f45a0f7529ba8e01dff1fff
https://git.kernel.org/linus/ede6747c2f8975892ab98bed94357dc8c35d790c
https://git.kernel.org/linus/d652d5f1eeeb06046009f4fcb9b4542249526916

```diff
diff --git a/drivers/net/ethernet/stmicro/stmmac/dwmac-ipq806x.c b/drivers/net/ethernet/stmicro/stmmac/dwmac-ipq806x.c
index 28dd0ed85a82..e12285da44f7 100644
--- a/drivers/net/ethernet/stmicro/stmmac/dwmac-ipq806x.c
+++ b/drivers/net/ethernet/stmicro/stmmac/dwmac-ipq806x.c
@@ -329,8 +329,10 @@ static int ipq806x_gmac_probe(struct platform_device *pdev)
                                NSS_COMMON_CLK_GATE_GMII_TX_EN(gmac->id);
                break;
        default:
-               /* We don't get here; the switch above will have errored out */
-               unreachable();
+               dev_err(&pdev->dev, "Unsupported PHY mode: \"%s\"\n",
+                       phy_modes(gmac->phy_mode));
+               err = -EINVAL;
+               goto err_remove_config_dt;
        }
        regmap_write(gmac->nss_common, NSS_COMMON_CLK_GATE, val);
```

I think the last few paragraphs of Linus's message in the final link makes it clear that this is a proper fix.

**Comment by samitolvanen** [comment] 2021-08-05 21:41
> Not sure why we cannot just copy and paste the previous default case here, given that it exists twice already?

Sure, I'm fine with that. Not sure if generating an invalid jump is the ideal compiler behavior here though, but I assume that's going to be harder to fix.

> I think the last few paragraphs of Linus's message in the final link makes it clear that this is a proper fix.

Except that fix is even cleaner, just making default fall through to one of the cases without duplicating the error.

**Comment by nathanchance** [comment] 2021-08-05 21:52
> Sure, I'm fine with that. Not sure if generating an invalid jump is the ideal compiler behavior here though, but I assume that's going to be harder to fix.

I agree this should probably be fixed in the compiler but at the same time, this could be considered a case of "Patient: Doctor, it hurts when I do this. Doctor: So don't do that." :)

> Except that fix is even cleaner, just making default fall through to one of the cases without duplicating the error.

Fair, this might be a little bit better?

```diff
diff --git a/drivers/net/ethernet/stmicro/stmmac/dwmac-ipq806x.c b/drivers/net/ethernet/stmicro/stmmac/dwmac-ipq806x.c
index 28dd0ed85a82..f7dc8458cde8 100644
--- a/drivers/net/ethernet/stmicro/stmmac/dwmac-ipq806x.c
+++ b/drivers/net/ethernet/stmicro/stmmac/dwmac-ipq806x.c
@@ -289,10 +289,7 @@ static int ipq806x_gmac_probe(struct platform_device *pdev)
                val &= ~NSS_COMMON_GMAC_CTL_PHY_IFACE_SEL;
                break;
        default:
-               dev_err(&pdev->dev, "Unsupported PHY mode: \"%s\"\n",
-                       phy_modes(gmac->phy_mode));
-               err = -EINVAL;
-               goto err_remove_config_dt;
+               goto err_unsupported_phy;
        }
        regmap_write(gmac->nss_common, NSS_COMMON_GMAC_CTL(gmac->id), val);

@@ -309,10 +306,7 @@ static int ipq806x_gmac_probe(struct platform_device *pdev)
                        NSS_COMMON_CLK_SRC_CTRL_OFFSET(gmac->id);
                break;
        default:
-               dev_err(&pdev->dev, "Unsupported PHY mode: \"%s\"\n",
-                       phy_modes(gmac->phy_mode));
-               err = -EINVAL;
-               goto err_remove_config_dt;
+               goto err_unsupported_phy;
        }
        regmap_write(gmac->nss_common, NSS_COMMON_CLK_SRC_CTRL, val);

@@ -329,8 +323,7 @@ static int ipq806x_gmac_probe(struct platform_device *pdev)
                                NSS_COMMON_CLK_GATE_GMII_TX_EN(gmac->id);
                break;
        default:
-               /* We don't get here; the switch above will have errored out */
-               unreachable();
+               goto err_unsupported_phy;
        }
        regmap_write(gmac->nss_common, NSS_COMMON_CLK_GATE, val);

@@ -361,6 +354,11 @@ static int ipq806x_gmac_probe(struct platform_device *pdev)

        return 0;

+err_unsupported_phy:
+       dev_err(&pdev->dev, "Unsupported PHY mode: \"%s\"\n",
+               phy_modes(gmac->phy_mode));
+       err = -EINVAL;
+
 err_remove_config_dt:
        stmmac_remove_config_dt(pdev, plat_dat);

```

**Comment by samitolvanen** [comment] 2021-08-05 22:06
> Fair, this might be a little bit better?

LGTM, and I confirmed that this fixes my objtool issue with LTO+CFI. Feel free to add `Tested-by: Sami Tolvanen <samitolvanen@google.com>`.

**Comment by nathanchance** [comment] 2021-08-06 17:49
@samitolvanen could you send me a `.config` that reproduces this? I want to add the exact `objtool` warning to the commit message and I am not able to reproduce it with the few combinations I have tried. It does not even seem possible to build this file with x86_64 allyesconfig + full LTO because `CONFIG_DWMAC_LPC18XX` depends on `CONFIG_COMPILE_TEST` but `CONFIG_COMPILE_TEST` has to be disabled for `CONFIG_LTO_CLANG_FULL`.

**Comment by samitolvanen** [comment] 2021-08-06 17:59
Sorry, it was ThinLTO. I can't access my workstation right now, so I can't send you the exact config, but I was able to repro initially with allyesconfig + LTO_CLANG_THIN + CFI_CLANG + CFI_PERMISSIVE using [the x86_64 clang-cfi tree](https://github.com/samitolvanen/linux/commits/clang-cfi) and ToT Clang.

I could later repro this also with defconfig + LTO_CLANG_THIN + CFI_CLANG + STMMAC_ETH + STMMAC_PLATFORM + DWMAC_LPC18XX (and whatever other configs it might have depended on...). It's reproducible even if DWMAC_LPC18XX is compiled as a module.

**Comment by nathanchance** [comment] 2021-08-06 19:14
Ah, I forgot that with LTO, `objtool` runs on `vmlinux` rather than the `.o` file so building `all` instead of `drivers/net/ethernet/stmicro/stmmac/dwmac-ipq806x.o` shows it.

Patch submitted: https://lore.kernel.org/r/20210806191339.576318-1-nathan@kernel.org/

**Comment by nathanchance** [comment] 2021-08-08 02:46
Patch accepted: https://git.kernel.org/netdev/net-next/c/4367355dd909

I forgot to add the link to this issue unfortunately :/

**Comment by nickdesaulniers** [comment] 2021-09-29 20:17
4367355dd90942a71641c98c40c74589c9bddf90 v5.15-rc1

**Closed as completed by nickdesaulniers** 2021-09-29 20:17 UTC
Labels: [BUG] llvm, [ARCH] x86_64, [FIXED][LINUX] 5.15
