### ISSUE TITLE
-Wenum-conversion in drivers/scsi/bfa/bfa_svc.c

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#149] opened 2018-09-20 13:55 UTC
```
drivers/scsi/bfa/bfa_svc.c:2025:25: warning: implicit conversion from enumeration type
      'enum bfa_port_aen_event' to different enumeration type 'enum bfa_ioc_aen_event'
      [-Wenum-conversion]
                                  BFA_AEN_CAT_PORT, event);
                                                    ^~~~~
1 warning generated.
```

**Comment by tpimh** [comment] 2018-09-20 14:14
Realized after posting that it's just another case of #147

**Comment by nathanchance** [comment] 2018-09-26 04:59
Closing as duplicate of #147 (patch posted solves this issue).

**Closed** 2018-09-26 04:59 UTC
Labels: duplicate
