### ISSUE TITLE
error: invalid operand for inline asm constraint 'i'

### ISSUE THREAD

**Issue by xdevs23** [ClangBuiltLinux/linux#908] opened 2020-02-29 14:55 UTC
Kernel version: 5.5.7
Tree: https://gitlab.com/xdevs23/linux-nitrous
Branch: v5.5+
Commit: https://gitlab.com/xdevs23/linux-nitrous/-/commit/e55e84f1e89c91cecb371aa23578abfcc9965a92
Clang version:
```
clang version 9.0.1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

OS:
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

uname -a:
```
Linux simbox 5.5.6-arch1-1 #1 SMP PREEMPT Mon, 24 Feb 2020 12:20:16 +0000 x86_64 GNU/Linux
```

Log file: [ln-full-log-557.txt](https://github.com/ClangBuiltLinux/linux/files/4270454/ln-full-log-557.txt)

Related: https://github.com/ClangBuiltLinux/linux/commit/0670525ded48caf958b6535d388e6478b6b14a4b#commitcomment-37095899 @nathanchance 

```
  CC [M]  drivers/gpu/drm/amd/amdgpu/gfx_v8_0.o
  CC      fs/io-wq.o
In file included from drivers/hid/wacom_wac.c:11:
In file included from drivers/hid/wacom_wac.h:9:
In file included from ./include/linux/hid.h:19:
In file included from ./include/linux/slab.h:15:
In file included from ./include/linux/gfp.h:5:
In file included from ./include/linux/mmdebug.h:5:
In file included from ./include/linux/bug.h:5:
In file included from ./arch/x86/include/asm/bug.h:83:
In file included from ./include/asm-generic/bug.h:19:
In file included from ./include/linux/kernel.h:15:
In file included from ./include/linux/printk.h:331:
In file included from ./include/linux/dynamic_debug.h:6:
In file included from ./include/linux/jump_label.h:117:
./arch/x86/include/asm/jump_label.h:25:20: error: invalid operand for inline asm constraint 'i'
        asm_volatile_goto("1:"
                          ^
1 error generated.
make[2]: *** [scripts/Makefile.build:266: drivers/hid/wacom_wac.o] Error 1
make[1]: *** [scripts/Makefile.build:503: drivers/hid] Error 2
make[1]: *** Waiting for unfinished jobs....
  CC      fs/dax.o

```

This happens occasionally – a rebuild usually fixes the problem.

These commits have helped previously as well:
https://gitlab.com/xdevs23/linux-nitrous/commit/d96b96a0932d0becd991797f5a6e7a8fb6c4e92e
https://gitlab.com/xdevs23/linux-nitrous/commit/9a40ff74d136791ed36a5e431d0a928ed406fcb4

**Comment by nickdesaulniers** [comment] 2020-03-02 09:01
pretty sure I fixed that in the clang-9 release: https://github.com/llvm/llvm-project/commit/8728e457065365f8f6fbbf86a665885d9dde082a

**Comment by nickdesaulniers** [comment] 2020-03-02 09:03
are you compiling with `-O3` [again](https://github.com/ClangBuiltLinux/linux/commit/0670525ded48caf958b6535d388e6478b6b14a4b#commitcomment-37095796)?

**Comment by xdevs23** [comment] 2020-03-06 16:19
> are you compiling with `-O3` [again](https://github.com/ClangBuiltLinux/linux/commit/0670525ded48caf958b6535d388e6478b6b14a4b#commitcomment-37095796)?

Yes, `-O3`. Always.
The error isn't always repoducible. I get it like once every 6 builds.
The build is run using: `make -j$(nproc --all)`

**Comment by nickdesaulniers** [comment] 2020-03-17 23:38
I wasn't able to reproduce this:
```diff
diff --git a/Makefile b/Makefile
index 171f2b004c8a..fdda401f2808 100644
--- a/Makefile
+++ b/Makefile
@@ -701,7 +701,7 @@ KBUILD_CFLAGS       += $(call cc-disable-warning, format-overflow)
 KBUILD_CFLAGS  += $(call cc-disable-warning, address-of-packed-member)
 
 ifdef CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE
-KBUILD_CFLAGS += -O2
+KBUILD_CFLAGS += -O3
 else ifdef CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE_O3
 KBUILD_CFLAGS += -O3
 else ifdef CONFIG_CC_OPTIMIZE_FOR_SIZE
```
```sh
$ make CC=clang -j71 defconfig
$ ./scripts/config -e HID_WACOM
$ for _ in $(seq 1 30); do rm -f drivers/hid/wacom_wac.o; make CC=clang -j71 drivers/hid/wacom_wac.o; done
```
30 compiles, no error.

@xdevs23 , can you please:
1. share your `.config` that reproduces?
2. back up your `.config`, then repeat the `defconfig`+`config -e` command I ran above, and see if you can still reproduce?

**Comment by xdevs23** [comment] 2020-03-18 07:06
Thanks for getting back to me. I'll try that later today. Have to say, this seems to be happening at random times.

**Comment by xdevs23** [comment] 2020-03-18 22:19
I ran the commands you specified. .config is attached.
[nitrous.config.txt](https://github.com/ClangBuiltLinux/linux/files/4351477/nitrous.config.txt)


Kernel source: https://gitlab.com/xdevs23/linux-nitrous/

I was able to reproduce it exactly once using your commands (see attached log file)

[reproduced_log.txt](https://github.com/ClangBuiltLinux/linux/files/4351486/reproduced_log.txt)

After that, I went ahead and did the following:

```
git reset --hard
git clean -fdx
make CC=clang mrproper
git clean -fdx
make CC=clang -j71 nitrous_defconfig
./scripts/config -e HID_WACOM
for _ in $(seq 1 30); do rm -f drivers/hid/wacom_wac.o; make CC=clang -j71 drivers/hid/wacom_wac.o; done
```

The first time it did not happen, so I ran the same again:

```
for _ in $(seq 1 30); do rm -f drivers/hid/wacom_wac.o; make CC=clang -j71 drivers/hid/wacom_wac.o; done
```

And again:

```
for _ in $(seq 1 30); do rm -f drivers/hid/wacom_wac.o; make CC=clang -j71 drivers/hid/wacom_wac.o; done
```

and... again:

```
for _ in $(seq 1 30); do rm -f drivers/hid/wacom_wac.o; make CC=clang -j71 drivers/hid/wacom_wac.o; done
```

yes, again:
```
for _ in $(seq 1 30); do rm -f drivers/hid/wacom_wac.o; make CC=clang -j71 drivers/hid/wacom_wac.o; done
```

this time:
```
make CC=clang -j71 nitrous_defconfig
./scripts/config -e HID_WACOM
for _ in $(seq 1 30); do rm -f drivers/hid/wacom_wac.o; make CC=clang -j71 drivers/hid/wacom_wac.o; done
```

and I ran this again:

```
for _ in $(seq 1 30); do rm -f drivers/hid/wacom_wac.o; make CC=clang -j71 drivers/hid/wacom_wac.o; done
```

but I wasn't able to reproduce it again.... Maybe it takes more tries? Or what's going on here?

I'd like to point out that I also run AOSP builds on the same machine – not at the same time as the kernel builds but they do run and they do succeed. I haven't seen any weird issues with that and most of the time the kernel there is compiled using clang as well (as of right now it's clang 10.0.4 but it has been on clang 9 before)

**Comment by nickdesaulniers** [comment] 2020-03-18 23:06
You can change `30` in the above command to a larger upper bound, rather than rerun.

So it sounds like you can reproduce, though it sounds like 1 in 7*30 (210)? Sounds like maybe compiler non-determinism, which is the worst to debug (generally, we like compilers to be deterministic, same inputs, same outputs).  Let's say there is non-determinism in clang-9; it's too late to fix clang-9.  Best we can hope for is it's fixed in a newer release, or that we can find it before clang-10 releases.

(I just ran 210 builds with ToT clang + your config + mainline no issue, though with nondeterminism you may never see a particular ordering ever again)

If you have access to a newer release of Clang, can you please see if you can reproduce?

Also, it is possible to have bad memory corrupt a process (I've actually had RAM sticks go bad/fail memtest) so a memtest might be good to run, too.  Or see if you can reproduce on a different machine.

Also, if you can, try limiting the concurrency of your build (`make -j1`), spooky things happen when `malloc` fails, and it's not always `abort`.

**Comment by xdevs23** [comment] 2020-03-19 06:29
I'll set up a script that counts how many times it falls and I'll let it run for a while.
I can also test it on another machine with the same OS and clang version.

If it's really my machine, then I suspect one of the following:

- cron job messing around
- memory corruption (I doubt this since AOSP builds work just fine and they often take up almost the entire memory)
- bug in Intel skylake speculative execution/branch prediction
- multithreaded build causing issues

I use the clang version that is available in the official Arch repositories.

**Comment by nickdesaulniers** [comment] 2020-03-19 15:48
Another idea one of my colleagues gave me was to print a hash of the object file every run; that makes it more obvious if we're getting different binaries every run or not.  I haven't checked that this generally works for the kernel (embedding timestamps from the build usually always messes this up; we get the same issue with ccache, which we have a fix we make use of in our CI).

**Comment by xdevs23** [comment] 2020-03-19 17:03
Thanks for that idea. I'm running my script now.

It compiles the file 400 times and prints the SHA256 hash.
The hash has always been the same so far, I just started running the script though.

I'll let you know the result when it's done.

**Comment by xdevs23** [comment] 2020-03-19 18:39
I have some news.

I tested the script on two machines with different hardware, same OS and clang version.
This is the script (had to rename to .txt so that I could upload it here):

[test-kernel.sh.txt](https://github.com/ClangBuiltLinux/linux/files/4356143/test-kernel.sh.txt)

Both machines had failures. At the very end the failure count is printed.
The machine I usually use had 3 failures, my main computer had 4.

Logs:
[simbox-results.txt](https://github.com/ClangBuiltLinux/linux/files/4356149/simbox-results.txt)
[simao-arch-results.txt](https://github.com/ClangBuiltLinux/linux/files/4356379/simao-arch-results.txt)

**Comment by nickdesaulniers** [comment] 2020-03-19 19:56
> It compiles the file 400 times and prints the SHA256 hash.
> The hash has always been the same so far, I just started running the script though.

So I expect either:
1. the SHA subtly changes between runs in obvious non-determinism
  1. potentially due to timestamps in headers
  2. potentially due to compiler non-determinism
2. the SHA is stable between runs or crashes in a deterministic spot, though the crashes are non-deterministic.

> I tested the script on two machines with different hardware, same OS and clang version.
> The machine I usually use had 3 failures, my main computer had 4.

Then that rules out of favor hardware issues.  The next variable to tweak in this experiment would be the compiler version.  Things we could check:
1. does this manifest in newer versions
2. what version did this start manifesting in

It sounds like the issue is reproducible every 100-200 runs or so.  Even if we bisect the compiler, we may not pinpoint where this is exactly, as some unrelated change just makes accessing it more difficult or hidden.

I can go back to the clang-9 release branch and give this 400 compiles.  Are you comfortable building llvm from source and testing with a newer clang? I have some info [here](https://clangbuiltlinux.github.io/CBL-meetup-2020-slides/nick/debugging_llvm.html#/2).

**Comment by xdevs23** [comment] 2020-03-19 20:01
The SHA seems to be the same everywhere, on both machines it produces the same exact hash.

I will build llvm from source and test it using that.
Since I build a AOSP-based ROM as well, I actually do have the clang-r353983c version and will use that as well.

Let's see how long this takes. I'll post an update when I'm done testing.

**Comment by xdevs23** [comment] 2020-03-19 21:26
I built it.
```
clang version 11.0.0 (git@github.com:llvm/llvm-project.git e23d78652691f360700a08a245ee28db151844f4)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /mnt/building/llvm/llvm-project/llvm/build/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/9.3.0
Selected GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/9.3.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```

I wasn't able to build using that though... I think I've gotten something wrong there.
Do I have to specify `CROSS_COMPILE=/mnt/building/llvm/llvm-project/llvm/build/bin/`?
or do I need to specify full paths for CC, HOSTCC, LD and HOSTLD?

I tried it for a bit but always got errors, here is one of them:

```
  HOSTLD  scripts/dtc/dtc
/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x58): first defined here
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [scripts/Makefile.host:116: scripts/dtc/dtc] Error 1
make: *** [Makefile:1260: scripts_dtc] Error 2
```

**Comment by nathanchance** [comment] 2020-03-19 21:40
The easiest way to use it is to add `PATH= /mnt/building/llvm/llvm-project/llvm/build/bin:${PATH}` before your script invocation so that all of the `clang` commands use that.

#925 has the patch to fix that error.

**Comment by xdevs23** [comment] 2020-03-19 21:45
I had already done that before but I just noticed that I made a typo... Oops. I corrected it and even added `PATH="/mnt/building/llvm/llvm-project/llvm/build/bin:$PATH"` before the script invocation but it didn't help. Still getting the same error.

**Comment by xdevs23** [comment] 2020-03-19 21:51
Quick update: I picked the commit https://git.kernel.org/pub/scm/linux/kernel/git/robh/linux.git/commit/?id=35595372d95c0d10784bce1aec8cc144a39eb66d as @nathanchance mentioned in issue #925 

After that, I symlinked lld.ld to `ld` inside the bin directory and made sure that it is in the PATH.
I also removed any LD=... and HOSTLD=.. that I had previously added for testing.

Now it works. It's compiling. Hash is: 8b04feadea8b87a79cb7f91d1c7861a101acaf6aaa52384344eb3b11883594ba (different from clang 9)

**Comment by xdevs23** [comment] 2020-03-19 22:16
With this new clang version, running the script it didn't fail a single time.
400 runs, none failed, all seem to have the same hash.

So I guess this got fixed with clang 10/11?
I'll let the script run again tomorrow and I'll also compile the entire kernel using this version and see what happens.

**Comment by nickdesaulniers** [comment] 2020-03-19 22:57
> So I guess this got fixed with clang 10/11?

Scary stories to tell in the dark; the absence of crash does not disprove non-determinism.  A crash every so often can prove there is non-determinism, but 0 crashes in 400 builds doesn't prove that the non-determinism requires 10000 builds to reproduce one crash.

That said, yeah, it probably got fixed.  It sucks no one spotted it before clang-9 shipped, but compiler release engineering is really hard, and we need people to help test releases before they go out.

If we really cared, we could bisect between clang-9 and clang-10 to see when this got fixed (a "reverse bisection") but there's maybe better uses of your time, and knowing what the fix is may not be helpful to anyone. 🤷‍♂ 

Sorry you were affected by this, but I hope it was interesting, at least.

**Comment by xdevs23** [comment] 2020-03-20 06:01
First of all thanks a lot for helping and being so dedicated to getting this repoduced and fixed.

> A crash every so often can prove there is non-determinism, but 0 crashes in 400 builds doesn't prove that the non-determinism requires 10000 builds to reproduce one crash. Schrodinger's non-deterministic compiler.

I understand what you mean and I'm aware that this isn't really proving that it got fixed, it's rather an indication that, at least, it got better.

I'm the script, the object was always compiled using `-j1` so make couldn't be launching multiple things at once. 

As mentioned before, I'll let the script run again and I'll also try the same on another machine, just to make sure.

What I don't understand is how this error could occur in the first place. You've shown me that the particular error I am facing has been fixed in https://github.com/llvm/llvm-project/commit/8728e457065365f8f6fbbf86a665885d9dde082a so how come it did not actually do anything in some cases?

Non-deterninism can be caused by a number of things, this may or may not have to do with address space layout randomization and speculative execution.

It might be interesting to disable KASLR and retpoline (and everything related) to see if it does anything different. I'm using an Intel Skylake and Haswell processor, hyper threading is disabled via cmdline

**Comment by nickdesaulniers** [comment] 2020-03-20 17:26
> the particular error I am facing has been fixed in llvm/llvm-project@8728e45 so how come it did not actually do anything in some cases?

🤷‍♂ I swear the compiler is haunted 👻 Try casting holy on it.

One issue I recall, and looked at briefly is that Clang's error messages for inline assembly have room for improvement.  When you have multiple assembler operands that all use the same constraint, clang doesn't specify which operand is problematic, while GCC does. (It was becoming a bit of yak shave in Clang when I tried to fix it).  All it takes is someone to store operands or print modifiers in an unordered container then process them iteratively, then every once in a while, you get a crash or a warning from the wrong place.

> the object was always compiled using -j1 so make couldn't be launching multiple things at once.

I wonder if you do some other heavy processing in the background if that changes the observed rate of reproduction?

**Comment by xdevs23** [comment] 2020-03-20 17:33
> :man_shrugging: I swear the compiler is haunted :ghost: Try casting holy on it.

:joy: I'm starting to think the same

> One issue I recall, and looked at briefly is that Clang's error messages for inline assembly have room for improvement. When you have multiple assembler operands that all use the same constraint, clang doesn't specify which operand is problematic, while GCC does. (It was becoming a bit of yak shave in Clang when I tried to fix it). All it takes is someone to store operands or print modifiers in an unordered container then process them iteratively, then every once in a while, you get a crash or a warning from the wrong place.

While I do know some good amount of C, I've never worked with inline assembly so I can't give my 2 cents to this.

> I wonder if you do some other heavy processing in the background if that changes the observed rate of reproduction?

I can try that.

By the way, I've run the script another time and it gave zero failures.
Now running it on my main computer. Gonna try `stress --cpu $(nproc --all)` now and let the script run at the same time (with clang 9).

**Comment by xdevs23** [comment] 2020-03-20 19:47
I ran both machines with `stress --cpu $(nproc --all)`.
One produces 1 failure, the other one produced 3. Same script, this time clang 9 again.

Now I'm running the script with `cpulimit -il 1`

**Comment by nickdesaulniers** [comment] 2020-03-20 21:39
I wonder if Clang publishes erratta, @hans ? Maybe we could note this about clang-9?

**Comment by xdevs23** [comment] 2020-03-20 21:39
14 in, already failed. 20 compiled so far. I'm aborting this now, it would take too long.
I think it does not make that big of a difference. The compiler being haunted doesn't care whatever else is going on.

**Comment by xdevs23** [comment] 2020-03-20 21:40
> I wonder if Clang publishes erratta, ? Maybe we could note this about clang-9?

Not sure.

**Comment by xdevs23** [comment] 2020-03-21 14:36
I got a clang 11 crash... will update clang and if it still happens, should I open an issue here or at LLVM?
[clang11-crash.txt](https://github.com/ClangBuiltLinux/linux/files/4363120/clang11-crash.txt)

**Comment by nathanchance** [comment] 2020-03-22 01:03
You can file an issue here so we can triage it.

**Comment by xdevs23** [comment] 2020-03-22 10:49
Alright, I'll do that.

Can we close this one?

**Closed** 2020-03-22 16:27 UTC
Labels: Compiler haunted, question, unreproducible

**Comment by zmodem** [comment] 2020-03-23 13:19
> I wonder if Clang publishes erratta, @zmodem? Maybe we could note this about clang-9?

Clang/LLVM does have an errate list. It would be a nice thing to have, but I think in practice all we've got at the moment is the bug tracker.
