### ISSUE TITLE
ppc32/CONFIG_ALTIVEC=y: frame-larger-than in arch/powerpc/lib/xor_vmx.c

### ISSUE THREAD

**Issue by malaterre** [ClangBuiltLinux/linux#563] opened 2019-06-21 07:59 UTC
Using clang-8, compilation fails with:

```
../arch/powerpc/lib/xor_vmx.c:119:6: error: stack frame size of 1200 bytes in function '__xor_altivec_5' [-Werror,-Wframe-larger-than=]
void __xor_altivec_5(unsigned long bytes, unsigned long *v1_in,

```

Using:

```
$ clang-8 --version
clang version 8.0.0-5 (tags/RELEASE_800/final)
Target: powerpc-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

```

**Comment by malaterre** [comment] 2019-06-21 08:00
Obviously a quick hack is something as simple as:

* https://patchwork.ozlabs.org/patch/991235/

It would be interesting to understand why clang optimizer fails this case.

**Comment by malaterre** [comment] 2019-06-21 08:01
@shenki

**Comment by malaterre** [comment] 2019-06-21 09:01
Workaround posted:

* https://patchwork.ozlabs.org/patch/1120047/

**Comment by nickdesaulniers** [comment] 2019-06-21 18:31
workarounds :(

so we have a known bug if you assign a global variable from a designated initializer in a function that's causing significant stack usage.  Also, this warning may be correct if it's stack allocating something really large that should not be. Clang and GCC may disagree on the level of inlining performed, and admittedly we don't really have great tools to debug these kind of warnings just yet.

**Comment by arndb** [comment] 2021-02-15 16:01
Interestingly, this only happens with the llvm version of altivec.h. If I preprocess the file using gcc and compile using clang, the stack frame usage is only around 300 bytes. The difference seems to be the definition of vec_xor(), which for gcc is

```c
#define vec_xor(v1, v2) __built_vec_xor(v1, v2)
```
and for clang is
```c
static inline __attribute__((__gnu_inline__)) __attribute__((__unused__)) __attribute__((__no_instrument_function__)) vector signed char __attribute__((__overloadable__, __always_inline__))
vec_xor(vector signed char __a, vector signed char __b) {
  return __a ^ __b;
}
```
I tried to just replace the definition of vec_xor(), but could not get that to compile.

**Comment by nickdesaulniers** [comment] 2021-04-22 18:11
@glaubitz noted this is easily reproducible with pmac32_defconfig.

> but could not get that to compile.

Right, clang does not have `__builtin_vec_xor`: https://godbolt.org/z/h54eM7EMd

Instead, it defines multiple implementations of vec_xor using `__attribute__((__overloadable__))`. Not sure why the other functions here like `__xor_altivec_4` seem to use much less stack space quite yet.

**Comment by nathanchance** [comment] 2022-01-04 21:14
I noticed that Ard's commit [e754a2be51e5](https://git.kernel.org/ardb/c/e754a2be51e5330e138271067808681b4a13ade2) ("lib/xor: make xor prototypes more friendely to compiler vectorization"), which aims to resolve https://github.com/ClangBuiltLinux/linux/issues/503. fixes this issue as well.

It does need a fixup to [build properly](https://lore.kernel.org/r/202112310646.kuh2pXiG-lkp@intel.com/):

```diff
diff --git a/arch/powerpc/lib/xor_vmx.c b/arch/powerpc/lib/xor_vmx.c
index 54e61979e80e..36bcb4cfe509 100644
--- a/arch/powerpc/lib/xor_vmx.c
+++ b/arch/powerpc/lib/xor_vmx.c
@@ -49,8 +49,9 @@ typedef vector signed char unative_t;
 		V1##_3 = vec_xor(V1##_3, V2##_3);	\
 	} while (0)
 
-void __xor_altivec_2(unsigned long bytes, unsigned long *v1_in,
-		     unsigned long *v2_in)
+void __xor_altivec_2(unsigned long bytes,
+		     unsigned long * __restrict v1_in,
+		     unsigned long const * __restrict v2_in)
 {
 	DEFINE(v1);
 	DEFINE(v2);
@@ -67,8 +68,10 @@ void __xor_altivec_2(unsigned long bytes, unsigned long *v1_in,
 	} while (--lines > 0);
 }
 
-void __xor_altivec_3(unsigned long bytes, unsigned long *v1_in,
-		     unsigned long *v2_in, unsigned long *v3_in)
+void __xor_altivec_3(unsigned long bytes,
+		     unsigned long * __restrict v1_in,
+		     unsigned long const * __restrict v2_in,
+		     unsigned long const * __restrict v3_in)
 {
 	DEFINE(v1);
 	DEFINE(v2);
@@ -89,9 +92,11 @@ void __xor_altivec_3(unsigned long bytes, unsigned long *v1_in,
 	} while (--lines > 0);
 }
 
-void __xor_altivec_4(unsigned long bytes, unsigned long *v1_in,
-		     unsigned long *v2_in, unsigned long *v3_in,
-		     unsigned long *v4_in)
+void __xor_altivec_4(unsigned long bytes,
+		     unsigned long * __restrict v1_in,
+		     unsigned long const * __restrict v2_in,
+		     unsigned long const * __restrict v3_in,
+		     unsigned long const * __restrict v4_in)
 {
 	DEFINE(v1);
 	DEFINE(v2);
@@ -116,9 +121,12 @@ void __xor_altivec_4(unsigned long bytes, unsigned long *v1_in,
 	} while (--lines > 0);
 }
 
-void __xor_altivec_5(unsigned long bytes, unsigned long *v1_in,
-		     unsigned long *v2_in, unsigned long *v3_in,
-		     unsigned long *v4_in, unsigned long *v5_in)
+void __xor_altivec_5(unsigned long bytes,
+		     unsigned long * __restrict v1_in,
+		     unsigned long const * __restrict v2_in,
+		     unsigned long const * __restrict v3_in,
+		     unsigned long const * __restrict v4_in,
+		     unsigned long const * __restrict v5_in)
 {
 	DEFINE(v1);
 	DEFINE(v2);
```

but after that, I do not see this warning with

```
$ make -skj"$(nproc)" ARCH=powerpc CROSS_COMPILE=powerpc-linux-gnu- LLVM=1 LLVM_IAS=0 distclean pmac32_defconfig all
```

**Comment by nathanchance** [comment] 2022-01-27 21:40
https://lore.kernel.org/r/20220127081227.2430-1-ardb@kernel.org/

**Comment by nathanchance** [comment] 2022-02-11 18:16
Patch accepted: https://git.kernel.org/herbert/cryptodev-2.6/c/297565aa22cfa80ab0f88c3569693aea0b6afb6d

**Comment by nathanchance** [comment] 2022-03-23 23:27
Merged into mainline: https://git.kernel.org/linus/297565aa22cfa80ab0f88c3569693aea0b6afb6d

**Closed by nathanchance** 2022-03-23 23:27 UTC
Labels: [BUG] linux, [ARCH] powerpc, [PATCH] Accepted, -Wframe-larger-than=
