### ISSUE TITLE
lld: relocation R_ARM_CALL out of range

### ISSUE THREAD

**Issue by arndb** [ClangBuiltLinux/linux#1305] opened 2021-02-19 20:57 UTC
In very rare randconfig builds, lld fails to link a 32-bit ARM kernel:

$ cat build/arm/0xAF64BE88_defconfig/faillog 
ld.lld: error: gf119.c:(function gf119_disp_super: .text+0x3D4): relocation R_ARM_CALL out of range: -33554440 is not in [-33554432, 33554431]
$ cat build/arm/0xFD37B9A0_defconfig/faillog 
ld.lld: error: hso.c:(function hso_serial_open: .text+0x110F0): relocation R_ARM_CALL out of range: -33554436 is not in [-33554432, 33554431]
ld.lld: error: drbd_debugfs.c:(function in_flight_summary_show: .text+0x1D98): relocation R_ARM_CALL out of range: -33554436 is not in [-33554432, 33554431]

These are always within a few bytes of the expected range for R_ARM_CALL, so my best guess is that the linker adds trampolines for calls that are further apart, but not those that are just within the range, but then the added trampolines cause other symbols to fall out of the range.

Updating the kernel sources sometimes randomly changes which symbols are affected, but without avoiding the problem itself.

[0xFD37B9A0_defconfig.gz](https://github.com/ClangBuiltLinux/linux/files/6012878/0xFD37B9A0_defconfig.gz)
[0xAF64BE88_defconfig.gz](https://github.com/ClangBuiltLinux/linux/files/6012879/0xAF64BE88_defconfig.gz)

**Comment by MaskRay** [comment] 2021-02-20 00:48
@smithp35

**Comment by smithp35** [comment] 2021-02-22 09:38
I can take a look, but it will have to be in spare time so it may take a few days. The trampoline addition is done via repeated "insert trampoline", "recalculate addresses" until no more trampolines need inserting so it is expected be able to handle the impact of inserting trampolines affecting calls that were just out of range. 

I can think of a few possible problems:
* There is a range calculation error somewhere (consistently 4-bytes out looks suspicious). The Arm branch range is a bit awkward due to signed offset and 8 byte PC-bias so it is possible a mistake has been made somewhere.
* There are sizes that change after trampoline insertion, there weren't any at time of writing the trampoline code but it is possible they've crept in.
* IIRC the code didn't handle arbitrary addends very well, BL symbol + 256. I've not known any compiled code use this before but I guess there is always the first.

**Comment by smithp35** [comment] 2021-02-23 11:33
Would it be possible to write out the instructions I need to reproduce from the config files? I can make a guess, but if someone knows of the top of their head it could save me a lot of time. Alternatively, and preferably for me, if the output of lld --reproduce can be saved and put/sent to me then that would be ideal. It is likely that unless I get precisely the same inputs this won't reproduce. A final alternative is if I send a patch to LLD with some extra debugging information (such as are the relocations all in range after thunk creation, if yes then the addresses have been changed afterwards etc.)

I've made some checks by testing boundary conditions and I have a theory but no failing test case.
Checked:
* Range check of BL is fine
* Range check of when thunk is needed is fine
* Range check of when thunk can be used is fine
* Range check of when short branch thunk can be used is fine

I had a theory that assignOffsets could in some rare circumstances not detect a change in thunk status as it relies on the size of the section to monotonically increase. Given that a long thunk may never transition to a short one, and the order of sections doesn't change I can't see that check failing for that purpose. 

My next theory that I haven't checked yet is in Writer.cpp
https://github.com/llvm/llvm-project/blob/main/lld/ELF/Writer.cpp#L1698
Reproduced below:
`
template <class ELFT> void Writer<ELFT>::finalizeAddressDependentContent() {
  llvm::TimeTraceScope timeScope("Finalize address dependent content");
  ThunkCreator tc;
  AArch64Err843419Patcher a64p;
  ARMErr657417Patcher a32p;
  script->assignAddresses();
  // .ARM.exidx and SHF_LINK_ORDER do not require precise addresses, but they
  // do require the relative addresses of OutputSections because linker scripts
  // can assign Virtual Addresses to OutputSections that are not monotonically
  // increasing.
  for (Partition &part : partitions)
    finalizeSynthetic(part.armExidx);
  resolveShfLinkOrder();

  // Converts call x@GDPLT to call __tls_get_addr
  if (config->emachine == EM_HEXAGON)
    hexagonTLSSymbolUpdate(outputSections);

  int assignPasses = 0;
  for (;;) {
    bool changed = target->needsThunks && tc.createThunks(outputSections);

    // With Thunk Size much smaller than branch range we expect to
    // converge quickly; if we get to 15 something has gone wrong.
    if (changed && tc.pass >= 15) {
      error("thunk creation not converged");
      break;
    }

    if (config->fixCortexA53Errata843419) {
      if (changed)
        script->assignAddresses();
      changed |= a64p.createFixes();
    }
    if (config->fixCortexA8) {
      if (changed)
        script->assignAddresses();
      changed |= a32p.createFixes();
    }

    if (in.mipsGot)
      in.mipsGot->updateAllocSize();

    for (Partition &part : partitions) {
      changed |= part.relaDyn->updateAllocSize();
      if (part.relrDyn)
        changed |= part.relrDyn->updateAllocSize();
    }

    const Defined *changedSym = script->assignAddresses();
    if (!changed) {
      // Some symbols may be dependent on section addresses. When we break the
      // loop, the symbol values are finalized because a previous
      // assignAddresses() finalized section addresses.
      if (!changedSym)
        break;
      if (++assignPasses == 5) {
        errorOrWarn("assignment to symbol " + toString(*changedSym) +
                    " does not converge");
        break;
      }
    }
  }

  // If addrExpr is set, the address may not be a multiple of the alignment.
  // Warn because this is error-prone.
  for (BaseCommand *cmd : script->sectionCommands)
    if (auto *os = dyn_cast<OutputSection>(cmd))
      if (os->addr % os->alignment != 0)
        warn("address (0x" + Twine::utohexstr(os->addr) + ") of section " +
             os->name + " is not a multiple of alignment (" +
             Twine(os->alignment) + ")");
}
`

If  finalizeSynthetic(part.armExidx); changes addresses then assignAddresses is not called before the first round of Thunks. If thunk creation returns no thunks based on slightly out of date addresses we will break out of the loop. If the out of date addresses meant that a thunk was necessary we will have missed it. I should be able to write a test case for that but I'm unsure whether it would be likely to affect the kernel as usually exception tables are discarded, or placed in a location where they don't affect the address of the code.

To check this theory I suggest adding something like the following after resolveShfLinkOrder();
if (config->emachine == EM_ARM)
  script->assignAddresses();

The optimizeBasicBlockJumps() is not safe in the presence of thunks but I don't think it is supported on Arm and in any case requires basic block sections to be enabled https://github.com/llvm/llvm-project/blob/main/lld/ELF/Writer.cpp#L1819

**Comment by smithp35** [comment] 2021-02-23 12:46
I've a test case that can provoke the error. No idea if it is the problem affecting the kernel though:
bl.s

        .section .text.0, "ax"
        .globl dst
        .globl src
        .type dst, %function
        .type src, %function
        .arm
         .fnstart
        .cantunwind
        dst:    nop
        .fnend

        .section .text.1, "ax"

        .global nop1
        .type nop1, %function
        nop1:
        .fnstart
        nop
        .cantunwind
        .fnend


        .section .text.2, "ax"

        .arm
        src:    .fnstart
        bl dst
        .cantunwind
        .fnend

with linker script

SECTIONS {
  .ARM.exidx 0 : { *(.ARM.exidx) }
  .text.0  : { *(.text.0) }
  .text.1 : { *(.text.1) }
  .text.2 0x200000c : { *(.text.2) }
}


> llvm-mc bl.s --triple=armv7-a-linux-gnueabihf -filetype=obj -o bl.o --arm-add-build-attributes
> ld.lld bl.o -o bl.axf --image-base=0 --nmagic --script=bl.lds
> ld.lld: error: bl.o:(.text.2+0x0): relocation R_ARM_CALL out of range: -33554436 is not in [-33554432, 33554431]; references dst
> defined in bl.o

The linker script is not needed, but it avoids the need for .space directives in the assembler file. The fault is caused by the estimation of the size of .ARM.exidx pre finalize being larger than the merged + sentinel size post finalize. This enough to trick the thunks generation code to thinking dst is in range.

I can confirm that the suggestion I made in the comment above fixes this problem.

**Comment by smithp35** [comment] 2021-02-23 12:47
Will prepare a patch soon. If there is a rush then I'm quite happy for someone else to submit one, the information to fix and a test case is here.

**Comment by arndb** [comment] 2021-02-23 12:50
Uploaded a tarball with a reproducer to 
https://drive.google.com/file/d/1Rc3-2msYxEjyWFOZnxN0HI-hzWDrzm_b/view?usp=sharing

**Comment by arndb** [comment] 2021-02-23 12:51
There is no rush on this, as far as I know this is a very rare problem that happens during randconfig test builds but not for production kernels.

**Comment by smithp35** [comment] 2021-02-23 13:24
Thanks for the example. Sadly the problem I found doesn't look to be the same one affecting the kernel. Will keep looking.

**Comment by smithp35** [comment] 2021-02-23 14:34
OK I think I know what the problem is. I think https://github.com/llvm/llvm-project/blob/main/lld/ELF/Relocations.cpp#L1956 is double counting the pc bias (having previously been added on https://github.com/llvm/llvm-project/blob/main/lld/ELF/Relocations.cpp#L1936

Will need some time to write a small test case. It involves a thunk going out of range of its caller by 8 bytes (pc-bias), when it tries to find another func, due to the double counting of the pc-bias it passes the range check of the thunk it has just decided it was out of range from.

**Comment by smithp35** [comment] 2021-02-24 09:41
Writing a small test case in assembler to reproduce has defeated me, it needs several things to happen after a few iterations of the algorithm, then landing an out of range within 8-bytes and my brain can't think that far ahead. 

In trying I've spotted at least one other problem with the PC-bias although that is a reuse efficiency problem https://github.com/llvm/llvm-project/blob/main/lld/ELF/Relocations.cpp#L1975 needs to subtract the pc-bias. Fixing this also fixes, or at least masks, the kernel build problem.

My thoughts on how to proceed here are to do the refactoring to the Arm target in LLD (inBranchRange needs to handle addends) then we can remove the pc-bias from the Thunk code. This will fix both of these problems and simplify the code.

**Comment by smithp35** [comment] 2021-02-26 14:07
Created https://reviews.llvm.org/D97550 

This refactors the Arm inBranchRange to not add in the PC-bias, instead it will get that information from the addend. It permits many calls to getPCBias() to be removed which fixes the problem found in https://github.com/llvm/llvm-project/blob/main/lld/ELF/Relocations.cpp#L1975

My original diagnosis in "OK I think I know what the problem is." Looks to be incorrect, or at least incomplete as the addend is only used as a key.

**Comment by arndb** [comment] 2021-02-26 14:32
Thanks a lot for the fix.

Do you need me to test this on the randconfig build machine, or can I wait until I get it from the daily builds once it is merged?

**Comment by smithp35** [comment] 2021-02-26 16:35
I'm hoping it will be OK to wait till it gets merged. If upstream are a bit nervous about the change it might be useful to get some evidence that it isn't breaking anything.

**Closed as completed** 2021-03-02 11:06 UTC
Labels: [TOOL] lld, [ARCH] arm32, [FIXED][LLVM] 13

**Comment by nickdesaulniers** [comment] 2021-03-02 18:30
I can't verify 0xAF64BE88_defconfig.gz; I hit #1276 .

For 0xFD37B9A0_defconfig.gz;
> ld.lld: error: undefined symbol: iwl_so_trans_cfg
>>> referenced by drv.c
>>>               net/wireless/intel/iwlwifi/pcie/drv.o:(iwl_pci_probe) in archive drivers/built-in.a

(Am I supposed to be able to:
```sh
$ wget https://github.com/ClangBuiltLinux/linux/files/6012878/0xFD37B9A0_defconfig.gz
$ gunzip 0xFD37B9A0_defconfig.gz
$ cp 0xFD37B9A0_defconfig .config
$ ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- make LLVM=1 LLVM_IAS=1 -j72 clean olddefconfig
$ ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- make LLVM=1 LLVM_IAS=1 -j72
```
?)

**Comment by arndb** [comment] 2021-03-02 20:57
I have added quick patch to #1276, while the other build error needs https://lore.kernel.org/lkml/20210225143236.3543360-1-arnd@kernel.org/raw .

Unfortunately, reproducing the bug is not 100% reliable as the specific symbol that gets hit changes with pretty much any kernel or toolchain change. With the two fixes on top of my current tree, I cannot reproduce the bug with the  0xFD37B9A0 config, but I do see it with the 0xFD37B9A0 config using lld-1:13.0-53~20210203102228.6

**Comment by arndb** [comment] 2021-03-03 22:26
Retesting the same kernel with 1:13~++20210303104412+3b47bd32f9df-1~exp1~20210303095117.250, and I cannot reproduce the problem any more. I assume the fix worked, thanks a lot!
