### ISSUE TITLE
drivers/gpu/drm/i915/gem/i915_gem_execbuffer: objtool warning on stack state mismatch

### ISSUE THREAD

**Issue by bulwahn** [ClangBuiltLinux/linux#1192] opened 2020-11-06 04:07 UTC
Build with clang-10.0.1 on x86_64 defconfig on next-20201105 reports these objtool warnings:

```
drivers/gpu/drm/i915/gem/i915_gem_execbuffer.o: warning: objtool: eb_prefault_relocations()+0xc6: stack state mismatch: cfa1=7+8 cfa2=-1+0
drivers/gpu/drm/i915/gem/i915_gem_execbuffer.o: warning: objtool: eb_copy_relocations()+0x249: stack state mismatch: cfa1=7+104 cfa2=-1+0
```

**Comment by dileks** [comment] 2020-12-27 18:55
CC @jpoimboe

Looks similiar here:
```
$ grep -i warning: build-log_5.10.3-1-amd64-clang-ias.txt | grep i915
drivers/gpu/drm/i915/gem/i915_gem_execbuffer.o: warning: objtool: eb_relocate_parse_slow()+0x3e3: stack state mismatch: cfa1=7+120 cfa2=-1+0
drivers/gpu/drm/i915/gem/i915_gem_execbuffer.o: warning: objtool: eb_copy_relocations()+0x229: stack state mismatch: cfa1=7+120 cfa2=-1+0
```

**Comment by dileks** [comment] 2020-12-28 15:31
@bulwahn 

If this is a different issue I can open a new issue?

**Comment by bulwahn** [comment] 2020-12-28 17:22
Agree. It looks pretty similar.

I just cross-checked on next-20201223; the warning on defconfig still occurs:

```
drivers/gpu/drm/i915/gem/i915_gem_execbuffer.o: warning: objtool: eb_prefault_relocations()+0xc6: stack state mismatch: cfa1=7+8 cfa2=-1+0
drivers/gpu/drm/i915/gem/i915_gem_execbuffer.o: warning: objtool: eb_copy_relocations()+0x249: stack state mismatch: cfa1=7+104 cfa2=-1+0
```

**Comment by bulwahn** [comment] 2020-12-28 17:29
On current master, v5.11-rc1, the same error on defconfig is reported:
```
drivers/gpu/drm/i915/gem/i915_gem_execbuffer.o: warning: objtool: eb_prefault_relocations()+0xc6: stack state mismatch: cfa1=7+8 cfa2=-1+0
drivers/gpu/drm/i915/gem/i915_gem_execbuffer.o: warning: objtool: eb_copy_relocations()+0x249: stack state mismatch: cfa1=7+104 cfa2=-1+0
```

**Comment by bulwahn** [comment] 2020-12-28 17:30
Let us track these issues in the same one for now; probably they will be resolved by the same fix anyway.

**Comment by dileks** [comment] 2020-12-28 17:31
OK, let's see what @jpoimboe says.

**Comment by jpoimboe** [comment] 2021-01-05 22:05
The warning is caused by some unusual code which is saving/restoring the stack pointer:
```
0000000000004dc0 <eb_prefault_relocations>:
    4dc0:	44 8b 47 58          	mov    0x58(%rdi),%r8d
    4dc4:	4d 85 c0             	test   %r8,%r8
    4dc7:	0f 84 ba 00 00 00    	je     4e87 <eb_prefault_relocations+0xc7>
    4dcd:	49 b9 00 f0 ff ff ff 	movabs $0xfffffffffff000,%r9
    4dd4:	ff ff 00 
    4dd7:	45 31 d2             	xor    %r10d,%r10d
    4dda:	49 bb 00 f0 ff ff ff 	movabs $0x7ffffffff000,%r11
    4de1:	7f 00 00 
    4de4:	eb 2d                	jmp    4e13 <eb_prefault_relocations+0x53>
    4de6:	66 2e 0f 1f 84 00 00 	nopw   %cs:0x0(%rax,%rax,1)
    4ded:	00 00 00 
    4df0:	48 89 c2             	mov    %rax,%rdx
    4df3:	48 89 d4             	mov    %rdx,%rsp
    4df6:	48 83 c1 ff          	add    $0xffffffffffffffff,%rcx
    4dfa:	48 89 c8             	mov    %rcx,%rax
    4dfd:	e8 00 00 00 00       	callq  4e02 <eb_prefault_relocations+0x42>
			4dfe: R_X86_64_PLT32	__get_user_nocheck_1-0x4
    4e02:	85 c0                	test   %eax,%eax
    4e04:	0f 85 7c 00 00 00    	jne    4e86 <eb_prefault_relocations+0xc6>
    4e0a:	49 83 c2 01          	add    $0x1,%r10
    4e0e:	4d 39 c2             	cmp    %r8,%r10
    4e11:	74 74                	je     4e87 <eb_prefault_relocations+0xc7>
    4e13:	48 8b 47 18          	mov    0x18(%rdi),%rax
    4e17:	49 6b d2 38          	imul   $0x38,%r10,%rdx
    4e1b:	8b 4c 10 04          	mov    0x4(%rax,%rdx,1),%ecx
    4e1f:	48 85 c9             	test   %rcx,%rcx
    4e22:	74 e6                	je     4e0a <eb_prefault_relocations+0x4a>
    4e24:	48 8b 74 10 08       	mov    0x8(%rax,%rdx,1),%rsi
    4e29:	48 c1 e1 05          	shl    $0x5,%rcx
    4e2d:	4c 89 ca             	mov    %r9,%rdx
    4e30:	e9 00 00 00 00       	jmpq   4e35 <eb_prefault_relocations+0x75>
			4e31: R_X86_64_PC32	.altinstr_aux+0x56
    4e35:	4c 89 ca             	mov    %r9,%rdx
    4e38:	eb 09                	jmp    4e43 <eb_prefault_relocations+0x83>
    4e3a:	66 0f 1f 44 00 00    	nopw   0x0(%rax,%rax,1)
    4e40:	4c 89 da             	mov    %r11,%rdx
    4e43:	b8 f2 ff ff ff       	mov    $0xfffffff2,%eax
    4e48:	48 01 f1             	add    %rsi,%rcx
    4e4b:	72 39                	jb     4e86 <eb_prefault_relocations+0xc6>
    4e4d:	48 39 d1             	cmp    %rdx,%rcx
    4e50:	77 34                	ja     4e86 <eb_prefault_relocations+0xc6>
    4e52:	48 89 e0             	mov    %rsp,%rax
    4e55:	48 39 f1             	cmp    %rsi,%rcx
    4e58:	76 96                	jbe    4df0 <eb_prefault_relocations+0x30>
    4e5a:	66 0f 1f 44 00 00    	nopw   0x0(%rax,%rax,1)
    4e60:	48 89 c4             	mov    %rax,%rsp
    4e63:	48 89 f0             	mov    %rsi,%rax
    4e66:	e8 00 00 00 00       	callq  4e6b <eb_prefault_relocations+0xab>
			4e67: R_X86_64_PLT32	__get_user_nocheck_1-0x4
    4e6b:	85 c0                	test   %eax,%eax
    4e6d:	75 17                	jne    4e86 <eb_prefault_relocations+0xc6>
    4e6f:	48 89 e0             	mov    %rsp,%rax
    4e72:	48 89 e2             	mov    %rsp,%rdx
    4e75:	48 81 c6 00 10 00 00 	add    $0x1000,%rsi
    4e7c:	48 39 ce             	cmp    %rcx,%rsi
    4e7f:	72 df                	jb     4e60 <eb_prefault_relocations+0xa0>
    4e81:	e9 6d ff ff ff       	jmpq   4df3 <eb_prefault_relocations+0x33>
    4e86:	c3                   	retq   
    4e87:	31 c0                	xor    %eax,%eax
    4e89:	c3                   	retq   
    4e8a:	66 0f 1f 44 00 00    	nopw   0x0(%rax,%rax,1)

```
There are several cases of saving/restoring %rsp in that function, for seemingly no reason.  For example:
```
    4e52:	48 89 e0             	mov    %rsp,%rax
    4e55:	48 39 f1             	cmp    %rsi,%rcx
    4e58:	76 96                	jbe    4df0 <eb_prefault_relocations+0x30>
    4e5a:	66 0f 1f 44 00 00    	nopw   0x0(%rax,%rax,1)
    4e60:	48 89 c4             	mov    %rax,%rsp
...
    4df0:	48 89 c2             	mov    %rax,%rdx
    4df3:	48 89 d4             	mov    %rdx,%rsp

```

**Comment by nickdesaulniers** [comment] 2021-01-07 18:29
cc @topperc any idea what might cause `%rsp` to be spilled/reloaded? It doesn't look like it's being used as a GPR (I would have guessed maybe register pressure).

**Comment by topperc** [comment] 2021-01-07 18:45
Can you provide me pre-processed source code and the clang command line so I can take look?

**Comment by nickdesaulniers** [comment] 2021-01-07 21:29
This seems very specific to clang-10 or clang-11; I can't repro with ToT LLVM (clang-12), but can when I checkout+build origin/release/11.x.  So probably going to close at wontfix.  We can run a bisection on upstream LLVM to see where the fix came from.

**Closed** 2021-04-28 22:50 UTC
Labels: [BUG] linux, [BUG] linux-next, [BUG] linux-stable, [FIXED][LLVM] 12, [Reported-by] KernelCI, [TOOL] objtool
