### ISSUE TITLE
static calls on x86_64 are broken with clang conditional tail calls

### ISSUE THREAD

**Issue by ernsteiswuerfel** [ClangBuiltLinux/linux#1774] opened 2022-12-23 19:50 UTC
Got another seemingly clang problem on another box of mine. Built with clang-15.0.6 the 6.1.1 kernel fails to boot on the machine, stuck at showing the "Loading Linux 6.1.1 ..." message. I don't get any screen/console output after that, it's also too early for netconsole. So unfortunately I can't provide more details.

The same kernel + config built with GCC 12 just boots fine. I'll attach the 2 configs and the dmesg from a successfull GCC 12 kernel boot.

Some data about the machine:
```
$ inxi -bZ
System:
  Host: outsider Kernel: 6.1.1-bdver2 arch: x86_64 bits: 64 Desktop: MATE
    v: 1.26.0 Distro: Gentoo Base System release 2.9
Machine:
  Type: Desktop System: Gigabyte product: N/A v: N/A
    serial: <superuser required>
  Mobo: Gigabyte model: 970-GAMING v: x.x serial: <superuser required>
    UEFI: American Megatrends v: F2 date: 04/06/2016
CPU:
  Info: 8-core AMD FX-8370 [MT MCP] speed (MHz): avg: 1491 min/max: 1400/4000
Graphics:
  Device-1: AMD Turks XT [Radeon HD 6670/7670] driver: radeon v: kernel
  Display: x11 server: X.Org v: 21.1.4 driver: X: loaded: radeon
    unloaded: fbdev,modesetting gpu: radeon resolution: 1920x1080~60Hz
  OpenGL: renderer: AMD TURKS (DRM 2.50.0 / 6.1.1-bdver2 LLVM 15.0.6)
    v: 3.3 Mesa 22.2.3
Network:
  Device-1: Qualcomm Atheros Killer E2400 Gigabit Ethernet driver: alx
```
[config_611_clang.txt](https://github.com/ClangBuiltLinux/linux/files/10297093/config_611_clang.txt)
[config_611_gcc.txt](https://github.com/ClangBuiltLinux/linux/files/10297094/config_611_gcc.txt)
[dmesg_611_gcc.txt](https://github.com/ClangBuiltLinux/linux/files/10297095/dmesg_611_gcc.txt)

**Comment by ernsteiswuerfel** [comment] 2022-12-30 16:01
Definitely a problem. Same issue on my Thinkpad A275.

Booting does not get past the initial "Loading Linux 6.1.1 ..." message on screen. No netconsole output.

**Comment by nathanchance** [comment] 2022-12-30 22:21
I will see if I can reproduce this through QEMU on Tuesday when I get back online (I am running out of time today) but something that immediately sticks out to me in your `clang` configuration is `CONFIG_INIT_STACK_ALL_PATTERN=y` (I realize it is there for GCC as well but there could be other internal compiler differences). Does changing that choice to `CONFIG_INIT_STACK_NONE=y` fix this issue? It is entirely possible that we have an uninitialized variable somewhere that is fine with even zero initialization but not the pattern initialization, which purposefully poisons the initialization with a large value.

Lack of output will make getting more information a little bit more difficult if that does not work...

**Comment by ernsteiswuerfel** [comment] 2022-12-31 15:54
Ok tried now with INIT_STACK_NONE and LTO_NONE (was  LTO_CLANG_THIN before) but unfortunately it didn't make a difference.

**Comment by nathanchance** [comment] 2023-01-03 16:03
That's good to know! Couple of follow up questions:

1. Do you know if older kernels exhibit this issue? It would be good to know if someone on the Linux side caused this, as it might make it easier to narrow down what is going wrong.
2. Is your configuration slimmed down from another configuration? It does not have many virtual drivers so I am not sure my VM will boot without those. If it is slimmed down from another configuration, is the fuller one still available?

**Comment by ernsteiswuerfel** [comment] 2023-01-03 16:10
1. No, 6.0.x series boots & works fine (besides https://bugzilla.kernel.org/show_bug.cgi?id=216143 which is also a gcc vs. clang issue). But your are right, probably it will be easier if I'll just try a kernel bisect and see which commit it reveals.
2. Yes, this is simple the kernel drivers I need to run my machines in question. As it's easy to use custom built kernels on Gentoo I do just that. 😉

**Comment by ernsteiswuerfel** [comment] 2023-01-07 15:23
Finally found some time for the bisect which revealed following commit:
```
 # git bisect bad
706460a96fc654e80b6bed1f562b00d2ce9f2f4d is the first bad commit
commit 706460a96fc654e80b6bed1f562b00d2ce9f2f4d
Author: Sandipan Das <sandipan.das@amd.com>
Date:   Thu Aug 11 17:59:51 2022 +0530

    perf/x86/amd/core: Add generic branch record interfaces
    
    AMD processors that are capable of recording branches support either Branch
    Sampling (BRS) or Last Branch Record (LBR). In preparation for adding Last
    Branch Record Extension Version 2 (LbrExtV2) support, introduce new static
    calls which act as gateways to call into the feature-dependent functions
    based on what is available on the processor.
    
    Signed-off-by: Sandipan Das <sandipan.das@amd.com>
    Signed-off-by: Peter Zijlstra (Intel) <peterz@infradead.org>
    Link: https://lore.kernel.org/r/b75dbc32663cb395f0d701167e952c6a6b0445a3.1660211399.git.sandipan.das@amd.com

 arch/x86/events/amd/core.c | 34 ++++++++++++++++++++++------------
 1 file changed, 22 insertions(+), 12 deletions(-)
```
Unfortunately I can't test this via simply reverting the commit on v6.1.4 or v6.1-rc1 as it is part of a larger series ([klick](https://lore.kernel.org/all/cover.1660211399.git.sandipan.das@amd.com/#t)) Reverting the whole series on current stable or -rc1 failed too.

Bisect log attached: [bisect.log](https://github.com/ClangBuiltLinux/linux/files/10366585/bisect.log)

**Comment by ernsteiswuerfel** [comment] 2023-01-19 01:25
Turns out kernel v6.2-rc4 is still affected. Posted the issue now at linux-kernel@vger.kernel.org  CCing Sandipan and Peter.
[config_62-rc4_bdver4.txt](https://github.com/ClangBuiltLinux/linux/files/10452584/config_62-rc4_bdver4.txt)

**Comment by sandip4n** [comment] 2023-01-19 10:52
@ernsteiswuerfel With my daily development config and LLVM/Clang 16 packages from apt.llvm.org, I was able to build and boot the latest upstream kernel with  on a system with an AMD EPYC 7713 processor. With the 6.2-rc4 config that you attached in the comment above, I wasn't able to build a bootable kernel with either Clang 16 or GCC 11 (both bare-metal and guest boot failed). The commit in question just adds some static calls and I see that `CONFIG_HAVE_STATIC_CALL*` is enabled in your config as well. Need to investigate further and see what is making a difference.

Attaching my config as well:
[linux-config-llvm-16.txt](https://github.com/ClangBuiltLinux/linux/files/10455953/linux-config-llvm-16.txt)

**Comment by nathanchance** [comment] 2023-01-19 15:59
@sandip4n I believe @ernsteiswuerfel's configurations were stripped down for particular machines so it is possible that it not working for you is just due to missing drivers for your hardware.

The change around `amd_pmu_sched_task()` to `amd_pmu_brs_sched_task()` seems suspicious, since we are dropping a check against `x86_pmu.lbr_nr`, could that matter?

**Comment by sandip4n** [comment] 2023-01-20 06:11
@nathanchance The `lbr_users` check inside `amd_pmu_brs_sched_task()` seems to be sufficient for that. It is incremented only when branch stacks are requested for an event but creating such an event is possible only if `lbr_nr` is greater than zero.

Based on Peter's observations, I tried using a combination of `defconfig`, `kvm_guest.config` and `localyesconfig`. The only thing that made a difference was the choice of compiler optimization. Clang-built kernels built with `CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=y` booted just fine but not `CONFIG_CC_OPTIMIZE_FOR_SIZE=y`. This applies to both Clang 15 and 16.

Edit: I see the same happening with kernel 6.0 which doesn't have the LBRv2 patches.

**Comment by nathanchance** [comment] 2023-01-20 17:06
@sandip4n Aha, great catch! Thank you for taking a look at this.

Upstream thread: https://lore.kernel.org/20230119022303.177052e4@yea/

Pending patches from Peter: https://git.kernel.org/pub/scm/linux/kernel/git/peterz/queue.git/log/?h=x86/core

**Comment by nathanchance** [comment] 2023-01-23 21:39
These are now submitted: https://lore.kernel.org/20230123205915.751729592@infradead.org/

**Comment by nathanchance** [comment] 2023-01-31 22:14
Accepted: https://git.kernel.org/tip/923510c88d2b7d947c4217835fd9ca6bd65cc56c

Not sure if these are going to 6.2 right away but they probably should?

**Comment by ernsteiswuerfel** [comment] 2023-01-31 23:26
For me the issue appeared with 6.1.x so in the end they should probably go into 6.1 LTS as well.

**Comment by nathanchance** [comment] 2023-02-08 22:38
I have retitled the issue to be a little more descriptive. See #1800, where [a recent LLVM change](https://github.com/llvm/llvm-project/commit/ee5585ed09aff2e54cb540fad4c33f0c93626b1b) causes conditional tail calls to be generated at higher optimization levels like `-O2` and `-O3` too, resulting in the same non-booting behavior observed here.

I have pinged the upstream thread to see if this series can be applied to mainline sooner so that it can be backported sooner:

https://lore.kernel.org/Y+QkAXfhWfGevWz7@dev-arch.thelio-3990X/

@ernsteiswuerfel @ms178 I have prepared Peter's accepted series on top of 6.1.10. If you could help test it, that would be much appreciated :)

https://git.kernel.org/nathan/l/cbl-1800-1774-6.1

**Comment by ms178** [comment] 2023-02-09 09:19
@nathanchance Unfortunatly with these patches applied, I get a compile issue, Sorttab is erroring out.

**Comment by nathanchance** [comment] 2023-02-09 14:23
@ms178 what is the exact error or configuration that shows the issue?

**Comment by ms178** [comment] 2023-02-09 15:07
@nathanchance I've tried it a second time, now the Kernel compiles fine. The only thing which could be a factor was the Kernel config, the working version does not use ZSTD-compressed debug info. Update: The new Kernel also boots fine.

**Comment by ernsteiswuerfel** [comment] 2023-02-09 17:26
@nathanchance Your patchset works perfectly fine with my .config! No build problems (even with ZSTD compression) and fixes the clang -Os build for 6.1.

**Comment by ms178** [comment] 2023-02-09 19:05
@nathanchance @ernsteiswuerfel Great news! These fixes also fixed the boot problem I encountered with the Clang-PGO Kernel patch which I've just tried again on top with Kernel 6.1.11, I've used an old Kernel profile of mine and it seems to work just fine now: https://github.com/CachyOS/kernel-patches/blob/master/6.1/misc/0001-Clang-PGO.patch

**Comment by nathanchance** [comment] 2023-02-21 19:52
This is now fixed in mainline: https://git.kernel.org/linus/923510c88d2b7d947c4217835fd9ca6bd65cc56c

I have requested stable backports: https://lore.kernel.org/Y%2FUf9WUi%2FrANmOk8@dev-arch.thelio-3990X/

I am closing this for now, as there is nothing else for us to do. I will leave this pinned in the issue tracker so that there is some visibility on it until the stable backports are actually released.

**Closed as completed by nathanchance** 2023-02-21 19:52 UTC
Labels: [BUG] linux, [ARCH] x86_64, boot failure, [FIXED][LINUX] 6.3
