### ISSUE TITLE
Section mismatch in reference from the function kirin_pcie_probe()

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#101] opened 2018-09-17 23:09 UTC
```sh
  MODPOST vmlinux.o
WARNING: vmlinux.o(.text+0x1cac09c): Section mismatch in reference from the function kirin_pcie_probe() to the function .init.text:kirin_add_pcie_port()
The function kirin_pcie_probe() references
the function __init kirin_add_pcie_port().
This is often because kirin_pcie_probe lacks a __init 
annotation or the annotation of kirin_add_pcie_port is wrong.
```

This surely isn't due to clang, and may have been fixed upstream (maybe in -next tree).  Either `kirin_pcie_probe` should be marked `__init`, or `kirin_add_pcie_port` should have its `__init` removed.

`CONFIG_PCIE_KIRIN`

**Comment by nathanchance** [comment] 2018-09-17 23:16
Not fixed in -next, caused by commit 141cb3d4ee52 ("PCI: kirin: Add MSI support").

`kirin_add_pcie_port` should probably have its `__init` removed.

**Comment by nathanchance** [comment] 2018-09-19 05:39
Funny enough, I don't get this warning with GCC... I wonder if it is just silently dropping the `__init` attribute.

Regardless, it is an actual issue so patch sent: https://lore.kernel.org/lkml/20180919053829.4858-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment] 2018-10-25 16:38
Merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=6870b673509779195cab300aedc844b352d9cfbc

**Closed by nathanchance** 2018-10-25 16:38 UTC
Labels: [BUG] linux, [PATCH] Accepted, low priority
