### ISSUE TITLE
x86_64 kernels fail to boot after D140931

### ISSUE THREAD

**Issue by ms178** [ClangBuiltLinux/linux#1800] opened 2023-02-07 16:12 UTC
I've been on the distribution provided Clang-15.0.7 for a while and tried out LLVM/Clang-17 (7bff37783f72ed99e4cdd0fd7dad1bf1f119f793) today, I've noticed that my 6.1.10 Kernel compiled and booted fine with Clang-15 but now fails to boot with Clang-17 and the same flags/patches used. It hangs right when Grub tries to load the Kernel image. CPU: Intel Haswell-EP, 64-bit.

More details on the patches used, as always, [in my public repo](https://github.com/ms178/archpkgbuilds/tree/main/packages/linux-cachyos-bore).

[config.txt](https://github.com/ClangBuiltLinux/linux/files/10677089/config.txt)

While skimming through other issues, I've found https://github.com/ClangBuiltLinux/linux/issues/1774, but while the symptoms were the same, I cannot tell if they are related. As I compile my Kernel with `-O3`, and the patch series adressed issues with `-Os`, it seems to be something different to me.

**Comment by ms178** [comment] 2023-02-07 16:20
I've uploaded the faulty binaries (compatible with Arch) here: https://1drv.ms/u/s!Agwwh-axGk6DhjdKaq-2UkieWB85?e=Np26mv

**Comment by nickdesaulniers** [comment] 2023-02-07 17:54
Thanks for the report. Are you able to run a bisection against LLVM to find which commit may be the culprit?

**Comment by ms178** [comment] 2023-02-07 18:18
@nickdesaulniers I am afraid, I cannot afford too much time for that at the moment. If it is a more widespread issue, I am sure it will pop up sooner or later on some bots. I'll re-visit this with a future ToT-LLVM-17 snapshot and let you know if it had been fixed by then.

**Comment by nathanchance** [comment] 2023-02-07 18:27
I'll see if I can reproduce this in QEMU at some point today.

**Comment by nathanchance** [comment] 2023-02-08 04:22
I can reproduce this with just defconfig and mainline with current LLVM main, I am about to bisect once I find a good point. I ran into a separate QEMU main regression that impacted my ability to use my full distribution QEMU wrapper to boot my own kernels and I never thought to try `boot-qemu.py` first :)

**Comment by nathanchance** [comment] 2023-02-08 05:32
My bisect landed on commit [ee5585ed09af](https://github.com/llvm/llvm-project/commit/ee5585ed09aff2e54cb540fad4c33f0c93626b1b) ("Recommit "Improve and enable folding of conditional branches with tail calls." (2nd Try)"). I will see if I can investigate more tomorrow, unless somebody else beats me to it.

**Comment by nathanchance** [comment] 2023-02-08 20:23
Okay, this ultimately appears to have the same root cause and fix as #1774. As far as I understand it, the LLVM patch causes the problematic sequence of instructions to be emitted that caused #1774, even at `-O2`.

In other words, if I build a kernel using a toolchain that contains https://github.com/llvm/llvm-project/commit/ee5585ed09aff2e54cb540fad4c33f0c93626b1b and I pull the current [`x86/alternatives` branch from tip](https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/log/?h=x86/alternatives) (currently at [923510c88d2b7](https://git.kernel.org/tip/923510c88d2b7d947c4217835fd9ca6bd65cc56c)) into mainline, everything boots up fine for me; without `x86/alternatives`, it is broken.

I will ping that thread to see if these patches can be merged into mainline ahead of 6.3 and inquire about a backport to 6.1, as the series appears to require some changes from the call depth tracking series that was merged in 6.2.

**Comment by nathanchance** [comment] 2023-02-08 22:32
Closing this in favor of #1774, which I have renamed to more accurately describe the issue.

**Closed as completed by nathanchance** 2023-02-08 22:32 UTC
Labels: duplicate
