### ISSUE TITLE
-Wignored-attributes in arch/powerpc/platforms/maple/setup.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#943] opened 2020-03-23 21:53 UTC
```
arch/powerpc/platforms/maple/setup.c:365:1: error: attribute declaration must precede definition [-Werror,-Wignored-attributes]
machine_device_initcall(maple, maple_cpc925_edac_setup);
^
./arch/powerpc/include/asm/machdep.h:294:43: note: expanded from macro 'machine_device_initcall'
#define machine_device_initcall(mach, fn)       __define_machine_initcall(mach, fn, 6)
                                                ^
./arch/powerpc/include/asm/machdep.h:277:7: note: expanded from macro '__define_machine_initcall'
                if (machine_is(mach)) return fn(); \
                    ^
./arch/powerpc/include/asm/machdep.h:248:19: note: expanded from macro 'machine_is'
                        __attribute__((weak));           \
                                       ^
arch/powerpc/platforms/maple/setup.c:294:1: note: previous definition is here
define_machine(maple) {
^
./arch/powerpc/include/asm/machdep.h:243:23: note: expanded from macro 'define_machine'
        struct machdep_calls mach_##name __machine_desc =
                             ^
<scratch space>:218:1: note: expanded from here
mach_maple
^
```
linux-next ARCH=powerpc defconfig.

**Comment by nathanchance** [comment] 2020-03-23 21:54
Dupe of #662.

**Closed by nathanchance** 2020-03-23 21:54 UTC
Labels: -Wignored-attributes, [ARCH] powerpc, [BUG] linux, [low priority] workaround applied, good first issue
