### ISSUE TITLE
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:354: at least one side of the expression must be absolute

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/linux#377] opened 2019-02-25 17:37 UTC
When linking with `ld.lld` I see the following:
```
+ make -f ./scripts/Makefile.build obj=init
/bin/bash ./scripts/mkcompile_h include/generated/compile.h \
"x86_64" "y" "" "mycompiler -Wall -Wundef -Werror=strict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -fno-PIE -Werror-implicit-function-declaration -Werror=implicit-int -Wno-format-security -std=gnu89 -no-integrated-as -fuse-ld=lld -no-integrated-as -fuse-ld=lld -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64   -mno-80387  -mstack-alignment=8  -mtune=generic -mno-red-zone -mcmodel=kernel -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -Wno-sign-compare -fno-asynchronous-unwind-tables -mretpoline-external-thunk -fno-delete-null-pointer-checks     -O2  --param=allow-store-data-races=0  -Wframe-larger-than=2048 -fstack-protector-strong -Wno-format-invalid-specifier -Wno-gnu -Wno-address-of-packed-member -Wno-tautological-compare  -mno-global-merge  -Wno-unused-const-variable  -g -pg -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wvla -Wno-pointer-sign  -fno-strict-overflow -fno-merge-all-constants  -fno-stack-check  -Werror=date-time -Werror=incompatible-pointer-types    -Wno-initializer-overrides -Wno-unused-value -Wno-format -Wno-sign-compare -Wno-format-zero-length -Wno-uninitialized     "
(cat /dev/null; ) > init/modules.order
+ archive_builtin
+ info AR built-in.a
+ '[' '' '!=' silent_ ']'
+ printf '  %-7s %s\n' AR built-in.a
  AR      built-in.a
+ rm -f built-in.a
+ ar rcsTPD built-in.a arch/x86/kernel/head_64.o arch/x86/kernel/head64.o arch/x86/kernel/ebda.o arch/x86/kernel/platform-quirks.o init/built-in.a usr/built-in.a arch/x86/built-in.a kernel/built-in.a certs/built-in.a mm/built-in.a fs/built-in.a ipc/built-in.a security/built-in.a crypto/built-in.a block/built-in.a lib/built-in.a arch/x86/lib/built-in.a drivers/built-in.a sound/built-in.a firmware/built-in.a arch/x86/pci/built-in.a arch/x86/power/built-in.a arch/x86/video/built-in.a net/built-in.a virt/built-in.a
+ info LD vmlinux.o
+ '[' '' '!=' silent_ ']'
+ printf '  %-7s %s\n' LD vmlinux.o
  LD      vmlinux.o
+ modpost_link vmlinux.o
+ local objects
+ objects='--whole-archive                                              built-in.a                                                      --no-whole-archive                                              --start-group                        lib/lib.a  arch/x86/lib/lib.a                                           --end-group'
+ ld.lld -m elf_x86_64 -z max-page-size=0x200000 -O2 -r -o vmlinux.o --whole-archive built-in.a --no-whole-archive --start-group lib/lib.a arch/x86/lib/lib.a --end-group
+ make -f ./scripts/Makefile.modpost vmlinux.o
  scripts/mod/modpost -m  -o ./Module.symvers    -S   vmlinux.o
+ kallsymso=
+ kallsyms_vmlinux=
+ '[' -n y ']'
+ kallsymso=.tmp_kallsyms2.o
+ kallsyms_vmlinux=.tmp_vmlinux2
+ vmlinux_link '' .tmp_vmlinux1
+ local lds=./arch/x86/kernel/vmlinux.lds
+ local objects
+ '[' x86 '!=' um ']'
+ objects='--whole-archive                                              built-in.a                                                      --no-whole-archive                                              --start-group                        lib/lib.a  arch/x86/lib/lib.a                                           --end-group                                                     '
+ ld.lld -m elf_x86_64 -z max-page-size=0x200000 -O2 --emit-relocs --build-id -X -o .tmp_vmlinux1 -T ./arch/x86/kernel/vmlinux.lds --whole-archive built-in.a --no-whole-archive --start-group lib/lib.a arch/x86/lib/lib.a --end-group
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:354: at least one side of the expression must be absolute
ld.lld: error: ./arch/x86/kernel/vmlinux.lds:355: at least one side of the expression must be absolute
+ on_exit
+ '[' 1 -ne 0 ']'
+ cleanup
+ rm -f .tmp_System.map
+ rm -f '.tmp_kallsyms*'
+ rm -f '.tmp_vmlinux*'
+ rm -f built-in.a
+ rm -f System.map
+ rm -f vmlinux
+ rm -f vmlinux.o
make[3]: *** [Makefile:1028: vmlinux] Error 1
```

**Comment by nathanchance** [comment] 2019-02-25 17:41
Duplicate of #29.

**Closed by nathanchance** 2019-02-25 17:41 UTC
Labels: [ARCH] x86_64, lld
