### ISSUE TITLE
-Wframe-larger-than in net/rxrpc/rxkad.c

### ISSUE THREAD

**Issue by tpgxyz** [ClangBuiltLinux/linux#699] opened 2019-09-24 20:55 UTC
Trying to compile kernel 5.3.1 with LLVM/clang on armv7hnl
Full log is here https://abf.openmandriva.org/build_lists/610529 also links to GitHub sources.

```
  CC [M]  net/rxrpc/rxkad.o
BUILDSTDERR: net/rxrpc/rxkad.c:240:12: warning: stack frame size of 1280 bytes in function 'rxkad_secure_packet' [-Wframe-larger-than=]
BUILDSTDERR: static int rxkad_secure_packet(struct rxrpc_call *call,
BUILDSTDERR:            ^
BUILDSTDERR: net/rxrpc/rxkad.c:487:12: warning: stack frame size of 1280 bytes in function 'rxkad_verify_packet' [-Wframe-larger-than=]
BUILDSTDERR: static int rxkad_verify_packet(struct rxrpc_call *call, struct sk_buff *skb,
BUILDSTDERR:            ^
BUILDSTDERR: 2 warnings generated.
```

**Comment by nickdesaulniers** [comment] 2021-04-22 21:23
Thank you for submitting this bug report.  I'm not able to reproduce
it using llvm @ c440b97d89994feb965a9026bc121d154f7b4584 and linux at 16fc44d6387e260f4932e9248b985837324705d8 using the following commands:
```sh
$ wget https://raw.githubusercontent.com/OpenMandrivaAssociation/kernel-release/master/armv7hnl-desktop-omv-defconfig -O .config
$ ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make LLVM=1 -j72 olddefconfig
$ ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make LLVM=1 -j72 menuconfig
<re-enable CONFIG_RXKAD=y, re-enable CONFIG_FRAME_WARN=1024>
$ ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make LLVM=1 -j72  net/rxrpc/rxkad.o
```

Therefore, I am closing this bug report as obsolete; please feel free
to reopen with additional steps to reproduce beyond what was attempted
above.

**Closed by nickdesaulniers** 2021-04-22 21:23 UTC
Labels: -Wframe-larger-than=, [ARCH] arm32, low priority
