### ISSUE TITLE
macro defined with named parameters which are not used in macro body, possible positional parameter found in body which will have no effect

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1444] opened 2021-08-30 17:21 UTC
building linux-next for mips:
```
./arch/mips/include/asm/asmmacro.h:48:2: warning: macro defined with named parameters which are not used in macro body, possible positional parameter found in body which will have no effect
 .macro local_irq_enable reg=$8
 ^
./arch/mips/include/asm/asmmacro.h:53:2: warning: macro defined with named parameters which are not used in macro body, possible positional parameter found in body which will have no effect
 .macro local_irq_disable reg=$8
 ^
```

**Comment by nathanchance** [comment] 2021-08-30 17:27
Dupe of #1415.

**Closed as completed by nathanchance** 2021-08-30 17:27 UTC
Labels: duplicate
