### ISSUE TITLE
can't find switch jump table in drivers/ata/sata_dwc_460ex.o

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#873] opened 2020-02-13 17:41 UTC
via allyesconfig:

```sh
$ ./tools/objtool/objtool orc generate  --no-fp --no-unreachable --retpoline --uaccess drivers/ata/sata_dwc_460ex.o
drivers/ata/sata_dwc_460ex.o: warning: objtool: sata_dwc_bmdma_start_by_tag()+0x3a2: can't find switch jump table
```

[drivers_ata_sata_dwc_460ex.o.txt](https://github.com/ClangBuiltLinux/linux/files/4199983/drivers_ata_sata_dwc_460ex.o.txt)

**Comment by nathanchance** [comment] 2020-02-13 18:10
Dupe of #485.

**Closed by nathanchance** 2020-02-13 18:10 UTC
Labels: [ARCH] x86_64, [BUG] linux-next, [TOOL] objtool
