### ISSUE TITLE
source register same as write-back base

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#923] opened 2020-03-06 23:48 UTC
Reported-by: kernelci.org bot <bot@kernelci.org>

```
$ ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make CC=clang -j71 badge4_defconfig
$ ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make CC=clang -j71 kernel/futex.o
/tmp/futex-00ae91.s: Assembler messages:
/tmp/futex-00ae91.s:28310: Warning: source register same as write-back base
$ ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make CC=clang -j71 kernel/futex.s
$ arm-linux-gnueabihf-as kernel/futex.s
kernel/futex.s: Assembler messages:
kernel/futex.s:9107: Warning: source register same as write-back base
```

kernel/futex.s:9107 looks like:
```
2:  strteq  r1, [r1]                                                            
```

**Comment by nickdesaulniers** [comment] 2020-03-06 23:50
This is coming from `arch/arm/include/asm/futex.h` `futex_atomic_cmpxchg_inatomic`'s inline asm `TUSERCOND`.

**Comment by ihalip** [comment] 2020-03-08 07:31
This doesn't happen at `-O0`.

**Comment by nickdesaulniers** [comment] 2020-03-08 08:25
[strt](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0471h/Cjagfhbb.html)-[eq](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.100076_0200_00_en/dom1361289860997.html).

**Comment by ihalip** [comment] 2020-03-09 10:59
The same thing happens with GCC (on my machine, arm-linux-gnueabihf-gcc version 7.4.0): https://godbolt.org/z/DoV98X

**Comment by nickdesaulniers** [comment] 2020-03-09 20:34
ah, that's helpful, thanks!  It seems like GCC is emitting `.thumb`
```asm
  .text                                                                                                                          
  .syntax unified                                                                                                                
  .thumb                                                                                                                         
main:                                                                                                                            
  it  eq  @ explicit IT needed for the 2b label                                                                                  
  2:  strteq  r3, [r3]
```
whereas gcc is not.  cc @agners , I wonder if we need to put `.thumb` in the inline asm?  kernel/futex.o is being compiled as `-marm`.  Is the inline asm thumb syntax?

From the example @ihalip provided:
```sh
$ arm-linux-gnueabihf-gcc -O2 y.c
$ arm-linux-gnueabihf-gcc -O2 y.c -mthumb
$ arm-linux-gnueabihf-gcc -O2 y.c -marm                               
/tmp/cckbXZCx.s: Assembler messages:
/tmp/cckbXZCx.s:36: Warning: source register same as write-back base

$ clang -O2 y.c --target=arm-linux-gnueabihf -no-integrated-as      
/tmp/y-1506fd.s: Assembler messages:
/tmp/y-1506fd.s:39: Warning: source register same as write-back base
$ clang -O2 y.c --target=arm-linux-gnueabihf -no-integrated-as -mthumb
/tmp/y-4057dd.s: Assembler messages:
/tmp/y-4057dd.s:38: Error: selected processor does not support `ldrt r3,[r0]' in Thumb mode
/tmp/y-4057dd.s:39: Error: selected processor does not support `teq r3,r0' in Thumb mode
/tmp/y-4057dd.s:40: Error: selected processor does not support `it eq' in Thumb mode
/tmp/y-4057dd.s:41: Error: selected processor does not support `strteq r0,[r0]' in Thumb mode
clang-11: error: assembler command failed with exit code 1 (use -v to see invocation)
$ clang -O2 y.c --target=arm-linux-gnueabihf -no-integrated-as -marm  
/tmp/y-df1c04.s: Assembler messages:
/tmp/y-df1c04.s:39: Warning: source register same as write-back base
```

**Comment by nickdesaulniers** [comment] 2020-03-09 20:35
cc @smithp35

**Comment by smithp35** [comment] 2020-03-09 20:51
From https://static.docs.arm.com/ddi0487/fa/DDI0487F_a_armv8_arm.pdf
F5.1.243 STRT
The A32 instruction uses a post-indexed addressing mode, that uses a base register value as the address for the memory access, and calculates a new address from a base register value and an offset and writes it back to the base register.

STRT{<c>}{<q>} <Rt>, [<Rn>] {, #{+/-}<imm>}
Decode for this encoding
t = UInt(Rt); n = UInt(Rn); postindex = TRUE; add = (U == '1');
register_form = FALSE; imm32 = ZeroExtend(imm12, 32);
if n == 15 || n == t then UNPREDICTABLE;

This would imply that in Arm state strteq  r1, [r1]  is unpredictable as n == t.

In your example above clang -O2 y.c --target=arm-linux-gnueabihf -no-integrated-as -mthumb
I think that should pass -mthumb to GNU as (check using -v) however it might give it a -mcpu that doesn't support the strt instruction.

Apologies at home at the moment.

**Comment by agners** [comment] 2020-03-10 00:22
@nickdesaulniers The header file can be assembled by either Thumb or ARM, depending what the kernel configuration has been. But this has nothing to do with Thumb from what I can tell. 

The `TUSERCOND` macro just makes sure to generate a `ldr`/`str` with `t` at the end to indicate that a user load/store is being done.

So it seems that inlining can lead to break assumptions being made that %3/%4 are different registers? Can we convey such restrictions using assembly syntax somehow?

**Comment by nickdesaulniers** [comment] 2020-03-10 04:08
> The same thing **can happen** with GCC (on my machine, arm-linux-gnueabihf-gcc version 7.4.0): https://godbolt.org/z/DoV98X
> Clang inlines the `cmpxchg_futex_value_locked` function, GCC doesn't. If I mark it as inline and build with GCC, I get the same message.

I wonder then when `cmpxchg_futex_value_locked` gets inlined [here](https://github.com/torvalds/linux/blob/0cc2682d8baaa6c7383e40153afc19239ad28d77/kernel/futex.c#L4150).  `NULL` declared as `(void*)0` should alias with `0` (well, maybe it's not aliasing): https://godbolt.org/z/MLw_-8

Is HAVE_FUTEX_CMPXCHG set for ARM?

**Comment by ihalip** [comment] 2020-03-10 05:41
> So it seems that inlining can lead to break assumptions being made that %3/%4 are different registers? Can we convey such restrictions using inline assembly syntax somehow?
I tried that and think I found a way to do that by marking `uaddr` as earlyclobber. Judging by the arch document you linked, the LDR/STR instructions may write back into (%4) - I don't think that's the case here since there's no offset. But with this diff I see that the code generated by both clang and gcc no longer use the same register for load/store instructions:
```diff
diff --git a/arch/arm/include/asm/futex.h b/arch/arm/include/asm/futex.h
index 83c391b597d4..805827902b60 100644
--- a/arch/arm/include/asm/futex.h
+++ b/arch/arm/include/asm/futex.h
@@ -111,13 +111,13 @@ futex_atomic_cmpxchg_inatomic(u32 *uval, u32 __user *uaddr,
        __ua_flags = uaccess_save_and_enable();
        __asm__ __volatile__("@futex_atomic_cmpxchg_inatomic\n"
        "       .syntax unified\n"
-       "1:     " TUSER(ldr) "  %1, [%4]\n"
-       "       teq     %1, %2\n"
+       "1:     " TUSER(ldr) "  %1, [%2]\n"
+       "       teq     %1, %3\n"
        "       it      eq      @ explicit IT needed for the 2b label\n"
-       "2:     " TUSERCOND(str, eq) "  %3, [%4]\n"
+       "2:     " TUSERCOND(str, eq) "  %4, [%2]\n"
        __futex_atomic_ex_table("%5")
-       : "+r" (ret), "=&r" (val)
-       : "r" (oldval), "r" (newval), "r" (uaddr), "Ir" (-EFAULT)
+       : "+r" (ret), "=&r" (val), "=&r" (uaddr)
+       : "r" (oldval), "r" (newval), "Ir" (-EFAULT)
        : "cc", "memory");
        uaccess_restore(__ua_flags);
```

This works... but I don't know why.

**Comment by agners** [comment] 2020-03-10 12:13
@ihalip from what I can tell you moved uaddr from input operand list to the output operand list and marked it as earlyclobber. This StackOverflow post mentions using early clobber to prevent the compiler from assigning it the same register:
https://stackoverflow.com/questions/15819794/when-to-use-earlyclobber-constraint-in-extended-gcc-inline-assembly

So I guess its really earlyclobber which helps here to avoid that newval and uaddr gets the same register assigned.

The only think I wonder is whether its safe to mark `uaddr` as write only (using the equal sign).

**Comment by ihalip** [comment] 2020-03-10 12:20
Without the = sign, both compilers complain.
gcc:
```
<source>: In function 'foo':
<source>:15:5: error: output operand constraint lacks '='
     );
     ^
```
clang:
```
<source>:12:32: error: invalid output constraint '&r' in asm
    : "+r" (ret), "=&r" (val), "&r" (uaddr)
                               ^
```

**Comment by agners** [comment] 2020-03-10 12:31
@ihalip yeah I see, I guess we could use `+` to at least mark it read/write, see https://gcc.gnu.org/onlinedocs/gcc/Modifiers.html.

However, it still feels somewhat hacky.

**Comment by nathanchance** [comment] 2021-04-23 00:08
Still reproducible on linux-next with ToT LLVM:

```
$ make -skj"$(nproc)" ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- LLVM=1 badge4_defconfig kernel/futex.o
/tmp/futex-27dfc4.s: Assembler messages:
/tmp/futex-27dfc4.s:22310: Warning: source register same as write-back base
```

**Comment by nathanchance** [comment] 2023-10-13 17:45
I can't reproduce this at https://git.kernel.org/linus/8faf91c48ca20c714e0dd8cc5f510e3819852912 (as `badge4_defconfig` was removed in https://git.kernel.org/linus/9a9e1be12c6d49e15429311714c4b1cc4ddcfe55) using LLVM 18.

```
$ make -skj"$(nproc)" ARCH=arm LLVM=1 badge4_defconfig kernel/futex/
```

It might be due to `HAVE_FUTEX_CMPXCHG` no longer existing, as that was mentioned earlier. I have not seen this in my builds, so I am closing this for now.

**Closed by nathanchance** 2023-10-13 17:45 UTC
Labels: [BUG] Untriaged, [ARCH] arm32, [Reported-by] KernelCI
