### ISSUE TITLE
inline asm clobber list contains reserved registers: R7

### ISSUE THREAD

**Issue by tpgxyz** [ClangBuiltLinux/linux#701] opened 2019-09-24 20:59 UTC
Trying to compile kernel 5.3.1 with LLVM/clang on armv7hnl

Builds for armv7hnl can be found here https://abf.openmandriva.org/openmandriva/kernel-release-clang/build_lists#?page=1&per_page=25&ownership=everything
 also link to GitHub sources.
https://github.com/OpenMandrivaAssociation/kernel-release-clang
```

  CC      arch/arm/mach-vexpress/tc2_pm.o
BUILDSTDERR: arch/arm/mach-vexpress/tc2_pm.c:110:2: warning: inline asm clobber list contains reserved registers: R7 [-Winline-asm]
BUILDSTDERR:         v7_exit_coherency_flush(all);
BUILDSTDERR:         ^
BUILDSTDERR: ./arch/arm/include/asm/cacheflush.h:460:2: note: expanded from macro 'v7_exit_coherency_flush'
BUILDSTDERR:         ".arch  armv7-a \n\t" \
BUILDSTDERR:         ^
BUILDSTDERR: <inline asm>:1:1: note: instantiated into assembly here
BUILDSTDERR:         .arch   armv7-a 
BUILDSTDERR: ^
BUILDSTDERR: arch/arm/mach-vexpress/tc2_pm.c:110:2: note: Reserved registers on the clobber list may not be preserved across the asm statement, and clobbering them may lead to undefined behaviour.
BUILDSTDERR:         v7_exit_coherency_flush(all);
BUILDSTDERR:         ^
BUILDSTDERR: ./arch/arm/include/asm/cacheflush.h:460:2: note: expanded from macro 'v7_exit_coherency_flush'
BUILDSTDERR:         ".arch  armv7-a \n\t" \
BUILDSTDERR:         ^
BUILDSTDERR: <inline asm>:1:1: note: instantiated into assembly here
BUILDSTDERR:         .arch   armv7-a 
BUILDSTDERR: ^
BUILDSTDERR: arch/arm/mach-vexpress/tc2_pm.c:93:2: warning: inline asm clobber list contains reserved registers: R7 [-Winline-asm]
BUILDSTDERR:         v7_exit_coherency_flush(louis);
BUILDSTDERR:         ^
BUILDSTDERR: ./arch/arm/include/asm/cacheflush.h:460:2: note: expanded from macro 'v7_exit_coherency_flush'
BUILDSTDERR:         ".arch  armv7-a \n\t" \
BUILDSTDERR:         ^
BUILDSTDERR: <inline asm>:1:1: note: instantiated into assembly here
BUILDSTDERR:         .arch   armv7-a 
BUILDSTDERR: ^
BUILDSTDERR: arch/arm/mach-vexpress/tc2_pm.c:93:2: note: Reserved registers on the clobber list may not be preserved across the asm statement, and clobbering them may lead to undefined behaviour.
BUILDSTDERR:         v7_exit_coherency_flush(louis);
BUILDSTDERR:         ^
BUILDSTDERR: ./arch/arm/include/asm/cacheflush.h:460:2: note: expanded from macro 'v7_exit_coherency_flush'
BUILDSTDERR:         ".arch  armv7-a \n\t" \
BUILDSTDERR:         ^
BUILDSTDERR: <inline asm>:1:1: note: instantiated into assembly here
BUILDSTDERR:         .arch   armv7-a 
BUILDSTDERR: ^
BUILDSTDERR: 2 warnings generated.
```

**Comment by nathanchance** [comment] 2019-09-24 21:11
Most of the -Wasm-inline warnings you filed are related to `v7_exit_coherency_flush` it seems. I’m going to collapse them all into this issue.

**Comment by nickdesaulniers** [comment] 2019-10-09 06:16
cc @jcai19

**Comment by agners** [comment] 2019-11-10 20:31
@tpgxyz the link above is not(/no longer) valid, do you happen to have one at hand which still works? In particular, I am interested what exact kernel configuration you have been using.

From what I understand, that should only happen when using integrated assembler and Thumb mode. In that configuration a bunch of other stuff does not work yet, so I wasn't able to reproduce.

FWIW, this is the change where the warning has been introduced in LLVM: https://reviews.llvm.org/D49727

**Comment by tpgxyz** [comment] 2019-11-12 09:13
@agners  Latest armv7hnl build is here https://abf.openmandriva.org/build_lists/639833

All OpenMandriva kernel builds with LLVM/clang are available here:
https://abf.openmandriva.org/openmandriva/kernel-release-clang/build_lists#?page=1&per_page=25&ownership=everything

**Comment by agners** [comment] 2020-02-02 21:28
@tpgxyz thanks for the link. The src rpm has a `arm-common.config` file, which I assume is the kernel config you are building?

The config has `CONFIG_THUMB2_KERNEL=y`. And I can reproduce the issue with regular multi_v7_defconfig+CONFIG_THUMB2_KERNEL using Clang 9. In my Qemu testing environment the kernel was also not bootable. 

Did you tried booting any of those kernels?

**Comment by jcai19** [comment] 2020-02-24 21:20
Does this issue still reproduce with latest LLVM? Seems the latest armv7hnl builds have been passing https://abf.openmandriva.org/openmandriva/kernel-release-clang/build_lists#?page=1&per_page=25&ownership=everything&arch_id=2 

Tried to reproduce locally but failed due to #858 
ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make CC=clang AS=clang multi_v7_defconfig
ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make CC=clang AS=clang V=1 CONFIG_THUMB2_KERNEL=y arch/arm/mach-vexpress/tc2_pm.o

**Comment by nickdesaulniers** [comment] 2020-02-25 21:45
@tpgxyz link is dead again. Please attach config file to github.

**Comment by tpgxyz** [comment] 2020-02-26 08:18
@nickdesaulniers  Here is the latest armv7hnl build
https://abf.openmandriva.org/build_lists/714160

Sources can be found here:
https://github.com/OpenMandrivaAssociation/kernel-release-clang

All kernel-release-clang builds can be found here:
https://abf.openmandriva.org/openmandriva/kernel-release-clang/build_lists#?page=1&per_page=25&ownership=everything

**Comment by agners** [comment] 2020-02-26 08:25
The warnings are still there.

@tpgxyz Which clang version has this been built with?

**Comment by nickdesaulniers** [comment] 2020-02-26 08:26
https://github.com/OpenMandrivaAssociation/kernel-release-clang/blob/master/arm-common.config looks like maybe the config.  CONFIG_ARCH_MPS2 or CONFIG_ARCH_VEXPRESS may be relevant.

Warning comes from [calls to v7_exit_coherency_flush](https://github.com/ClangBuiltLinux/linux/blob/c5f86891185c408b2241ba9a82ae8622d8386aff/arch/arm/include/asm/cacheflush.h#L430-L474).

Note that I suspect this may be a new warning in Clang as I think r7 being in the clobber list is problematic as ARM would like to reclaim it for a dedicated frame register, IIRC.

**Comment by nickdesaulniers** [comment] 2020-02-26 09:04
strange, I can't reproduce with:
```c
// $ clang -target arm-linux-gnueabihf -Winline-asm
void foo(void) {
    asm volatile ("":::"r7");
}
```

**Comment by nickdesaulniers** [comment] 2020-02-26 09:05
maybe from: https://reviews.llvm.org/D51165 ?

**Comment by nickdesaulniers** [comment] 2020-02-26 09:07
this reproduces:
```c
// -target arm-linux-gnueabihf -Winline-asm -mthumb
void foo(void) {
    asm volatile ("mov r0, #0":::"r7");
}
```

**Comment by nickdesaulniers** [comment] 2020-02-26 09:20
I suspect that `v7_flush_dcache_all` can just be rewritten to make use of `r6` (or `r8`) rather than `r7`. `r6` is used strictly after, and the value in `r6` doesn't survive the loop "up" to `flush_levels` (though I shouldn't be reading assembly at 1am 🐺 🌕 🦇 ).  Then `v7_exit_coherency_flush` wouldn't have to mark `r7` as clobbered.

**Comment by smithp35** [comment] 2020-02-26 09:24
I agree that this is likely from the pair of changes:
(https://reviews.llvm.org/D51165 , https://reviews.llvm.org/D49727 ) 

r7 is the frame pointer for Thumb (Thumb-1 instructions can mostly only read from r0 - r7), it is r11 in Arm state which is why the warning is only being seen with -mthumb.

For more background there is also https://llvm.org/pr34165 which illustrates an example of incorrect code-generation. 

There could be an argument that the warning should only be given when the frame pointer is enabled -fno-omit-frame-pointer but it may be good practice to avoid r7 if it all possible given that the frame pointer may be enabled later on.

**Comment by jcai19** [comment] 2020-02-26 09:25
@nickdesaulniers Thanks for the repro example. If would be ideal if the v7_exit_coherency_flush can use a different register. Otherwise I was going to propose to maybe disable -Winline-asm for v7_exit_coherency_flush 

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored " -Winline-asm "
 // code of interest
#pragma GCC diagnostic pop

**Comment by agners** [comment] 2020-02-26 09:51
@nickdesaulniers rewriting `v7_flush_dcache_all` might not be a trivial task as it is used in various call sites which could cause a avalanche of changes... But still worth a try.

I am a bit unclear, can clobbering the fp actually lead to broken code? So we were lucky all the time?

Afaik the function is used mostly in CPU shutdown code (either taking cores offline/going into sleep).

**Comment by tpgxyz** [comment] 2020-02-26 13:45
@agners we are using llvm-10.0.0-0.20200214.1

**Comment by nickdesaulniers** [comment] 2020-05-08 00:27
llvm bug: https://llvm.org/pr45826
gcc bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94986
cc @arndb

**Comment by m-gupta** [comment] 2020-05-19 02:03
This is currently blocking Chrome OS next llvm update: https://bugs.chromium.org/p/chromium/issues/detail?id=1084372

**Comment by nathanchance** [comment] 2021-01-05 18:27
Is this fixed?

```
$ make -skj"$(nproc)" ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- LLVM=1 O=out/arm distclean defconfig

$ scripts/config --file out/arm/.config -e THUMB2_KERNEL

$ make -skj"$(nproc)" ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- LLVM=1 O=out/arm olddefconfig arch/arm/mach-vexpress/
```

is all clean for me. Was there something else that I needed to reproduce?

**Comment by nickdesaulniers** [comment] 2021-01-05 22:58
Looks like the CrOS issue was resolved by https://lore.kernel.org/linux-arm-kernel/20200608205711.109418-1-ndesaulniers@google.com/ / https://git.kernel.org/pub/scm/linux/kernel/git/arm64/linux.git/commit/?id=625412c210fb, then the CrOS LLVM revert was dropped. GCC bug for arm32: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69690.

**Comment by nickdesaulniers** [comment] 2021-04-22 21:42
> Is this fixed?

I can't seem to be able to reproduce this anymore.

Thank you for submitting this bug report.  I'm not able to reproduce
it using llvm @ c440b97d89994feb965a9026bc121d154f7b4584 and linux @ 16fc44d6387e260f4932e9248b985837324705d8 using the following commands:
```sh
$ wget https://raw.githubusercontent.com/OpenMandrivaAssociation/kernel-release/master/armv7hnl-desktop-omv-defconfig -O .config
$ ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make LLVM=1 LLVM_IAS=1 -j72 olddefconfig
$ ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make LLVM=1 LLVM_IAS=1 -j72 arch/arm/mach-vexpress/
```

Therefore, I am closing this bug report as obsolete; please feel free
to reopen with additional steps to reproduce beyond what was attempted above.

`v7_flush_dcache_all` still looks to be using `r7`, oh, perhaps because `# CONFIG_UNWINDER_FRAME_POINTER is not set`? In that case, that unwinder isn't supported for EABI IIUC.

**Closed by nickdesaulniers** 2021-04-22 21:42 UTC
Labels: -Winline-asm, Reported upstream, [ARCH] arm32

**Comment by nickdesaulniers** [comment] 2022-02-08 22:41
@ardbiesheuvel 's [patch](https://lore.kernel.org/linux-arm-kernel/20220203082204.1176734-12-ardb@kernel.org/) I think finally truly resolves this.
