### ISSUE TITLE
Linking fails with undefined reference to `__compiletime_assert_191' in DRM_I915 driver

### ISSUE THREAD

**Issue by bulwahn** [ClangBuiltLinux/linux#191] opened 2018-10-05 05:15 UTC
On linux-next (next-20181002), linking of the DRM_I915 driver fails when the "64-bit kernel" is deactivated. Here are my observations:

defconfig works.
defconfig - "64-bit kernel":

```
MODPOST vmlinux.o
ld: drivers/gpu/drm/i915/i915_params.o: in function `i915_params_dump':
i915_params.c:(.text+0x56): undefined reference to `__compiletime_assert_191'
ld: i915_params.c:(.text+0xed): undefined reference to `__compiletime_assert_191'
ld: i915_params.c:(.text+0x188): undefined reference to `__compiletime_assert_191'
ld: i915_params.c:(.text+0x223): undefined reference to `__compiletime_assert_191'
ld: i915_params.c:(.text+0x2be): undefined reference to `__compiletime_assert_191'
ld: drivers/gpu/drm/i915/i915_params.o:i915_params.c:(.text+0x359): more undefined references to `__compiletime_assert_191' follow
make: *** [Makefile:1037: vmlinux] Error 1
```

defconfig - "64-bit kernel" - DRM_I915 works.
defconfig - DRM_I915 works (no surprise!).

I just tried it yet on linux-next and with clang-8. I will need to check with the current release and rc, and with clang-7.

The issue was discovered by investigating the cause for #186.

**Comment by bulwahn** [comment] 2018-10-05 15:37
Following the BUILD_BUG() documentation (https://elixir.bootlin.com/linux/v4.19-rc6/source/include/linux/build_bug.h#L47), it would be expected that the BUILD_BUG() is eliminated during the build, but without the 64-bit kernel, this BUILD_BUG() seems potentially reachable (at least for clang). So, possibly there is a case missing in the `_print_param` function for the 32-bit kernel. I still wondering why clang fails, but gcc does not, though.

**Comment by nickdesaulniers** [comment] 2018-10-05 15:40
Can you get a build removing always inline?

**Comment by nickdesaulniers** [comment] 2018-10-05 16:04
Oh, I think rather than:

If a:
  ...
Else if b:
  ...
Else:
  BUILD_BUG_ON()

we probably want:

If a:
  ...
Else if b:
  ...
BUILD_BUG_ON(!a && !b)

IIRC, clang doesn't like empty build bug on.

**Comment by bulwahn** [comment] 2018-10-05 16:11
Okay, after removing `__always_inline`, it still fails. I will try the other alternative you suggested.

**Comment by nickdesaulniers** [comment] 2018-10-05 16:33
Ah, the full body of the function looks like:

```c
static __always_inline void _print_param(struct drm_printer *p,
                                         const char *name,
                                         const char *type,
                                         const void *x)
{
        if (!__builtin_strcmp(type, "bool"))
                drm_printf(p, "i915.%s=%s\n", name, yesno(*(const bool *)x));
        else if (!__builtin_strcmp(type, "int"))
                drm_printf(p, "i915.%s=%d\n", name, *(const int *)x);
        else if (!__builtin_strcmp(type, "unsigned int"))
                drm_printf(p, "i915.%s=%u\n", name, *(const unsigned int *)x);
        else if (!__builtin_strcmp(type, "char *"))
                drm_printf(p, "i915.%s=%s\n", name, *(const char **)x);
        else
                BUILD_BUG();
}
```

So the issue is that this code is only valid AFTER inlining.  Clang will never support this, as semantic analysis occurs before optimization starts.  Needs to be converted to a macro.

**Comment by nathanchance** [comment] 2018-10-05 20:02
Like this?

```diff
diff --git a/drivers/gpu/drm/i915/i915_params.c b/drivers/gpu/drm/i915/i915_params.c
index 295e981e4a39..f82697d696a0 100644
--- a/drivers/gpu/drm/i915/i915_params.c
+++ b/drivers/gpu/drm/i915/i915_params.c
@@ -174,22 +174,19 @@ i915_param_named(enable_dpcd_backlight, bool, 0600,
 i915_param_named(enable_gvt, bool, 0400,
        "Enable support for Intel GVT-g graphics virtualization host support(default:false)");
 
-static __always_inline void _print_param(struct drm_printer *p,
-                                        const char *name,
-                                        const char *type,
-                                        const void *x)
-{
-       if (!__builtin_strcmp(type, "bool"))
-               drm_printf(p, "i915.%s=%s\n", name, yesno(*(const bool *)x));
-       else if (!__builtin_strcmp(type, "int"))
-               drm_printf(p, "i915.%s=%d\n", name, *(const int *)x);
-       else if (!__builtin_strcmp(type, "unsigned int"))
-               drm_printf(p, "i915.%s=%u\n", name, *(const unsigned int *)x);
-       else if (!__builtin_strcmp(type, "char *"))
-               drm_printf(p, "i915.%s=%s\n", name, *(const char **)x);
-       else
-               BUILD_BUG();
-}
+#define _print_param(p, name, type, x)                                         \
+({                                                                             \
+       if (!__builtin_strcmp(type, "bool"))                                    \
+               drm_printf(p, "i915.%s=%s\n", name, yesno(*(const bool *)x));   \
+       else if (!__builtin_strcmp(type, "int"))                                \
+               drm_printf(p, "i915.%s=%d\n", name, *(const int *)x);           \
+       else if (!__builtin_strcmp(type, "unsigned int"))                       \
+               drm_printf(p, "i915.%s=%u\n", name, *(const unsigned int *)x);  \
+       else if (!__builtin_strcmp(type, "char *"))                             \
+               drm_printf(p, "i915.%s=%s\n", name, *(const char **)x);         \
+       else                                                                    \
+               BUILD_BUG();                                                    \
+})
 
 /**
  * i915_params_dump - dump i915 modparams
```

With Clang 8 and the following commands, I can compile just fine with that change.
```bash
make -j8 CC=clang HOSTCC=clang defconfig
./scripts/config -d 64BIT
make -j8 CC=clang HOSTCC=clang olddefconfig
make -j8 CC=clang HOSTCC=clang
```

**Comment by nickdesaulniers** [comment] 2018-10-05 21:42
It might be preferable to use a `do { ... } while (0)` instead of a GNU statement expression, since I think the statement expressions implicitly return the value of the final statement, but it's good to know that inline->macro conversion works.

It's trying to see if a runtime value is on a whitelist, otherwise fail the build at compile time.  That this ever worked depends on compiler-implementation-specific behavior of performing optimizations during or before semantic analysis, as this function standalone is semantically invalid unless it's first both inlined then constant folded.

Seeing typenames in a string also upsets me.  There's probably a better patch, reimplementing this whole abstraction/what `_print_param` is trying to do.

I'm also curious what config change causes us to see this error, and how that config is related to `_print_param`.

**Comment by nickdesaulniers** [comment] 2018-10-05 21:45
I think a macro switching on the typeof(T) is a much much better solution than this __builtin_strcmp of the tokenized type.  I will prototype that up.

**Comment by nathanchance** [comment] 2018-10-05 21:59
Just to summarize, with `ARCH=x86_64`:

`defconfig` -> vmlinux link succeeds
`defconfig` + `# CONFIG_64BIT is not set` -> vmlinux link fails

I'll mess around with the macro in the meantime.

**Comment by nathanchance** [comment] 2018-10-05 22:00
I'll also poke my head around what else gets set/unset when `CONFIG_64BIT` gets unset.

**Comment by nickdesaulniers** [comment] 2018-10-05 22:05
Sorry, I'm not sure what I had in mind when I said `switch on typeof`.  I think @nathanchance 's inline->macro conversion is required.  I think this macro can further be simplified to not tokenize the type using [`__builtin_types_compatible_p`](https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html#index-_005f_005fbuiltin_005ftypes_005fcompatible_005fp)

**Comment by nathanchance** [comment] 2018-10-05 22:07
I'll get started on it now, thanks!

**Comment by nathanchance** [comment] 2018-10-05 22:51
Okay I just want to make sure I'm doing this right. What you have in mind is this:

```diff
diff --git a/drivers/gpu/drm/i915/i915_params.c b/drivers/gpu/drm/i915/i915_params.c
index fd5644a8e9f1..c95dcbfa3d1a 100644
--- a/drivers/gpu/drm/i915/i915_params.c
+++ b/drivers/gpu/drm/i915/i915_params.c
@@ -178,7 +178,7 @@ i915_param_named(enable_gvt, bool, 0400,
 ({                                                                            \
        if (!__builtin_strcmp(type, "bool"))                                   \
                drm_printf(p, "i915.%s=%s\n", name, yesno(*(const bool *)x));  \
-       else if (!__builtin_strcmp(type, "int"))                               \
+       else if (__builtin_types_compatible_p(typeof(x), int))                 \
                drm_printf(p, "i915.%s=%d\n", name, *(const int *)x);          \
        else if (!__builtin_strcmp(type, "unsigned int"))                      \
                drm_printf(p, "i915.%s=%u\n", name, *(const unsigned int *)x); \
```

correct? Just that change alone results in different compiletime assert errors:

```
ld: drivers/gpu/drm/i915/i915_params.o: in function `i915_params_dump':
i915_params.c:(.text+0x29): undefined reference to `__compiletime_assert_201'
ld: i915_params.c:(.text+0x2e): undefined reference to `__compiletime_assert_201'
ld: i915_params.c:(.text+0x33): undefined reference to `__compiletime_assert_201'
ld: i915_params.c:(.text+0x38): undefined reference to `__compiletime_assert_201'
ld: i915_params.c:(.text+0x3d): undefined reference to `__compiletime_assert_201'
ld: drivers/gpu/drm/i915/i915_params.o:i915_params.c:(.text+0x42): more undefined references to `__compiletime_assert_201' follow
make: *** [Makefile:1037: vmlinux] Error 1
```

Looking into it further, the tokenizing of the types is a result of the params being defined using macros in `i915_params.h`:

```C
#define I915_PARAMS_FOR_EACH(param) \
	param(char *, vbt_firmware, NULL) \
	param(int, modeset, -1) \
	param(int, lvds_channel_mode, 0) \
	param(int, panel_use_ssc, -1) \
	param(int, vbt_sdvo_panel_type, -1) \
	param(int, enable_dc, -1) \
	param(int, enable_fbc, -1) \
	param(int, enable_ppgtt, -1) \
	param(int, enable_psr, -1) \
	param(int, disable_power_well, -1) \
	param(int, enable_ips, 1) \
	param(int, invert_brightness, 0) \
	param(int, enable_guc, 0) \
	param(int, guc_log_level, -1) \
	param(char *, guc_firmware_path, NULL) \
	param(char *, huc_firmware_path, NULL) \
	param(char *, dmc_firmware_path, NULL) \
	param(int, mmio_debug, 0) \
	param(int, edp_vswing, 0) \
	param(int, reset, 2) \
	param(unsigned int, inject_load_failure, 0) \
	/* leave bools at the end to not create holes */ \
	param(bool, alpha_support, IS_ENABLED(CONFIG_DRM_I915_ALPHA_SUPPORT)) \
	param(bool, enable_hangcheck, true) \
	param(bool, fastboot, false) \
	param(bool, prefault_disable, false) \
	param(bool, load_detect_test, false) \
	param(bool, force_reset_modeset_test, false) \
	param(bool, error_capture, true) \
	param(bool, disable_display, false) \
	param(bool, verbose_state_checks, true) \
	param(bool, nuclear_pageflip, false) \
	param(bool, enable_dp_mst, true) \
	param(bool, enable_dpcd_backlight, false) \
	param(bool, enable_gvt, false)

#define MEMBER(T, member, ...) T member;
struct i915_params {
	I915_PARAMS_FOR_EACH(MEMBER);
};
#undef MEMBER
```

**Comment by nickdesaulniers** [comment] 2018-10-05 23:36
That's fine, macro-ization is a good first step then.

**Comment by nathanchance** [comment] 2018-10-06 00:55
Proposed patch: https://github.com/nathanchance/patches/blob/4b13d28ac61b/linux/pending/0005-drm-i915-Convert-_print_param-to-a-macro.patch

**Comment by nickdesaulniers** [comment] 2018-10-08 18:17
Triple check that the first trailing `\` has the correct amount of indentation (it might just be GH's code formatter), but it looks like it has an extra tab.

**Comment by nathanchance** [comment] 2018-10-08 18:20
Yeah it's correct, 80 across the board: https://del.dog/raw/suwujayoxa, GitHub's formatting is weird.

**Comment by bulwahn** [comment] 2018-10-09 07:44
I did not see that patch sent out to LKML yet (I checked LKML's patchwork). @nathanchance If you send it out, make me CC and I can provide my Tested-by on that patch.

**Comment by nathanchance** [comment] 2018-10-09 16:29
@bulwahn thanks for verifying, I will sent it to LKML shortly with you CC'd.

**Comment by nathanchance** [comment] 2018-10-09 17:14
Patch sent: https://lore.kernel.org/lkml/20181009171401.14980-1-natechancellor@gmail.com/

**Comment by nickdesaulniers** [comment] 2018-10-16 18:39
Jani Nikula has posted a fix for this: https://lists.freedesktop.org/archives/intel-gfx/2018-October/178685.html

**Comment by nathanchance** [comment] 2018-10-17 19:13
Jani's patch has been committed to drm/drm-intel: https://cgit.freedesktop.org/drm/drm-intel/commit/?id=7b3e51dd439bead71d9e4504d89a32a8496ac0aa

Unfortunately, this won't make it into 4.20 :(

**Comment by nathanchance** [comment] 2019-01-01 02:17
Merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=7b3e51dd439bead71d9e4504d89a32a8496ac0aa

**Closed by nathanchance** 2019-01-01 02:17 UTC
Labels: [ARCH] x86, [BUG] linux, [PATCH] Accepted, low priority
