### ISSUE TITLE
clang ias: error: unknown token in expression

### ISSUE THREAD

**Issue by arndb** [ClangBuiltLinux/linux#1283] opened 2021-01-28 13:47 UTC
Building arch/arm/mach-at91 with IAS results in a build failure:

<instantiation>:14:13: error: unknown token in expression
 ldr tmp1, =#0x00020010UL
            ^
/git/arm-soc/arch/arm/mach-at91/pm_suspend.S:542:2: note: while in macro instantiation
 at91_plla_enable
 ^

**Comment by nickdesaulniers** [comment] 2021-01-28 21:19
Pretty sure we've removed previous uses of the pseudo op for octa-literals in the past...

**Comment by arndb** [comment] 2021-01-28 21:36
Maybe this instance was added later? It seems to come from commit 4fd36e458392 ("ARM: at91: pm: add plla disable/enable support for sam9x60") in linux-5.7-rc1.

**Comment by jcai19** [comment] 2021-04-22 23:37
Thank you for submitting this bug report.  I'm not able to reproduce
it using llvm ed1734931aa9ac074b9430b9e643b0d0a67b3227 and kernel 90c911ad7445ccec9936763f05fa5db6a3da53be using the following commands:
ARCH=arm CROSS_COMPILE=armv7a-linux-gnueabihf- make LLVM=1 LLVM_IAS=1 defconfig V=1
ARCH=arm CROSS_COMPILE=armv7a-linux-gnueabihf- make -j32 LLVM=1 LLVM_IAS=1 V=1 arch/arm/mach-at91

Therefore, I am closing this bug report as obsolete; please feel free
to reopen with additional steps to reproduce beyond what was attempted above.

**Closed as completed by jcai19** 2021-04-22 23:37 UTC
Labels: wontfix, [TOOL] integrated-as, [ARCH] arm32
