### ISSUE TITLE
LLD fails to link MIPS kernel

### ISSUE THREAD

**Issue by nabijaczleweli** [ClangBuiltLinux/linux#1267] opened 2021-01-25 00:17 UTC
`make LLVM=1 CC=clang CROSS_COMPILE=mips-linux-gnu ARCH=mips` in 228a65d4544af5086bd167dcc5a0cb4fae2c42b4 (and, previously, accefff5b547a9a1d959c7e76ad539bf2480e78b) yields this:
```
ld.lld: error: arch/mips/vdso/elf.o is incompatible with elf32-tradlittlemips
ld.lld: error: arch/mips/vdso/vgettimeofday.o is incompatible with elf32-tradlittlemips
ld.lld: error: arch/mips/vdso/sigreturn.o is incompatible with elf32-tradlittlemips
make[2]: *** [arch/mips/vdso/Makefile:121: arch/mips/vdso/vdso.so.dbg.raw] Error 1
make[1]: *** [scripts/Makefile.build:496: arch/mips/vdso] Error 2
make[1]: *** Waiting for unfinished jobs....
```

However, overriding just LD to binutils' works, so a success nonetheless.

Toolchain, as obtained from http://apt.llvm.org/buster/:
```
nabijaczleweli@tarta:~/store/Carambola2/linux$ ld.lld --version
LLD 12.0.0 (compatible with GNU linkers)
nabijaczleweli@tarta:~/store/Carambola2/linux$ clang --version
Debian clang version 12.0.0-++20210124115112+5d12b976b004-1~exp1~20210124105850.1269
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /bin
```

**Comment by nathanchance** [comment] 2021-01-25 01:57
This is a duplicate of #1025, which is a known issue with `ld.lld` because it does not properly support a triple version of `OUTPUT_FORMAT`.

Thank you for testing and reporting it back, I appreciate it!

**Closed as completed by nathanchance** 2021-01-25 01:57 UTC
Labels: duplicate
