### ISSUE TITLE
Kernel build never starts

### ISSUE THREAD

**Issue by pcercuei** [ClangBuiltLinux/linux#1545] opened 2021-12-13 17:12 UTC
At the tag `v5.16-rc5`, on Debian testing, with Clang/LLVM are at version 13.0.

Preparing the kernel like this:
`ARCH=mips CC=clang make gcw0_defconfig LLVM=1 LLVM_IAS=1`

Trying to build the kernel like this:
`ARCH=mips CC=clang make LLVM=1 LLVM_IAS=1 -j7 vmlinuz.bin`

The kernel build will just output the following line, repeated every ~3 seconds or so:
```
SYNC    include/config/auto.conf.cmd
SYNC    include/config/auto.conf.cmd
SYNC    include/config/auto.conf.cmd
...
```

**Comment by nathanchance** [comment] 2021-12-13 17:42
Hmmm, I cannot reproduce this in a Debian testing container... I can get past linking `vmlinux` but then I error out on linking `vmlinuz`.

Containerfile:

```
FROM docker.io/debian:testing

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update -qq && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        bc \
        bison \
        build-essential \
        ca-certificates \
        cpio \
        flex \
        gnupg2 \
        kmod \
        libelf-dev \
        libssl-dev \
        lsb-release \
        software-properties-common \
        wget && \
    wget https://apt.llvm.org/llvm.sh && \
    bash llvm.sh 13 && \
    rm -f llvm.sh && \
    ln -fsv /usr/lib/llvm-13/bin/* /usr/local/bin
```

```
$ git show -s
commit 2585cf9dfaaddf00b069673f27bb3f8530e2039c (HEAD -> master, tag: v5.16-rc5, origin/master)
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Sun Dec 12 14:53:01 2021 -0800

    Linux 5.16-rc5

$ make -kj"$(nproc)" ARCH=mips LLVM=1 gcw0_defconfig vmlinuz.bin
...
  LD      vmlinux
  SORTTAB vmlinux
  SYSMAP  System.map
  AS      arch/mips/boot/compressed/head.o
  CC      arch/mips/boot/compressed/decompress.o
  CC      arch/mips/boot/compressed/string.o
  CC      arch/mips/boot/compressed/bswapsi.o
  CC      arch/mips/boot/compressed/dummy.o
  OBJCOPY arch/mips/boot/compressed/vmlinux.bin
  HOSTCC  arch/mips/boot/compressed/calc_vmlinuz_load_addr
  GZIP    arch/mips/boot/compressed/vmlinux.bin.z
  OBJCOPY arch/mips/boot/compressed/piggy.o
  LD      vmlinuz
ld.lld: error: section .text at 0xFFFFFFFF81000000 of size 0x3954 exceeds available address space
ld.lld: error: section .MIPS.abiflags at 0xFFFFFFFF81003958 of size 0x18 exceeds available address space
ld.lld: error: section .rodata.str1.1 at 0xFFFFFFFF81003970 of size 0x164 exceeds available address space
ld.lld: error: section .data at 0xFFFFFFFF81003AE0 of size 0x427270 exceeds available address space
ld.lld: error: section .got at 0xFFFFFFFF8142AD50 of size 0x8 exceeds available address space
ld.lld: error: section .appended_dtb at 0xFFFFFFFF8142AD58 of size 0x100000 exceeds available address space
ld.lld: error: section .bss at 0xFFFFFFFF8152AD60 of size 0x402010 exceeds available address space
...
```

Usually, syncconfig only happens when something is different between configuring and building, such as a variable that influences the configuration but it does not seem like that is happening here?

**Comment by pcercuei** [comment] 2021-12-13 18:07
I did the same command as before, but with `PATH=/usr/local/bin:/usr/bin:/usr` prepended, and it unlocked the situation, and now I can't reproduce it anymore.

**Comment by nickdesaulniers** [comment] 2021-12-13 19:48
closing, please reopen with additional steps to reproduce.

**Closed as completed by nickdesaulniers** 2021-12-13 19:48 UTC
Labels: unreproducible

**Comment by pcercuei** [comment] 2021-12-13 22:09
@nathanchance What are those errors at the end of the build though? `arch/mips/Makefile:294` should take care of the leading 0xffffffff...

**Comment by nathanchance** [comment] 2021-12-14 04:17
@pcercuei I opened #1546 to track that error with some explanation of what I think is going on.
