### ISSUE TITLE
ld.lld: error: ld-temp.o <inline asm>:14577:1: symbol '__BTF_ID__struct__cgroup__624' is already defined

### ISSUE THREAD

**Issue by ms178** [ClangBuiltLinux/linux#1913] opened 2023-08-11 11:44 UTC
Hi, with the following config, Clang-18 (52aa6bd3fd6f48f583beaadcbb53edc0f3def4a1), Full-LTO, several SRSO-patches applied as well as "CONFIG_DEBUG_LIST_MINIMAL"-patches (see the attached ms178.patch file), I now see the following on 6.4.9:

```
  AR      vmlinux.a
  GEN     .tmp_initcalls.lds
  LD      vmlinux.o
ld.lld: error: ld-temp.o <inline asm>:14577:1: symbol '__BTF_ID__struct__cgroup__624' is already defined
__BTF_ID__struct__cgroup__624:                                     
^
```
[config.txt](https://github.com/ClangBuiltLinux/linux/files/12321077/config.txt)
[0001-ms178.patch.txt](https://github.com/ClangBuiltLinux/linux/files/12321088/0001-ms178.patch.txt)

[edit:] As the question of pahole came up, I am on a very recent snapshot: 1.25.r7.g37e3bf0

**Comment by ms178** [comment] 2023-08-11 11:58
ThinLTO with the same patches and config doesn't error out, by the way.

**Comment by nickdesaulniers** [comment] 2023-08-11 15:39
cc @melver

**Comment by melver** [comment] 2023-08-11 15:46
Does the same happen with v4 (renamed to CONFIG_LIST_HARDENED and some other fixes)? https://lkml.kernel.org/r/20230811151847.1594958-1-elver@google.com
(I suspect yes, but just double checking.)

**Comment by nathanchance** [comment] 2023-08-11 15:48
This is reproducible for me with just the two SRSO patches on top of 6.4.10, so I think the other patches are a red herring.

```
$ clang --version | head -1
ClangBuiltLinux clang version 18.0.0 (https://github.com/llvm/llvm-project 989f25001aee3457738c431ba1e977a8140726a0)

$ git log --oneline @{u}^..
897a51cdd98f x86/retpoline,kprobes: Fix position of thunk sections with CONFIG_LTO_CLANG
371970c7dd86 x86/srso: fix build breakage for LD=ld.lld
b269b0268d41 Linux 6.4.10

$ curl -LSso .config https://github.com/ClangBuiltLinux/linux/files/12321077/config.txt

$ scripts/config -d LTO_CLANG_THIN -e LTO_CLANG_FULL

$ make -skj"$(nproc)" ARCH=x86_64 LLVM=1 olddefconfig all
...
ld.lld: error: ld-temp.o <inline asm>:14542:1: symbol '__BTF_ID__struct__cgroup__624' is already defined
__BTF_ID__struct__cgroup__624:
^
```

I'll see if this is an LLVM regression.

**Comment by ms178** [comment] 2023-08-11 16:56
Sorry, I did not want to imply that Marco's series was causal in any sort, as I was unsure which of the new patches caused it, I just wanted to mention that I carried Marco's series as well. Great that Nathan could reproduce the issue and happy hunting for a fix.

`Reported-by: Marcus Seyfarth <m.seyfarth@gmail.com>`

**Comment by nathanchance** [comment] 2023-08-11 20:44
It reproduces for me with LLVM 17.0.0-rc2 and 16.0.6 as well, so this is probably something configuration related if it is not a recent Linux regression. I don't know how much more time I will have today to look at this so I might not be able to get back to it until next week.

**Comment by nickdesaulniers** [comment] 2023-08-14 22:45
Strange, I could not reproduce:

```
$ git log --oneline @{u}^.. | cat
b269b0268d41 Linux 6.4.10
$ clang --version | head -n 1
clang version 18.0.0 (git@github.com:llvm/llvm-project.git 2105c32b32bf3360f524f1f3a1e5af605821eff8
$ curl -LSso .config https://github.com/ClangBuiltLinux/linux/files/12321077/config.txt
$ scripts/config -d LTO_CLANG_THIN -e LTO_CLANG_FULL
$ make -skj"$(nproc)" ARCH=x86_64 LLVM=1 olddefconfig all
ld.lld: warning: drivers/gpu/drm/amd/amdgpu/../display/dc/dml/dcn31/display_mode_vba_31.c:3798:0: stack frame size (2440) exceeds limit (2048) in function 'dml31_ModeSupportAndSystemConfigurationFull'
ld.lld: warning: drivers/gpu/drm/amd/amdgpu/../display/dc/dml/dcn314/display_mode_vba_314.c:3893:0: stack frame size (2472) exceeds limit (2048) in function 'dml314_ModeSupportAndSystemConfigurationFull'
```

**Comment by nathanchance** [comment] 2023-08-14 22:55
Hmmm... Could this `pahole` related?

```
$ pahole --version
v1.25
```

**Comment by nathanchance** [comment] 2023-08-17 21:45
Interestingly, this is not visible in mainline with the same configuration. I reverse bisected to [b5ad4cdc46c7](https://git.kernel.org/linus/b5ad4cdc46c7d6e7f8d2c9e24b6c9a1edec95154) ("bpf: Add bpf_task_under_cgroup() kfunc") as the "fix" but that does not seem like a real fix to me. I'll see if there is something about the configuration that specifically triggers this.

**Comment by nathanchance** [comment] 2023-08-18 21:58
I am able to reproduce this with `defconfig` but the configuration changes do not make it obvious what is happening here... specifically, it only appears for me when `CONFIG_KEXEC` is disabled.

```
$ make -skj"$(nproc)" ARCH=x86_64 LLVM=1 mrproper defconfig

$ scripts/config \
    -d DEBUG_INFO_NONE \
    -d KEXEC \
    -d LTO_NONE \
    -e BPF_SYSCALL \
    -e DEBUG_INFO_BTF \
    -e DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT \
    -e LTO_CLANG_FULL

$ make -skj"$(nproc)" ARCH=x86_64 LLVM=1 olddefconfig vmlinux
ld.lld: error: ld-temp.o <inline asm>:27367:1: symbol '__BTF_ID__struct__cgroup__591' is already defined
__BTF_ID__struct__cgroup__591:
^
...
```

**Comment by nickdesaulniers** [comment] 2023-09-07 18:41
>> Strange, I could not reproduce:
> Hmmm... Could this pahole related?

No; I'm an idiot; after reimaging my machine, I lost my previous build of `pahole`. With that rebuilt+updated, I can reproduce on mainline with b5ad4cdc46c7 reverted).

Looks like Android is now hitting this too, bumping this issue up in my priority.

I didn't see any similar reports in recent [pahole](https://git.kernel.org/pub/scm/devel/pahole/pahole.git/log/) or [libbpf](https://github.com/libbpf/libbpf/commits/master) commits.

An identifier like `__BTF_ID__struct__cgroup__591` comes from the use of `BTF_ID` macro in include/linux/btf_ids.h. It uses a macro `__ID` which "pastes" `__COUNTER__` on the end of the identifier.

I almost wonder if there is a slight chance that given some esoteric set of configs, it is possible to generate a conflict between the usage of `BTF_ID` in two different translation units.  For example:

kernel/bpf/helpers.c:2460:BTF_ID(struct, cgroup)
kernel/bpf/verifier.c:5075:BTF_ID(struct, cgroup)

Surely the probability of that is very low, but perhaps non-zero?  Should one of those be deleted?

**Comment by nickdesaulniers** [comment] 2023-09-07 19:00
> With that rebuilt+updated, I can reproduce on mainline with https://github.com/ClangBuiltLinux/linux/commit/b5ad4cdc46c7d6e7f8d2c9e24b6c9a1edec95154 reverted).

Sorry, that's not true.  I still am not able to reproduce on mainline @ dd1386dd3c4f w/ or w/o b5ad4cdc46c7 reverted, w @ms178 's .config or @nathanchance 's [STR](https://github.com/ClangBuiltLinux/linux/issues/1913#issuecomment-1684474480).

I think this lends to my theory of "near zero but not impossible probability of __COUNTER__ resulting in collision." Will mail the BPF mailing list.

**Comment by nathanchance** [comment] 2023-09-07 19:49
FWIW, I do not know that I was ever able to reproduce this on mainline... Did you try `b5ad4cdc46c7d6e7f8d2c9e24b6c9a1edec95154^`? I can still reproduce it with my simplified reproducer above on 6.4.15. I agree with you that this is likely a `__COUNTER__` collision. I bet the fix commit that I landed on changes the `__COUNTER__` value for the `BTF_ID(struct, cgroup)` in `kernel/bpf/helpers.c`, helping avoid this issue.

**Comment by nickdesaulniers** [comment] 2023-09-07 20:40
thread: https://lore.kernel.org/llvm/CAKwvOdnaEakT_y8TA9b_nMY3kMp=xxqKpGQPc2drNqRdV39RQw@mail.gmail.com/

will test @ b5ad4cdc46c7d6e7f8d2c9e24b6c9a1edec95154.

**Comment by nickdesaulniers** [comment] 2023-09-07 21:25
Mainline:
```sh
$ git checkout b5ad4cd
$ make -skj"$(nproc)" ARCH=x86_64 LLVM=1 mrproper defconfig
$ scripts/config \
    -d DEBUG_INFO_NONE \
    -d KEXEC \
    -d LTO_NONE \
    -e BPF_SYSCALL \
    -e DEBUG_INFO_BTF \
    -e DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT \
    -e LTO_CLANG_FULL
$ make -skj"$(nproc)" ARCH=x86_64 LLVM=1 olddefconfig vmlinux
WARN: resolve_btfids: unresolved symbol bpf_cpumask
$ echo $?
130
$
```

Stable:
```
$ git log -1 --format=oneline | cat
f60d5fd5e950c89a38578ae6f25877de511bb031 Linux 6.4.15
$ make -skj"$(nproc)" ARCH=x86_64 LLVM=1 mrproper defconfig
$ scripts/config \
    -d DEBUG_INFO_NONE \
    -d KEXEC \
    -d LTO_NONE \
    -e BPF_SYSCALL \
    -e DEBUG_INFO_BTF \
    -e DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT \
    -e LTO_CLANG_FULL
$ make -skj"$(nproc)" ARCH=x86_64 LLVM=1 olddefconfig vmlinux
ld.lld: error: ld-temp.o <inline asm>:27411:1: symbol '__BTF_ID__struct__cgroup__598' is already defined
__BTF_ID__struct__cgroup__598:                                     
^
$ llvm-nm vmlinux.a 2>/dev/null | grep __BTF_ID__ | grep cgroup
...
---------------- t __BTF_ID__struct__cgroup__598
...
---------------- t __BTF_ID__struct__cgroup__598
...
```
aha! Thanks for the reproducer! Ok, that should make debugging this faster.

**Comment by nickdesaulniers** [comment] 2023-09-07 21:31
Testing:
```diff
diff --git a/tools/include/linux/btf_ids.h b/tools/include/linux/btf_ids.h
index 71e54b1e3796..30e920b96a18 100644
--- a/tools/include/linux/btf_ids.h
+++ b/tools/include/linux/btf_ids.h
@@ -38,7 +38,7 @@ asm(                                                  \
        ____BTF_ID(symbol)
 
 #define __ID(prefix) \
-       __PASTE(prefix, __COUNTER__)
+       __PASTE(prefix, __COUNTER__ __LINE__)
 
 /*
  * The BTF_ID defines unique symbol for each ID pointing
```

**Comment by ms178** [comment] 2023-09-07 22:16
I don't know why Nick's patch from above doesn't apply on my 6.4.15 Kernel, maybe there was some whitespace issue? This one does apply though:

```
diff --git a/tools/include/linux/btf_ids.h b/tools/include/linux/btf_ids.h
index 71e54b1e3796..30e920b96a18 100644
--- a/tools/include/linux/btf_ids.h
+++ b/tools/include/linux/btf_ids.h
@@ -38,7 +38,7 @@ asm(							\
 	____BTF_ID(symbol)

 #define __ID(prefix) \
-	__PASTE(prefix, __COUNTER__)
+	__PASTE(prefix, __COUNTER__ __LINE__)

 /*
  * The BTF_ID defines unique symbol for each ID pointing
```

**Comment by ms178** [comment] 2023-09-07 22:29
The issue is gone with that patch on 6.4.15 with Full LTO and my Kernel. `Tested-by: Marcus Seyfarth <m.seyfarth@gmail.com>`

**Comment by nickdesaulniers** [comment] 2023-09-11 20:28
https://lore.kernel.org/llvm/ZPsJ4AAqNMchvms%2F@krava/ is the latest patch from Jiri.

**Comment by nickdesaulniers** [comment] 2023-09-15 16:59
sent: https://lore.kernel.org/bpf/20230915-bpf_collision-v2-1-027670d38bdf@google.com/

**Comment by nickdesaulniers** [comment] 2023-09-15 20:30
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf.git/commit/?id=8f908db77782

**Closed as completed** 2023-09-27 20:09 UTC
Labels: [BUG] linux, [ARCH] x86_64, [FEATURE] LTO, [FIXED][LINUX] 6.6

**Comment by nickdesaulniers** [comment] 2023-09-28 16:58
commit 8f908db77782 ("bpf: Fix BTF_ID symbol generation collision")
v6.6-rc3
