### ISSUE TITLE
-Wenum-conversion in drivers/pinctrl/sprd/pinctrl-sprd.c

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#138] opened 2018-09-20 13:30 UTC
```
drivers/pinctrl/sprd/pinctrl-sprd.c:845:19: warning: implicit conversion from
      enumeration type 'enum sprd_pinconf_params' to different enumeration type
      'enum pin_config_param' [-Wenum-conversion]
        {"sprd,control", SPRD_PIN_CONFIG_CONTROL, 0},
        ~                ^~~~~~~~~~~~~~~~~~~~~~~
drivers/pinctrl/sprd/pinctrl-sprd.c:846:22: warning: implicit conversion from
      enumeration type 'enum sprd_pinconf_params' to different enumeration type
      'enum pin_config_param' [-Wenum-conversion]
        {"sprd,sleep-mode", SPRD_PIN_CONFIG_SLEEP_MODE, 0},
        ~                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/pinctrl/sprd/pinctrl-sprd.c:851:12: warning: implicit conversion from
      enumeration type 'enum sprd_pinconf_params' to different enumeration type
      'enum pin_config_param' [-Wenum-conversion]
        PCONFDUMP(SPRD_PIN_CONFIG_CONTROL, "global control", NULL, true),
        ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/pinctrl/pinconf-generic.h:163:11: note: expanded from macro 'PCONFDUMP'
        .param = a, .display = b, .format = c, .has_arg = d     \
                 ^
drivers/pinctrl/sprd/pinctrl-sprd.c:852:12: warning: implicit conversion from
      enumeration type 'enum sprd_pinconf_params' to different enumeration type
      'enum pin_config_param' [-Wenum-conversion]
        PCONFDUMP(SPRD_PIN_CONFIG_SLEEP_MODE, "sleep mode", NULL, true),
        ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/pinctrl/pinconf-generic.h:163:11: note: expanded from macro 'PCONFDUMP'
        .param = a, .display = b, .format = c, .has_arg = d     \
                 ^
4 warnings generated.
```

**Comment by nathanchance** [comment] 2018-09-25 06:19
Patch sent: https://lore.kernel.org/lkml/20180925061855.19557-1-natechancellor@gmail.com/

Also fixes #139 and #140.

**Comment by nathanchance** [comment] 2018-09-25 06:19
I'm marking this as a duplicate of #138 because the fix is identical.

**Comment by tpimh** [comment] 2018-09-25 07:15
#144 is also very similar.

**Comment by nathanchance** [comment] 2018-11-01 00:44
Linus Walleij would like these fixed a different way. Seems that most drivers actually use the `#define` directive to set their extra `pin_config_param` values so I have converted all drivers to do that so there is no more warning.

Patch sent for this issue: https://lore.kernel.org/lkml/20181101004410.6893-1-natechancellor@gmail.com/

I will {re,}open issues for the other individual patches:

**Comment by nathanchance** [comment] 2018-11-21 05:01
Patch accepted: https://git.kernel.org/pub/scm/linux/kernel/git/linusw/linux-pinctrl.git/commit/?id=957063c924736d4341e5d588757b9f31e8f6fa24

**Comment by nathanchance** [comment] 2019-01-02 03:05
Merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=957063c924736d4341e5d588757b9f31e8f6fa24

**Closed by nathanchance** 2019-01-02 03:05 UTC
Labels: -Wenum-conversion, [BUG] linux, [PATCH] Accepted, low priority
