### ISSUE TITLE
-Wshift-count-overflow in arch/arm/plat-orion/common.o

### ISSUE THREAD

**Issue by shenki** [ClangBuiltLinux/linux#295] opened 2018-12-12 06:06 UTC
```
make multi_v5_defconfig
./scripts/config -d CONFIG_FTRACE
```
```
  CC      arch/arm/plat-orion/common.o
arch/arm/plat-orion/common.c:625:29: warning: shift count >= width of type [-Wshift-count-overflow]
                .coherent_dma_mask      = DMA_BIT_MASK(64),
                                          ^~~~~~~~~~~~~~~~
./include/linux/dma-mapping.h:139:54: note: expanded from macro 'DMA_BIT_MASK'
#define DMA_BIT_MASK(n) (((n) == 64) ? ~0ULL : ((1ULL<<(n))-1))
                                                     ^ ~~~
arch/arm/plat-orion/common.c:686:29: warning: shift count >= width of type [-Wshift-count-overflow]
                .coherent_dma_mask      = DMA_BIT_MASK(64),
                                          ^~~~~~~~~~~~~~~~
./include/linux/dma-mapping.h:139:54: note: expanded from macro 'DMA_BIT_MASK'
#define DMA_BIT_MASK(n) (((n) == 64) ? ~0ULL : ((1ULL<<(n))-1))
                                                     ^ ~~~
```

**Comment by nickdesaulniers** [comment] 2018-12-12 07:08
dupe of #92

**Closed** 2018-12-12 07:08 UTC
Labels: duplicate
