### ISSUE TITLE
overlayfs/overlay.lto.o ld.lld: error: Never resolved function from blockaddress

### ISSUE THREAD

**Issue by emojifreak** [ClangBuiltLinux/linux#1516] opened 2021-11-27 23:18 UTC
`make allmodconfig` in linux 5.15.5 with LTO produces the following error only with amd64 and arm64:

```
  LTO [M] fs/overlayfs/overlay.lto.o
ld.lld: error: Never resolved function from blockaddress (Producer: 'LLVM13.0.0' Reader: 'LLVM 13.0.0')
```

I could not reproduce the above error without `allmodconifg`. Usual configuration does not have the above error. Architectures other than am64 or arm64 does not give the above error, neither. This looks similar to #1215.  It can be reproduced with clang-13 in Debian unstable amd64 with the following build script:

```
#!/bin/sh

KVER=5.15.5
cd /var/tmp
wget -T 10 -c https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-${KVER}.tar.xz

for a in alpha arc arm arm64 csky h8300 hexagon ia64 m68k microblaze mips nds32 nios2 openrisc parisc powerpc riscv s390 sh sparc um x86 xtensa; do
  mkdir /var/tmp/$a
  cd /var/tmp/$a
  exec </dev/null >build-log-${KVER}-${a}.txt 2>&1
  set -xe
  tar Jxf /var/tmp/linux-${KVER}.tar.xz
  cd linux-${KVER}
  make LLVM=1 LLVM_IAS=1 allmodconfig
  cat >>.config <<EOF
CONFIG_FTRACE_MCOUNT_USE_RECORDMCOUNT=n
CONFIG_KASAN=n
CONFIG_GCOV_KERNEL=n
CONFIG_COMPILE_TEST=n
CONFIG_LTO_CLANG_FULL=y
CONFIG_TRIM_UNUSED_KSYMS=y
CONFIG_CFI_CLANG=y
CONFIG_CFI_CLANG_SHADOW=y
CONFIG_SHADOW_CALL_STACK=y
CONFIG_INIT_STACK_ALL_ZERO=y
EOF

  yes '' |
    make  --keep-going ARCH=$a LLVM=1 LLVM_IAS=1 all &
  exec </dev/null >/dev/null 2>&1
done 
wait
```

**Comment by nathanchance** [comment] 2021-11-30 05:01
As it is highly unlikely that this is a different root cause from #1215, I am going to close this in favor of that issue. I just reduced down `fs/overlayfs/file.c` and posted about it in that thread. Thank you for the report!

**Closed as completed by nathanchance** 2021-11-30 05:01 UTC
Labels: duplicate
