### ISSUE TITLE
ld.lld: error: <internal>:(.rodata.cst640.K512): sh_addralign is not a power of 2

### ISSUE THREAD

**Issue by E5ten** [ClangBuiltLinux/linux#417] opened 2019-03-11 15:00 UTC
Error occurs when `CONFIG_CRYPTO_SHA512_SSSE3` is enabled (with =y or =m). Originally brought up in separate issue #218

**Comment by dileks** [comment] 2019-03-12 08:23
Confirmed here, too.

Workaround by:
```
scripts/config -d CRYPTO_SHA512_SSSE3
```

**Comment by E5ten** [comment] 2019-03-17 22:02
Ok so the problem is that in the assembly files for the sha512 SSSE3 code, there's this
```
# Mergeable 640-byte rodata section. This allows linker to merge the table
# with other, exactly the same 640-byte fragment of another rodata section
# (if such section exists).
.section	.rodata.cst640.K512, "aM", @progbits, 640
```
which is apparently trying to align to 640, not really sure because I have no idea what I'm doing here, what I do know is that when I added this patch the kernel successfully compiled (I chose 1024 because it was the first PO2 above 640, I don't know if that's what I'm supposed to do)
```
--- a/arch/x86/crypto/sha512-ssse3-asm.S
+++ b/arch/x86/crypto/sha512-ssse3-asm.S
@@ -378,7 +378,7 @@
 # Mergeable 640-byte rodata section. This allows linker to merge the table
 # with other, exactly the same 640-byte fragment of another rodata section
 # (if such section exists).
-.section	.rodata.cst640.K512, "aM", @progbits, 640
+.section	.rodata.cst640.K512, "aM", @progbits, 1024
 .align 64
 # K[t] used in SHA512 hashing
 K512:
--- a/arch/x86/crypto/sha512-avx-asm.S
+++ b/arch/x86/crypto/sha512-avx-asm.S
@@ -378,7 +378,7 @@
 # Mergeable 640-byte rodata section. This allows linker to merge the table
 # with other, exactly the same 640-byte fragment of another rodata section
 # (if such section exists).
-.section	.rodata.cst640.K512, "aM", @progbits, 640
+.section	.rodata.cst640.K512, "aM", @progbits, 1024
 .align 64
 # K[t] used in SHA512 hashing
 K512:
--- a/arch/x86/crypto/sha512-avx2-asm.S
+++ b/arch/x86/crypto/sha512-avx2-asm.S
@@ -378,7 +378,7 @@
 # Mergeable 640-byte rodata section. This allows linker to merge the table
 # with other, exactly the same 640-byte fragment of another rodata section
 # (if such section exists).
-.section	.rodata.cst640.K512, "aM", @progbits, 640
+.section	.rodata.cst640.K512, "aM", @progbits, 1024
 .align 64
 # K[t] used in SHA512 hashing
 K512:
```
So either lld is wrong in saying that shouldn't be allowed, or this idea of the 3 objects having mergeable 640-byte rodata sections is wrong. I feel like it's the latter because those 3 sha512 SSSE3 files are the only instances of a line like `.section	.rodata.cst<number>.<something>, "aM", @progbits, <number>` where <number> isn't a power of 2.

**Comment by E5ten** [comment] 2019-03-18 01:36
It seems @dvlasenk was the author of this 640-byte merge thing, maybe you could shed some light on this?

**Comment by E5ten** [comment] 2019-03-18 03:15
Based on the above from @MaskRay it seems the issue is with lld for requiring `sh_entsize` to be a power of 2 when it apparently does not need to be.

**Comment by MaskRay** [comment] 2019-03-18 03:18
lld may should support this use case. This was also raised before in https://llvm.org/pr39044

I created https://reviews.llvm.org/D59478

**Comment by E5ten** [comment] 2019-03-18 04:23
I successfully compiled and linked the kernel after applying the patch to lld.

**Comment by dileks** [comment] 2019-03-18 08:10
@E5ten 
Confirmed, with the lld patch `D59478 diff 191054` I was able to compile and link with `CRYPTO_SHA512_SSSE3=m`.
@MaskRay 
Thanks /o\.

**Comment by dileks** [comment] 2019-03-18 08:27
Run test-case:
```
#!/bin/sh

export LANG=C
export LC_ALL=C

cd build

# CBL issue #218
# https://github.com/ClangBuiltLinux/linux/issues/218
# https://reviews.llvm.org/D58670 ("[LLD][ELF] - Improve "sh_addralign is not a power of 2" diagnostics.")
# RUN: sdi@iniza:~/src/llvm-toolchain/build$ ./bin/llvm-lit ../llvm/tools/lld/test/ELF/invalid/section-alignment2.s
LLD_TESTS="ELF/invalid/section-alignment2.s"

# CBL issue #417
# https://github.com/ClangBuiltLinux/linux/issues/417
# https://reviews.llvm.org/D59478
LLD_TESTS="$LLD_TESTS ELF/icf-merged-sections.s"
LLD_TESTS="$LLD_TESTS ELF/merge-entsize.s"
LLD_TESTS="$LLD_TESTS ELF/merge-gc-piece.s"
LLD_TESTS="$LLD_TESTS ELF/merge-reloc-O0.s"
LLD_TESTS="$LLD_TESTS ELF/merge-sym.s"

for t in $LLD_TESTS ; do ./bin/llvm-lit -v ./tools/lld/test/$t ; done
```

**Comment by MaskRay** [comment] 2019-03-19 01:33
https://reviews.llvm.org/D59478 was committed as rLLD356428

**Closed** 2019-03-19 02:15 UTC
Labels: [ARCH] x86_64, [BUG] llvm, [PATCH] Accepted, lld

**Comment by dileks** [comment] 2019-03-19 07:36
I applied the above patch and set `CONFIG_X86_VERBOSE_BOOTUP=y`and now I see:

```
$ LC_ALL=C sudo dmesg -T | grep sysfs: | grep duplicate
[Tue Mar 19 07:49:51 2019] sysfs: cannot create duplicate filename '/module/usbcore/sections/.rodata.cst16'
[Tue Mar 19 07:49:59 2019] sysfs: cannot create duplicate filename '/module/nfsd/sections/.rodata.cst32'
[Tue Mar 19 07:50:00 2019] sysfs: cannot create duplicate filename '/module/iwlwifi/sections/.rodata.cst16'
[Tue Mar 19 07:50:00 2019] sysfs: cannot create duplicate filename '/module/i915/sections/.rodata.cst32'
[Tue Mar 19 07:50:00 2019] sysfs: cannot create duplicate filename '/module/mac80211/sections/.rodata.cst32'
[Tue Mar 19 07:50:00 2019] sysfs: cannot create duplicate filename '/module/iwlmvm/sections/.rodata.cst16'
[Tue Mar 19 07:50:01 2019] sysfs: cannot create duplicate filename '/module/bluetooth/sections/.rodata.cst16'
```

Here for iwlwifi:
```
[Tue Mar 19 07:50:00 2019] sysfs: cannot create duplicate filename '/module/iwlmvm/sections/.rodata.cst16'
[Tue Mar 19 07:50:00 2019] CPU: 1 PID: 481 Comm: modprobe Not tainted 5.0.2-5-amd64-cbl-asmgoto #5~buster+dileks1
[Tue Mar 19 07:50:00 2019] Hardware name: LENOVO 20HDCTO1WW/20HDCTO1WW, BIOS N1QET81W (1.56 ) 02/20/2019
[Tue Mar 19 07:50:00 2019] Call Trace:
[Tue Mar 19 07:50:00 2019]  dump_stack+0x54/0x8b
[Tue Mar 19 07:50:00 2019]  sysfs_warn_dup+0x5e/0x70
[Tue Mar 19 07:50:00 2019]  sysfs_add_file_mode_ns+0x130/0x160
[Tue Mar 19 07:50:00 2019]  internal_create_group+0x1f6/0x440
[Tue Mar 19 07:50:00 2019]  load_module+0x2f94/0x3200
[Tue Mar 19 07:50:00 2019]  ? kernel_read_file_from_fd+0x46/0x80
[Tue Mar 19 07:50:00 2019]  __do_sys_finit_module+0x150/0x180
[Tue Mar 19 07:50:00 2019]  do_syscall_64+0x56/0x70
[Tue Mar 19 07:50:00 2019]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[Tue Mar 19 07:50:00 2019] RIP: 0033:0x7fd104a752a9
[Tue Mar 19 07:50:00 2019] Code: 00 c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d b7 6b 0c 00 f7 d8 64 89 01 48
[Tue Mar 19 07:50:00 2019] RSP: 002b:00007ffdccca2698 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
[Tue Mar 19 07:50:00 2019] RAX: ffffffffffffffda RBX: 0000564fbb991da0 RCX: 00007fd104a752a9
[Tue Mar 19 07:50:00 2019] RDX: 0000000000000000 RSI: 0000564fbae553f0 RDI: 0000000000000001
[Tue Mar 19 07:50:00 2019] RBP: 0000564fbae553f0 R08: 0000000000000000 R09: 0000000000000000
[Tue Mar 19 07:50:00 2019] R10: 0000000000000001 R11: 0000000000000246 R12: 0000000000000000
[Tue Mar 19 07:50:00 2019] R13: 0000564fbb991c10 R14: 0000000000040000 R15: 0000564fbb991da0
[Tue Mar 19 07:50:00 2019] iwlwifi 0000:04:00.0: Detected Intel(R) Dual Band Wireless AC 8265, REV=0x230
```

Can you please verify? Unsure if this is due to the lld patch.
