### ISSUE TITLE
Unsupported relocation type: R_X86_64_8 (14)

### ISSUE THREAD

**Issue by kees** [ClangBuiltLinux/linux#741] opened 2019-10-16 23:53 UTC
After working around issue #739 I see a `relocs` failure of:

```
Unsupported relocation type: R_X86_64_8 (14)
```

Finding these in the disassembly (`objdump -Sdr vmlinux`) it appears to be references to the CFI jump table:

```
        return vdev->config->find_vqs(vdev, nvqs, vqs, callbacks, names, NULL, desc);
ffffffff81032b98:       49 8b 86 d8 04 00 00    mov    0x4d8(%r14),%rax
ffffffff81032b9f:       4c 8b 58 30             mov    0x30(%rax),%r11
ffffffff81032ba3:       48 c7 c0 b0 0c 21 82    mov    $0xffffffff82210cb0,%rax
                        ffffffff81032ba6: R_X86_64_32S  __typeid__ZTSFiP13virtio_devicejPP9virtqueuePPFvS2_EPKPKcPKbP12irq_affinityE_global_addr
ffffffff81032baa:       4c 89 d9                mov    %r11,%rcx
ffffffff81032bad:       48 29 c1                sub    %rax,%rcx
ffffffff81032bb0:       48 c1 c9 03             ror    $0x3,%rcx
                        ffffffff81032bb3: R_X86_64_8    __typeid__ZTSFiP13virtio_devicejPP9virtqueuePPFvS2_EPKPKcPKbP12irq_affinityE_align
```

If I teach `relocs.c` to ignore these, I can also get past this error and ThinLTO gets me a building (and booting) kernel, before I hit issue #740 

```
diff --git a/arch/x86/tools/relocs.c b/arch/x86/tools/relocs.c
index ce7188cbdae5..7bf495a1d86e 100644
--- a/arch/x86/tools/relocs.c
+++ b/arch/x86/tools/relocs.c
@@ -48,6 +48,7 @@ static const char * const sym_regex_kernel[S_NSYMTYPES] = {
        "^(xen_irq_disable_direct_reloc$|"
        "xen_save_fl_direct_reloc$|"
        "VDSO|"
+       "__typeid__|"
        "__crc_)",
 
 /*
@@ -808,6 +809,12 @@ static int do_reloc64(struct section *sec, Elf_Rel *rel, ElfW(Sym) *sym,
                            symname);
                break;
 
+       case R_X86_64_8:
+               if (!shn_abs || !is_reloc(S_ABS, symname))
+                       die("Non-whitelisted %s relocation: %s\n",
+                           rel_type(r_type), symname);
+               break;
+
        case R_X86_64_32:
        case R_X86_64_32S:
        case R_X86_64_64:
```

**Comment by kees** [comment] 2019-10-17 00:06
Thin LTO:
```
        do_trace_initcall_start(fn);
        ret = fn();
ffffffff8116b170:       48 c7 c0 90 a7 23 82    mov    $0xffffffff8223a790,%rax
                        ffffffff8116b173: R_X86_64_32S  __typeid__ZTSFivE_global
_addr
ffffffff8116b177:       4c 89 f9                mov    %r15,%rcx
ffffffff8116b17a:       48 29 c1                sub    %rax,%rcx
ffffffff8116b17d:       48 c1 c9 03             ror    $0x3,%rcx
                        ffffffff8116b180: R_X86_64_8    __typeid__ZTSFivE_align
ffffffff8116b181:       48 81 f9 f2 02 00 00    cmp    $0x2f2,%rcx
                        ffffffff8116b184: R_X86_64_32S  __typeid__ZTSFivE_size_m1
ffffffff8116b188:       0f 87 f4 01 00 00       ja     ffffffff8116b382 <do_one_initcall+0x492>
ffffffff8116b18e:       41 81 e6 ff ff ff 7f    and    $0x7fffffff,%r14d
ffffffff8116b195:       4d 89 fb                mov    %r15,%r11
ffffffff8116b198:       e8 e3 9a e9 ff          callq  ffffffff81004c80 <__x86_indirect_thunk_r11>
                        ffffffff8116b199: R_X86_64_PLT32        __x86_indirect_thunk_r11-0x4
```

Full LTO:
```
        do_trace_initcall_start(fn);
        ret = fn();
ffffffff810548ac:       48 c7 c0 a0 2c 44 82    mov    $0xffffffff82442ca0,%rax
                        ffffffff810548af: R_X86_64_32S  .text+0x1442ca0
ffffffff810548b3:       4c 89 e9                mov    %r13,%rcx
ffffffff810548b6:       48 29 c1                sub    %rax,%rcx
ffffffff810548b9:       48 c1 c1 3d             rol    $0x3d,%rcx
ffffffff810548bd:       48 81 f9 f3 02 00 00    cmp    $0x2f3,%rcx
ffffffff810548c4:       0f 83 67 02 00 00       jae    ffffffff81054b31 <do_one_initcall+0x521>
ffffffff810548ca:       41 81 e6 ff ff ff 7f    and    $0x7fffffff,%r14d
ffffffff810548d1:       4d 89 eb                mov    %r13,%r11
ffffffff810548d4:       e8 a7 03 fb ff          callq  ffffffff81004c80 <__x86_indirect_thunk_r11>
                        ffffffff810548d5: R_X86_64_PLT32        __x86_indirect_thunk_r11-0x4
```

Looks like some kind of visibility difference in the symbol name?

**Comment by nickdesaulniers** [comment] 2019-12-13 18:39
Kees, were you linking with LLD or BFD?  I assume it's just a missing case of an unimplemented relocation type in LLD?

**Comment by kees** [comment] 2019-12-30 19:35
> Kees, were you linking with LLD or BFD? I assume it's just a missing case of an unimplemented relocation type in LLD?

LLD (since this was under LTO).

**Comment by nickdesaulniers** [comment] 2020-07-17 18:45
cc @MaskRay is this relocation type something that is not implemented in LLD?

**Comment by MaskRay** [comment] 2020-07-18 04:11
R_X86_64_8 has been supported since 2017 (https://reviews.llvm.org/D28841).

**Comment by nickdesaulniers** [comment] 2020-07-19 00:51
Those two patches landed before @kees filed this report. So unless @kees was using a non-ToT version of LLD, then there may be an additional failure.  @kees , is the warning you first reported produced by LLD, or some host tool (arch/x86/tools/relocs.c) ?

**Comment by nickdesaulniers** [comment] 2020-07-19 00:52
@kees  Can you also please retest with ToT LLD (though maybe we should resolve #739 first, then revist this).

**Comment by nickdesaulniers** [comment] 2021-04-22 21:57
Thank you for submitting this bug report.  I'm not able to reproduce
it using llvm @ c440b97d89994feb965a9026bc121d154f7b4584 using the following commands:
```
$ git remote add sami https://github.com/samitolvanen/linux.git
$ git fetch sami
$ git checkout -b cfi sami/clang-cfi
$ make LLVM=1 LLVM_IAS=1 -j72 defconfig
$ make LLVM=1 LLVM_IAS=1 -j72 menuconfig
<enable LTO_CLANG_THIN and CFI_CLANG>
$ make LLVM=1 LLVM_IAS=1 -j72
```
Therefore, I am closing this bug report as obsolete; please feel free
to reopen with additional steps to reproduce beyond what was attempted above (or if the CFI series is carrying a workaround for this).

**Closed by nickdesaulniers** 2021-04-22 21:57 UTC
Labels: [ARCH] x86_64, [FEATURE] CFI, [FEATURE] LTO, [TOOL] lld
