### ISSUE TITLE
CFI: enum vs integer function type mismatches

### ISSUE THREAD

**Issue by samitolvanen** [ClangBuiltLinux/linux#1703] opened 2022-09-07 15:49 UTC
@error27 was kind enough to run [Smatch](https://lwn.net/Articles/691882/) to locate [enum vs int type mismatches](https://lore.kernel.org/linux-staging/CA+_b7DKssU6SjwBvfwHSeOAnZ9PeSW2Nz7wJp8tu-BzwGwHdGQ@mail.gmail.com/) that trip CFI checking. Here's a slightly formatted list:

- [x] [drivers/staging/rtl8723bs/os_dep/os_intfs.c:430](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/staging/rtl8723bs/os_dep/os_intfs.c#L430): `rtw_netdev_ops.ndo_start_xmit = rtw_xmit_entry` (enum netdev_tx)
- [x] [drivers/staging/octeon/ethernet.c:521](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/staging/octeon/ethernet.c#L521): `cvm_oct_npi_netdev_ops.ndo_start_xmit = cvm_oct_xmit` (enum netdev_tx)
- [x] [drivers/staging/octeon/ethernet.c:535](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/staging/octeon/ethernet.c#L535): `cvm_oct_xaui_netdev_ops.ndo_start_xmit = cvm_oct_xmit` (enum netdev_tx)
- [x] [drivers/staging/octeon/ethernet.c:551](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/staging/octeon/ethernet.c#L551): `cvm_oct_sgmii_netdev_ops.ndo_start_xmit = cvm_oct_xmit` (enum netdev_tx)
- [x] [drivers/staging/octeon/ethernet.c:567](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/staging/octeon/ethernet.c#L567): `cvm_oct_spi_netdev_ops.ndo_start_xmit = cvm_oct_xmit` (enum netdev_tx)
- [x] [drivers/staging/octeon/ethernet.c:581](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/staging/octeon/ethernet.c#L581): `cvm_oct_rgmii_netdev_ops.ndo_start_xmit = cvm_oct_xmit` (enum netdev_tx)
- [x] [drivers/staging/octeon/ethernet.c:597](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/staging/octeon/ethernet.c#L597): `cvm_oct_pow_netdev_ops.ndo_start_xmit = cvm_oct_xmit_pow` (enum netdev_tx)
- [x] [drivers/staging/rtl8192e/rtl8192e/rtl_core.c:2264](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/staging/rtl8192e/rtl8192e/rtl_core.c#L2264): `rtl8192_netdev_ops.ndo_start_xmit = rtllib_xmit` (enum netdev_tx)
- [x] [drivers/staging/rtl8712/os_intfs.c:188](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/staging/rtl8712/os_intfs.c#L188): `rtl8712_netdev_ops.ndo_start_xmit = r8712_xmit_entry` (enum netdev_tx)
- [x] [drivers/staging/rtl8192u/r8192U_core.c:4494](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/staging/rtl8192u/r8192U_core.c#L4494): `rtl8192_netdev_ops.ndo_start_xmit = ieee80211_xmit` (enum netdev_tx)
- [x] [drivers/staging/r8188eu/os_dep/os_intfs.c:316](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/staging/r8188eu/os_dep/os_intfs.c#L316): `rtw_netdev_ops.ndo_start_xmit = rtw_xmit_entry` (enum netdev_tx)
- [x] [drivers/gpu/drm/rockchip/cdn-dp-core.c:335](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/gpu/drm/rockchip/cdn-dp-core.c#L335): `cdn_dp_connector_helper_funcs.mode_valid = cdn_dp_connector_mode_valid` (enum drm_mode_status)
- [x] [drivers/gpu/drm/i915/display/dvo_tfp410.c:310](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/gpu/drm/i915/display/dvo_tfp410.c#L310): `tfp410_ops.mode_valid = tfp410_mode_valid` (enum drm_mode_status)
- [x] [drivers/gpu/drm/i915/display/dvo_ch7017.c:406](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/gpu/drm/i915/display/dvo_ch7017.c#L406): `ch7017_ops.mode_valid = ch7017_mode_valid` (enum drm_mode_status)
- [x] [drivers/gpu/drm/i915/display/dvo_ch7xxx.c:358](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/gpu/drm/i915/display/dvo_ch7xxx.c#L358): `ch7xxx_ops.mode_valid = ch7xxx_mode_valid` (enum drm_mode_status)
- [x] [drivers/gpu/drm/i915/display/dvo_ns2501.c:702](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/gpu/drm/i915/display/dvo_ns2501.c#L702): `ns2501_ops.mode_valid = ns2501_mode_valid` (enum drm_mode_status)
- [x] [drivers/gpu/drm/i915/display/dvo_ivch.c:494](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/gpu/drm/i915/display/dvo_ivch.c#L494): `ivch_ops.mode_valid = ivch_mode_valid` (enum drm_mode_status)
- [x] [drivers/gpu/drm/i915/display/dvo_sil164.c:271](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/gpu/drm/i915/display/dvo_sil164.c#L271): `sil164_ops.mode_valid = sil164_mode_valid` (enum drm_mode_status)
- [x] [drivers/gpu/drm/xlnx/zynqmp_dp.c:1393](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/gpu/drm/xlnx/zynqmp_dp.c#L1393): `zynqmp_dp_connector_helper_funcs.mode_valid = zynqmp_dp_connector_mode_valid` (enum drm_mode_status)
- [x] [drivers/gpu/drm/imx/imx-tve.c:318](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/gpu/drm/imx/imx-tve.c#L318): `imx_tve_connector_helper_funcs.mode_valid = imx_tve_connector_mode_valid` (enum drm_mode_status)
- [x] [drivers/gpu/drm/sun4i/sun4i_tv.c:507](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/gpu/drm/sun4i/sun4i_tv.c#L507): `sun4i_tv_comp_connector_helper_funcs.mode_valid = sun4i_tv_comp_mode_valid` (enum drm_mode_status)
- [x] [drivers/gpu/drm/exynos/exynos_mixer.c:1120](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/gpu/drm/exynos/exynos_mixer.c#L1120): `mixer_crtc_ops.mode_valid = mixer_mode_valid` (enum drm_mode_status)
- [x] [drivers/gpu/drm/exynos/exynos_hdmi.c:945](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/gpu/drm/exynos/exynos_hdmi.c#L945): `hdmi_connector_helper_funcs.mode_valid = hdmi_mode_valid` (enum drm_mode_status)
- [x] [drivers/gpu/drm/solomon/ssd130x.c:670](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/gpu/drm/solomon/ssd130x.c#L670): `ssd130x_pipe_funcs.mode_valid = ssd130x_display_pipe_mode_valid` (enum drm_mode_status)
- [x] [drivers/gpu/drm/msm/disp/mdp4/mdp4_lvds_connector.c:87](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/gpu/drm/msm/disp/mdp4/mdp4_lvds_connector.c#L87): `mdp4_lvds_connector_helper_funcs.mode_valid = mdp4_lvds_connector_mode_valid` (enum drm_mode_status)
- [x] [drivers/net/wwan/t7xx/t7xx_netdev.c:108](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/net/wwan/t7xx/t7xx_netdev.c#L108): `ccmni_netdev_ops.ndo_start_xmit = t7xx_ccmni_start_xmit` (enum netdev_tx)
- [x] [drivers/net/wwan/iosm/iosm_ipc_wwan.c:152](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/net/wwan/iosm/iosm_ipc_wwan.c#L152): `ipc_inm_ops.ndo_start_xmit = ipc_wwan_link_transmit` (enum netdev_tx) 
- [x] [drivers/net/ethernet/litex/litex_liteeth.c:196](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/net/ethernet/litex/litex_liteeth.c#L196): `liteeth_netdev_ops.ndo_start_xmit = liteeth_start_xmit` (enum netdev_tx)
- [x] [drivers/net/ethernet/korina.c:1269](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/net/ethernet/korina.c#L1269): `korina_netdev_ops.ndo_start_xmit = korina_send_packet` (enum netdev_tx) 
- [x] [drivers/net/ethernet/microsoft/mana/mana_en.c:378](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/net/ethernet/microsoft/mana/mana_en.c#L378): `mana_devops.ndo_start_xmit = mana_start_xmit` (enum netdev_tx)
- [x] [drivers/net/ethernet/ti/davinci_emac.c:1715](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/net/ethernet/ti/davinci_emac.c#L1715): `emac_netdev_ops.ndo_start_xmit = emac_dev_xmit` (enum netdev_tx)
- [x] [drivers/net/ethernet/davicom/dm9000.c:1369](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/net/ethernet/davicom/dm9000.c#L1369): `dm9000_netdev_ops.ndo_start_xmit = dm9000_start_xmit` (enum netdev_tx)
- [x] [drivers/net/ethernet/microchip/sparx5/sparx5_netdev.c:220](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/net/ethernet/microchip/sparx5/sparx5_netdev.c#L220): `sparx5_port_netdev_ops.ndo_start_xmit = sparx5_port_xmit_impl` (enum netdev_tx)
- [x] [drivers/net/ethernet/microchip/lan966x/lan966x_main.c:458](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/net/ethernet/microchip/lan966x/lan966x_main.c#L458): `lan966x_port_netdev_ops.ndo_start_xmit = lan966x_port_xmit` (enum netdev_tx)
- [x] [drivers/net/ethernet/asix/ax88796c_main.c:934](https://elixir.bootlin.com/linux/v6.0-rc4/source/drivers/net/ethernet/asix/ax88796c_main.c#L934): `ax88796c_netdev_ops.ndo_start_xmit = ax88796c_start_xmit` (enum netdev_tx)
- [x] [net/openvswitch/vport-geneve.c:117](https://elixir.bootlin.com/linux/v6.0-rc4/source/net/openvswitch/vport-geneve.c#L117): `ovs_geneve_vport_ops.send = dev_queue_xmit` (enum netdev_tx)
- [x] [net/openvswitch/vport-netdev.c:194](https://elixir.bootlin.com/linux/v6.0-rc4/source/net/openvswitch/vport-netdev.c#L194): `ovs_netdev_vport_ops.send = dev_queue_xmit` (enum netdev_tx)
- [x] [net/openvswitch/vport-gre.c:81](https://elixir.bootlin.com/linux/v6.0-rc4/source/net/openvswitch/vport-gre.c#L81): `ovs_gre_vport_ops.send = dev_queue_xmit` (enum netdev_tx)
- [x] [net/openvswitch/vport-vxlan.c:146](https://elixir.bootlin.com/linux/v6.0-rc4/source/net/openvswitch/vport-vxlan.c#L146): `ovs_vxlan_netdev_vport_ops.send = dev_queue_xmit` (enum netdev_tx)

cc @kees

**Comment by nhukc** [comment] 2022-09-14 18:20
Patches are in-flight for all issues. I'm checking them off as they get accepted.

**Comment by kees** [comment] 2022-10-19 19:03
cc @GustavoARSilva

**Comment by nathanchance** [comment] 2022-11-02 17:37
@nhukc From what I can tell the following changes are still floating around not picked up:

* https://lore.kernel.org/20220913205600.155172-1-nhuck@google.com/
* https://lore.kernel.org/20220929181411.61331-1-nhuck@google.com/

The first one has a conflict against [the drm-next tree](https://cgit.freedesktop.org/drm/drm); the issue is still there but the function got updated in a rework:

https://cgit.freedesktop.org/drm/drm/commit/?id=47e801bd0749f0691a137255e2db35f5348f4f4f
https://cgit.freedesktop.org/drm/drm/commit/?id=cbb11ef9871956244c38ab8520dc9abe87ccdb3b

The second one should just be updated against [net-next](https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/), as [the move of `mana.h` is still in review](https://lore.kernel.org/1666396889-31288-8-git-send-email-longli@linuxonhyperv.com/) as far as I can tell. There may be a conflict at merge time but dealing with that is up to the maintainers.

If you are too busy to send updated versions of those, I do not mind doing it, as they impact the work on #1750.

**Comment by nhukc** [comment] 2022-11-08 23:29
> @nhukc From what I can tell the following changes are still floating around not picked up:
> 
> * https://lore.kernel.org/20220913205600.155172-1-nhuck@google.com/
> * https://lore.kernel.org/20220929181411.61331-1-nhuck@google.com/
> 
> The first one has a conflict against [the drm-next tree](https://cgit.freedesktop.org/drm/drm); the issue is still there but the function got updated in a rework:
> 
> https://cgit.freedesktop.org/drm/drm/commit/?id=47e801bd0749f0691a137255e2db35f5348f4f4f https://cgit.freedesktop.org/drm/drm/commit/?id=cbb11ef9871956244c38ab8520dc9abe87ccdb3b
> 
> The second one should just be updated against [net-next](https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/), as [the move of `mana.h` is still in review](https://lore.kernel.org/1666396889-31288-8-git-send-email-longli@linuxonhyperv.com/) as far as I can tell. There may be a conflict at merge time but dealing with that is up to the maintainers.
> 
> If you are too busy to send updated versions of those, I do not mind doing it, as they impact the work on #1750.

Yep, I'm too busy with other stuff to handle the rest of these. Feel free to take over. Thanks.

**Comment by nathanchance** [comment] 2022-11-09 00:31
> Yep, I'm too busy with other stuff to handle the rest of these. Feel free to take over. Thanks.

No worries, done!

https://lore.kernel.org/20221109001424.1422495-1-nathan@kernel.org/
https://lore.kernel.org/20221109002629.1446680-1-nathan@kernel.org/

I think we can close this issue in favor of tracking via #1750.

**Closed as completed by nathanchance** 2022-11-09 00:31 UTC
Labels: [FEATURE] CFI
