### ISSUE TITLE
LLD commit 9e33c096476ab5e02ab1c8442cc3cb4e32e29f17 causes Android devices to fail to boot

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#958] opened 2020-03-30 21:12 UTC
@kdrag0n and @Panchajanya1999 reported that https://github.com/llvm/llvm-project/commit/9e33c096476ab5e02ab1c8442cc3cb4e32e29f17 cause their 4.14 based kernels to fail to boot when linked with LLD. I do not have an Android device to verify this myself.

Looking at the section diff with [`bloaty`](https://github.com/google/bloaty), as suggested by @kdrag0n, it looks like there are a bunch of new `.data..compoundliteral.*` sections:

```
$ ./bloaty ../proton_zf6/out/arm64-9e33c096476ab5e02ab1c8442cc3cb4e32e29f17/vmlinux -- ../proton_zf6/out/arm64-9607a119bd5e01ccbbe45c2a5ae6bfbdd219e6c5/vmlinux
   FILE SIZE        VM SIZE
 --------------  -------------- 
 +13e2%  +609Ki  +835%  +377Ki    [3746 Others]
 +18e3%  +101Ki  [ = ]       0    .shstrtab
  [NEW] +17.7Ki  [NEW] +17.6Ki    .data..compoundliteral
  +162% +2.00Ki  [ = ]       0    [ELF Headers]
   +24%    +744   +24%    +744    __modver
  [NEW]    +700  [NEW]    +636    .data..compoundliteral.16
  [NEW]    +640  [NEW]    +576    .data..compoundliteral.24
  [NEW]    +600  [NEW]    +536    .data..compoundliteral.50
  [NEW]    +476  [NEW]    +412    .data..compoundliteral.26
  [NEW]    +472  [NEW]    +408    .data..compoundliteral.14
  [NEW]    +464  [NEW]    +400    .data..compoundliteral.40
  [NEW]    +456  [NEW]    +392    .data..compoundliteral.69
  [NEW]    +448  [NEW]    +384    .data..compoundliteral.58
  [NEW]    +432  [NEW]    +368    .data..compoundliteral.55
  [NEW]    +432  [NEW]    +368    .data..compoundliteral.57
  [NEW]    +424  [NEW]    +360    .data..compoundliteral.30
  [ = ]       0  -0.0%    -432    .bss
  -5.1%    -960  [ = ]       0    __param
 -27.2% -1.05Ki -27.2% -1.05Ki    [LOAD #14 [RW]]
  -7.8% -16.1Ki  [ = ]       0    [Unmapped]
 -21.7%  -398Ki -21.7%  -398Ki    .data
  +1.0%  +320Ki  +0.0%    +144    TOTAL
```

Adding `-n 0` to `bloaty` reveals thousands of these sections: https://gist.github.com/dc8f19ab1ccd80f3668edb1131718cbf

Should you need to build this kernel to further examine (`ld.lld` is set in the Makefile so no need for `LD=ld.lld`):

```bash
$ git clone -j$(nproc) --recursive https://github.com/kdrag0n/proton_zf6

$ cd proton_zf6

# kdrag0n removed -mno-global-merge; he says that it does not impact the outcome so to match upstream and avoid a weird revert, add it to KCFLAGS here
$ make -j$(nproc) -s \
     AR=llvm-ar \
     ARCH=arm64 \
     CC=clang \
     CROSS_COMPILE=aarch64-linux-gnu- \
     CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
     KCFLAGS=-mno-global-merge \
     NM=llvm-nm \
     O=out/arm64 \
     OBJCOPY=llvm-objcopy \
     OBJDUMP=llvm-objdump \
     STRIP=llvm-strip \
     vendor/kirin_defconfig all
```

cc @MaskRay @kees

**Comment by nickdesaulniers** [comment] 2020-03-30 21:20
cc @samitolvanen

**Comment by samitolvanen** [comment] 2020-03-30 23:17
I have a ton of `.data..compoundliteral.*` in my ToT vmlinux, and it boots just fine, so might be unrelated?

`kirin_defconfig` doesn't have LTO enabled, but it does have `LD_DEAD_CODE_DATA_ELIMINATION`, which might have some issues. Have you tried disabling that?

**Comment by MaskRay** [comment] 2020-03-30 23:27
https://github.com/llvm/llvm-project/commit/9e33c096476ab5e02ab1c8442cc3cb4e32e29f17 only affects orphan sections (sections not specified by an output section description in a `SECTIONS` command). You may need to add an input section description `.data..compoundliteral.*` inside `.data : { ... }`

**Comment by samitolvanen** [comment] 2020-03-30 23:35
> You may need to add an input section description `.data..compoundliteral.*` inside `.data : { ... }`. One section costs 64 bytes.

Sounds like something that should be upstreamed in that case. Why does LLVM create these sections?

**Comment by nathanchance** [comment] 2020-03-31 00:25
> Sounds like something that should be upstreamed in that case.

We could potentially upstream that fix but given that arm64 does not support `CONFIG_LD_DEAD_CODE_DATA_ELIMINATION` upstream (rather, it was forcibly enabled in https://github.com/kdrag0n/proton_zf6/commit/26cc44a527cb70c8b4bd6a687d35e619d10f3b71 and https://github.com/kdrag0n/proton_zf6/commit/5843e391cd0c24fbea642a96d351ba4e71aca66b), I am not sure there is much justification there.

I cannot reproduce the boot up issue with an upstream arm64 kernel when forcing `CONFIG_LD_DEAD_CODE_DATA_ELIMINATION` on; it successfully boots in QEMU so there must be something exposed by bare metal (or maybe an out of tree driver?)

We'll need one of the two reporters to test MaskRay's suggestion (which I assume would look like this?)

https://gist.github.com/c21428d1723f2a63dd2d2b6793c65523

```diff
diff --git a/include/asm-generic/vmlinux.lds.h b/include/asm-generic/vmlinux.lds.h
index e60ea67cffa4..a10bdc829b43 100644
--- a/include/asm-generic/vmlinux.lds.h
+++ b/include/asm-generic/vmlinux.lds.h
@@ -68,8 +68,8 @@
 #ifdef CONFIG_LD_DEAD_CODE_DATA_ELIMINATION
 #define TEXT_MAIN .text .text.[0-9a-zA-Z_]*
 #define TEXT_CFI_MAIN .text.cfi .text.[0-9a-zA-Z_]*.cfi
-#define DATA_MAIN .data .data.[0-9a-zA-Z_]*
-#define BSS_MAIN .bss .bss.[0-9a-zA-Z_]*
+#define DATA_MAIN .data .data.[0-9a-zA-Z_]* .data..compoundliteral*
+#define BSS_MAIN .bss .bss.[0-9a-zA-Z_]* .bss..compoundliteral*
 #else
 #define TEXT_MAIN .text
 #define TEXT_CFI_MAIN .text.cfi
```

**Comment by kdrag0n** [comment] 2020-03-31 00:40
It works fine when `LD_DEAD_CODE_DATA_ELIMINATION` is disabled. That breaks building with LLD due to a commit from Qualcomm (https://github.com/kdrag0n/proton_zf6/commit/d4807bd60dc166a6445c3b13684f1d1afb722bc5), but reverting it (as seen on the Pixel 4) fixes the issue.

Applying the above patch to coalesce `compoundliteral` sections (and `L_MergedGlobals` sections if `-fno-global-merge` isn't passed) also fixes it.

**Comment by kdrag0n** [comment] 2020-03-31 05:46
https://github.com/llvm/llvm-project/commit/9e33c096476ab5e02ab1c8442cc3cb4e32e29f17 doesn't appear to change anything on mainline or stable 4.14.

| Config       | Mainline | Stable 4.14.174 | android-4.14 |
| ---          | ---      | ---             | ---          |
| No DCE       | 🗸        | 🗸              | 🗸
| DCE          | EL1 only | 🗸               | 🗸
| DCE + revert | EL1 only | 🗸               | 🗸

`🗸` means that it works irrespective of whether virtualization is on, and `EL1 only` means that it only works when virtualization is disabled. I applied the bare minimum patches from android-4.14 to make `LD_DEAD_CODE_DATA_ELIMINATION` work on 4.14.

Upstreaming my Android kernel to 4.14.174 didn't help, and android-4.14 works, so it looks like there's an issue with either Qualcomm's out-of-tree code or some patches many of us Android custom kernel developers cherry-picked.

All the arm64 builds were tested on QEMU, so it's also possible that this issue only manifests on bare-metal for some reason.

Interestingly, android-4.14 has a recent patch related to these extra sections as well: http://github.com/aosp-mirror/kernel_common/commit/bec540fac475142085d5e8b2950ffa639e6c7eee

**Comment by Panchajanya1999** [comment] 2020-03-31 05:49
> It works fine when `LD_DEAD_CODE_DATA_ELIMINATION` is disabled. That breaks building with LLD due to a commit from Qualcomm ([kdrag0n/proton_zf6@d4807bd](https://github.com/kdrag0n/proton_zf6/commit/d4807bd60dc166a6445c3b13684f1d1afb722bc5)), but reverting it (as seen on the Pixel 4) fixes the issue.
> 
> Applying the above patch to coalesce `compoundliteral` sections (and `L_MergedGlobals` sections if `-fno-global-merge` isn't passed) also fixes it.

So? Reverting this commit as per google and disabling `LD_DEAD_CODE_DATA_ELIMINATION` fixes this booting issue??

**Comment by kdrag0n** [comment] 2020-03-31 05:55
> So? Reverting this commit as per google and disabling LD_DEAD_CODE_DATA_ELIMINATION fixes this booting issue??

Indeed, but you lose out on some size savings when dead code elimination is disabled. The section coalescing patch doesn't come with that tradeoff.

**Comment by Panchajanya1999** [comment] 2020-03-31 08:01
Kernel boots with `LD_DEAD_CODE_DATA_ELIMINATION` disabled, and `selinux: Relocate ss_initialized and selinux_enforcing to separate 4k` reverted and LLD linker.
Thanks guys!

**Comment by jesec** [comment] 2020-04-26 10:27
Confirmed in android-4.19 (msm-4.19 LA.UM.8.12.r1-10400-sm8250.0 + android-4.19-q):
```
# Compiler: Clang version 11.0.0-++20200424052627+3ae9957871f-1~exp1~20200424153232.21
CONFIG_LTO_CLANG=y
# CONFIG_LD_DEAD_CODE_DATA_ELIMINATION is not set
```

In android-4.19, CONFIG_LTO_CLANG also enables the [section](https://github.com/aosp-mirror/kernel_common/blob/72e7c2d100b394e4e971c3cdb4219cfa2ddf52d4/include/asm-generic/vmlinux.lds.h#L69). 
```
#if defined(CONFIG_LD_DEAD_CODE_DATA_ELIMINATION) || defined(CONFIG_LTO_CLANG)
...
#define DATA_MAIN .data .data.[0-9a-zA-Z_]* .data..LPBX*
...
#define BSS_MAIN .bss .bss.[0-9a-zA-Z_]*
...
#else
```
https://github.com/aosp-mirror/kernel_common/commit/0e0752ebd2b5865c38cb46d61609b5bdb8863505
```
-#ifdef CONFIG_LD_DEAD_CODE_DATA_ELIMINATION
+#if defined(CONFIG_LD_DEAD_CODE_DATA_ELIMINATION) || defined(CONFIG_LTO_CLANG)
```

The solution is to coalesce ```compoundliteral``` and ```L_MergedGlobals```: (Suggested-by: @MaskRay, @nathanchance and @kdrag0n) (https://github.com/ClangBuiltLinux/linux/issues/958#issuecomment-606304894, https://github.com/ClangBuiltLinux/linux/issues/958#issuecomment-606323020 and https://github.com/ClangBuiltLinux/linux/issues/958#issuecomment-606327684)
```
diff --git a/include/asm-generic/vmlinux.lds.h b/include/asm-generic/vmlinux.lds.h
index 07b709ab1ff6..2915fa0fbd79 100644
--- a/include/asm-generic/vmlinux.lds.h
+++ b/include/asm-generic/vmlinux.lds.h
@@ -69,10 +69,10 @@
 #if defined(CONFIG_LD_DEAD_CODE_DATA_ELIMINATION) || defined(CONFIG_LTO_CLANG)
 #define TEXT_MAIN .text .text.[0-9a-zA-Z_]*
 #define TEXT_CFI_MAIN .text.[0-9a-zA-Z_]*.cfi
-#define DATA_MAIN .data .data.[0-9a-zA-Z_]* .data..LPBX*
+#define DATA_MAIN .data .data.[0-9a-zA-Z_]* .data..LPBX* .data..compoundliteral* .data..L_MergedGlobals*
 #define SDATA_MAIN .sdata .sdata.[0-9a-zA-Z_]*
 #define RODATA_MAIN .rodata .rodata.[0-9a-zA-Z_]*
-#define BSS_MAIN .bss .bss.[0-9a-zA-Z_]*
+#define BSS_MAIN .bss .bss.[0-9a-zA-Z_]* .bss..compoundliteral* .bss..L_MergedGlobals*
 #define SBSS_MAIN .sbss .sbss.[0-9a-zA-Z_]*
 #else
 #define TEXT_MAIN .text
```

Before patch:
```
kmsg (unbootable)
<6>[    0.000000]  [0:        swapper:    0] Booting Linux on physical CPU 0x0000000000 [0x51df805e]
<5>[    0.000000]  [0:        swapper:    0] Linux version 4.19.118-c9528ac (jc@DESKTOP) (clang version 11.0.0-++20200424052627+3ae9957871f-1~exp1~20200424153232.21) #1 SMP PREEMPT Sat Apr 25 14:55:52 UTC 2020
...
<1>[    1.704120]  [7:      swapper/0:    1] Unable to handle kernel write to read-only memory at virtual address ffffff8012d599b8
<1>[    1.708026] I[2:      swapper/2:    0] Unable to handle kernel write to read-only memory at virtual address ffffff8012d7f780
```
```
bloaty vmlinux
    FILE SIZE        VM SIZE
 --------------  --------------
  53.5%  33.7Mi  51.3%  33.7Mi    .text
   0.0%       0  24.2%  15.9Mi    .bss
  13.1%  8.27Mi  12.6%  8.27Mi    .rodata
  13.1%  8.25Mi   0.0%       0    .symtab
   7.5%  4.75Mi   7.2%  4.75Mi    .data
   7.5%  4.74Mi   0.0%       0    .strtab
   1.9%  1.17Mi   2.0%  1.30Mi    [5909 Others]
   0.8%   545Ki   0.8%   545Ki    .init.text
   0.8%   521Ki   0.8%   521Ki    __bug_table
   0.5%   349Ki   0.5%   349Ki    .altinstructions
   0.3%   187Ki   0.0%       0    [Unmapped]
   0.3%   166Ki   0.0%       0    .shstrtab
   0.2%   117Ki   0.2%   117Ki    .altinstr_replacement
   0.1%  65.4Ki   0.1%  65.3Ki    .init.data
   0.1%  61.1Ki   0.1%  61.0Ki    .relr.dyn
   0.1%  58.6Ki   0.1%  58.5Ki    .data..percpu
   0.1%  36.1Ki   0.1%  36.1Ki    .exit.text
   0.0%  24.1Ki   0.0%  23.3Ki    __param
   0.0%  19.0Ki   0.0%  18.9Ki    __ex_table
   0.0%  11.7Ki   0.0%       0    [ELF Headers]
   0.0%  4.05Ki   0.0%  3.99Ki    .data..L_MergedGlobals.149160
 100.0%  63.0Mi 100.0%  65.7Mi    TOTAL
```
```
aarch64-linux-gnu-readelf --sections --wide vmlinux | grep -c compoundliteral
5662
aarch64-linux-gnu-readelf --sections --wide vmlinux | grep -c L_MergedGlobals
236
```

After patch: (bootable)
```
bloaty vmlinux
    FILE SIZE        VM SIZE
 --------------  --------------
  53.9%  33.7Mi  51.3%  33.7Mi    .text
   0.0%       0  25.0%  16.4Mi    .bss
  13.2%  8.27Mi  12.6%  8.27Mi    .rodata
  13.2%  8.25Mi   0.0%       0    .symtab
   8.9%  5.57Mi   8.5%  5.57Mi    .data
   7.6%  4.74Mi   0.0%       0    .strtab
   0.9%   545Ki   0.8%   545Ki    .init.text
   0.8%   521Ki   0.8%   521Ki    __bug_table
   0.5%   349Ki   0.5%   349Ki    .altinstructions
   0.3%   187Ki   0.0%       0    [Unmapped]
   0.2%   117Ki   0.2%   117Ki    .altinstr_replacement
   0.1%  65.4Ki   0.1%  65.3Ki    .init.data
   0.1%  61.2Ki   0.1%  61.2Ki    .relr.dyn
   0.1%  58.6Ki   0.1%  58.5Ki    .data..percpu
   0.1%  36.1Ki   0.1%  36.1Ki    .exit.text
   0.0%  24.1Ki   0.0%  23.3Ki    __param
   0.0%  19.0Ki   0.0%  18.9Ki    __ex_table
   0.0%  3.84Ki   0.0%  3.84Ki    [LOAD #16 [RW]]
   0.0%  3.77Ki   0.0%  3.71Ki    __modver
   0.0%  1.78Ki   0.0%     574    [10 Others]
   0.0%  1.41Ki   0.0%       0    [ELF Headers]
 100.0%  62.4Mi 100.0%  65.7Mi    TOTAL
```

**Comment by nickdesaulniers** [comment] 2020-07-14 18:34
A revert for the section merging was posted in https://android-review.googlesource.com/c/kernel/common/+/1361089, due to a boot failure report.  I'm trying to get more information from the reporter.

> or some patches many of us Android custom kernel developers cherry-picked.
> So? Reverting this commit as per google and disabling LD_DEAD_CODE_DATA_ELIMINATION fixes this booting issue??

All of those things worry me, since:
1. out of tree drivers
2. out of tree cherry picks
3. LD_DEAD_CODE_DATA_ELIMINATION being forcibly enabled

Are downstream and are probably conflating the issue.

Let me see if we can get `selinux: Relocate ss_initialized and selinux_enforcing to separate 4k` working, or what the issue is with that so that we might not need to revert it.

**Comment by nickdesaulniers** [comment] 2020-07-14 21:05
To find what symbols these sections are coming from, we can:
1. find which `.ko` files have these sections
```sh
$ for F in $(find . -name \*.ko); do llvm-readelf -S $F | grep compound &>/dev/null && echo $F; done
```
2. Given a file, we can disassemble all sections and grep for the symbol:
```sh
$ llvm-objdump -Dr net/ipv6/ipv6.ko
...
0000000000002ea0 <ip6addrlbl_init_table>:
                ...
    2eac: 01 00 00 00   udf     #1
    2eb0: 00 00 00 00   udf     #0
                0000000000002eb0:  R_AARCH64_ABS64      .data..compoundliteral
```
3. Check the source file for that identifier.
```c
// net/ipv6/addrlabel.c
 65 static const __net_initconst struct ip6addrlbl_init_table                                                                                                                                                                                                           
 66 {                                                                                                                                                                                                                                                                   
 67   const struct in6_addr *prefix;                                                                                                                                                                                                                                    
 68   int prefixlen;                                                                                                                                                                                                                                                    
 69   u32 label;                                                                                                                                                                                                                                                        
 70 } ip6addrlbl_init_table[] = {                                                                                                                                                                                                                                       
 71   { /* ::/0 */                                                                                                                                                                                                                                                      
 72     .prefix = &in6addr_any,                                                                                                                                                                                                                                         
 73     .label = 1,                                                                                                                                                                                                                                                     
 74   }, {  /* fc00::/7 */      
```
https://gcc.gnu.org/onlinedocs/gcc/Compound-Literals.html

> @kdrag0n and @Panchajanya1999 reported that llvm/llvm-project@9e33c09 

So if I revert 9e33c09, I shouldn't see any `*.compoundliteral*` sections, right? Looks like I still do.
```sh
$ for F in $(find . -name \*.ko); do llvm-readelf -S $F | grep compound &>/dev/null && echo $F; done | wc -l
41
```
If I checkout the commit before 9e33c096, ie 9607a119bd5e01ccbbe45c2a5ae6bfbdd219e6c5, then disable `ARCH_TEGRA_210_SOC` to work around #510, I get the same measure.

So that bisection is not correct.

**Comment by nickdesaulniers** [comment] 2020-07-14 22:09
Regarding "selinux: Relocate ss_initialized and selinux_enforcing to sep"

"kbuild: add support for Clang LTO" from @samitolvanen add's the wild card for `BSS_MAIN` for the config.

`BSS` could be modified if page alignment is required around the symbol.

**Comment by nickdesaulniers** [comment] 2020-07-15 20:59
for a bisection range, I don't see compound literals at c88220836768732a9cb1fb66f042f64d1107a8d6 (Sep 1 2019), I do see them for 0cb274de397a193fb37c60653b336d48a3a4f1bd (Nov 28 2019).  Let me run an automated bisection on that range and see if we can pinpoint the point at which compoundliteral sections were being produced.  Though I think MLIR was grafted into the tree in that range, which can/will mess up automated bisection.

**Comment by nickdesaulniers** [comment] 2020-07-15 21:00
sigh 0cb274de397a193fb37c60653b336d48a3a4f1bd has a funny commit date...wasn't actually around the time of Nov 28 when it was committed...

**Comment by nickdesaulniers** [comment] 2020-07-15 22:43
Damn, I've been running a bisection all afternoon, just to realize it's converging on the clang-11 version bump (llvm commit 5852475e2c049ce29dcb1f0da3ac33035f8c9156)...since the LTO patchset depends on clang-11.

**Comment by nickdesaulniers** [comment] 2020-11-25 02:41
I just hit this again trying to upgrade pixel 5 redfin to AOSP LLVM 11.0.5; https://reviews.llvm.org/D75225 will cause the device to fail to resume after suspend.

Looking at @samitolvanen 's latest LTO series, it looks like the suggested changes to include/asm-generic/vmlinux.lds.h are included, so it just seems that some Android/Pixel devices are out of date with this change to the LTO patch series.  Looking at Android common kernel, they don't share the same change as in @samitolvanen 's series sent upstream.  That should be fixed first, then the rest of the Pixel kernels.

**Comment by nathanchance** [comment] 2021-01-14 00:51
Seems like we can close this up as there is a kernel solution that people can pick to resolve this (and it is fixed in the upstream LTO patchset)?

**Closed** 2021-01-14 02:13 UTC
Labels: [BUG] llvm (master), [TOOL] lld
