### ISSUE TITLE
argument unused during compilation: '-no-pie'

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#803] opened 2019-12-10 10:29 UTC
During the compilation of RISC-V vDSO clang produces this warning:
```
clang: warning: argument unused during compilation: '-no-pie' [-Wunused-command-line-argument]
```
I wonder if we can just remove `$(call cc-option, -no-pie)` from here:
https://github.com/ClangBuiltLinux/linux/blob/b7aea68a19f3b13455a889ab58954c5fb2b5e1db/arch/riscv/kernel/vdso/Makefile#L58

**Comment by nickdesaulniers** [comment] 2019-12-12 21:44
shouldn't it be `-fno-pie`?

**Comment by tpimh** [comment] 2019-12-13 11:26
The compile command has both `-fno-pie` and `-no-pie`. Just  `-fno-pie` should be enough.

**Comment by nathanchance** [comment] 2020-03-20 04:18
`-no-pie` is the linker flag. This was deliberately added in commit [`85602bea297f`](https://git.kernel.org/linus/85602bea297fc4e5223adbf7006dcce9aa694f17) ("RISC-V: build vdso-dummy.o with -no-pie") to work around distro toolchains that force PIE and I can reproduce that error when `$(call cc-option, -no-pie)` is removed.

This does not seem like it matters for clang though since `-shared` implies `-no-pie` (because `-shared -pie` errors, see #280 and https://github.com/ClangBuiltLinux/linux/commit/3bbd3db86470c701091fb1d67f1fab6621debf50).

Realistically, this is probably the best fix from the kernel side of things:

```diff
diff --git a/arch/riscv/kernel/vdso/Makefile b/arch/riscv/kernel/vdso/Makefile
index 33b16f4212f7..7c729ad114d0 100644
--- a/arch/riscv/kernel/vdso/Makefile
+++ b/arch/riscv/kernel/vdso/Makefile
@@ -54,8 +54,9 @@ $(obj)/%.so: $(obj)/%.so.dbg FORCE
 # The DSO images are built using a special linker script
 # Add -lgcc so rv32 gets static muldi3 and lshrdi3 definitions.
 # Make sure only to export the intended __vdso_xxx symbol offsets.
+no-pie-$(CONFIG_CC_IS_GCC) := $(call cc-option, -no-pie)
 quiet_cmd_vdsold = VDSOLD  $@
-      cmd_vdsold = $(CC) $(KBUILD_CFLAGS) $(call cc-option, -no-pie) -nostdlib -nostartfiles $(SYSCFLAGS_$(@F)) \
+      cmd_vdsold = $(CC) $(KBUILD_CFLAGS) $(no-pie-y) -nostdlib -nostartfiles $(SYSCFLAGS_$(@F)) \
                            -Wl,-T,$(filter-out FORCE,$^) -o $@.tmp && \
                    $(CROSS_COMPILE)objcopy \
                            $(patsubst %, -G __vdso_%, $(vdso-syms)) $@.tmp $@ && \
```

I think this happens because if I am reading `clang`'s source right, `-shared` means that `-pie`/`-no-pie` does not get consumed:

https://elixir.bootlin.com/llvm/llvmorg-11-init/source/clang/lib/Driver/ToolChains/Gnu.cpp#L358

https://elixir.bootlin.com/llvm/llvmorg-11-init/source/clang/lib/Driver/ToolChains/Gnu.cpp#L312

I am not sure if they should be though.

Note, this is the only warning that I see when building a riscv64 kernel with `AS=clang` on linux-next, it'd be nice to get this cleaned up.

**Comment by nickdesaulniers** [comment] 2020-03-20 21:42
>-no-pie is the linker flag

I'm surprised it's not `-Wl,-no-pie` then.

**Comment by nathanchance** [comment] 2020-03-20 21:48
Should have linked GCC’s manual since clang’s seems rather bare:

https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html

Appears there are certain special flags that are passed to the compiler, who merely passes them through down to the linker.

**Comment by kees** [comment] 2020-07-06 22:38
Same for -pg and now -enable-trivial-auto-var-init-zero-knowing-it-will-be-removed-from-clang

https://groups.google.com/d/msg/clang-built-linux/ghiOQ5KIFug/LOmK7sJcBgAJ

Similar upstream issue:
https://llvm.org/pr38772

And I've specifically open this one now:
https://llvm.org/pr46612

**Comment by nathanchance** [comment] 2021-03-18 01:25
Tentative patch:

```diff
From b0bf48ac821afefb9e9e3a339875074f9bf98f30 Mon Sep 17 00:00:00 2001
From: Nathan Chancellor <nathan@kernel.org>
Date: Wed, 17 Mar 2021 16:01:03 -0700
Subject: [PATCH] riscv: Do not include '-no-pie' in VDSOLD command

When building with clang, there is a warning that this option is not
actually being used:

clang-12: warning: argument unused during compilation: '-no-pie' [-Wunused-command-line-argument]

This flag was added to VDSOLD in commit 85602bea297f ("RISC-V: build
vdso-dummy.o with -no-pie") because vdso-dummy.o was built as an static
executable, meaning that toolchains that were configured with
'--enable-default-pie' would need this option to override '-pie' getting
passed along to GNU ld.

$ echo 'int main(void) { return 0; }' | gcc -o tmp -x c -
$ file tmp
tmp: ELF 64-bit LSB pie executable ...
$ ld -r --just-symbols tmp -o tmp2
ld: attempted static link of dynamic object `tmp'

$ echo 'int main(void) { return 0; }' | gcc -no-pie -o tmp -x c -
$ file tmp
tmp: ELF 64-bit LSB executable ...
$ ld -r --just-symbols tmp -o tmp2
$

However, commit c2c81bb2f691 ("RISC-V: Fix the VDSO symbol generaton for
binutils-2.35+") stopped building vdso-dummy.o in favor of generating
vdso-syms.S from vdso.so with $(NM) due to a compatibility change in GNU
binutils, leaving vdso.so.dbg as the only rule that uses VDSOLD.

vdso.so.dbg is built with '-shared', which overrides '-pie' in both GCC
and clang, meaning that '-no-pie' serves no purpose and it can be
removed. Do so to fix this warning.

Link: https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=528dc60364bc1aace27c0694e22eb02233ceb188
Link: https://github.com/llvm/llvm-project/commit/24c67c6a63d67615748944fea9c8caf7bb891241
Link: https://github.com/ClangBuiltLinux/linux/issues/803
Reported-by: Dmitry Golovin <dima@golovin.in>
Signed-off-by: Nathan Chancellor <nathan@kernel.org>
---
 arch/riscv/kernel/vdso/Makefile | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/arch/riscv/kernel/vdso/Makefile b/arch/riscv/kernel/vdso/Makefile
index 71a315e73cbe..8856ee913826 100644
--- a/arch/riscv/kernel/vdso/Makefile
+++ b/arch/riscv/kernel/vdso/Makefile
@@ -63,7 +63,7 @@ $(obj)/%.so: $(obj)/%.so.dbg FORCE
 # Add -lgcc so rv32 gets static muldi3 and lshrdi3 definitions.
 # Make sure only to export the intended __vdso_xxx symbol offsets.
 quiet_cmd_vdsold = VDSOLD  $@
-      cmd_vdsold = $(CC) $(KBUILD_CFLAGS) $(call cc-option, -no-pie) -nostdlib -nostartfiles $(SYSCFLAGS_$(@F)) \
+      cmd_vdsold = $(CC) $(KBUILD_CFLAGS) -nostdlib -nostartfiles $(SYSCFLAGS_$(@F)) \
                            -Wl,-T,$(filter-out FORCE,$^) -o $@.tmp && \
                    $(CROSS_COMPILE)objcopy \
                            $(patsubst %, -G __vdso_%, $(vdso-syms)) $@.tmp $@ && \
-- 
2.31.0

```

I plan to send this with #1268 because I am touching the same area.

**Comment by nathanchance** [comment] 2021-03-25 21:53
https://lore.kernel.org/r/20210325215156.1986901-1-nathan@kernel.org/

**Comment by nathanchance** [comment] 2021-04-13 18:15
Patch accepted: https://git.kernel.org/riscv/c/7ad85ab93d03

**Comment by nathanchance** [comment] 2021-05-06 17:51
Merged into mainline: https://git.kernel.org/torvalds/c/7f3d349065d0

**Closed by nathanchance** 2021-05-06 17:51 UTC
Labels: [ARCH] risc-v, [BUG] linux, [PATCH] Accepted, [Reported-by] KernelCI
