### ISSUE TITLE
undefined libm functions in AMDGPU

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#327] opened 2019-01-24 19:19 UTC
@groeck reported that x86_64 defconfig +
CONFIG_DRM_AMDGPU=y
CONFIG_DRM_AMDGPU_SI=y
CONFIG_DRM_AMDGPU_CIK=y
CONFIG_DRM_AMDGPU_USERPTR=y
CONFIG_DRM_AMDGPU_GART_DEBUGFS=y
CONFIG_DRM_AMD_ACP=y
causes tons of linkage failures for undefined references to libm floating point helper functions.  Looks similar to #186 .

**Comment by groeck** [comment] 2019-01-24 19:50
__divdi3 (#186) is most likely due to 64-bit divide operations, not related to floating point.

Setting CONFIG_DRM_AMDGPU=y on top of defconfig is sufficient to produce the error. Partial output:

drivers/gpu/drm/amd/display/dc/calcs/dcn_calcs.o: In function `dcn_validate_bandwidth':
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calcs.c:(.text+0x55): undefined reference to `__mulsf3'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calcs.c:(.text+0x5c): undefined reference to `__fixsfsi'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calcs.c:(.text+0x72): undefined reference to `__floatsidf'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calcs.c:(.text+0x84): undefined reference to `__divdf3'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calcs.c:(.text+0x8c): undefined reference to `__truncdfsf2'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calcs.c:(.text+0xa5): undefined reference to `__mulsf3'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calcs.c:(.text+0xac): undefined reference to `__fixsfsi'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calcs.c:(.text+0xbf): undefined reference to `__floatsidf'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calcs.c:(.text+0xd1): undefined reference to `__divdf3'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calcs.c:(.text+0xd9): undefined reference to `__truncdfsf2'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calcs.c:(.text+0xf3): undefined reference to `__mulsf3'
...
 drivers/gpu/drm/amd/display/dc/calcs/dcn_calc_math.o: In function `dcn_bw_mod':
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calc_math.c:(.text+0xa): undefined reference to `__unordsf2'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calc_math.c:(.text+0x17): undefined reference to `__unordsf2'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calc_math.c:(.text+0x24): undefined reference to `__divsf3'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calc_math.c:(.text+0x2b): undefined reference to `__fixsfsi'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calc_math.c:(.text+0x32): undefined reference to `__floatsisf'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calc_math.c:(.text+0x3b): undefined reference to `__mulsf3'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calc_math.c:(.text+0x44): undefined reference to `__subsf3'
...
drivers/gpu/drm/amd/display/dc/calcs/dcn_calc_auto.o: In function `scaler_settings_calculation':
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calc_auto.c:(.text+0x129): undefined reference to `__nesf2'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calc_auto.c:(.text+0x138): undefined reference to `__addsf3'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calc_auto.c:(.text+0x154): undefined reference to `__nesf2'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calc_auto.c:(.text+0x166): undefined reference to `__mulsf3'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calc_auto.c:(.text+0x17b): undefined reference to `__mulsf3'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calc_auto.c:(.text+0x1d4): undefined reference to `__gtsf2'
drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calc_auto.c:(.text+0x1f5): undefined reference to `__addsf3'

**Comment by jyknight** [comment] 2019-01-24 21:38
drivers/gpu/drm/amd/display/dc/calcs/Makefile specifies -mhard-float for building dcn_calcs.o.

I guess that's not getting through to the clang invocation, or else is being ignored for some reason?

**Comment by nathanchance** [comment] 2019-01-24 21:58
It looks like it makes it to the Clang invocation...

```
/usr/bin/ccache clang -Wp,-MD,drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/.dcn_calcs.o.d  -nostdinc -isystem /home/nathan/cbl/usr/lib/clang/9.0.0/include -I/home/nathan/cbl/linux/arch/x86/include -I./arch/x86/include/generated  -I/home/nathan/cbl/linux/include -I./include -I/home/nathan/cbl/linux/arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I/home/nathan/cbl/linux/include/uapi -I./include/generated/uapi -include /home/nathan/cbl/linux/include/linux/kconfig.h -include /home/nathan/cbl/linux/include/linux/compiler_types.h  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu -Idrivers/gpu/drm/amd/amdgpu -D__KERNEL__ -Qunused-arguments -Wall -Wundef -Werror=strict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -fno-PIE -Werror-implicit-function-declaration -Werror=implicit-int -Wno-format-security -std=gnu89 -no-integrated-as -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -mno-80387 -mstack-alignment=8 -mtune=generic -mno-red-zone -mcmodel=kernel -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -Wno-sign-compare -fno-asynchronous-unwind-tables -mretpoline-external-thunk -D__BPF_TRACING__ -fno-delete-null-pointer-checks -O2 -Wframe-larger-than=2048 -fstack-protector-strong -Wno-format-invalid-specifier -Wno-gnu -Wno-address-of-packed-member -Wno-tautological-compare -mno-global-merge -Wno-unused-const-variable -fomit-frame-pointer -Wdeclaration-after-statement -Wvla -Wno-pointer-sign -fno-strict-overflow -fno-merge-all-constants -fno-stack-check -Werror=date-time -Werror=incompatible-pointer-types -Wno-initializer-overrides -Wno-unused-value -Wno-format -Wno-sign-compare -Wno-format-zero-length -Wno-uninitialized  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../powerplay/inc/  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../include/asic_reg  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../include  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../powerplay/smumgr  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../powerplay/hwmgr  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../display/dc/inc/  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../display/dc/inc/hw  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../display/modules/inc  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../display/modules/freesync  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../display/modules/color  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../display/modules/info_packet  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../display/modules/power -DBUILD_FEATURE_TIMING_SYNC=0  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../display/dc  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../include/asic_reg  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../include  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../amdgpu  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../powerplay/inc  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../acp/include  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../display  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../display/include  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../display/dc  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../display/amdgpu_dm  -I/home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../amdkfd -mhard-float -msse -mstack-alignment=16    -DKBUILD_BASENAME='"dcn_calcs"' -DKBUILD_MODNAME='"amdgpu"' -c -o drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calcs.o /home/nathan/cbl/linux/drivers/gpu/drm/amd/amdgpu/../display/dc/calcs/dcn_calcs.c
```

Here's the full `.cmd` file output: https://gist.github.com/d2cc096cafb0a341e603a799890534cb

**Comment by nickdesaulniers** [comment] 2019-01-24 23:36
reproducer:
```c
// $ clang -O2 -mno-sse -mno-80387 -c float.c
// $ nm float.o
// 0000000000000000 T div
//                  U __divsf3
float div (float a, float b) {
  return b / a;
}
```

**Comment by nickdesaulniers** [comment] 2019-01-24 23:58
Better reproducer:

```c
// $ clang -c -O2 -mno-sse2 -mno-80387 -msse float.c
double div (double a, double b) {                                               
  return b / a;                                                                 
} 
```

The solution is turning back on `-msse2` for enabling HW FP support for double precision operations with Clang.

**Comment by nickdesaulniers** [comment] 2019-01-25 00:03
RFT:

```
From 0007415a8c6d8ffea63c6a99e8f69a6f25142bea Mon Sep 17 00:00:00 2001
From: Nick Desaulniers <ndesaulniers@google.com>
Date: Thu, 24 Jan 2019 15:59:58 -0800
Subject: [PATCH] drm/amd/display: add -msse2 to prevent clang from emitting
 libcalls to undefined SW FP routines

Top level Makefile disables SSE for the whole kernel.  Turn on SSE2 to
support emitting double precision floating point instructions rather
than calls to non-existent (usually available from gcc_s or compiler_rt)
floating point helper routines.

Link: https://gcc.gnu.org/onlinedocs/gccint/Soft-float-library-routines.html
Link: https://github.com/ClangBuiltLinux/linux/issues/327
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
---
 drivers/gpu/drm/amd/display/dc/calcs/Makefile | 2 +-
 drivers/gpu/drm/amd/display/dc/dml/Makefile   | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/drivers/gpu/drm/amd/display/dc/calcs/Makefile b/drivers/gpu/drm/amd/display/dc/calcs/Makefile
index 95f332ee3e7e..dc85a3c088af 100644
--- a/drivers/gpu/drm/amd/display/dc/calcs/Makefile
+++ b/drivers/gpu/drm/amd/display/dc/calcs/Makefile
@@ -30,7 +30,7 @@ else ifneq ($(call cc-option, -mstack-alignment=16),)
 	cc_stack_align := -mstack-alignment=16
 endif
 
-calcs_ccflags := -mhard-float -msse $(cc_stack_align)
+calcs_ccflags := -mhard-float -msse -msse2 $(cc_stack_align)
 
 CFLAGS_dcn_calcs.o := $(calcs_ccflags)
 CFLAGS_dcn_calc_auto.o := $(calcs_ccflags)
diff --git a/drivers/gpu/drm/amd/display/dc/dml/Makefile b/drivers/gpu/drm/amd/display/dc/dml/Makefile
index d97ca6528f9d..33c7d7588712 100644
--- a/drivers/gpu/drm/amd/display/dc/dml/Makefile
+++ b/drivers/gpu/drm/amd/display/dc/dml/Makefile
@@ -30,7 +30,7 @@ else ifneq ($(call cc-option, -mstack-alignment=16),)
 	cc_stack_align := -mstack-alignment=16
 endif
 
-dml_ccflags := -mhard-float -msse $(cc_stack_align)
+dml_ccflags := -mhard-float -msse -msse2 $(cc_stack_align)
 
 CFLAGS_display_mode_lib.o := $(dml_ccflags)
 CFLAGS_display_pipe_clocks.o := $(dml_ccflags)
-- 
2.20.1.321.g9e740568ce-goog

```

**Comment by groeck** [comment] 2019-01-25 00:12
Excellent! Do you plan to send this upstream ? If so, please feel free to add

Tested-by: Guenter Roeck <linux@roeck-us.net>

**Comment by nickdesaulniers** [comment] 2019-01-25 00:13
> Do you plan to send this upstream

Will do; thanks for helping test + report, @groeck I appreciate it!

**Comment by nickdesaulniers** [comment] 2019-01-25 00:54
thanks all for the report and help: https://lore.kernel.org/r/20190125005304.183322-1-ndesaulniers@google.com/

**Comment by dileks** [comment] 2019-01-25 07:28
Just for the records:
I reported "[Linux-v4.18-rc6] modpost-errors when compiling with clang-7 and CONFIG_DRM_AMDGPU=m"

Workaround for me was `CONFIG_DRM_AMDGPU=n`

UPDATE: I can try Nick's patch here.
UPDATE-2: Please CC Christian König and amd-gfx ML. Feel free to add a Reported-by.

My 1st priority for testing is to see clang-8.0.0rc1 with asm-goto RFC patches building and booting an 5.0-rc3+ amd64 kernel on Debian/buster.

UPDATE-3: My selfmade llvm-toolchain-8.0.0rc1 consists of llvm, clang and compiler-rt.
UPDATE-4: Feedback from Christian K. in [2].

[1] https://lore.kernel.org/r/0e782eaa-f495-61a2-b30e-61057dcfc611@amd.com/
[2] https://lore.kernel.org/r/54cdfdd5-d889-5714-263f-a663f8649d42@amd.com/

**Comment by nathanchance** [comment] 2019-01-26 05:00
Patch accepted: https://cgit.freedesktop.org/~agd5f/linux/commit/?id=10117450735c7a7c0858095fb46a860e7037cb9a

**Comment by dileks** [comment] 2019-01-28 09:01
Tested-by: Sedat Dilek <sedat.dilek@gmail.com> [ Linux v5.0-rc3+ with LLVM/Clang asm-goto ]

Which versions of the Linux-kernel are affected?
I have seen this 1st with Linux v4.18-rc6 and `CONFIG_DRM_AMDGPU=m`, so I guess it is a good idea to get this patch into Linux v4.19 LTS, v4.20 and v5.0 as the patch is qeued for Linux v5.1?

[1] https://lore.kernel.org/r/0e782eaa-f495-61a2-b30e-61057dcfc611@amd.com/
[2] https://cgit.freedesktop.org/~agd5f/linux/commit/?h=drm-next-5.1&id=10117450735c7a7c0858095fb46a860e7037cb9a

**Comment by ms178** [comment] 2019-01-31 06:41
FYI: That patch was reverted due to causing this bug, https://bugs.freedesktop.org/show_bug.cgi?id=109487

Update: From the discussion on the LKML, it seems that older GCC (5.4) is fine, while 7.3 and 8.2 shows issues: https://lore.kernel.org/r/CAKwvOdkzVv4_hruDkbgiq0TRbPw6uyXAHZ+tAWyqN7CoyOLU_g@mail.gmail.com/  - Nick is already in the loop, so this post is just for documenting the issue here as well.

**Comment by nickdesaulniers** [comment] 2019-02-14 18:32
@ms178 @groeck any idea what ended up happening here?

**Comment by groeck** [comment] 2019-02-14 19:15
Nothing. AMD reassigned the Google-internal bug back to me. Presumably the assumption on the AMD side is that we'll have to track down and fix the problem(s) ourselves if we are interested building v4.19+ with clang.

**Comment by nickdesaulniers** [comment] 2019-02-14 19:45
please cc me on it

**Comment by ms178** [comment] 2019-02-14 20:01
Unfortunately, I am also not of much help for you, as I am just an interested bystander of this project. If I spot something noteworthy on the mailing lists, I'll let you know though.

**Comment by ms178** [comment] 2019-02-14 20:20
As the bug was reported on Raven Ridge and was display related, that reminds me that the DC code on Raven Ridge relies on SSE code as pointed out to me here: https://www.phoronix.com/forums/forum/linux-graphics-x-org-drivers/open-source-amd-linux/1070582-it-turns-out-amdgpu-kfd-compute-support-can-work-on-64-bit-arm

And there might be regressions with the mentioned different GCC versions with SSE2 enabled. But that's just an uneducated guess. ;)

**Comment by groeck** [comment] 2019-02-14 20:41
Yes, enabling sse2 with recent versions of gcc exposes the problem. I suspect it generates different arithmetic results, which results in the observed crash. Someone would have to go in and figure out what those different results are, and if the driver is at fault or gcc. AMD says that gcc 7.3.0 with sse works, and older gcc versions work with sse2. But they are not interested tracking down _why_ gcc 7.3.0 and sse2 no longer works.

**Comment by nickdesaulniers** [comment] 2019-03-08 19:29
It seems this hit mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=10117450735c7a7c0858095fb46a860e7037cb9a

Then reverted in 193392ed9f6953713957c14045be1e920519870d.

**Comment by nathanchance** [comment] 2019-04-16 23:07
https://chromium-review.googlesource.com/c/chromiumos/overlays/board-overlays/+/1558742

I assume that the bug listed in this commit message is the internal one mentioned above.

**Comment by nickdesaulniers** [comment] 2019-05-17 19:39
@samitolvanen cleaned this up in https://android-review.googlesource.com/c/kernel/common/+/963207. (I'm cool w/ Sami taking ownership of this patch; the commit should be cleaned up to mention how it was previously merged, then reverted, and this is a resend cleaned up).  (I could do this, but is low hanging fruit if someone else wants to take it).

**Comment by dileks** [comment] 2019-06-06 12:53
"drm/amd/display: add -msse2 to prevent Clang from emitting libcalls to undefined SW FP routines"

Tested-by: Sedat Dilek <sedat.dilek@gmail.com>

[1] https://github.com/samitolvanen/linux/commits/clang-lto
[2] https://github.com/samitolvanen/linux/commit/d13b3379ab8f4a2991303be3c90b465455a4cff3

**Comment by dileks** [comment] 2019-06-06 15:30
With `CONFIG_DRM_AMDGPU=m`:
```
make -f ./scripts/Makefile.modpost
  find .tmp_versions -name '*.mod' | xargs -r grep -h '\.ko$' | sort -u | sed 's/\.ko$/.o/' | scripts/mod/modpost -m  -o ./Module.symvers       -s -T -
ERROR: "__gedf2" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
ERROR: "__ltdf2" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
ERROR: "__floatdidf" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
ERROR: "__divdf3" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
ERROR: "__subdf3" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
ERROR: "__floatsidf" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
ERROR: "__ledf2" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
ERROR: "__muldf3" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
ERROR: "__extendsfdf2" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
ERROR: "__gtdf2" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
ERROR: "__adddf3" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
ERROR: "__floatunsidf" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
ERROR: "__truncdfsf2" [drivers/gpu/drm/amd/amdgpu/amdgpu.ko] undefined!
make[4]: *** [scripts/Makefile.modpost:91: __modpost] Error 1
make[3]: *** [Makefile:1268: modules] Error 2
make[2]: *** [debian/rules:6: build] Error 2
```

**Comment by dileks** [comment] 2019-06-06 15:44
Hmmm...
```
 calcs_ccflags := -mhard-float -msse $(cc_stack_align)
 
+# Use -msse2 only with clang:
+#   https://bugs.freedesktop.org/show_bug.cgi?id=109487
+ifdef CONFIG_CC_IS_CLANG
+calcs_cc_flags += -msse2
+endif
```
s/calcs_cc_flags/calcs_ccflags

**Comment by samitolvanen** [comment] 2019-06-06 16:13
Thanks, updated.

**Comment by nickdesaulniers** [comment] 2019-07-22 22:31
resubmitted: https://lore.kernel.org/r/20190722223112.199769-1-ndesaulniers@google.com/

**Comment by nickdesaulniers** [comment] 2019-08-07 21:35
accepted: https://cgit.freedesktop.org/~agd5f/linux/commit/?h=amd-staging-drm-next&id=b59953fdf2252a140cd6fab9ab5fe42ea07f0182

**Comment by nathanchance** [comment] 2019-09-28 01:28
Merged into mainline: https://git.kernel.org/linus/0f0727d971f6fdf8f1077180d495ddb9928f0c8b

@nickdesaulniers reopen this issue for the runtime issues if you feel it necessary (or maybe file a new one given that this one is just about the build failure).

**Closed by nathanchance** 2019-09-28 01:28 UTC
Labels: [ARCH] x86_64, [BUG] linux, [PATCH] Accepted
