### ISSUE TITLE
Section mismatch warning from arch/x86/mm/amdtopology.c

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1301] opened 2021-02-11 22:46 UTC
```
$ make -skj"$(nproc)" CC=clang O=build/x86_64 defconfig vmlinux
WARNING: modpost: vmlinux.o(.text+0x68943): Section mismatch in reference from the function __nodes_weight() to the variable .init.data:numa_nodes_parsed
The function __nodes_weight() references
the variable __initdata numa_nodes_parsed.
This is often because __nodes_weight lacks a __initdata
annotation or the annotation of numa_nodes_parsed is wrong.
```

Looks like this comes from `arch/x86/mm/amdtopology.c` as that is the only place where I see `nodes_weight` and `numa_nodes_parsed` together.

Apparently `__nodes_weight` does not get inlined anymore, although it really seems like it should :/

```
$ sed -n '237,242p' include/linux/nodemask.h
#define nodes_weight(nodemask) __nodes_weight(&(nodemask), MAX_NUMNODES)
static inline int __nodes_weight(const nodemask_t *srcp, unsigned int nbits)
{
        return bitmap_weight(srcp->bits, nbits);
}
```

**Comment by nathanchance** [comment] 2021-02-11 22:56
I think there is another one with `allmodconfig`:

```
$ make -skj"$(nproc)" LLVM=1 O=build/x86_64 distclean allmodconfig vmlinux
...
WARNING: modpost: vmlinux.o(.text+0x144328): Section mismatch in reference from the function early_get_smp_config() to the variable .init.data:x86_init
The function early_get_smp_config() references
the variable __initdata x86_init.
This is often because early_get_smp_config lacks a __initdata
annotation or the annotation of x86_init is wrong.

WARNING: modpost: vmlinux.o(.text+0x144334): Section mismatch in reference from the function early_get_smp_config() to the variable .init.data:x86_init
The function early_get_smp_config() references
the variable __initdata x86_init.
This is often because early_get_smp_config lacks a __initdata
annotation or the annotation of x86_init is wrong.
...
```

**Comment by arndb** [comment] 2021-02-14 08:41
The early_get_smp_config() etc should get fixed in the kernel by annotating them as either __init or __always_inline: the problem here is that they reference an __initdata symbol.

In case of __nodes_weight(), I would tend to blame llvm, as there is nothing wrong with kernel code: amd_numa_init() is correctly annotated __init, and it passes an __initdata variable into a generic interface. This would be fine if either __nodes_weight() gets inlined as expected, or if __nodes_weight() gets turned into a normal static function. What llvm does instead is to emit a specialized version of __nodes_weight() that ignores its argument but references the global __initdata variable.

A possible workaround would be for the specialized __nodes_weight() function in this case to inherit the __init section attribute, or some logic to prevent this optimization to happen when the caller and the callee are in different sections.

**Comment by arndb** [comment] 2021-02-21 00:11
Reduced test case https://godbolt.org/z/KMaYvW

**Comment by arndb** [comment] 2021-02-27 19:22
I reduced a test case for the function not getting inlined to https://godbolt.org/z/xW8G9c

This is a bit odd, as in the reduced test case, we have a function that is marked 'inline' and that does nothing at all but is still not inlined, which feels like a bug in llvm. It only happens with  -fsanitize=object-size, which doesn't seem related to the code in the test case either.

**Comment by nickdesaulniers** [comment] 2021-03-01 01:06
Since this is only reproducible on newer versions of LLVM, it should be possible to bisect to find the regression.

**Comment by nathanchance** [comment] 2021-03-01 02:17
I am sure this is NPM related but I can reverse bisect later this week to confirm.

**Comment by nickdesaulniers** [comment] 2021-03-01 07:26
ah right, both this and #1302 mention `numa_nodes_parsed`. Duplicate?

**Comment by nathanchance** [comment] 2021-03-01 15:55
I think the second comment makes this a unique issue but it is up to you, we can roll these all into one issue if you would like because they exclusively affect x86_64.

**Comment by nickdesaulniers** [comment] 2021-03-03 18:24
> A possible workaround would be for the specialized __nodes_weight() function in this case to inherit the __init section attribute, or some logic to prevent this optimization to happen when the caller and the callee are in different sections.

I'm looking into this, it looks like there's 2 distinct passes here. `ipsccp` replaces the use of function arguments with global constants, `deadargelim` is what notices the argument is not unused, and specializes the function.  So technically `deadargelim` is creating the specialized version of the callee, but it doesn't know that the parameters were previously replaced.

Since these are distinctly separate passes, it's not yet clear to me where best to make an incision.

> I reduced a test case for the function not getting inlined to https://godbolt.org/z/xW8G9c
> It only happens with -fsanitize=object-size, which doesn't seem related to the code in the test case either.

This isn't sinking the parameter into the caller, so a distinctly separate issue IMO.

It looks like Clang is emitting a relatively large fn in LLVM IR:
```llvm
define internal void @early_get_smp_config() #2 {
entry:
  %0 = call i64 @llvm.objectsize.i64.p0i8(i8* bitcast (%struct.anon* @e to i8*), i1 false, i1 false, i1 false), !nosanitize !6
  %1 = icmp uge i64 %0, 8, !nosanitize !6
  br i1 %1, label %cont, label %handler.type_mismatch, !prof !7, !nosanitize !6

handler.type_mismatch:                            ; preds = %entry
  call void @__ubsan_handle_type_mismatch_v1(i8* bitcast ({ { [6 x i8]*, i32, i32 }, { i16, i16, [11 x i8] }*, i8, i8 }* @1 to i8*), i64 ptrtoint (%struct.anon* @e to i64)) #6, !nosanitize !6
  br label %cont, !nosanitize !6

cont:                                             ; preds = %handler.type_mismatch, %entry
  %2 = call i64 @llvm.objectsize.i64.p0i8(i8* bitcast (%struct.anon* @e to i8*), i1 false, i1 false, i1 false), !nosanitize !6
  %3 = icmp uge i64 %2, 8, !nosanitize !6
  br i1 %3, label %cont2, label %handler.type_mismatch1, !prof !7, !nosanitize !6

handler.type_mismatch1:                           ; preds = %cont
  call void @__ubsan_handle_type_mismatch_v1(i8* bitcast ({ { [6 x i8]*, i32, i32 }, { i16, i16, [9 x i8] }*, i8, i8 }* @3 to i8*), i64 ptrtoint (%struct.anon* @e to i64)) #6, !nosanitize !6
  br label %cont2, !nosanitize !6

cont2:                                            ; preds = %handler.type_mismatch1, %cont
  %4 = load i8*, i8** getelementptr inbounds (%struct.anon, %struct.anon* @e, i32 0, i32 0, i32 0), align 8, !tbaa !8
  ret void
}
```
at some point, LLVM will trim this down to simply:
```llvm
define internal fastcc void @early_get_smp_config() unnamed_addr #2 {
entry:
  ret void
}
```
It looks like `LowerConstantIntrinsicsPass` is what cuts out most of the body of `early_get_smp_config`.  It looks like inlining occurs much earlier than `LowerConstantIntrinsicsPass`, IIUC.
```sh
$ clang -O2 foo.c -emit-llvm -o /dev/null -S -fsanitize=object-size -mllvm -print-after-all -mllvm -print-module-scope 2> foo.tx
$ grep 'IR Dump' foo.txt | grep -n -e InlinerPass -e LowerCon   
24:*** IR Dump After InlinerPass *** (scc: (early_get_smp_config))
25:*** IR Dump After InlinerPass *** (scc: (early_get_smp_config))
62:*** IR Dump After InlinerPass *** (scc: (g))
63:*** IR Dump After InlinerPass *** (scc: (g))
107:*** IR Dump After LowerConstantIntrinsicsPass *** (function: g)
132:*** IR Dump After LowerConstantIntrinsicsPass *** (function: early_get_smp_config)
```
I wonder if we can reorder the pipeline, or rerun `LowerConstantIntrinsicsPass`?  Since we decide not to inline `early_get_smp_config` into `g` because it's too big, but then eliminate `early_get_smp_config` via optimization.  But this should really be discussed further in a distinct bug.

**Comment by nickdesaulniers** [comment] 2021-03-04 19:58
Please help test: https://reviews.llvm.org/D97971

**Comment by nickdesaulniers** [comment] 2021-03-05 21:33
I'm duping this to #1302 , for cases where IPSCCP and DeadArgElim create specialized functions.

Let's use #1321 to track `early_get_smp_config()` `x86_init` and `-fsanitize=object-size`.

**Closed as completed by nickdesaulniers** 2021-03-05 21:33 UTC
Labels: duplicate, [BUG] llvm, [ARCH] x86_64
