### ISSUE TITLE
BUG: kernel NULL pointer dereference, address: 00000020

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1938] opened 2023-09-29 15:58 UTC
```
[    0.106881] BUG: kernel NULL pointer dereference, address: 00000020
[    0.107329] #PF: supervisor write access in kernel mode
[    0.107516] #PF: error_code(0x0002) - not-present page
[    0.107719] *pde = 00000000 
[    0.107952] Oops: 0002 [#1] PREEMPT SMP
[    0.108325] CPU: 0 PID: 0 Comm: swapper Not tainted 6.6.0-rc3 #1
[    0.108657] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS Arch Linux 1.16.2-2-2 04/01/2014
[    0.109104] EIP: __ring_buffer_alloc+0x32/0x170
[    0.110059] Code: 08 89 4d f0 89 d7 89 c3 a1 a0 a5 d2 da 8d 48 6f f7 d8 21 c8 ba c0 0d 00 00 e8 6a 8e 07 00 89 c6 31 c0 85 f6 0f 84 33 01 00 00 <c7> 46 10 00 00 00 00 89 3e c7 46 38 b0 3d b4 d9 8b 45 f0 89 46 14
[    0.110990] EAX: 00000000 EBX: 00001000 ECX: 0000006f EDX: 00000dc0
[    0.111276] ESI: 00000010 EDI: 00000001 EBP: dab57f68 ESP: dab57f54
[    0.111504] DS: 007b ES: 007b FS: 00d8 GS: 0000 SS: 0068 EFLAGS: 00200002
[    0.111791] CR0: 80050033 CR2: 00000020 CR3: 1ae1f000 CR4: 00000090
Warning: [    0.112106] Call Trace:
[    0.113144]  ? __die_body+0x56/0xa0
[    0.113390]  ? __die+0x6b/0x80
[    0.113517]  ? page_fault_oops+0x28b/0x2d0
[    0.113671]  ? kernelmode_fixup_or_oops+0xa0/0xb0
[    0.113823]  ? __bad_area_nosemaphore+0x4b/0x180
[    0.113966]  ? bad_area_nosemaphore+0xd/0x20
[    0.114103]  ? do_user_addr_fault+0x2f2/0x3e0
[    0.114[239](https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/6345880639/job/17239383391#step:6:240)]  ? pcpu_alloc+0x57e/0x7d0
[    0.114361]  ? exc_page_fault+0x46/0x124
[    0.114489]  ? pvclock_clocksource_read_nowd+0xe4/0xe4
[    0.114669]  ? handle_exception+0x133/0x133
[    0.114805]  ? pvclock_clocksource_read_nowd+0xe4/0xe4
[    0.114972]  ? __ring_buffer_alloc+0x32/0x170
[    0.115116]  ? pvclock_clocksource_read_nowd+0xe4/0xe4
[    0.115285]  ? __ring_buffer_alloc+0x32/0x170
[    0.115427]  tracer_alloc_buffers+0x8f/0x2d0
[    0.115697]  early_trace_init+0x60/0x68
[    0.115839]  start_kernel+0x130/0x328
[    0.115977]  i386_start_kernel+0x219/0x21c
[    0.116119]  startup_32_smp+0x156/0x158
[    0.116368] Modules linked in:
[    0.116727] CR2: 0000000000000020
[    0.117[249](https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/6345880639/job/17239383391#step:6:250)] ---[ end trace 0000000000000000 ]---
[    0.117463] EIP: __ring_buffer_alloc+0x32/0x170
[    0.117632] Code: 08 89 4d f0 89 d7 89 c3 a1 a0 a5 d2 da 8d 48 6f f7 d8 21 c8 ba c0 0d 00 00 e8 6a 8e 07 00 89 c6 31 c0 85 f6 0f 84 33 01 00 00 <c7> 46 10 00 00 00 00 89 3e c7 46 38 b0 3d b4 d9 8b 45 f0 89 46 14
[    0.118126] EAX: 00000000 EBX: 00001000 ECX: 0000006f EDX: 00000dc0
[    0.118300] ESI: 00000010 EDI: 00000001 EBP: dab57f68 ESP: dab57f54
[    0.118462] DS: 007b ES: 007b FS: 00d8 GS: 0000 SS: 0068 EFLAGS: 00200002
[    0.118678] CR0: 80050033 CR2: 00000020 CR3: 1ae1f000 CR4: 00000090
[    0.119034] Kernel panic - not syncing: Attempted to kill the idle task!
[    0.120086] ---[ end Kernel panic - not syncing: Attempted to kill the idle task! ]---
```
Seeing failures in tip for clang-17 and clang-18 overnight:
https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/6345880639/job/17239383391#step:6:299

**Comment by nickdesaulniers** [comment] 2023-10-02 16:59
I wonder if this is specific to a particular version of qemu? I can't seem to reproduce with:

```
$ ARCH=i386 make LLVM=1 -j128 defconfig clean all -s
# or
$ make LLVM=1 -j128 i386_defconfig clean all -s
```
linux @ 651e6e534250629675e90cf86387f4510b7ea640 (tip/master)
llvm @ 4b4d3832b131760d6abf76e68f3034259b61c2f0
qemu @ QEMU version: QEMU emulator version 8.0.4 (Debian 1:8.0.4+dfsg-2)

CI seems to be using QEMU version: QEMU emulator version 8.1.1

(though maybe not, [there were earlier](https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/6342673281/job/17229692845) green runs on 8.1.1)

**Comment by nickdesaulniers** [comment] 2023-10-02 17:18
> linux @ 651e6e534250629675e90cf86387f4510b7ea640 (tip/master)

651e6e534250629675e90cf86387f4510b7ea640 is [what tip/master is at, today](https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=651e6e534250629675e90cf86387f4510b7ea640).

From [the logs](https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/6374614715/job/17300282808#step:6:24) though, we seem to be checking out 18a1f37f57ff28fa544124151ef0171ffdafd162 which is weird. Even if I forcibly check that out, I still can't reproduce locally.

```
$ git fetch tip 18a1f37f57ff28fa544124151ef0171ffdafd162
$ git checkout 18a1f37f57ff28fa544124151ef0171ffdafd162
```

why is CI checking out tip/master at some rando sha?

**Comment by nathanchance** [comment] 2023-10-02 17:30
> why is CI checking out tip/master at some rando sha?

It looks like 18a1f37f57ff28fa544124151ef0171ffdafd162 was what tip/master was at until only eight hours ago: ~~https://git.kernel.org/pub/scm/infra/transparency-logs/gitolite/git/1.git/commit/?id=3c79ba61327b4d7969165d8be4d30ad59080a670~~ (EDIT: actually, I think it is this commit if I am reading things correctly now: https://git.kernel.org/pub/scm/infra/transparency-logs/gitolite/git/1.git/commit/?id=f5d989846e0dcbdc0a68d38e5cc6609ab47a727a)

The last CI run was from 17 hours ago or so.

**Comment by nathanchance** [comment] 2023-10-02 20:05
This does not appear to be LLVM related, as I can reproduce it with GCC. Report sent upstream: https://lore.kernel.org/20231002200426.GA4127272@dev-arch.thelio-3990X/

**Comment by nathanchance** [comment] 2023-10-03 18:11
Patch accepted: https://git.kernel.org/tip/3e32552652917f10c0aa8ac75cdc8f0b8d257dec

**Comment by nathanchance** [comment] 2023-10-10 20:07
This has been resolved in -next for a while.

**Closed as completed by nathanchance** 2023-10-10 20:07 UTC
Labels: [ARCH] x86, [BUG] linux-next, [FIXED][LINUX] development cycle, boot failure
