### ISSUE TITLE
`clang: error: unsupported argument '-mpower4' to option 'Wa,'`

### ISSUE THREAD

**Issue by paulmenzel** [ClangBuiltLinux/linux#1451] opened 2021-09-09 06:58 UTC
$ clang --version
    Ubuntu clang version 12.0.0-3ubuntu1~21.04.1
    Target: powerpc64le-unknown-linux-gnu
    Thread model: posix
    InstalledDir: /usr/bin
    $ git log --oneline -1
    a3fa7a101dcf Merge branches 'akpm' and 'akpm-hotfixes' (patches from Andrew)
    $ time make LLVM=1 bindeb-pkg V=1
    […]
    make -f ./scripts/Makefile.build obj=scripts/mod
      clang -Wp,-MMD,scripts/mod/.empty.o.d -nostdinc -isystem /usr/lib/llvm-12/lib/clang/12.0.0/include -I./arch/powerpc/include -I./arch/powerpc/include/generated  -I./include -I./arch/powerpc/include/uapi -I./arch/powerpc/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/compiler-version.h -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -I ./arch/powerpc -DHAVE_AS_ATHIGH=1 -Qunused-arguments -Wall -Wundef -Werror=strict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -fno-PIE -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Wno-format-security -std=gnu89 --target=powerpc64le-linux-gnu -fintegrated-as -Werror=unknown-warning-option -mlittle-endian -m64 -msoft-float -pipe -mcmodel=medium -mcpu=power8 -mno-altivec -mno-vsx -mno-spe -fno-asynchronous-unwind-tables -Wa,-mpower4 -Wa,-many -mlittle-endian -fno-delete-null-pointer-checks -O2 -Wframe-larger-than=2048 -fno-stack-protector -Wno-gnu -mno-global-merge -pg -Wdeclaration-after-statement -Wvla -Wno-pointer-sign -Wno-array-bounds -fno-strict-overflow -fno-stack-check -Werror=date-time -Wno-initializer-overrides -Wno-format -Wno-sign-compare -Wno-format-zero-length -Wno-tautological-constant-out-of-range-compare  -fsanitize=array-bounds -fsanitize=shift -fsanitize=object-size -fsanitize=bool -fsanitize=enum    -DKBUILD_MODFILE='"scripts/mod/empty"' -DKBUILD_BASENAME='"empty"' -DKBUILD_MODNAME='"empty"' -D__KBUILD_MODNAME=kmod_empty -c -o scripts/mod/empty.o scripts/mod/empty.c
    clang: error: unsupported argument '-mpower4' to option 'Wa,'
    clang: error: unsupported argument '-many' to option 'Wa,'

**Comment by nickdesaulniers** [comment] 2021-09-09 07:02
dupe of #672

**Comment by nickdesaulniers** [comment] 2021-09-09 07:03
You'll need to set `LLVM_IAS=0` now to continue building, ie `ARCH=powerpc make LLVM=1 LLVM_IAS=0 -j$(nproc)`

**Closed as completed by nickdesaulniers** 2021-09-09 07:02 UTC
Labels: duplicate

**Comment by paulmenzel** [comment] 2021-09-09 07:06
[Configuration file `.config`](https://github.com/ClangBuiltLinux/linux/files/7134248/linux-5.14-10557-ga3fa7a101dcf.config.txt)

**Comment by paulmenzel** [comment] 2021-09-09 07:06
Thank you, and sorry for not seeing the other issue.

**Comment by nickdesaulniers** [comment] 2021-09-09 18:26
No worries; I think it's better to report a bug twice than never at all!
