### ISSUE TITLE
'power10' is not a recognized processor for this target (ignoring processor)

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1799] opened 2023-02-06 23:48 UTC
```
$ make LLVM=1 -j128 -sk ARCH=powerpc LD=powerpc64le-linux-gnu-ld powernv_defconfig mm/maccess.o
...
'power10' is not a recognized processor for this target (ignoring processor)
'power10' is not a recognized processor for this target (ignoring processor)
'power10' is not a recognized processor for this target (ignoring processor)
'power10' is not a recognized processor for this target (ignoring processor)
```

**Comment by mpe** [comment] 2023-02-16 07:52
Caused by torvalds/linux@7fd123e544886bf04fa853869efe55cb3f22d0c0, which added `-mtune=power10`.

**But**, the code use `cc-option`, so clang must be saying it supports that option?

```
CFLAGS-$(CONFIG_POWERPC64_CPU) += $(call cc-option,-mtune=power10,	\
				  $(call cc-option,-mtune=power9,	\
				  $(call cc-option,-mtune=power8)))
```

In fact prior to that commit clang complained about `power9`:
```
'power9' is not a recognized processor for this target (ignoring processor)
```

So it seems `cc-option` doesn't work with `-mtune` on clang?

**Comment by mpe** [comment] 2023-02-16 07:56
Looks like `clang` supports `-mtune=pwr10`, and AFAICS so does binutils. So we should be able to switch to that, will test.

**Comment by mpe** [comment] 2023-02-16 08:52
> Looks like `clang` supports `-mtune=pwr10`, and AFAICS so does binutils. So we should be able to switch to that, will test.

But that doesn't help because we pass the option to the compiler, and GCC rejects `-mtune=pwr10` (and 8/9) :facepalm: 

I guess we'll have to do some Makefile gunk to use the different options on GCC vs clang.

**Comment by nathanchance** [comment] 2023-02-16 16:42
There appears to be a mismatch between the CPUs that LLVM and clang recognize for the sake of `-mtune`; clang supports `power<ver>` and `pwr<ver>` but LLVM only appears to accept `pwr<ver>`.

```
$ clang --target=powerpc64le -mtune=foobar -c -o /dev/null -x c /dev/null
error: unknown target CPU 'foobar'
note: valid target CPU values are: generic, 440, 450, 601, 602, 603, 603e, 603ev, 604, 604e, 620, 630, g3, 7400, g4, 7450, g4+, 750, 8548, 970, g5, a2, e500, e500mc, e5500, power3, pwr3, power4, pwr4, power5, pwr5, power5x, pwr5x, power6, pwr6, power6x, pwr6x, power7, pwr7, power8, pwr8, power9, pwr9, power10, pwr10, powerpc, ppc, ppc32, powerpc64, ppc64, powerpc64le, ppc64le, future

$ llc --mtriple powerpc64le --mcpu help
Available CPUs for this target:

  440     - Select the 440 processor.
  450     - Select the 450 processor.
  601     - Select the 601 processor.
  602     - Select the 602 processor.
  603     - Select the 603 processor.
  603e    - Select the 603e processor.
  603ev   - Select the 603ev processor.
  604     - Select the 604 processor.
  604e    - Select the 604e processor.
  620     - Select the 620 processor.
  7400    - Select the 7400 processor.
  7450    - Select the 7450 processor.
  750     - Select the 750 processor.
  970     - Select the 970 processor.
  a2      - Select the a2 processor.
  e500    - Select the e500 processor.
  e500mc  - Select the e500mc processor.
  e5500   - Select the e5500 processor.
  future  - Select the future processor.
  g3      - Select the g3 processor.
  g4      - Select the g4 processor.
  g4+     - Select the g4+ processor.
  g5      - Select the g5 processor.
  generic - Select the generic processor.
  ppc     - Select the ppc processor.
  ppc32   - Select the ppc32 processor.
  ppc64   - Select the ppc64 processor.
  ppc64le - Select the ppc64le processor.
  pwr10   - Select the pwr10 processor.
  pwr3    - Select the pwr3 processor.
  pwr4    - Select the pwr4 processor.
  pwr5    - Select the pwr5 processor.
  pwr5x   - Select the pwr5x processor.
  pwr6    - Select the pwr6 processor.
  pwr6x   - Select the pwr6x processor.
  pwr7    - Select the pwr7 processor.
  pwr8    - Select the pwr8 processor.
  pwr9    - Select the pwr9 processor.

$ llc --mtriple powerpc64le --mcpu pwr10 -o /dev/null </dev/null

$ llc --mtriple powerpc64le --mcpu power10 -o /dev/null </dev/null
'power10' is not a recognized processor for this target (ignoring processor)
'power10' is not a recognized processor for this target (ignoring processor)
```

**Comment by mpe** [comment] 2023-02-17 01:27
Hmm, I get different results here.

Your `clang` invocation gives me no output at all.

I've been using:
```
$ clang --target=powerpc64le -mtune=?
clang version 14.0.5 (Fedora 14.0.5-2.fc36)
Target: powerpc64le
Thread model: posix
InstalledDir: /usr/bin
Available CPUs for this target:

        440
        450
	...
        pwr10
        pwr3
        pwr4
        pwr5
        pwr5x
        pwr6
        pwr6x
        pwr7
        pwr8
        pwr9
```

**Comment by nathanchance** [comment] 2023-02-17 18:53
Ah yes, checking the value of `-mcpu`/`-mtune` for PowerPC was a recent change that will be in `clang-16` (https://github.com/llvm/llvm-project/commit/1fdbe5c573b920f00e5bfdbcea0e837833ae77a0), so that explains that difference.

It is still odd that they appear to support different values. That is certainly problematic for `cc-option`.

I suppose we could work around this with something like this but it is certainly not the prettiest :/

```diff
diff --git a/arch/powerpc/Makefile b/arch/powerpc/Makefile
index dc4cbf0a5ca9..bfbf95d02411 100644
--- a/arch/powerpc/Makefile
+++ b/arch/powerpc/Makefile
@@ -152,9 +152,11 @@ CFLAGS-$(CONFIG_GENERIC_CPU) += -mcpu=power8
 else
 CFLAGS-$(CONFIG_GENERIC_CPU) += -mcpu=power4
 endif
-CFLAGS-$(CONFIG_GENERIC_CPU) += $(call cc-option,-mtune=power10,       \
-                                 $(call cc-option,-mtune=power9,       \
-                                 $(call cc-option,-mtune=power8)))
+tune-prefix-$(CONFIG_CC_IS_CLANG) := pwr
+tune-prefix-$(CONFIG_CC_IS_GCC) := power
+CFLAGS-$(CONFIG_GENERIC_CPU) += $(call cc-option,-mtune=$(tune-prefix-y)10,    \
+                                 $(call cc-option,-mtune=$(tune-prefix-y)9,    \
+                                 $(call cc-option,-mtune=$(tune-prefix-y)8)))
 else ifdef CONFIG_PPC_BOOK3E_64
 CFLAGS-$(CONFIG_GENERIC_CPU) += -mcpu=powerpc64
 endif
```

**Comment by nickdesaulniers** [comment] 2023-02-18 01:06
cc @qiongsiwu @nemanjai

**Comment by nemanjai** [comment] 2023-02-20 01:42
This is an omission in LLVM that relates to how XLC worked (i.e. it only used `pwr<version>`). We need to fix this in LLVM. Thanks for the bug report. I'll try to get it in as soon as I can (although I suspect you'll still need the workaround for existing versions of LLVM).

**Comment by nathanchance** [comment] 2023-02-21 19:15
@nemanjai Thanks for taking a look! If it is possible to fix this relatively soon, we could make the workaround a little more precise, which would allow us to easily notice it when bumping the minimum required version of clang to build the kernel, so that we can eventually remove it:

```diff
diff --git a/arch/powerpc/Makefile b/arch/powerpc/Makefile
index e91d7e91347d..7a6eb974ee5a 100644
--- a/arch/powerpc/Makefile
+++ b/arch/powerpc/Makefile
@@ -156,9 +156,12 @@ endif
 CFLAGS-$(CONFIG_TARGET_CPU_BOOL) += -mcpu=$(CONFIG_TARGET_CPU)
 AFLAGS-$(CONFIG_TARGET_CPU_BOOL) += -mcpu=$(CONFIG_TARGET_CPU)

-CFLAGS-$(CONFIG_POWERPC64_CPU) += $(call cc-option,-mtune=power10,     \
-                                 $(call cc-option,-mtune=power9,       \
-                                 $(call cc-option,-mtune=power8)))
+tune-prefix-$(call clang-min-version, 170000) := power
+tune-prefix-$(call clang-min-version, 110000) := pwr
+tune-prefix-$(CONFIG_CC_IS_GCC) := power
+CFLAGS-$(CONFIG_POWERPC64_CPU) += $(call cc-option,-mtune=$(tune-prefix-y)10,  \
+                                 $(call cc-option,-mtune=$(tune-prefix-y)9,    \
+                                 $(call cc-option,-mtune=$(tune-prefix-y)8)))

 asinstr := $(call as-instr,lis 9$(comma)foo@high,-DHAVE_AS_ATHIGH=1)

```

If it is going to take some time to fix, no worries, we can always send the first diff to apply the workaround immediately, then update it in a future patch when the exact version that it is fixed in is known.

**Comment by MaskRay** [comment] 2023-02-22 21:58
> This is an omission in LLVM that relates to how XLC worked (i.e. it only used `pwr<version>`). We need to fix this in LLVM. Thanks for the bug report. I'll try to get it in as soon as I can (although I suspect you'll still need the workaround for existing versions of LLVM).

If `pwr9` is the preferred spelling, shouldn't it be an issue for GCC to recognize `pwr9`, instead of adding `power10` to Clang?
From a user perspective, I'd like to see fewer aliases so that uses can converge on the canonical spellings.

**Comment by nemanjai** [comment] 2023-02-23 02:21
The `pwr<version>` spelling comes from the XL compiler. The XL compiler is the canonical source on AIX. However, GCC never allowed that spelling and always only supported the `power<version>` spelling. Of course, GCC is the canonical source on Linux. Since Clang wants to play nice with both compilers, I am afraid we don't have much choice but to support both spellings. We already do so in the front end, this is of course just to extend it to the back end as well.

**Comment by nemanjai** [comment] 2023-02-28 15:35
@nathanchance I have proposed a fix in https://reviews.llvm.org/D144967

**Comment by mpe** [comment] 2023-03-02 13:20
Kernel workaround: https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=344416

**Comment by nathanchance** [comment] 2023-03-07 15:13
I do not think the kernel workaround is needed now that the LLVM change has been merged into main and `release/16.x`:

https://lore.kernel.org/20230302164324.GB3010526@dev-arch.thelio-3990X/

https://github.com/llvm/llvm-project/commit/59cd692454c9430f0fb77ca14b65cb9afcfe2776
https://github.com/llvm/llvm-project/commit/9b2e09e9fb1aa3bbe3668d7cc585188a3014d1b9

I am closing this up for now.

**Closed as completed by nathanchance** 2023-03-07 15:13 UTC
Labels: [BUG] llvm, [ARCH] powerpc, [FIXED][LLVM] 16
