### ISSUE TITLE
llvm-strip+llvm-objcopy missing wildcard/glob support

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#478] opened 2019-05-14 20:36 UTC
Copy pasta from @nathanchance :
https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/199950114
https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/199950118
https://travis-ci.com/ClangBuiltLinux/continuous-integration/jobs/199950120

Stuff along the lines of:

```
0000000000000000 R_AARCH64_ABS64 sort
0000000000000008 R_AARCH64_ABS64 __ksymtab_strings
drivers/firmware/efi/libstub/lib-sort.stub.o: absolute symbol references not allowed in the EFI stub
```

It looks like this is probably caused by `llvm-strip` not supporting the globs in `STUBCOPY_RM-y`, which @rupprecht noted [here](https://github.com/ClangBuiltLinux/linux/issues/435#issuecomment-477387356). These were removed upstream in https://github.com/torvalds/linux/commit/02562d0ca1084a688ac5c92e0e92947f62f13093 because of https://github.com/torvalds/linux/commit/f922c4abdf7648523589abee9460c87f51630d2f. https://github.com/torvalds/linux/commit/f922c4abdf7648523589abee9460c87f51630d2f decently backports to 4.9 and 4.14, not so clean for 4.4. Might be wise to conditionally turn on `llvm-strip`.
cc @rupprecht

**Comment by rupprecht** [comment] 2019-05-14 20:43
It sound like there's no opposition to just supporting glob characters: https://llvm.org/pr41268. But no one has gotten around to it yet.

**Comment by nathanchance** [comment] 2019-05-14 21:39
Just as an FYI, even without `llvm-strip`, `llvm-objcopy` fails on 4.4 with:

```
...
000000000000013c R_AARCH64_ABS64 .init.text
0000000000000014 R_AARCH64_ABS32 .debug_frame
0000000000000018 R_AARCH64_ABS64 .init.text
000000000000003c R_AARCH64_ABS32 .debug_frame
0000000000000040 R_AARCH64_ABS64 .init.text+168
000000000000005c R_AARCH64_ABS32 .debug_frame
0000000000000060 R_AARCH64_ABS64 .init.text+192
000000000000007c R_AARCH64_ABS32 .debug_frame
0000000000000080 R_AARCH64_ABS64 .init.text+216
00000000000000ac R_AARCH64_ABS32 .debug_frame
00000000000000b0 R_AARCH64_ABS64 .init.text+628
00000000000000cc R_AARCH64_ABS32 .debug_frame
00000000000000d0 R_AARCH64_ABS64 .init.text+656
00000000000000fc R_AARCH64_ABS32 .debug_frame
0000000000000100 R_AARCH64_ABS64 .init.text+1440
000000000000012c R_AARCH64_ABS32 .debug_frame
0000000000000130 R_AARCH64_ABS64 .init.text+1740
drivers/firmware/efi/libstub/arm-stub.stub.o: absolute symbol references not allowed in the EFI stub
```

Same root cause it seems ([drivers/firmware/efi/libstub/Makefile](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/firmware/efi/libstub/Makefile?h=linux-4.4.y)):

```
STUBCOPY_FLAGS-y		:= -R .debug* -R *ksymtab* -R *kcrctab*
...
quiet_cmd_stubcopy = STUBCPY $@
      cmd_stubcopy = if $(OBJCOPY) $(STUBCOPY_FLAGS-y) $< $@; then	\
		     $(OBJDUMP) -r $@ | grep $(STUBCOPY_RELOC-y)	\
		     && (echo >&2 "$@: absolute symbol references not allowed in the EFI stub"; \
			 rm -f $@; /bin/false); else /bin/false; fi
```

I don't think backporting the fixes for that is feasible, glob support would need to be added for this to work I think.

**Comment by nickdesaulniers** [comment] 2019-08-22 22:50
patch: https://reviews.llvm.org/D66613

**Comment by rupprecht** [comment] 2019-10-17 20:52
Finally landed just now in r375169. Closing this finally, and please let me know if it works in the kernel build!

**Closed by rupprecht** 2019-10-17 20:52 UTC
Labels: [ARCH] arm64, [BUG] llvm, [PATCH] Submitted, llvm-objcopy, llvm-strip

**Comment by nathanchance** [comment] 2019-10-17 23:21
```
% make -j$(nproc) -s ARCH=arm64 CC=clang CROSS_COMPILE=aarch64-linux-gnu- O=out OBJCOPY=llvm-objcopy STRIP=llvm-strip distclean defconfig all
```

succeeds for me on 4.4.196 with a build of LLVM at https://github.com/llvm/llvm-project/commit/9a335b6eda4fa619c37ec23f2c8bce20c9207eb2.
