### ISSUE TITLE
-Wtautological-constant-out-of-range-compare in drivers/gpu/drm/i915/gem/i915_gem_execbuffer.c

### ISSUE THREAD

**Issue by tpgxyz** [ClangBuiltLinux/linux#868] opened 2020-02-10 12:27 UTC
I'm compiling kernel-5.5.2 with LLVM/clang-10.x (RC1) on OpenMandriva, and it fails on x86_64 with below error.

More details for build can be found here https://abf.openmandriva.org/build_lists/681723

```
   if [ drivers/leds/trigger/ledtrig-heartbeat.o != "scripts/mod/empty.o" ]; then ./scripts/recordmcount  "drivers/leds/trigger/ledtrig-heartbeat.o"; fi;
  clang -Wp,-MD,drivers/gpu/drm/i915/gem/.i915_gem_execbuffer.o.d -nostdinc -isystem /usr/lib64/clang/10.0.0/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -Qunused-arguments -Wall -Wundef -Werror=strict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -fno-PIE -Werror=implicit-function-declaration -Werror=implicit-int -Wno-format-security -std=gnu89 -no-integrated-as -Werror=unknown-warning-option -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -mno-80387 -mstack-alignment=8 -mtune=generic -mno-red-zone -mcmodel=kernel -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -Wno-sign-compare -fno-asynchronous-unwind-tables -mretpoline-external-thunk -fno-delete-null-pointer-checks -Wno-address-of-packed-member -O2 -Wframe-larger-than=2048 -fstack-protector-strong -Wno-format-invalid-specifier -Wno-gnu -Wno-tautological-compare -mno-global-merge -Wno-unused-const-variable -pg -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wvla -Wno-pointer-sign -fno-strict-overflow -fno-merge-all-constants -fno-stack-check -Werror=date-time -Werror=incompatible-pointer-types -fmacro-prefix-map=./= -fcf-protection=none -Wno-initializer-overrides -Wno-format -Wno-sign-compare -Wno-format-zero-length -Wall -Wextra -Wno-unused-parameter -Wno-type-limits -Wno-missing-field-initializers -Wno-sign-compare -Wno-sometimes-uninitialized -Wno-initializer-overrides -Wno-uninitialized -Werror -DCONFIG_AS_MOVNTDQA -I./drivers/gpu/drm/i915 -I ./drivers/gpu/drm/i915 -I ./drivers/gpu/drm/i915/gvt/  -DMODULE  -DKBUILD_BASENAME='"i915_gem_execbuffer"' -DKBUILD_MODNAME='"i915"' -c -o drivers/gpu/drm/i915/gem/i915_gem_execbuffer.o drivers/gpu/drm/i915/gem/i915_gem_execbuffer.c
BUILDSTDERR: drivers/gpu/drm/i915/gem/i915_gem_execbuffer.c:1485:22: error: result of comparison of constant 576460752303423487 with expression of type 'unsigned int' is always false [-Werror,-Wtautological-constant-out-of-range-compare]
BUILDSTDERR:         if (unlikely(remain > N_RELOC(ULONG_MAX)))
BUILDSTDERR:             ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
BUILDSTDERR: ./include/linux/compiler.h:78:42: note: expanded from macro 'unlikely'
BUILDSTDERR: # define unlikely(x)    __builtin_expect(!!(x), 0)
BUILDSTDERR:                                             ^
BUILDSTDERR: 1 error generated.
BUILDSTDERR: make[4]: *** [scripts/Makefile.build:266: drivers/gpu/drm/i915/gem/i915_gem_execbuffer.o] Error 1
BUILDSTDERR: make[3]: *** [scripts/Makefile.build:503: drivers/gpu/drm/i915] Error 2
BUILDSTDERR: make[3]: *** Waiting for unfinished jobs....
```

**Comment by nathanchance** [comment] 2020-02-10 15:23
Dupe of #778

**Closed by nathanchance** 2020-02-10 15:23 UTC
Labels: [BUG] Untriaged
