### ISSUE TITLE
constant expression expected in arch/arm/mach-tegra/reset-handler.S

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1329] opened 2021-03-11 18:12 UTC
specifically on 4.19.y branch of stable:
```
$ ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make LLVM=1 LLVM_IAS=1 -j72 defconfig
$ ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make LLVM=1 LLVM_IAS=1 -j72
...
arch/arm/mach-tegra/reset-handler.S:175:19: error: constant expression expected                                                                                             
strbne r0, [r5, #__tegra20_cpu1_resettable_status_offset]                                                                                                                  
                      ^    
```
I'm not sure yet whether this is an assembler bug or what.
cc @jcai19 

I'm going to skip backporting [this series](https://lore.kernel.org/lkml/20190317225211.23091-1-digetx@gmail.com/) to 4.19 for now, but the relevant upstream commits are:
1. ebca2a6ee161502828de017b28a8f1d7422073f0 v5.2-rc1
2. 96446e21d6e9303cce0374af3f4012556dc501ce v5.2-rc1
3. ebc7c1a26578683a4d12ab3434a92c225a97e240 v5.2-rc1
4. 6ad27b8350401a3c79899b431097afc361b46374 v5.2-rc1
5. 2af6597ac3fab8a3796786bb73f8bd14a9f2d376 v5.2-rc1
6. dae84be59d667089a7ad3d27a0662e6b71f13116 v5.2-rc1
7. 78ee399f1632a00a92dcdb0ebba8cfe0081a3e5d v5.2-rc1

CONFIG_ARCH_TEGRA

**Comment by jcai19** [comment] 2021-03-11 20:46
Issue reproduced locally.  
```
$ ARCH=arm make clean
$ ARCH=arm CROSS_COMPILE=armv7a-linux-gnueabihf- make LLVM=1 LLVM_IAS=1 defconfig
$ ./scripts/config -e CONFIG_ARCH_TEGRA
$ ARCH=arm CROSS_COMPILE=armv7a-linux-gnueabihf- make -j32 LLVM=1 LLVM_IAS=1 V=1 arch/arm/mach-tegra/reset-handler.o
```

**Comment by jcai19** [comment] 2021-03-11 21:05
Reduced repro.

```
$ cat foo.s 
0:
nop
.equ res, . - 0b
strneb r0, [r5, #res]
arm-linux-gnueabihf-as -march=armv7-a foo.s -o gas.o
arm-linux-gnueabihf-objdump -d gas.o

gas.o:     file format elf32-littlearm


Disassembly of section .text:

00000000 <.text>:
   0:	e320f000 	nop	{0}
   4:	15c50004 	strbne	r0, [r5, #4]
llvm-mc -triple=armv7a -filetype=obj foo.s -o ias.o
foo.s:4:18: error: constant expression expected
strneb r0, [r5, #res]
                 ^

```

**Comment by jcai19** [comment] 2021-03-12 22:51
The problem is that the IAS ARM backend only support constant expressions in memory operations, so it fails to parse the expression in strneb, which is defined as follows,

```
.equ    __tegra20_cpu1_resettable_status_offset,  . - __tegra_cpu_reset_handler_start
```

I hacked IAS to parse and build the [simple repro](https://github.com/ClangBuiltLinux/linux/issues/1329#issuecomment-797048434) (at the cost of many failed tests) but it still failed to build reset-handler.S, likely due to the two symbols defining __tegra20_cpu1_resettable_status_offset are not in the same subsection so their difference cannot be resolved until the layout of fragments (list of data blocks that comprise subsections and sections) are finalized. So it looks like we would need to support expressions and resolve them after the layout is known. The [failed check in LLVM code](https://llvm.org/doxygen/ARMAsmParser_8cpp_source.html#l05825) mentions <label> forms of memory instructions. It would be helpful to have a working example for comparison but so far I haven't found one.

Also the problem seems to be two fold: IAS does not recognize strneb.

```
$ cat bar.s 
strneb r0, [r5, #4]
$ arm-linux-gnueabihf-as -march=armv7-a bar.s -o gas.o
$ arm-linux-gnueabihf-objdump -d gas.o

gas.o:     file format elf32-littlearm


Disassembly of section .text:

00000000 <.text>:
   0:	15c50004 	strbne	r0, [r5, #4]

$ llvm-mc -triple=armv7a -filetype=obj bar.s -o ias.o
bar.s:1:1: error: invalid instruction, did you mean: strb, strexb?
strneb r0, [r5, #4]
```

**Comment by nickdesaulniers** [comment] 2021-03-12 23:00
> Also the problem seems to be two fold: IAS does not recognize strneb.

Ah, right, `strneb` is not UAL, it should be changed in kernel sources to `strbne`.

**Comment by nathanchance** [comment] 2021-03-12 23:06
Presumably, that is why we do not see this on mainline: https://git.kernel.org/linus/d90bdb72bb42369ae1493f5bbb3fadb3c854aad8

**Comment by nickdesaulniers** [comment] 2021-03-12 23:25
> Presumably, that is why we do not see this on mainline: https://git.kernel.org/linus/d90bdb72bb42369ae1493f5bbb3fadb3c854aad8

No, https://github.com/ClangBuiltLinux/linux/commit/2af6597ac3fab8a3796786bb73f8bd14a9f2d376 removes this and we can build, but that depends on other patches in that series.

**Comment by nathanchance** [comment] 2021-03-12 23:31
Sorry, I was talking about the `strneb` error, should have been more specific.

**Comment by jcai19** [comment] 2021-03-19 03:27
LLVM patch sent for review: https://reviews.llvm.org/D98916

**Comment by jcai19** [comment] 2021-04-22 22:13
Close it for now as I'm not aware of anyone building 4.19 on 32-bit ARM with Clang's integrated assembler.

**Closed as completed by jcai19** 2021-04-22 22:13 UTC
Labels: [BUG] llvm, [TOOL] integrated-as, [ARCH] arm32, [WORKAROUND] Applied, [FIXED][LLVM] 13
