### ISSUE TITLE
LLD 10 segfaults when linking vmlinux

### ISSUE THREAD

**Issue by pefoley2** [ClangBuiltLinux/linux#994] opened 2020-04-14 17:45 UTC
Occurred on a gentoo linux system building defconfig from 8f3d9f354286.

Running make LLVM=1 segfaults in linux-vmlinux.sh

Re-running the command under gdb gives:
Starting program: /usr/bin/ld.lld -m elf_x86_64 -z max-page-size=0x200000 --emit-relocs --discard-none --build-id --strip-debug -o .tmp_vmlinux.kallsyms1 -T ./arch/x86/kernel/vmlinux.lds --whole-archive arch/x86/kernel/head_64.o arch/x86/kernel/head64.o arch/x86/kernel/ebda.o arch/x86/kernel/platform-quirks.o init/built-in.a usr/built-in.a arch/x86/built-in.a kernel/built-in.a certs/built-in.a mm/built-in.a fs/built-in.a ipc/built-in.a security/built-in.a crypto/built-in.a block/built-in.a lib/built-in.a arch/x86/lib/built-in.a lib/lib.a arch/x86/lib/lib.a drivers/built-in.a sound/built-in.a arch/x86/pci/built-in.a arch/x86/power/built-in.a arch/x86/video/built-in.a net/built-in.a virt/built-in.a --no-whole-archive --start-group --end-group
Thread 1 "ld.lld" received signal SIGSEGV, Segmentation fault.
0x00007ffff4ca8e12 in llvm::Twine::printOneChild(llvm::raw_ostream&, llvm::Twine::Child, llvm::Twine::NodeKind) const () from /usr/lib64/llvm/10/lib64/libLLVM-10.so
(gdb) bt
#0  0x00007ffff4ca8e12 in llvm::Twine::printOneChild(llvm::raw_ostream&, llvm::Twine::Child, llvm::Twine::NodeKind) const () from /usr/lib64/llvm/10/lib64/libLLVM-10.so
#1  0x00007ffff4ca8f8d in llvm::Twine::toVector(llvm::SmallVectorImpl<char>&) const () from /usr/lib64/llvm/10/lib64/libLLVM-10.so
#2  0x00007ffff4ca9047 in llvm::Twine::str[abi:cxx11]() const () from /usr/lib64/llvm/10/lib64/libLLVM-10.so
#3  0x0000555555769f0d in lld::elf::getOutputSectionName(lld::elf::InputSectionBase const*) ()
#4  0x00005555556c5c08 in lld::elf::LinkerScript::addOrphanSections()::{lambda(lld::elf::InputSectionBase*)#1}::operator()(lld::elf::InputSectionBase*) const ()
#5  0x00005555556bf911 in lld::elf::LinkerScript::addOrphanSections() ()
#6  0x0000555555653194 in void lld::elf::LinkerDriver::link<llvm::object::ELFType<(llvm::support::endianness)1, true> >(llvm::opt::InputArgList&) ()
#7  0x000055555559953d in lld::elf::LinkerDriver::main(llvm::ArrayRef<char const*>) ()
#8  0x0000555555656785 in lld::elf::link(llvm::ArrayRef<char const*>, bool, llvm::raw_ostream&, llvm::raw_ostream&) ()
#9  0x0000555555597cda in main ()

It's possible to workaround this by passing LD=ld.bfd, but it's somewhat concerning.

**Comment by nathanchance** [comment] 2020-04-14 17:50
Thanks for the report! This is a duplicate of #962 (my title could have been better) and its fix has been picked for 10.0.1 already: https://github.com/llvm/llvm-project/commit/489a7356cca373de761ada4c06c5b43edc581b4b

**Closed** 2020-04-14 17:51 UTC
Labels: duplicate
