### ISSUE TITLE
objtool: ftrace + gcov warnings "call without frame pointer save/setup"

### ISSUE THREAD

**Issue by arndb** [ClangBuiltLinux/linux#1233] opened 2021-01-05 20:27 UTC
For each file in kernel/trace/, we get:

 kernel/trace/trace_clock.o: warning: objtool: __llvm_gcov_writeout()+0x7: call without frame pointer save/setup
 kernel/trace/trace_clock.o: warning: objtool: __llvm_gcov_reset()+0x0: call without frame pointer save/setup
 kernel/trace/trace_clock.o: warning: objtool: __llvm_gcov_flush()+0x0: call without frame pointer save/setup
 kernel/trace/trace_clock.o: warning: objtool: __llvm_gcov_init()+0x0: call without frame pointer save/setup

**Comment by arndb** [comment] 2021-01-05 20:27
[0x1FCB0B8C-config.gz](https://github.com/ClangBuiltLinux/linux/files/5772422/0x1FCB0B8C-config.gz)

**Comment by nathanchance** [comment] 2021-01-05 20:38
Is this a duplicate of #955?

**Comment by arndb** [comment] 2021-01-05 21:07
I no longer see the output referenced in #955, in sys_ia32.c, only in kernel/trace/, so I think that's a slightly different problem.

**Comment by nickdesaulniers** [comment] 2021-01-05 21:30
It's the same, maybe different files, but it's the same root cause.

**Closed by nickdesaulniers** 2021-01-05 21:30 UTC
