### ISSUE TITLE
error: instruction requires: TrustZone

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1880] opened 2023-06-22 16:55 UTC
some android kernels are failing to build with the above error:
https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/5342247982/jobs/9685209480#step:6:326

Perhaps some downstream change that shouldn't be built for 32b kernels?  Maybe a change in clang-17 exposed this?

**Comment by nathanchance** [comment] 2023-06-22 16:56
Dupe of #1878.

**Closed as not planned by nathanchance** 2023-06-22 16:56 UTC
Labels: duplicate
