### ISSUE TITLE
Warning: entity size for SHF_MERGE not specified

### ISSUE THREAD

**Issue by agners** [ClangBuiltLinux/linux#77] opened 2018-09-16 21:45 UTC
Currently building for ARM32 shows warnings for several files:

      CC      drivers/soc/tegra/fuse/speedo-tegra114.o
    /tmp/speedo-tegra114-a6d4fc.s: Assembler messages:
    /tmp/speedo-tegra114-a6d4fc.s:155: Warning: entity size for SHF_MERGE not specified

This appears for multiple files, at least `drivers/soc/tegra/fuse/speedo-tegra114.c`, `drivers/soc/tegra/fuse/speedo-tegra124.c`, `drivers/clk/berlin/berlin2-avpll.c` and `drivers/clk/ti/clkctrl.c` are affected. It seems to be related to structs marked with `__initconst`.

It is probably a LLVM issue, it has been reported here: https://bugs.llvm.org/show_bug.cgi?id=31828

**Comment by nickdesaulniers** [comment] 2018-09-17 17:04
I saw this during an arm64 build as well, in issue #44 which we've marked as a dupe of this one.

**Comment by nathanchance** [comment] 2018-10-10 02:01
I don't see any warnings on an arm64 allyesconfig build with that patch.

**Comment by nickdesaulniers** [comment] 2018-10-10 02:13
Thanks for testing! That's going above and beyond the call of duty!

**Comment by nickdesaulniers** [comment] 2018-10-11 20:46
Was reverted since the new test was failing on OSX. Relanding in https://reviews.llvm.org/D53146.

**Closed** 2018-10-12 19:45 UTC
Labels: [ARCH] arm32, [ARCH] arm64, [BUG] llvm, [FIXED][CLANG] 8
