### ISSUE TITLE
-Wenum-conversion in drivers/infiniband/hw/mlx4/mad.c

### ISSUE THREAD

**Issue by shenki** [ClangBuiltLinux/linux#89] opened 2018-09-17 08:28 UTC
```
drivers/infiniband/hw/mlx4/mad.c:1811:41: warning: implicit conversion from enumeration type
      'enum mlx4_ib_qp_flags' to different enumeration type 'enum ib_qp_create_flags' [-Wenum-conversion]
                qp_init_attr.init_attr.create_flags = MLX4_IB_SRIOV_TUNNEL_QP;
                                                    ~ ^~~~~~~~~~~~~~~~~~~~~~~
drivers/infiniband/hw/mlx4/mad.c:1819:41: warning: implicit conversion from enumeration type
      'enum mlx4_ib_qp_flags' to different enumeration type 'enum ib_qp_create_flags' [-Wenum-conversion]
                qp_init_attr.init_attr.create_flags = MLX4_IB_SRIOV_SQP;
                                                    ~ ^~~~~~~~~~~~~~~~~
```

**Comment by tpimh** [comment] 2018-09-18 12:36
Closed as duplicate of #64

**Closed by tpimh** 2018-09-18 12:36 UTC
Labels: duplicate
