### ISSUE TITLE
clang-12: Unsupported relocation type: R_386_PLT32 

### ISSUE THREAD

**Issue by arndb** [ClangBuiltLinux/linux#1210] opened 2020-12-07 13:40 UTC
The latest clang-12 fails to build some 32-bit x86 kernels:

Unsupported relocation type: R_386_PLT32 (4)
make[5]: *** [/git/arm-soc/arch/x86/boot/compressed/Makefile:120: arch/x86/boot/compressed/vmlinux.relocs] Error 1

This was no problem with a slightly older clang-12 snapshot, or with the latest clang-11.

**Comment by nickdesaulniers** [comment] 2020-12-07 21:11
Didn't @nivedita76 do some work to avoid PLT relocations in 32b x86 boot/?

**Comment by nivedita76** [comment] 2020-12-07 21:19
@arndb Is that from arch/x86/tools/relocs? That indicates a PLT32 relocation in the main kernel, which is unrelated to the boot/compressed work. The tool handles PLT relocs on 64-bit but apparently not on 32-bit, not sure why: they should be equivalent to PC32 on both, right?

**Comment by nivedita76** [comment] 2020-12-07 21:34
@MaskRay seems to have a commit that looks vaguely related, though I'd not expect it to produce R_386_PLT32 looking at the description.
https://reviews.llvm.org/rG37f0c8df47d84ba311fc9a2c1884935ba8961e84

hjl says R_386_PLT32 should only be produced for PIC code, though I don't quite follow the reasoning.
https://llvm.org/pr36674

**Comment by arndb** [comment] 2020-12-07 22:01
Yes, to confirm, this is PLT32 relocations in the main kernel. I don't have a reproducer at hand (currently building with clang-11, but could go back to clang-12 if needed), but from what I remember, it appeared that the PLT32 relocations were for compiler-generated function calls to things like memset(), memcpy() or stackprotector, not for normal function calls.

**Comment by MaskRay** [comment] 2020-12-08 06:00
> @MaskRay seems to have a commit that looks vaguely related, though I'd not expect it to produce R_386_PLT32 looking at the description.
> https://reviews.llvm.org/rG37f0c8df47d84ba311fc9a2c1884935ba8961e84
> 
> hjl says R_386_PLT32 should only be produced for PIC code, though I don't quite follow the reasoning.
> https://llvm.org/pr36674

There is no fundamental reason that GNU as's i386 port cannot use R_386_PLT32. Once it does, we can change LLVM MC as well.

Actually, PLT32 is preferred (see https://sourceware.org/pipermail/binutils/2020-April/000424.html).
https://llvm.org/pr36674 is probably about (a) establishing the convention that PC32 is for -fno-pic and non-pic PLT while PLT32 is for -fpie/-fpic and pic PLT (b) some legacy software processing relocations does not support PLT32.

```
commit 2585b7a5ce5830e60a089aa2316a329558902f0c
Author: H.J. Lu <hidden>
Date:   Sun Jul 19 06:51:32 2020

    x86: Change PLT32 reloc against section to PC32
    
    Commit 292676c1 resolved PLT32 reloc aganst local symbol to section.
    Since PLT32 relocation must be against symbols, turn such PLT32
    relocation into PC32 relocation.
```

I have tried `make -sk -j 50 ARCH=i386 LLVM=1 O=/tmp/out/i386 -j 50 i386_defconfig vmlinux` with Clang built today and it works.

**Comment by arndb** [comment] 2020-12-08 09:23
I got a minimized test case: https://godbolt.org/z/GP7q7a

All compilers turn a strcat() into strlen() plus store, but the generated call to strlen() in clang-12 uses a PLT32 reloc.

**Comment by arndb** [comment] 2020-12-08 09:26
I think it happens to work in defconfig because we build i386 with -ffreestanding, which prevents the strcat() optimization from my example (I have a local patch to remove the -ffreestanding), and the defconfig does not generate calls to __stack_chk_fail(), which have the same problem when enabled.

**Comment by MaskRay** [comment] 2020-12-08 17:09
The difference is due to `[TargetMachine] Don't imply dso_local on function declarations in Reloc::Static model for ELF/wasm`.

LLVM synthesized function declarations (e.g. strlen, as opposed to declarations written by the user) do not have the dso_local specifier. PLT32 can prevent canonical PLT entries (SHN_UNDEF with non-zero st_value) and is thus preferred.

`arch/x86/tools/relocs.c` and `arch/x86/kernel/module.c` should handle `R_386_PLT32` similar to `R_386_PC32`.

**Comment by nivedita76** [comment] 2020-12-08 17:14
> I think it happens to work in defconfig because we build i386 with -ffreestanding, which prevents the strcat() optimization from my example (I have a local patch to remove the -ffreestanding), and the defconfig does not generate calls to __stack_chk_fail(), which have the same problem when enabled.

@nickdesaulniers did https://lore.kernel.org/lkml/20200817220212.338670-5-ndesaulniers@google.com/ not get merged?

**Comment by nickdesaulniers** [comment] 2020-12-08 21:01
> @nickdesaulniers did https://lore.kernel.org/lkml/20200817220212.338670-5-ndesaulniers@google.com/ not get merged?

I don't think so; 1e1b6d63d6340764e00356873e5794225a2a03ea is ultimately what shipped.

**Comment by MaskRay** [comment] 2021-01-06 23:33
I'll post a kernel patch.

```
--- i/arch/x86/Makefile
+++ w/arch/x86/Makefile
@@ -75,7 +75,7 @@ ifeq ($(CONFIG_X86_32),y)
         KBUILD_CFLAGS += $(cflags-y)
 
         # temporary until string.h is fixed
-        KBUILD_CFLAGS += -ffreestanding
+        #KBUILD_CFLAGS += -ffreestanding
 else
         BITS := 64
         UTS_MACHINE := x86_64
```

With top-of-trunk clang, this reproduces
```
(cd ~/Dev/linux; PATH=/tmp/RelA/bin:$PATH make -sk -j 50 ARCH=i386 LLVM=1 O=/tmp/out/i386 -j 50 i386_defconfig all )
```

**Comment by MaskRay** [comment] 2021-01-06 23:51
```patch
From 6f4d68765bc6344851810deaff29a4677859114e Mon Sep 17 00:00:00 2001
From: Fangrui Song <hidden>
Date: Wed, 6 Jan 2021 15:31:28 -0800
Subject: [PATCH] x86: Treat R_386_PLT32 as R_386_PC32

This is similar to commit b21ebf2fb4cde1618915a97cc773e287ff49173e "x86:
Treat R_X86_64_PLT32 as R_X86_64_PC32", but for i386.  As far as Linux
kernel is concerned, R_386_PLT32 can be treated the same as R_386_PC32.

R_386_PC32/R_X86_64_PC32 are PC-relative relocation types with the
requirement that the symbol address is significant.
R_386_PLT32/R_X86_64_PLT32 are PC-relative relocation types without the
address significance requirement.

On i386, there are 2 types of PLTs, PIC and non-PIC. Currently the
convention is to use R_386_PC32 for non-PIC PLT and R_386_PLT32 for PIC
PLT but R_386_PLT32 is arguably preferable for -fno-pic code as well:
this can avoid a "canonical PLT entry" (st_shndx=0, st_value!=0) if the
symbol turns out to be defined externally. Latest Clang (since
961f31d8ad14c66829991522d73e14b5a96ff6d4) can use R_386_PLT32 for
compiler produced symbols and future GCC may use R_386_PLT32 as well
if the maintainers agree to adopt an option like
-fdirect-access-external-data to avoid "canonical PLT entry"/copy
relocations https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98112

On x86-64, there is no such distinction and R_X86_64_PLT32 is used for
`call/jump foo` with newer (2018) GNU as/LLVM integrated assembler.

Link: https://github.com/ClangBuiltLinux/linux/issues/1210
Reported-by: Arnd Bergmann <hidden>
Signed-off-by: Fangrui Song <hidden>
---
 arch/x86/Makefile        | 2 +-
 arch/x86/kernel/module.c | 1 +
 arch/x86/tools/relocs.c  | 2 ++
 3 files changed, 4 insertions(+), 1 deletion(-)

diff --git a/arch/x86/Makefile b/arch/x86/Makefile
index 7116da3980be..3beb852ff558 100644
--- a/arch/x86/Makefile
+++ b/arch/x86/Makefile
@@ -75,7 +75,7 @@ ifeq ($(CONFIG_X86_32),y)
         KBUILD_CFLAGS += $(cflags-y)
 
         # temporary until string.h is fixed
-        KBUILD_CFLAGS += -ffreestanding
+        #KBUILD_CFLAGS += -ffreestanding
 else
         BITS := 64
         UTS_MACHINE := x86_64
diff --git a/arch/x86/kernel/module.c b/arch/x86/kernel/module.c
index 34b153cbd4ac..5e9a34b5bd74 100644
--- a/arch/x86/kernel/module.c
+++ b/arch/x86/kernel/module.c
@@ -114,6 +114,7 @@ int apply_relocate(Elf32_Shdr *sechdrs,
 			*location += sym->st_value;
 			break;
 		case R_386_PC32:
+		case R_386_PLT32:
 			/* Add the value, subtract its position */
 			*location += sym->st_value - (uint32_t)location;
 			break;
diff --git a/arch/x86/tools/relocs.c b/arch/x86/tools/relocs.c
index ce7188cbdae5..717e48ca28b6 100644
--- a/arch/x86/tools/relocs.c
+++ b/arch/x86/tools/relocs.c
@@ -867,6 +867,7 @@ static int do_reloc32(struct section *sec, Elf_Rel *rel, Elf_Sym *sym,
 	case R_386_PC32:
 	case R_386_PC16:
 	case R_386_PC8:
+	case R_386_PLT32:
 		/*
 		 * NONE can be ignored and PC relative relocations don't
 		 * need to be adjusted.
@@ -910,6 +911,7 @@ static int do_reloc_real(struct section *sec, Elf_Rel *rel, Elf_Sym *sym,
 	case R_386_PC32:
 	case R_386_PC16:
 	case R_386_PC8:
+	case R_386_PLT32:
 		/*
 		 * NONE can be ignored and PC relative relocations don't
 		 * need to be adjusted.
-- 
2.29.2.729.g45daf8777d-goog
```

**Comment by dileks** [comment] 2021-01-07 00:59
Patch submitted: https://lore.kernel.org/lkml/20210107001739.1321725-1-maskray@google.com/

**Comment by dileks** [comment] 2021-01-07 20:41
Patch v2 submitted: https://lore.kernel.org/lkml/20210107185555.2781221-1-maskray@google.com/

**Comment by nickdesaulniers** [comment] 2021-01-28 17:59
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/commit/?id=bb73d07148c405c293e576b40af37737faf23a6a

**Comment by nathanchance** [comment] 2021-02-21 05:39
Merged into mainline: https://git.kernel.org/linus/bb73d07148c405c293e576b40af37737faf23a6a

**Closed by nathanchance** 2021-02-21 05:39 UTC
Labels: [ARCH] x86, [BUG] linux, [PATCH] Accepted

**Comment by nickdesaulniers** [comment] 2021-02-24 17:22
autosel picked this back to 4.4 for us.

**Comment by dileks** [comment] 2021-03-05 12:48
Picked up for several linux-stable (rc) releases.
