### ISSUE TITLE
Error: illegal operands `auipc a2,%got_pcrel_hi(kmalloc_caches)

### ISSUE THREAD

**Issue by tpgxyz** [ClangBuiltLinux/linux#898] opened 2020-02-21 08:07 UTC
I'm compiling kernel 5.5.4 with LLVM/clang on riscv64 and here is the errors:

Build details can be found here https://abf.openmandriva.org/build_lists/709794

```
clang -Wp,-MD,mm/.z3fold.o.d -nostdinc -isystem /usr/lib64/clang/10.0.0/include -I./arch/riscv/include -I./arch/riscv/include/generated  -I./include -I./arch/riscv/include/uapi -I./arch/riscv/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -Qunused-arguments -Wall -Wundef -Werror=strict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -fno-PIE -Werror=implicit-function-declaration -Werror=implicit-int -Wno-format-security -std=gnu89 -no-integrated-as -Werror=unknown-warning-option -mabi=lp64 -march=rv64imac -mno-save-restore -DCONFIG_PAGE_OFFSET=0xffffffe000000000 -mcmodel=medany -fno-delete-null-pointer-checks -Wno-address-of-packed-member -O2 -Wframe-larger-than=2048 -fno-stack-protector -Wno-format-invalid-specifier -Wno-gnu -Wno-tautological-compare -mno-global-merge -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -Wdeclaration-after-statement -Wvla -Wno-pointer-sign -fno-strict-overflow -fno-merge-all-constants -fno-stack-check -Werror=date-time -Werror=incompatible-pointer-types -fmacro-prefix-map=./= -Wno-initializer-overrides -Wno-format -Wno-sign-compare -Wno-format-zero-length  -DMODULE -fPIC -mno-relax  -DKBUILD_BASENAME='"z3fold"' -DKBUILD_MODNAME='"z3fold"' -c -o mm/z3fold.o mm/z3fold.c
BUILDSTDERR: In file included from mm/z3fold.c:27:
BUILDSTDERR: In file included from ./include/linux/sched.h:12:
BUILDSTDERR: ./arch/riscv/include/asm/current.h:30:9: warning: variable 'tp' is uninitialized when used here [-Wuninitialized]
BUILDSTDERR:         return tp;
BUILDSTDERR:                ^~
BUILDSTDERR: ./arch/riscv/include/asm/current.h:29:33: note: initialize the variable 'tp' to silence this warning
BUILDSTDERR:         register struct task_struct *tp __asm__("tp");
BUILDSTDERR:                                        ^
BUILDSTDERR:                                         = NULL
BUILDSTDERR: '-save-restore' is not a recognized feature for this target (ignoring feature)
BUILDSTDERR: '-save-restore' is not a recognized feature for this target (ignoring feature)
BUILDSTDERR: '-save-restore' is not a recognized feature for this target (ignoring feature)
BUILDSTDERR: 1 warning generated.
BUILDSTDERR: /tmp/z3fold-cd7cd6.s: Assembler messages:
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:127: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:127: Error: illegal operands `auipc a2,%got_pcrel_hi(kmalloc_caches)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:179: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:179: Error: illegal operands `auipc a1,%got_pcrel_hi(__cpu_possible_mask)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:185: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:185: Error: illegal operands `auipc a1,%got_pcrel_hi(nr_cpu_ids)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:198: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:198: Error: illegal operands `auipc a1,%got_pcrel_hi(__per_cpu_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:219: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:219: Error: illegal operands `auipc a1,%got_pcrel_hi(__cpu_possible_mask)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:225: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:225: Error: illegal operands `auipc a1,%got_pcrel_hi(nr_cpu_ids)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:562: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:562: Error: illegal operands `auipc a0,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:567: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:567: Error: illegal operands `auipc a1,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:572: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:572: Error: illegal operands `auipc a2,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:596: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:596: Error: illegal operands `auipc a0,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:601: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:601: Error: illegal operands `auipc a1,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:606: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:606: Error: illegal operands `auipc a1,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:788: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:788: Error: illegal operands `auipc a2,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:793: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:793: Error: illegal operands `auipc a3,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:798: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:798: Error: illegal operands `auipc a4,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:842: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:842: Error: illegal operands `auipc a0,%got_pcrel_hi(__per_cpu_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1046: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1046: Error: illegal operands `auipc a0,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1051: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1051: Error: illegal operands `auipc a1,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1056: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1056: Error: illegal operands `auipc a2,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1125: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1125: Error: illegal operands `auipc a0,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1130: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1130: Error: illegal operands `auipc a1,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1135: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1135: Error: illegal operands `auipc a2,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1262: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1262: Error: illegal operands `auipc a0,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1267: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1267: Error: illegal operands `auipc a1,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1272: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1272: Error: illegal operands `auipc a2,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1354: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1354: Error: illegal operands `auipc a2,%got_pcrel_hi(__cpu_online_mask)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1389: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1389: Error: illegal operands `auipc a0,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1394: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1394: Error: illegal operands `auipc a1,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1399: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1399: Error: illegal operands `auipc a2,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1414: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1414: Error: illegal operands `auipc a0,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1419: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1419: Error: illegal operands `auipc a1,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1424: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1424: Error: illegal operands `auipc a2,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1698: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1698: Error: illegal operands `auipc a0,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1704: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1704: Error: illegal operands `auipc a1,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1710: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:1710: Error: illegal operands `auipc a2,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2245: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2245: Error: illegal operands `auipc a0,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2250: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2250: Error: illegal operands `auipc a1,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2255: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2255: Error: illegal operands `auipc a2,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2349: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2349: Error: illegal operands `auipc a0,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2354: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2354: Error: illegal operands `auipc a1,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2359: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2359: Error: illegal operands `auipc a2,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2461: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2461: Error: illegal operands `auipc a0,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2466: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2466: Error: illegal operands `auipc a1,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2471: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2471: Error: illegal operands `auipc a2,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2514: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2514: Error: illegal operands `auipc a0,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2519: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2519: Error: illegal operands `auipc a1,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2524: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2524: Error: illegal operands `auipc a2,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2629: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2629: Error: illegal operands `auipc a0,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2635: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2635: Error: illegal operands `auipc a0,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2641: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2641: Error: illegal operands `auipc a1,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2836: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2836: Error: illegal operands `auipc a0,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2841: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2841: Error: illegal operands `auipc a1,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2846: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2846: Error: illegal operands `auipc a2,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2877: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2877: Error: illegal operands `auipc a0,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2882: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2882: Error: illegal operands `auipc a1,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2887: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:2887: Error: illegal operands `auipc a2,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3293: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3293: Error: illegal operands `auipc a0,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3298: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3298: Error: illegal operands `auipc a1,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3303: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3303: Error: illegal operands `auipc a2,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3478: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3478: Error: illegal operands `auipc a1,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3483: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3483: Error: illegal operands `auipc a2,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3488: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3488: Error: illegal operands `auipc a3,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3649: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3649: Error: illegal operands `auipc a0,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3654: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3654: Error: illegal operands `auipc a2,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3659: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3659: Error: illegal operands `auipc a3,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3774: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3774: Error: illegal operands `auipc a0,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3779: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3779: Error: illegal operands `auipc a1,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3784: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3784: Error: illegal operands `auipc a2,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3920: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:3920: Error: illegal operands `auipc a0,%got_pcrel_hi(__per_cpu_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4159: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4159: Error: illegal operands `auipc a0,%got_pcrel_hi(__per_cpu_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4283: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4283: Error: illegal operands `auipc a0,%got_pcrel_hi(__per_cpu_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4480: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4480: Error: illegal operands `auipc a1,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4485: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4485: Error: illegal operands `auipc a2,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4490: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4490: Error: illegal operands `auipc a3,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4647: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4647: Error: illegal operands `auipc a0,%got_pcrel_hi(__per_cpu_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4720: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4720: Error: illegal operands `auipc a0,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4726: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4726: Error: illegal operands `auipc a1,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4732: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4732: Error: illegal operands `auipc a2,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4787: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4787: Error: illegal operands `auipc a1,%got_pcrel_hi(__per_cpu_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4802: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4802: Error: illegal operands `auipc a1,%got_pcrel_hi(__cpu_online_mask)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4808: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4808: Error: illegal operands `auipc a1,%got_pcrel_hi(nr_cpu_ids)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4831: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4831: Error: illegal operands `auipc a1,%got_pcrel_hi(__cpu_online_mask)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4838: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4838: Error: illegal operands `auipc a1,%got_pcrel_hi(nr_cpu_ids)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4848: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4848: Error: illegal operands `auipc a2,%got_pcrel_hi(__per_cpu_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4892: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4892: Error: illegal operands `auipc a0,%got_pcrel_hi(mem_map)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4898: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4898: Error: illegal operands `auipc a1,%got_pcrel_hi(va_pa_offset)'
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4904: Error: bad expression
BUILDSTDERR: /tmp/z3fold-cd7cd6.s:4904: Error: illegal operands `auipc a2,%got_pcrel_hi(pfn_base)'
BUILDSTDERR: clang-10: error: assembler command failed with exit code 1 (use -v to see invocation)
BUILDSTDERR: make[1]: *** [scripts/Makefile.build:265: mm/z3fold.o] Error 1
BUILDSTDERR: make[1]: *** Waiting for unfinished jobs....
```
```

  rm -f arch/riscv/mm/built-in.a; llvm-ar cDPrST arch/riscv/mm/built-in.a arch/riscv/mm/init.o arch/riscv/mm/extable.o arch/riscv/mm/fault.o arch/riscv/mm/cacheflush.o arch/riscv/mm/context.o arch/riscv/mm/tlbflush.o
  ld.lld --icf=none --no-gc-sections -melf64lriscv  -r -R arch/riscv/kernel/vdso/vdso-dummy.o -o arch/riscv/kernel/vdso/vdso-syms.o
BUILDSTDERR: ld.lld: error: no input files
BUILDSTDERR: make[3]: *** [arch/riscv/kernel/vdso/Makefile:46: arch/riscv/kernel/vdso/vdso-syms.o] Error 1
BUILDSTDERR: make[2]: *** [scripts/Makefile.build:503: arch/riscv/kernel/vdso] Error 2
BUILDSTDERR: make[2]: *** Waiting for unfinished jobs....
```

**Comment by nathanchance** [comment] 2020-02-21 14:13
Dupe of #865.

**Closed by nathanchance** 2020-02-21 14:13 UTC
Labels: duplicate
