### ISSUE TITLE
clang-13 arm allmodconfig compiler crash: llvm::DataLayout::getStructLayout(llvm::StructType*) const

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1850] opened 2023-05-24 17:04 UTC
https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/5063397137/jobs/9091244904#step:5:262

**Comment by nathanchance** [comment] 2023-05-24 17:06
Was fine with 5.10.179: https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/4998028352/jobs/8953835502

I will bisect to see what change inadvertently introduced this to see if we can workaround it.

**Comment by nathanchance** [comment] 2023-05-24 22:17
Hmmm, I cannot reproduce this locally, even with TuxMake:

```
$ git show -s --format='%h ("%s")'
4c893ff55907 ("Linux 5.10.180")

$ tuxmake -a arm -k allmodconfig -r podman -t clang-13 LLVM=1 LLVM_IAS=0 default
...
I: config: PASS in 0:00:02.371960
I: default: PASS in 0:04:40.008649
I: build output in ...
```

The compiler version is obviously the same as CI:

```
$ podman run --rm -ti docker.io/tuxmake/arm_clang-13 clang --version
Debian clang version 13.0.1-++20220126092033+75e33f71c2da-1~exp1~20220126212112.63
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
```

Perhaps this was a spurious host system issue?

**Comment by nathanchance** [comment] 2023-07-25 18:26
We don't appear to have seen this since, so closing up for now.

**Closed as not planned by nathanchance** 2023-07-25 18:26 UTC
Labels: [BUG] llvm, [ARCH] arm32, unreproducible, Compiler crash, [CONFIG] allmodconfig
