### ISSUE TITLE
clang-12: ld.lld: error: Unexpected GOT entries detected!

### ISSUE THREAD

**Issue by AndyLavr** [ClangBuiltLinux/linux#1214] opened 2020-12-11 10:39 UTC
The latest Clang-12 (LTO + LLVM=1 LLVM_IAS=1) fails to build linux-next 20201210 64-bit x86 kernels:

```
Ubuntu clang version 12.0.0-++20201210105312+092e8a7ea36-1~exp1~20201210215955.85
```

```
  CC [M]  drivers/iio/light/veml6030.o
  CC [M]  drivers/iio/light/veml6070.o
  CC [M]  drivers/iio/light/vl6180.o
  CC [M]  drivers/iio/light/zopt2201.o
  GEN     .version
  CHK     include/generated/compile.h
  GEN     .tmp_initcalls.lds
  GEN     .tmp_symversions.lds
  LTO     vmlinux.o
  OBJTOOL vmlinux.o
  MODPOST vmlinux.symvers
  MODINFO modules.builtin.modinfo
  GEN     modules.builtin
  LD      .tmp_vmlinux.kallsyms1
ld.lld: error: Unexpected GOT entries detected!
ld.lld: error: Unexpected GOT entries detected!
ld.lld: error: Unexpected GOT entries detected!
```

This was no problem with a slightly older Clang-12 snapshot:

```
Ubuntu clang version 12.0.0-++20201205113630+e97dd119776-1~exp1~20201205104346.74
```

```
  CC [M]  drivers/iio/pressure/st_pressure_i2c.o
  CC [M]  drivers/iio/pressure/st_pressure_spi.o
  AR [M]  drivers/iio/pressure/bmp280.o
  AR [M]  drivers/iio/pressure/st_pressure.o
  AR      drivers/built-in.a
  GEN     .version
  CHK     include/generated/compile.h
  GEN     .tmp_initcalls.lds
  GEN     .tmp_symversions.lds
  LTO     vmlinux.o
  OBJTOOL vmlinux.o
  MODPOST vmlinux.symvers
  MODINFO modules.builtin.modinfo
  GEN     modules.builtin
  LD      .tmp_vmlinux.kallsyms1
  KSYMS   .tmp_vmlinux.kallsyms1.S
  AS      .tmp_vmlinux.kallsyms1.S
  LD      .tmp_vmlinux.kallsyms2
  KSYMS   .tmp_vmlinux.kallsyms2.S
  AS      .tmp_vmlinux.kallsyms2.S
  LD      vmlinux
  SORTTAB vmlinux
  SYSMAP  System.map
  CC      arch/x86/boot/a20.o
  AS      arch/x86/boot/bioscall.o
  CC      arch/x86/boot/cmdline.o
  AS      arch/x86/boot/copy.o
  HOSTCC  arch/x86/boot/mkcpustr
  CC      arch/x86/boot/cpuflags.o
  CC      arch/x86/boot/cpucheck.o
  CC      arch/x86/boot/early_serial_console.o
  CC      arch/x86/boot/edd.o
  CC      arch/x86/boot/main.o
  CC      arch/x86/boot/memory.o
  CC      arch/x86/boot/pm.o
  AS      arch/x86/boot/pmjump.o
  CC      arch/x86/boot/printf.o
  CC      arch/x86/boot/regs.o
  CC      arch/x86/boot/string.o
  CC      arch/x86/boot/tty.o
  CC      arch/x86/boot/video.o
  CC      arch/x86/boot/video-mode.o
  LDS     arch/x86/boot/compressed/vmlinux.lds
  CC      arch/x86/boot/version.o
  AS      arch/x86/boot/compressed/kernel_info.o
```

The problem is present in all Clang-12 builds after 20201205.

**Please view:**

https://elixir.bootlin.com/linux/v5.10-rc7/source/arch/x86/kernel/vmlinux.lds.S#L439

https://elixir.bootlin.com/linux/v5.10-rc7/source/arch/x86/boot/compressed/vmlinux.lds.S#L101

**Comment by nathanchance** [comment] 2020-12-12 06:34
Do you have a `.config` that I can use to try and trigger this? `defconfig` + `CONFIG_LTO_CLANG_THIN=y` alone does not appear to work.

**Comment by AndyLavr** [comment] 2020-12-12 08:10
> Do you have a `.config` that I can use to try and trigger this? `defconfig` + `CONFIG_LTO_CLANG_THIN=y` alone does not appear to work.

Check your mail.

**Comment by nathanchance** [comment] 2020-12-12 19:49
I still cannot reproduce this with the configuration file that you sent me on either `next-20201210` or `next-20201211` with [Sami's `clang-lto` branch](https://github.com/samitolvanen/linux/tree/clang-lto) merged in. I have tried using [`tuxmake`](https://gitlab.com/Linaro/tuxmake) to get closer to that environment and building my own version of clang at the same SHA as the problematic Ubuntu version and both build fine for me. What kernel source are you using?

**Comment by AndyLavr** [comment] 2020-12-13 05:36
1. [clang-lto-cfi branch](https://github.com/samitolvanen/linux/commits/clang-cfi)

2. [linux-next 20201211 branch](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/log/)

3. Ubuntu  kernel build environment.
```
LLVM=1 LLVM_IAS=1 AUTOBUILD=1 fakeroot debian/rules binary-headers binary-arch-headers binary-generic skipdbg=true skipabi=false
```

**Closed** 2020-12-14 05:41 UTC
Labels: [ARCH] x86_64, [BUG] Untriaged, [FEATURE] LTO
