### ISSUE TITLE
arm64 allyesconfig mainline broken

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#599] opened 2019-07-11 17:50 UTC
Reported-by: ci_notify@linaro.org

I can confirm:
```
WARNING: EXPORT symbol "kernel_neon_begin" [vmlinux] version generation failed, symbol will not be versioned.
  MODINFO modules.builtin.modinfo
aarch64-linux-gnu-ld: arch/arm64/kernel/fpsimd.o: relocation R_AARCH64_ABS32 against `__crc_kernel_neon_begin' can not be used when making a shared object
arch/arm64/kernel/fpsimd.o:(.data+0x8): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(.data+0x20): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(.data+0x40): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(".discard.addressable"+0x0): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(".discard.addressable"+0x8): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(".discard.addressable"+0x10): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(".discard.addressable"+0x18): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x0): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x8): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x10): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x18): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x20): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x28): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x30): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x38): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x40): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x48): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x50): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x58): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x60): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x68): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x70): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x78): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x80): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x88): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x90): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x98): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0xa0): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0xa8): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0xb0): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0xb8): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0xc0): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0xc8): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0xd0): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0xd8): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0xe0): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0xe8): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0xf0): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0xf8): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x100): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x108): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x110): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x118): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x120): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x128): dangerous relocation: unsupported relocation
arch/arm64/kernel/fpsimd.o:(__mcount_loc+0x130): dangerous relocation: unsupported relocation
Makefile:1052: recipe for target 'vmlinux' failed
make: *** [vmlinux] Error 1
```

**Comment by nathanchance** [comment] 2019-07-11 17:54
Duplicate of #536. I'll reopen that one so it's on everyone's radar.

**Closed by nathanchance** 2019-07-11 17:54 UTC
Labels: [ARCH] arm64, [BUG] linux
