### ISSUE TITLE
drivers/firmware/efi/libstub/Makefile overwrites KBUILD_CFLAGS for x86[_64]

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#112] opened 2018-09-18 18:15 UTC
These repeat a lot:
```
./arch/x86/include/asm/processor.h:555:17: warning: taking address of packed member 'sp0' of class or structure 'x86_hw_tss' may result in
      an unaligned pointer value [-Waddress-of-packed-member]
        this_cpu_write(cpu_tss_rw.x86_tss.sp0, sp0);
                       ^~~~~~~~~~~~~~~~~~~~~~
./include/linux/percpu-defs.h:510:68: note: expanded from macro 'this_cpu_write'
#define this_cpu_write(pcp, val)        __pcpu_size_call(this_cpu_write_, pcp, val)
                                                                          ^~~
./include/linux/percpu-defs.h:377:22: note: expanded from macro '__pcpu_size_call'
        __verify_pcpu_ptr(&(variable));                                 \
                            ^~~~~~~~
./include/linux/percpu-defs.h:221:47: note: expanded from macro '__verify_pcpu_ptr'
        const void __percpu *__vpp_verify = (typeof((ptr) + 0))NULL;    \
                                                     ^~~

./arch/x86/include/asm/processor.h:572:30: warning: taking address of packed member 'sp1' of class or structure 'x86_hw_tss' may result in
      an unaligned pointer value [-Waddress-of-packed-member]
        return this_cpu_read_stable(cpu_current_top_of_stack);
                                    ^~~~~~~~~~~~~~~~~~~~~~~~
./arch/x86/include/asm/processor.h:379:34: note: expanded from macro 'cpu_current_top_of_stack'
#define cpu_current_top_of_stack cpu_tss_rw.x86_tss.sp1
                                 ^~~~~~~~~~~~~~~~~~~~~~
./arch/x86/include/asm/percpu.h:392:59: note: expanded from macro 'this_cpu_read_stable'
#define this_cpu_read_stable(var)       percpu_stable_op("mov", var)
                                                                ^~~
./arch/x86/include/asm/percpu.h:219:16: note: expanded from macro 'percpu_stable_op'
                    : "p" (&(var)));                    \
                             ^~~
```

**Comment by tpimh** [comment] 2018-09-19 13:33
```
In file included from drivers/firmware/efi/libstub/gop.c:10:
In file included from ./include/linux/efi.h:17:
In file included from ./include/linux/time.h:6:
In file included from ./include/linux/seqlock.h:36:
In file included from ./include/linux/spinlock.h:51:
In file included from ./include/linux/preempt.h:81:
In file included from ./arch/x86/include/asm/preempt.h:7:
In file included from ./include/linux/thread_info.h:38:
In file included from ./arch/x86/include/asm/thread_info.h:53:
In file included from ./arch/x86/include/asm/cpufeature.h:5:
```

**Comment by nathanchance** [comment] 2018-09-25 20:02
Should we just apply commits 6c3b56b19730 ("x86/boot: Disable Clang warnings about GNU extensions") and bfb38988c51e ("kbuild: clang: Disable 'address-of-packed-member' warning") to that Makefile? I know rewriting the Makefile was suggested but it seems like steamrolling the CFLAGS is intentional for x86{,_64}.

**Comment by nickdesaulniers** [comment] 2018-09-25 20:39
If it was intentional, I'd be curious as to know _why_.

**Comment by nathanchance** [comment] 2018-09-25 20:42
From the top of the Makefile:

```make
# The stub may be linked into the kernel proper or into a separate boot binary,
# but in either case, it executes before the kernel does (with MMU disabled) so
# things like ftrace and stack-protector are likely to cause trouble if left
# enabled, even if doing so doesn't break the build.
#
cflags-$(CONFIG_X86_32)         := -march=i386
cflags-$(CONFIG_X86_64)         := -mcmodel=small
cflags-$(CONFIG_X86)            += -m$(BITS) -D__KERNEL__ -O2 \
                                   -fPIC -fno-strict-aliasing -mno-red-zone \
                                   -mno-mmx -mno-sse -fshort-wchar
```

I guess it could be converted to be like arm/arm64:

```make
# arm64 uses the full KBUILD_CFLAGS so it's necessary to explicitly
# disable the s.tackleak plugin
cflags-$(CONFIG_ARM64)          := $(subst -pg,,$(KBUILD_CFLAGS)) -fpie \
                                   $(DISABLE_STACKLEAK_PLUGIN)
cflags-$(CONFIG_ARM)            := $(subst -pg,,$(KBUILD_CFLAGS)) \
                                   -fno-builtin -fpic -mno-single-pic-base
```

Not sure though, I'll dig through git history here shortly.

**Comment by nathanchance** [comment] 2018-09-26 23:30
That steamroll has been present since the introduction of the file in commit f4f75ad5741f ("efi: efistub: Convert into static library"). Second paragraph I'm sure it relevant.

**Comment by nathanchance** [comment] 2018-10-13 01:06
Patch sent to mailing list for further discussion: https://lore.kernel.org/lkml/20181013010348.6740-1-natechancellor@gmail.com/

**Comment by dileks** [comment] 2018-10-23 07:43
OK. This is indeed a duplicate of #234. Can you please do a v2 with credits and TO/CC to maintainers (check with scripts/get_maintainer.pl)? Feel free to add my Reviewed-by/Tested-by. Thanks.

**Comment by nathanchance** [comment] 2018-10-23 16:57
@dileks thanks for testing! I did send it to the proper mailing lists and maintainers and since it hasn't been more than two weeks since I sent it out, I don't think a resend/v2 is necessary just yet (especially with the merge window happening right now).

Would you like me to send a email with those tags and you CC'd to the current revision then I'll carry those in any further revisions I need to do?

**Comment by dileks** [comment] 2018-10-23 17:28
OK. Ping them again?

Sedat

**Comment by nathanchance** [comment] 2018-11-05 16:54
Patch accepted: https://git.kernel.org/pub/scm/linux/kernel/git/efi/efi.git/commit/?id=b01b9dfaee3c47cbfae0842a591b504f3cecfbdb

**Comment by nathanchance** [comment] 2018-12-27 15:32
Merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=3db5e0ba8b8f4aee631d7ee04b7a11c56cfdc213

**Closed by nathanchance** 2018-12-27 15:32 UTC
Labels: [ARCH] x86_64, [BUG] linux, [PATCH] Accepted
