### ISSUE TITLE
changed section flags for .note.Linux in arch/x86/entry/vdso/vdso-note.S

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#913] opened 2020-03-02 19:57 UTC
```
arch/x86/entry/vdso/vdso-note.S:15:1: error: changed section flags for .note.Linux, expected: 0x2
.pushsection .note.Linux, "",@note ; .balign 4 ; .long 2f - 1f ; .long 4484f - 3f ; .long 0x100 ; 1:.asciz "Linux" ; 2:.balign 4 ; 3: .asciz "" ; 4484:.balign 4 ; .popsection ;
^
```

**Comment by nickdesaulniers** [comment] 2020-03-02 20:41
That's not a great error message, llvm should print the flag rather than the hex constant.  The `""` likely needs a letter or two in there for the section flags.

**Comment by ihalip** [comment] 2020-03-03 06:12
It seems that GNU as allows a second `.pushsection` with empty flags. Reproducer:

```
$ cat vdso-note.s
.pushsection .note.Linux, "a",@note ;
 .long 0x1234 ;
.popsection ;

.pushsection .note.Linux, "",@note ;
 .long 0x5678 ;
.popsection ;

$ as -o vdso-note.o vdso-note.s && objdump -D vdso-note.o
[...]
0000000000000000 <.note.Linux>:
   0:	34 12                	xor    $0x12,%al
   2:	00 00                	add    %al,(%rax)
   4:	78 56                	js     0x5c
	...

$ clang-11 -cc1as -triple x86_64-pc-linux-gnu -o vdso-note.o vdso-note.s
vdso-note.s:5:1: error: changed section flags for .note.Linux, expected: 0x2
.pushsection .note.Linux, "",@note ;
```

Looks like the fix should be easy enough on the LLVM side - just reuse the flags of the existing section. I'll try to fix this and send a review.

**Comment by MaskRay** [comment] 2020-03-03 20:39
See https://lists.llvm.org/pipermail/llvm-dev/2020-February/139390.html

https://reviews.llvm.org/D73999 added the error. I agree that the error message is not great but there is some technical difficulty there. I have noted we should improve it.

```
.section .foo,"ax",@progbits; .byte 1
.section .foo,"",@progbits; .byte 2
.section .foo,"a",@progbits; .byte 3
```

So GNU as does not error for the empty flags case.

```
a.s:3: Error: changed section attributes for .foo
```

Can you send an email to binutils@sourceware.org asking whether this is intended case?
Cite https://sourceware.org/ml/binutils/2020-02/msg00129.html for reference.

**Comment by nickdesaulniers** [comment] 2020-03-03 21:37
I agree that we should error; we can likely fix this in the Linux kernel source code.

**Comment by ihalip** [comment] 2020-03-04 10:28
The `ELFNOTE` macros are used with the "a" flags throughout the kernel. But I don't think changing the macro to make this hardcoded or implicit is a good idea.
On the other hand, the BUILD_SALT macro is there to add a piece of data to the binary ([to tie a vDSO build to the kernel build](https://github.com/ClangBuiltLinux/linux/blob/c60c04021353c55b133519804734415f647f08bd/Documentation/kbuild/reproducible-builds.rst#debug-info-conflicts)) and doesn't seem needed at runtime, so changing it to use the same flag also doesn't sit well with me.

What about moving the build salt into it's own section? Such a change would look like this:
```
diff --git a/include/linux/build-salt.h b/include/linux/build-salt.h
index bb007bd05e7a..95292c7b7e91 100644
--- a/include/linux/build-salt.h
+++ b/include/linux/build-salt.h
@@ -8,12 +8,12 @@
 #ifdef __ASSEMBLER__
 
 #define BUILD_SALT \
-       ELFNOTE(Linux, LINUX_ELFNOTE_BUILD_SALT, .asciz CONFIG_BUILD_SALT)
+       ELFNOTE(buildsalt, LINUX_ELFNOTE_BUILD_SALT, .asciz CONFIG_BUILD_SALT)
 
 #else
 
 #define BUILD_SALT \
-       ELFNOTE32("Linux", LINUX_ELFNOTE_BUILD_SALT, CONFIG_BUILD_SALT)
+       ELFNOTE32("buildsalt", LINUX_ELFNOTE_BUILD_SALT, CONFIG_BUILD_SALT)
 
 #endif
 
```

cc @masahir0y

**Comment by nickdesaulniers** [comment] 2020-03-04 17:11
If I preprocess the assembly, it looks like:
```asm
.pushsection .note.Linux, "a",@note ; .balign 4 ; .long 2f - 1f ; .long 4484f - 3f ; .long 0 ; 1:.asciz "Linux" ; 2:.balign 4 ; 3:
.long 329216
4484:.balign 4 ; .popsection ;
.pushsection .note.Linux, "",@note ; .balign 4 ; .long 2f - 1f ; .long 4484f - 3f ; .long 0x100 ; 1:.asciz "Linux" ; 2:.balign 4 ; 3: .asciz "" ; 4484:.balign 4 ; .popsection ;
```

So we have:
```asm
.pushsection .note.Linux, "a",@note ;
.pushsection .note.Linux, "",@note ;
```

**Comment by nickdesaulniers** [comment] 2020-03-04 17:17
Ah, so it looks like all instances of `ELFNOTE_START` in the kernel set `"a"`, except for `ELFNOTE`.  I think this would be the right fix:

```diff
diff --git a/include/linux/elfnote.h b/include/linux/elfnote.h
index f236f5b931b2..7fdd7f355b52 100644
--- a/include/linux/elfnote.h
+++ b/include/linux/elfnote.h
@@ -54,7 +54,7 @@
 .popsection                            ;
 
 #define ELFNOTE(name, type, desc)              \
-       ELFNOTE_START(name, type, "")           \
+       ELFNOTE_START(name, type, "a")          \
                desc                    ;       \
        ELFNOTE_END
```

**Comment by nickdesaulniers** [comment] 2020-03-04 17:21
(or better yet, I'd refactor the flag to be implicitly `"a"`, and update all uses so they were no longer able to pass potentially different flags).

**Comment by ihalip** [comment] 2020-03-05 10:08
>(or better yet, I'd refactor the flag to be implicitly "a", and update all uses so they were no longer able to pass potentially different flags).

Agreed. It actually doesn't seem to matter what flags are set for `.note.*` sections, since the linker merges them all into a PT_NOTE section which is marked as SHF_ALLOC only. Let me spin up a patch.

**Comment by masahir0y** [comment] 2020-03-05 13:09
>On the other hand, the BUILD_SALT macro is there to add a piece of data to the binary (to tie a vDSO build to the kernel build) and doesn't seem needed at runtime, so changing it to use the same flag also doesn't sit well with me.

Right, we do not need BUILD_SALT at runtime, but
linker scripts puts (.note.*) into the same section.
So, ".note.buildsalt" would go to the same section after all.

The buildsalt is only a few bytes data, so this is not a big deal.


> (or better yet, I'd refactor the flag to be implicitly "a", and update all uses so they were no longer able to pass potentially different flags).

I agree too.

**Comment by ihalip** [comment] 2020-03-05 17:01
This turned into a series because I found another opportunity to do a minor change. See the last 2 commits: https://github.com/ihalip/linux/commits/elfnote
If you think these are OK, I can send them to LKML.

**Comment by nickdesaulniers** [comment] 2020-03-05 22:12
First one LGTM, left [comments](https://github.com/ihalip/linux/commit/c58ec05c078a0349aaf6cb677414d5c4b735ba1d) on the second. Thank you for the fixes!

**Comment by masahir0y** [comment] 2020-03-06 03:01
> This turned into a series because I found another opportunity to do a minor change. See the last 2 commits: https://github.com/ihalip/linux/commits/elfnote
If you think these are OK, I can send them to LKML.

LGTM.
If there is no objection, please send them to ML.
Thanks.

**Comment by nickdesaulniers** [comment] 2020-03-25 23:15
I sent https://lore.kernel.org/lkml/20200325231250.99205-1-ndesaulniers@google.com/T/#u to the list.  I'd like to rebase @ihalip [changes](https://github.com/ihalip/linux/commits/elfnote) and get those submitted, too, though treewide changes sometimes take longer to land.

**Comment by nathanchance** [comment] 2020-04-18 21:54
Andrew Morton picked this up: https://lore.kernel.org/r/20200418201955.wltNE-2kB%25akpm@linux-foundation.org/

Should be here eventually: http://ozlabs.org/~akpm/mmotm/broken-out/elfnote-mark-all-note-sections-shf_alloc.patch

**Comment by MaskRay** [comment] 2020-04-19 00:42
> Andrew Morton picked this up: https://lore.kernel.org/r/20200418201955.wltNE-2kB%25akpm@linux-foundation.org/
> 
> Should be here eventually: http://ozlabs.org/~akpm/mmotm/broken-out/elfnote-mark-all-note-sections-shf_alloc.patch

Yeah.. I also received an email notification about this
 http://ozlabs.org/~akpm/mmotm/broken-out/elfnote-mark-all-note-sections-shf_alloc.patch is currently 404...

Just out of curiosity, why isn't the patch in an x86 tree?

`./scripts/get_maintainer.pl arch/x86/entry/vdso/vdso-note.S` => `x86@kernel.org (maintainer:X86 ARCHITECTURE (32-BIT AND 64-BIT))`

**Comment by nathanchance** [comment] 2020-04-19 00:56
> > Andrew Morton picked this up: https://lore.kernel.org/r/20200418201955.wltNE-2kB%25akpm@linux-foundation.org/
> > Should be here eventually: http://ozlabs.org/~akpm/mmotm/broken-out/elfnote-mark-all-note-sections-shf_alloc.patch
> 
> Yeah.. I also received an email notification about this
> http://ozlabs.org/~akpm/mmotm/broken-out/elfnote-mark-all-note-sections-shf_alloc.patch is currently 404...

mmotm (-mm of the moment) is uploaded at random so it might take a bit to show up there. Andrew Morton does not use `git`, he uses `quilt` so getting the patches out is not as simple as typing `git push`.

> Just out of curiosity, why isn't the patch in an x86 tree?
> 
> `./scripts/get_maintainer.pl arch/x86/entry/vdso/vdso-note.S` => `x86@kernel.org (maintainer:X86 ARCHITECTURE (32-BIT AND 64-BIT))`

The actual file modified is `include/linux/elfnote.h` which does not appear to have a formal maintainer:

```
$ ./scripts/get_maintainer.pl include/linux/elfnote.h
Vincenzo Frascino <vincenzo.frascino@arm.com> (commit_signer:1/1=100%,authored:1/1=100%,added_lines:1/1=100%,removed_lines:1/1=100%)
Thomas Gleixner <tglx@linutronix.de> (commit_signer:1/1=100%)
linux-kernel@vger.kernel.org (open list)
```

As a result, Andrew picks it up, since he's the catch all for files that do not have an entry in MAINTAINERS. Happens fairly often with header files.

**Comment by MaskRay** [comment] 2020-05-17 18:18
Is the `include/linux/elfnote.h` change still not picked? :)

**Comment by nathanchance** [comment] 2020-05-17 18:44
It is in -next, won’t be in mainline until the next merge window:

https://git.kernel.org/next/linux-next/c/0a1c42727be5d91b13699363701164c4050edc75

**Comment by nathanchance** [comment] 2020-06-05 03:59
https://git.kernel.org/linus/51da9dfb7f20911ae4e79e9b412a9c2d4c373d4b

**Closed by nathanchance** 2020-06-05 03:59 UTC
Labels: [ARCH] arm64, [ARCH] x86, [ARCH] x86_64, [BUG] linux, [PATCH] Accepted, [TOOL] integrated-as
