### ISSUE TITLE
-Wenum-conversion in drivers/infiniband/hw/cxgb4/cq.c

### ISSUE THREAD

**Issue by shenki** [ClangBuiltLinux/linux#87] opened 2018-09-17 08:26 UTC
```
drivers/infiniband/hw/cxgb4/cq.c:164:48: warning: implicit conversion from enumeration type
      'enum t4_bar2_qtype' to different enumeration type 'enum cxgb4_bar2_qtype' [-Wenum-conversion]
        cq->bar2_va = c4iw_bar2_addrs(rdev, cq->cqid, T4_BAR2_QTYPE_INGRESS,
                      ~~~~~~~~~~~~~~~                 ^~~~~~~~~~~~~~~~~~~~~
  CC      drivers/input/mouse/cypress_ps2.o
drivers/infiniband/hw/cxgb4/qp.c:282:53: warning: implicit conversion from enumeration type
      'enum t4_bar2_qtype' to different enumeration type 'enum cxgb4_bar2_qtype' [-Wenum-conversion]
        wq->sq.bar2_va = c4iw_bar2_addrs(rdev, wq->sq.qid, T4_BAR2_QTYPE_EGRESS,
                         ~~~~~~~~~~~~~~~                   ^~~~~~~~~~~~~~~~~~~~
drivers/infiniband/hw/cxgb4/qp.c:287:8: warning: implicit conversion from enumeration type
      'enum t4_bar2_qtype' to different enumeration type 'enum cxgb4_bar2_qtype' [-Wenum-conversion]
                                                 T4_BAR2_QTYPE_EGRESS,
                                                 ^~~~~~~~~~~~~~~~~~~~
drivers/infiniband/hw/cxgb4/qp.c:2575:47: warning: implicit conversion from enumeration type
      'enum t4_bar2_qtype' to different enumeration type 'enum cxgb4_bar2_qtype' [-Wenum-conversion]
        wq->bar2_va = c4iw_bar2_addrs(rdev, wq->qid, T4_BAR2_QTYPE_EGRESS,
                      ~~~~~~~~~~~~~~~                ^~~~~~~~~~~~~~~~~~~~
```

**Comment by tpimh** [comment] 2018-09-18 12:31
Closed as duplicate of #63

**Closed by tpimh** 2018-09-18 12:31 UTC
Labels: [BUG] linux, good first issue, help wanted, low priority
