### ISSUE TITLE
Several instances of -Wvoid-ptr-dereference

### ISSUE THREAD

**Issue by ms178** [ClangBuiltLinux/linux#1720] opened 2022-09-25 19:51 UTC
With clang version 16.0.0 (39e6077d97238ec13c9ed1b9dbae1e6408e5aba3) I see super noisy output when compiling a 5.19.11 Kernel. I've attached a snippet, but these noisy warnings span over the whole build process.

[message (1).txt](https://github.com/ClangBuiltLinux/linux/files/9641653/message.1.txt)

More details on the config and flags used are available in my repo: https://github.com/ms178/archpkgbuilds/tree/main/packages/linux-cachyos-bore

**Comment by nathanchance** [comment] 2022-09-25 21:32
They come from https://github.com/llvm/llvm-project/commit/e07ead85a368173a56e96a21d6841aa497ad80f8, which was merged yesterday so I have not had a chance to sit down and look at whether or not the warning is accurate or should be potentially adjusted.

**Comment by nathanchance** [comment] 2022-09-26 00:26
So far, I really only see two places where the macro actually triggers: the `__is_constexpr` macro and the checks in the `container_of` macro. Sample warnings + the offending C code:

```
In file included from scripts/mod/devicetable-offsets.c:3:
In file included from ./include/linux/mod_devicetable.h:13:
In file included from ./include/linux/uuid.h:12:
In file included from ./include/linux/string.h:253:
./include/linux/fortify-string.h:159:10: warning: ISO C does not allow indirection on operand of type 'void *' [-Wvoid-ptr-dereference]
        q_len = strlen(q);
                ^~~~~~~~~
./include/linux/fortify-string.h:131:24: note: expanded from macro 'strlen'
        __builtin_choose_expr(__is_constexpr(__builtin_strlen(p)),      \
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/const.h:12:25: note: expanded from macro '__is_constexpr'
        (sizeof(int) == sizeof(*(8 ? ((void *)((long)(x) * 0l)) : (int *)8)))
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In file included from arch/x86/kernel/asm-offsets.c:9:
In file included from ./include/linux/crypto.h:20:
In file included from ./include/linux/slab.h:15:
In file included from ./include/linux/gfp.h:7:
In file included from ./include/linux/mmzone.h:8:
In file included from ./include/linux/spinlock.h:55:
In file included from ./include/linux/preempt.h:78:
In file included from ./arch/x86/include/asm/preempt.h:7:
In file included from ./include/linux/thread_info.h:60:
In file included from ./arch/x86/include/asm/thread_info.h:53:
In file included from ./arch/x86/include/asm/cpufeature.h:5:
In file included from ./arch/x86/include/asm/processor.h:22:
In file included from ./arch/x86/include/asm/msr.h:11:
In file included from ./arch/x86/include/asm/cpumask.h:5:
In file included from ./include/linux/cpumask.h:12:
In file included from ./include/linux/bitmap.h:9:
./include/linux/find.h:40:17: warning: ISO C does not allow indirection on operand of type 'void *' [-Wvoid-ptr-dereference]
                val = *addr & GENMASK(size - 1, offset);
                              ^~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/bits.h:38:3: note: expanded from macro 'GENMASK'
        (GENMASK_INPUT_CHECK(h, l) + __GENMASK(h, l))
         ^~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/bits.h:25:3: note: expanded from macro 'GENMASK_INPUT_CHECK'
                __is_constexpr((l) > (h)), (l) > (h), 0)))
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/const.h:12:25: note: expanded from macro '__is_constexpr'
        (sizeof(int) == sizeof(*(8 ? ((void *)((long)(x) * 0l)) : (int *)8)))
                               ^
./include/linux/build_bug.h:16:62: note: expanded from macro 'BUILD_BUG_ON_ZERO'
#define BUILD_BUG_ON_ZERO(e) ((int)(sizeof(struct { int:(-!!(e)); })))
                                                             ^
```

```c
/*
 * This returns a constant expression while determining if an argument is
 * a constant expression, most importantly without evaluating the argument.
 * Glory to Martin Uecker <Martin.Uecker@med.uni-goettingen.de>
 */
#define __is_constexpr(x) \
	(sizeof(int) == sizeof(*(8 ? ((void *)((long)(x) * 0l)) : (int *)8)))
```

It seems like they were aware this may cause warnings? https://lore.kernel.org/CA+55aFyRgq7hbmxK9471xY-eja4X=gKHSjF4Q+a0FJjxVB1TYQ@mail.gmail.com/

```
In file included from sound/soc/sof/core.c:14:
In file included from ./include/sound/sof.h:14:
./include/linux/pci.h:600:9: warning: ISO C does not allow indirection on operand of type 'void *' [-Wvoid-ptr-dereference]
        return container_of(priv, struct pci_host_bridge, private);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/container_of.h:20:21: note: expanded from macro 'container_of'
                      __same_type(*(ptr), void),                        \
                      ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/compiler_types.h:295:63: note: expanded from macro '__same_type'
#define __same_type(a, b) __builtin_types_compatible_p(typeof(a), typeof(b))
                                                              ^
./include/linux/build_bug.h:77:50: note: expanded from macro 'static_assert'
#define static_assert(expr, ...) __static_assert(expr, ##__VA_ARGS__, #expr)
                                 ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/build_bug.h:78:56: note: expanded from macro '__static_assert'
#define __static_assert(expr, msg, ...) _Static_assert(expr, msg)
                                                       ^~~~
```

```c
/**
 * container_of - cast a member of a structure out to the containing structure
 * @ptr:	the pointer to the member.
 * @type:	the type of the container struct this is embedded in.
 * @member:	the name of the member within the struct.
 *
 */
#define container_of(ptr, type, member) ({				\
	void *__mptr = (void *)(ptr);					\
	static_assert(__same_type(*(ptr), ((type *)0)->member) ||	\
		      __same_type(*(ptr), void),			\
		      "pointer type mismatch in container_of()");	\
	((type *)(__mptr - offsetof(type, member))); })
```
```c
#define __same_type(a, b) __builtin_types_compatible_p(typeof(a), typeof(b))
```

This warning is so prevalent that it triggers 104 times in `init/main.c` alone. For what it's worth, these do not seem like actual problems because these places will be evaluated at compile time. I am not sure if the warning could account for this or not.

**Comment by ms178** [comment] 2022-09-26 06:59
I should add that the compilation itself went fine and the Kernel also booted and works fine. I saw these warnings all over the place up until the LTO stage though, it should be quite easy to reproduce.

**Comment by nickdesaulniers** [comment] 2022-09-26 07:55
Maybe let's disable the warning for now, and report them to the upstream Clang developers so that they're aware of the fallout?

**Comment by nathanchance** [comment] 2022-09-26 15:28
I have added some commentary on Phabricator: https://reviews.llvm.org/D134461#3815298

I will send a patch to disable `-Wvoid-ptr-dereference` if needed.

**Comment by nickdesaulniers** [comment] 2022-09-26 21:33
So far, I've needed:
```diff
diff --git a/arch/x86/boot/compressed/Makefile b/arch/x86/boot/compressed/Makefile
index 35ce1a64068b..07555d8e05d9 100644
--- a/arch/x86/boot/compressed/Makefile
+++ b/arch/x86/boot/compressed/Makefile
@@ -51,6 +51,7 @@ KBUILD_CFLAGS += -D__DISABLE_EXPORTS
 # Disable relocation relaxation in case the link is not PIE.
 KBUILD_CFLAGS += $(call as-option,-Wa$(comma)-mrelax-relocations=no)
 KBUILD_CFLAGS += -include $(srctree)/include/linux/hidden.h
+KBUILD_CFLAGS += $(call cc-disable-warning, void-ptr-dereference)
 
 # sev.c indirectly inludes inat-table.h which is generated during
 # compilation and stored in $(objtree). Add the directory to the includes so
diff --git a/drivers/firmware/efi/libstub/Makefile b/drivers/firmware/efi/libstub/Makefile
index 2c67f71f2375..94f286d9236d 100644
--- a/drivers/firmware/efi/libstub/Makefile
+++ b/drivers/firmware/efi/libstub/Makefile
@@ -13,6 +13,7 @@ cflags-$(CONFIG_X86)          += -m$(BITS) -D__KERNEL__ \
                                   -Wno-pointer-sign \
                                   $(call cc-disable-warning, address-of-packed-member) \
                                   $(call cc-disable-warning, gnu) \
+                                  $(call cc-disable-warning, void-ptr-dereference) \
                                   -fno-asynchronous-unwind-tables \
                                   $(CLANG_FLAGS)
 
diff --git a/scripts/Makefile.extrawarn b/scripts/Makefile.extrawarn
index 5769c1939d40..a43c82abc97c 100644
--- a/scripts/Makefile.extrawarn
+++ b/scripts/Makefile.extrawarn
@@ -64,6 +64,7 @@ KBUILD_CFLAGS += -Wno-sign-compare
 KBUILD_CFLAGS += $(call cc-disable-warning, pointer-to-enum-cast)
 KBUILD_CFLAGS += -Wno-tautological-constant-out-of-range-compare
 KBUILD_CFLAGS += $(call cc-disable-warning, unaligned-access)
+KBUILD_CFLAGS += $(call cc-disable-warning, void-ptr-dereference)
 endif
 
 endif
```

**Comment by nathanchance** [comment] 2022-09-27 15:16
https://reviews.llvm.org/D134702

**Comment by nathanchance** [comment] 2022-09-28 15:03
https://github.com/llvm/llvm-project/commit/89e56e732d5e89d8715a501158793ac305bc4b70

**Comment by nickdesaulniers** [comment] 2022-10-03 16:44
Still seeing errors in CI: https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/3172104057.  I can reproduce with ToT LLVM. Let me see if it's config/command-line-flag related.

**Comment by nickdesaulniers** [comment] 2022-10-03 17:34
I think it's because 5.15 used `-std=gnu89` rather than `-std=gnu11`.

```c
// x.c
void foo(void *vp) {
  sizeof(*vp);
  sizeof(*(vp));
  void inner(typeof(*vp));
}
```
```sh
$ clang -fsyntax-only x.c -Wno-unused-value -std=gnu11
$ clang -fsyntax-only x.c -Wno-unused-value -std=gnu89
x.c:2:10: warning: ISO C does not allow indirection on operand of type 'void *' [-Wvoid-ptr-dereference]
  sizeof(*vp);
         ^~~
x.c:3:10: warning: ISO C does not allow indirection on operand of type 'void *' [-Wvoid-ptr-dereference]
  sizeof(*(vp));
         ^~~~~
x.c:4:21: warning: ISO C does not allow indirection on operand of type 'void *' [-Wvoid-ptr-dereference]
  void inner(typeof(*vp));
                    ^~~
3 warnings generated.
```
https://reviews.llvm.org/D134702#3831208

**Comment by nickdesaulniers** [comment] 2022-10-03 17:47
https://reviews.llvm.org/D135090

**Comment by nickdesaulniers** [comment] 2022-11-07 17:34
[The latest report from kernelci](https://lore.kernel.org/llvm/6368a012.170a0220.42605.60dc@mx.google.com/T/#u) has thousands of these.

**Comment by nathanchance** [comment] 2022-11-07 17:36
They probably are using an old snapshot of `clang-16` because our CI does not see them. I'll ping them on IRC.

**Comment by nathanchance** [comment] 2022-11-16 19:45
I've been told that https://github.com/kernelci/kernelci-core/commit/8efde74a97ba85496d882ed4bad00455ccec1b2e should resolve that problem; KernelCI was using outdated images.

**Closed as completed by nathanchance** 2022-11-16 19:45 UTC
Labels: [BUG] llvm (main), [FIXED][LLVM] main, -Wvoid-ptr-dereference

**Comment by nickdesaulniers** [comment] 2022-12-05 19:56
cc @pirama-arumuga-nainar
