### ISSUE TITLE
-Wunneeded-internal-declaration in drivers/gpu/drm/i915/intel_ddi.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#208] opened 2018-10-10 04:50 UTC
```
drivers/gpu/drm/i915/intel_ddi.c:601:46: warning: variable 'icl_mg_phy_ddi_translations' is not needed and will not be emitted [-Wunneeded-internal-declaration]
static const struct icl_mg_phy_ddi_buf_trans icl_mg_phy_ddi_translations[] = {
                                             ^
```

**Comment by nathanchance** [comment] 2018-10-10 04:51
Dupe of #195.

**Closed by nathanchance** 2018-10-10 04:51 UTC
Labels: -Wunneeded-internal-declaration, [ARCH] x86_64, [BUG] linux, good first issue, low priority
