### ISSUE TITLE
ARCH=um not hermetic

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1829] opened 2023-04-07 23:31 UTC
```sh
$ ARCH=um make LLVM=1 -j128 defconfig all
...
/usr/bin/ld: init/main.o: warning: relocation in read-only section `.ref.text'
/usr/bin/ld: warning: .tmp_vmlinux.kallsyms1 has a LOAD segment with RWX permissions
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
```
why is GNU ld being invoked?

**Comment by nathanchance** [comment] 2023-04-07 23:43
Dupe of #1715, there is some information in there so closing this one.

**Closed as completed by nathanchance** 2023-04-07 23:43 UTC
Labels: duplicate
