### ISSUE TITLE
drivers/gpu/drm/amd/amdgpu/amdgpu.lto.o: warning: objtool: .text.amdgpu_amdkfd_gpuvm_alloc_memory_of_gpu: unexpected end of section

### ISSUE THREAD

**Issue by ms178** [ClangBuiltLinux/linux#1499] opened 2021-11-06 12:49 UTC
Hi, I see the mentioned new objtool error on 5.15.0 with the following config and makefile with LLVM/Clang-14 (63fff0f5bffe20fa2c84a45a41161afa0043cb34).

[config.txt](https://github.com/ClangBuiltLinux/linux/files/7490469/config.txt)
[Makefile.txt](https://github.com/ClangBuiltLinux/linux/files/7490470/Makefile.txt)

I haven't seen it yet in the issue section, hence I wanted to let you know.

**Comment by nathanchance** [comment] 2021-11-06 20:30
I think this might be a duplicate of #1480?

**Comment by ms178** [comment] 2021-11-06 22:12
Possibly, but that particular warning wasn't mentioned there and the one I found was with a Full LTO build.

**Comment by nathanchance** [comment] 2021-11-08 22:30
Reported upstream: https://reviews.llvm.org/D105169#3116810

I believe current ToT should be fine, as it has a revert of that change: https://github.com/llvm/llvm-project/commit/fd9b099906c61e46574d1ea2d99b973321fe1d21

**Comment by nickdesaulniers** [comment] 2021-11-10 19:44
If upstream reverted, should we close this as `[FIXED] llvm (main)`?

**Comment by nathanchance** [comment] 2021-11-10 19:45
Sure, we can reopen if it comes back.

**Closed as completed by nathanchance** 2021-11-10 19:45 UTC
Labels: duplicate, [ARCH] x86_64, [TOOL] objtool, [FEATURE] LTO, [BUG] llvm (main), [FIXED][LLVM] main, Reported upstream
