### ISSUE TITLE
6.4-rc4 kernel build fails with DEBUG_INFO_COMPRESSED_ZSTD=y (powerpc64, BE, clang 16.0.4)

### ISSUE THREAD

**Issue by ernsteiswuerfel** [ClangBuiltLinux/linux#1866] opened 2023-06-04 18:27 UTC
With DEBUG_INFO_COMPRESSED_ZLIB=y the kernel builds fine but when I change it to DEBUG_INFO_COMPRESSED_ZSTD=y I get
```
 # LLVM=1 LLVM_IAS=1 make
  CALL    scripts/checksyscalls.sh
  WRAP    arch/powerpc/boot/zImage.pseries
objdump: vmlinux: unable to initialize decompress status for section .debug_aranges
objdump: vmlinux: unable to initialize decompress status for section .debug_aranges
objdump: vmlinux: file format not recognized
objdump: vmlinux: unable to initialize decompress status for section .debug_aranges
objdump: vmlinux: unable to initialize decompress status for section .debug_aranges
objdump: vmlinux: file format not recognized
ld: unrecognised emulation mode: -T
Supported emulations: elf64ppc elf32ppc elf32ppclinux elf32ppcsim elf64lppc elf32lppc elf32lppclinux elf32lppcsim
make[1]: *** [arch/powerpc/boot/Makefile:402: arch/powerpc/boot/zImage.pseries] Error 1
make: *** [arch/powerpc/Makefile:240: zImage] Error 2
```
Kernel .config attached. [config_64-rc4_p9-clang.txt](https://github.com/ClangBuiltLinux/linux/files/11646367/config_64-rc4_p9-clang.txt)

**Comment by dileks** [comment] 2023-06-05 03:43
In that area I noticed in Linux `v6.4-rc5`  - cannot say if that helps you:

```
commit fadb74f9f2f609238070c7ca1b04933dc9400e4a
module/decompress: Fix error checking on zstd decompression
```

[1] https://git.kernel.org/linus/fadb74f9f2f609238070c7ca1b04933dc9400e4a

**Comment by ernsteiswuerfel** [comment] 2023-06-05 10:55
Nope, with v6.4-rc5 I still get the same error.

**Comment by nathanchance** [comment] 2023-06-05 14:51
What is the output of `objdump --version`? The PowerPC boot wrapper uses GNU tools unconditionally (which is being tracked as #1601, there is a WIP series linked in one of my comments that you can try) and I suspect your current version of binutils does not support zstd compressed sections (or there is some bug in their supportv?)

**Comment by ernsteiswuerfel** [comment] 2023-06-05 22:53
D'oh... of course I need a binutill with zstd support compiled. 🤦 And I can confirm compilation works with binutils-2.40 with zstd support enabled. 😉

**Comment by ernsteiswuerfel** [comment] 2023-06-05 23:35
I also tried your WIP patches from https://git.kernel.org/pub/scm/linux/kernel/git/nathan/linux.git/log/?h=wip/llvm-1-powerpc-boot-wrapper

I needed to alter them so they apply on 6.4-rc5. Now I am getting:
```
 # LLVM=1 LLVM_IAS=1 make
  CALL    scripts/checksyscalls.sh
  WRAP    arch/powerpc/boot/zImage.pseries
  WRAP    arch/powerpc/boot/zImage.epapr
ld.lld: error: relocation R_PPC_ADDR16_HA cannot be used against local symbol; recompile with -fPIC
>>> defined in arch/powerpc/boot/wrapper.a(opal-calls.o)
>>> referenced by opal-calls.o:(.text+0x3E) in archive arch/powerpc/boot/wrapper.a

ld.lld: error: relocation R_PPC_ADDR16_LO cannot be used against local symbol; recompile with -fPIC
>>> defined in arch/powerpc/boot/wrapper.a(opal-calls.o)
>>> referenced by opal-calls.o:(.text+0x42) in archive arch/powerpc/boot/wrapper.a
```

I thought your 2nd WIP patch would solve this but it does not seem to be the case:
```
--- a/arch/powerpc/boot/wrapper	2023-06-06 01:22:21.924532805 +0200
+++ b/arch/powerpc/boot/wrapper	2023-06-06 01:25:27.094505007 +0200
@@ -308,6 +308,7 @@
     if [ "$format" != "elf32ppc" ]; then
 	link_address=
 	pie=-pie
+    notext='-z notext'
     fi
     make_space=n
     ;;
```
[wip01.patch.txt](https://github.com/ClangBuiltLinux/linux/files/11658564/wip01.patch.txt)
[wip02.patch.txt](https://github.com/ClangBuiltLinux/linux/files/11658565/wip02.patch.txt)
[wip03.patch.txt](https://github.com/ClangBuiltLinux/linux/files/11658566/wip03.patch.txt)

Whole series would be:
```
diff --git a/arch/powerpc/boot/Makefile b/arch/powerpc/boot/Makefile
index 771b79423bbc..99fc6dea3b7f 100644
--- a/arch/powerpc/boot/Makefile
+++ b/arch/powerpc/boot/Makefile
@@ -267,6 +267,15 @@ CROSSWRAP := -C "$(CROSS_COMPILE)"
 endif
 endif
 
+ifneq ($(LLVM),)
+WRAPTOOLS := --ld $(LD)
+WRAPTOOLS += --nm $(NM)
+WRAPTOOLS += --objcopy $(OBJCOPY)
+WRAPTOOLS += --objdump $(OBJDUMP)
+# No $(STRINGS)
+WRAPTOOLS += --strings llvm-strings
+endif
+
 compressor-$(CONFIG_KERNEL_GZIP) := gz
 compressor-$(CONFIG_KERNEL_XZ)   := xz
 compressor-$(CONFIG_KERNEL_LZMA)   := lzma
@@ -275,7 +284,7 @@ compressor-$(CONFIG_KERNEL_LZO) := lzo
 # args (to if_changed): 1 = (this rule), 2 = platform, 3 = dts 4=dtb 5=initrd
 quiet_cmd_wrap	= WRAP    $@
       cmd_wrap	=$(CONFIG_SHELL) $(wrapper) -Z $(compressor-y) -c -o $@ -p $2 \
-		$(CROSSWRAP) $(if $3, -s $3)$(if $4, -d $4)$(if $5, -i $5) \
+		$(CROSSWRAP) $(WRAPTOOLS) $(if $3, -s $3)$(if $4, -d $4)$(if $5, -i $5) \
 		vmlinux
 
 image-$(CONFIG_PPC_PSERIES)		+= zImage.pseries
diff --git a/arch/powerpc/boot/wrapper b/arch/powerpc/boot/wrapper
index 352d7de24018..4293d2f3936d 100755
--- a/arch/powerpc/boot/wrapper
+++ b/arch/powerpc/boot/wrapper
@@ -167,6 +167,31 @@ while [ "$#" -gt 0 ]; do
         compression=
 	uboot_comp=none
         ;;
+    --ld)
+	shift
+	[ "$#" -gt 0 ] || usage
+	ld="$1"
+	;;
+    --nm)
+	shift
+	[ "$#" -gt 0 ] || usage
+	nm="$1"
+	;;
+    --objcopy)
+	shift
+	[ "$#" -gt 0 ] || usage
+	objcopy="$1"
+	;;
+    --objdump)
+	shift
+	[ "$#" -gt 0 ] || usage
+	objdump="$1"
+	;;
+    --strings)
+	shift
+	[ "$#" -gt 0 ] || usage
+	strings="$1"
+	;;
     -?)
 	usage
 	;;
@@ -178,6 +203,21 @@ while [ "$#" -gt 0 ]; do
     shift
 done
 
+if [ -z "$ld" ]; then
+    ld=${CROSS}ld
+fi
+if [ -z "$nm" ]; then
+    nm=${CROSS}nm
+fi
+if [ -z "$objcopy" ]; then
+    objcopy=${CROSS}objcopy
+fi
+if [ -z "$objdump" ]; then
+    objdump=${CROSS}objdump
+fi
+if [ -z "$strings" ]; then
+    strings=${CROSS}strings
+fi
 
 if [ -n "$dts" ]; then
     if [ ! -r "$dts" -a -r "$object/dts/$dts" ]; then
@@ -193,7 +233,7 @@ if [ -z "$kernel" ]; then
     kernel=vmlinux
 fi
 
-LC_ALL=C elfformat="`${CROSS}objdump -p "$kernel" | grep 'file format' | awk '{print $4}'`"
+LC_ALL=C elfformat="`$objdump -p "$kernel" | grep 'file format' | awk '{print $4}'`"
 case "$elfformat" in
     elf64-powerpcle)	format=elf64lppc	;;
     elf64-powerpc)	format=elf32ppc	;;
@@ -226,7 +266,7 @@ ld_is_lld()
 
 # Do not include PT_INTERP segment when linking pie. Non-pie linking
 # just ignores this option.
-LD_VERSION=$(${CROSS}ld --version | ld_version)
+LD_VERSION=$($ld --version | ld_version)
 LD_NO_DL_MIN_VERSION=$(echo 2.26 | ld_version)
 if [ "$LD_VERSION" -ge "$LD_NO_DL_MIN_VERSION" ] ; then
 	nodl="--no-dynamic-linker"
@@ -268,6 +308,7 @@ pseries)
     if [ "$format" != "elf32ppc" ]; then
 	link_address=
 	pie=-pie
+    notext='-z notext'
     fi
     make_space=n
     ;;
@@ -380,7 +421,7 @@ epapr)
     link_address='0x20000000'
     pie=-pie
     notext='-z notext'
-    rodynamic=$(if ${CROSS}ld -V 2>&1 | grep -q LLD ; then echo "-z rodynamic"; fi)
+    rodynamic=$(if $ld -V 2>&1 | grep -q LLD ; then echo "-z rodynamic"; fi)
     ;;
 mvme5100)
     platformo="$object/fixed-head.o $object/mvme5100.o"
@@ -396,7 +437,7 @@ esac
 vmz="$tmpdir/`basename \"$kernel\"`.$ext"
 
 # Calculate the vmlinux.strip size
-${CROSS}objcopy $objflags "$kernel" "$vmz.$$"
+$objcopy $objflags "$kernel" "$vmz.$$"
 strip_size=$(${CONFIG_SHELL} "${srctree}/scripts/file-size.sh" "$vmz.$$")
 
 if [ -z "$cacheit" -o ! -f "$vmz$compression" -o "$vmz$compression" -ot "$kernel" ]; then
@@ -449,14 +490,14 @@ fi
 
 # Extract kernel version information, some platforms want to include
 # it in the image header
-version=`${CROSS}strings "$kernel" | grep '^Linux version [-0-9.]' | \
+version=`$strings "$kernel" | grep '^Linux version [-0-9.]' | \
     head -n1 | cut -d' ' -f3`
 if [ -n "$version" ]; then
     uboot_version="-n Linux-$version"
 fi
 
 # physical offset of kernel image
-membase=`${CROSS}objdump -p "$kernel" | grep -m 1 LOAD | awk '{print $7}'`
+membase=`$objdump -p "$kernel" | grep -m 1 LOAD | awk '{print $7}'`
 
 case "$platform" in
 uboot)
@@ -491,7 +532,7 @@ uboot-obs600)
 esac
 
 addsec() {
-    ${CROSS}objcopy $4 $1 \
+    $objcopy $4 $1 \
 	--add-section=$3="$2" \
 	--set-section-flags=$3=contents,alloc,load,readonly,data
 }
@@ -521,18 +562,18 @@ if [ "$platform" != "miboot" ]; then
         text_start="-Ttext $link_address"
     fi
 #link everything
-    ${CROSS}ld -m $format -T $lds $text_start $pie $nodl $nowarn $rodynamic $notext -o "$ofile" $map \
+    $ld -m $format -T $lds $text_start $pie $nodl $nowarn $rodynamic $notext -z norelro -o "$ofile" $map \
 	$platformo $tmp $object/wrapper.a
     rm $tmp
 fi
 
 # Some platforms need the zImage's entry point and base address
-base=0x`${CROSS}nm "$ofile" | grep ' _start$' | cut -d' ' -f1`
-entry=`${CROSS}objdump -f "$ofile" | grep '^start address ' | cut -d' ' -f3`
+base=0x`$nm "$ofile" | grep ' _start$' | cut -d' ' -f1`
+entry=`$objdump -f "$ofile" | grep '^start address ' | cut -d' ' -f3`
 
 if [ -n "$binary" ]; then
     mv "$ofile" "$ofile".elf
-    ${CROSS}objcopy -O binary "$ofile".elf "$ofile"
+    $objcopy -O binary "$ofile".elf "$ofile"
 fi
 
 # post-processing needed for some platforms
@@ -541,7 +582,7 @@ pseries|chrp|maple)
     $objbin/addnote "$ofile"
     ;;
 coff)
-    ${CROSS}objcopy -O aixcoff-rs6000 --set-start "$entry" "$ofile"
+    $objcopy -O aixcoff-rs6000 --set-start "$entry" "$ofile"
     $objbin/hack-coff "$ofile"
     ;;
 cuboot*)
@@ -569,18 +610,18 @@ ps3)
     # copied to offset 0x100.  At runtime the bootwrapper program copies
     # the data at __system_reset_kernel back to addr 0x100.
 
-    system_reset_overlay=0x`${CROSS}nm "$ofile" \
+    system_reset_overlay=0x`$nm "$ofile" \
         | grep ' __system_reset_overlay$'       \
         | cut -d' ' -f1`
     system_reset_overlay=`printf "%d" $system_reset_overlay`
-    system_reset_kernel=0x`${CROSS}nm "$ofile" \
+    system_reset_kernel=0x`$nm "$ofile" \
         | grep ' __system_reset_kernel$'       \
         | cut -d' ' -f1`
     system_reset_kernel=`printf "%d" $system_reset_kernel`
     overlay_dest="256"
     overlay_size="512"
 
-    ${CROSS}objcopy -O binary "$ofile" "$ofile.bin"
+    $objcopy -O binary "$ofile" "$ofile.bin"
 
     run_cmd dd if="$ofile.bin" of="$ofile.bin" conv=notrunc   \
         skip=$overlay_dest seek=$system_reset_kernel          \
@@ -598,7 +639,7 @@ ps3)
     # reached, then enter the system reset vector of the partially decompressed
     # image.  No warning is issued.
     rm -f "$odir"/{otheros,otheros-too-big}.bld
-    size=$(${CROSS}nm --no-sort --radix=d "$ofile" | grep -E ' _end$' | cut -d' ' -f1)
+    size=$($nm --no-sort --radix=d "$ofile" | grep -E ' _end$' | cut -d' ' -f1)
     bld="otheros.bld"
     if [ $size -gt $((0x1000000)) ]; then
         bld="otheros-too-big.bld"
```

**Comment by nickdesaulniers** [comment] 2023-06-06 20:55
> objdump: vmlinux: unable to initialize decompress status for section .debug_aranges
> D'oh... of course I need a binutill with zstd support compiled. facepalm And I can confirm compilation works with binutils-2.40 with zstd support enabled. wink

This implies the `depends on` clauses for `DEBUG_INFO_COMPRESSED_ZLIB` is incomplete/incorrect.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/lib/Kconfig.debug#n330

@ernsteiswuerfel can you confirm that with your previous version of binutils with compressed debug info off, `make CC=clang menuconfig` would allow you to select `DEBUG_INFO_COMPRESSED_ZLIB=y` (vs forcing it on manually via scripts/config or modifying .config by hand)?  We may need to fix that upstream to make it a better user experience; Kconfig should block certain configs that would otherwise result in confusing build errors or warnings during a build.

> I needed to alter them so they apply on 6.4-rc5. Now I am getting:

Let's try to keep these issue reports to one distinct problem per thread.

**Comment by nathanchance** [comment] 2023-06-06 21:04
> > objdump: vmlinux: unable to initialize decompress status for section .debug_aranges
> > D'oh... of course I need a binutill with zstd support compiled. facepalm And I can confirm compilation works with binutils-2.40 with zstd support enabled. wink
> 
> This implies the `depends on` clauses for `DEBUG_INFO_COMPRESSED_ZLIB` is incomplete/incorrect. https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/lib/Kconfig.debug#n330

Not really. The wrapper in `arch/powerpc/boot` unconditionally uses GNU binutils (#1601), so we have the opportunity for there to be mismatched support between the version of LLVM being used to build the kernel and the version of GNU binutils used to build the boot wrappers; I am not really sure how that mismatch can be fixed in Kconfig because of the separation of `arch/powerpc/boot` and the rest of the kernel. I think the real solution is to make the boot wrapper respect `LLVM=1`, so that this opportunity for mismatch does not occur (which is what that WIP series aims to do). In other words, I believe this is a direct symptom of #1601, not a separate problem in its own right. I could be wrong though.

**Comment by nickdesaulniers** [comment] 2023-06-06 21:22
Then I'm inclined to close this as a duplicate of #1601. Perhaps time to revisit https://git.kernel.org/pub/scm/linux/kernel/git/nathan/linux.git/log/?h=wip/llvm-1-powerpc-boot-wrapper?

**Closed as completed by nickdesaulniers** 2023-06-06 21:22 UTC
Labels: duplicate
