### ISSUE TITLE
[PATCH] x86/crypto: aesni: Fix build with LLVM_IAS=1 (next part for 5.9+)

### ISSUE THREAD

**Issue by AndyLavr** [ClangBuiltLinux/linux#1118] opened 2020-08-04 12:24 UTC
```bash
From: Andy Lavr <andy.lavr@gmail.com>
Date: Tue, 4 Aug 2020 14:16:41 +0300
Subject: [PATCH] x86/crypto: aesni: Fix build with LLVM_IAS=1 (next part for 5.9+)


Signed-off-by: Andy Lavr <andy.lavr@gmail.com>
diff --git a/arch/x86/crypto/aesni-intel_asm.S b/arch/x86/crypto/aesni-intel_asm.S
index fc11d02..66ddd5c 100644
--- a/arch/x86/crypto/aesni-intel_asm.S
+++ b/arch/x86/crypto/aesni-intel_asm.S
@@ -977,7 +977,7 @@
 * arg1, %arg3, %arg4 are used as pointers only, not modified
 * %r11 is the data offset value
 */
-.macro GHASH_4_ENCRYPT_4_PARALLEL_enc TMP1 TMP2 TMP3 TMP4 TMP5 \
+.macro GHASH_4_ENCRYPT_4_PARALLEL_ENC TMP1 TMP2 TMP3 TMP4 TMP5 \
 TMP6 XMM0 XMM1 XMM2 XMM3 XMM4 XMM5 XMM6 XMM7 XMM8 operation
 
        movdqa    \XMM1, \XMM5
@@ -1185,7 +1185,7 @@
 * arg1, %arg3, %arg4 are used as pointers only, not modified
 * %r11 is the data offset value
 */
-.macro GHASH_4_ENCRYPT_4_PARALLEL_dec TMP1 TMP2 TMP3 TMP4 TMP5 \
+.macro GHASH_4_ENCRYPT_4_PARALLEL_DEC TMP1 TMP2 TMP3 TMP4 TMP5 \
 TMP6 XMM0 XMM1 XMM2 XMM3 XMM4 XMM5 XMM6 XMM7 XMM8 operation
 
        movdqa    \XMM1, \XMM5
```

**Comment by nickdesaulniers** [comment] 2020-08-04 17:50
dupe of #1050

**Closed by nickdesaulniers** 2020-08-04 17:50 UTC

**Comment by dileks** [comment] 2020-08-05 07:50
@AndyLavr 

Please see <https://github.com/ClangBuiltLinux/linux/issues/1049#issuecomment-662609378>
