### ISSUE TITLE
[cross compile] arm target fails with lld error: out of range

### ISSUE THREAD

**Issue by n8v8R** [ClangBuiltLinux/linux#1135] opened 2020-08-18 07:29 UTC
trying to cross compile 5.9-rc1 on a linux x86_64 node (_llvm-10_ | _gcc 9.3.0_) with `ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make -j8 LLVM=1` and this kconfig [.config.txt](https://github.com/ClangBuiltLinux/linux/files/5088859/default.config.txt)

the build process prematurely terminates with
```
  LD      vmlinux.o
  MODPOST vmlinux.symvers
  MODINFO modules.builtin.modinfo
  GEN     modules.builtin
  LD      .tmp_vmlinux.kallsyms1
ld.lld-10: error: .tmp_vmlinux.kallsyms1:(.ARM.exidx+0x5A0B0): relocation R_ARM_PREL31 out of range: 1322629248 is not in [-1073741824, 1073741823]
make: *** [Makefile:1167: vmlinux] Error 1
```

**Comment by nathanchance** [comment] 2020-08-18 07:36
I suspect this is a duplicate of #732.

**Comment by n8v8R** [comment] 2020-08-18 07:39
It should be fixed in _llvm_ | _lld_ version 11?

**Comment by nathanchance** [comment] 2020-08-26 05:16
Verified that the following config builds on ToT with LLVM 12 (I suspect LLVM 11 will compile fine as well but I do not have time to test). Marking as a duplicate of #732.

**Closed by nathanchance** 2020-08-26 05:16 UTC
