### ISSUE TITLE
arch/x86/include/asm/processor.h: Warning -Waddress-of-packed-member 

### ISSUE THREAD

**Issue by dileks** [ClangBuiltLinux/linux#234] opened 2018-10-22 09:13 UTC
With Linux v4.19 final and Debian's Clang-7 (1:7-6) I see the following:
```
  mycompiler -Wp,-MD,drivers/firmware/efi/libstub/.efi-stub-helper.o.d  -nostdinc -isystem /usr/lib/llvm-7/lib/clang/7.0.0/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -Qunused-arguments -mcmodel=small -m64 -D__KERNEL__ -O2 -fPIC -fno-strict-aliasing -mno-red-zone -mno-mmx -mno-sse -fshort-wchar -DDISABLE_BRANCH_PROFILING -D__NO_FORTIFY -ffreestanding -fno-stack-protector -D__DISABLE_EXPORTS    -DKBUILD_BASENAME='"efi_stub_helper"' -DKBUILD_MODNAME='"efi_stub_helper"' -c -o drivers/firmware/efi/libstub/.tmp_efi-stub-helper.o drivers/firmware/efi/libstub/efi-stub-helper.c
In file included from drivers/firmware/efi/libstub/efi-stub-helper.c:13:
In file included from ./include/linux/efi.h:17:
In file included from ./include/linux/time.h:6:
In file included from ./include/linux/seqlock.h:36:
In file included from ./include/linux/spinlock.h:51:
In file included from ./include/linux/preempt.h:81:
In file included from ./arch/x86/include/asm/preempt.h:7:
In file included from ./include/linux/thread_info.h:38:
In file included from ./arch/x86/include/asm/thread_info.h:53:
In file included from ./arch/x86/include/asm/cpufeature.h:5:
./arch/x86/include/asm/processor.h:555:17: warning: taking address of packed member 'sp0' of class or structure 'x86_hw_tss' may result in an unaligned pointer value [-Waddress-of-packed-member]
        this_cpu_write(cpu_tss_rw.x86_tss.sp0, sp0);
                       ^~~~~~~~~~~~~~~~~~~~~~
./include/linux/percpu-defs.h:510:68: note: expanded from macro 'this_cpu_write'
#define this_cpu_write(pcp, val)        __pcpu_size_call(this_cpu_write_, pcp, val)
                                                                          ^~~
./include/linux/percpu-defs.h:377:22: note: expanded from macro '__pcpu_size_call'
        __verify_pcpu_ptr(&(variable));                                 \
                            ^~~~~~~~
./include/linux/percpu-defs.h:221:47: note: expanded from macro '__verify_pcpu_ptr'
        const void __percpu *__vpp_verify = (typeof((ptr) + 0))NULL;    \
                                                     ^~~
In file included from drivers/firmware/efi/libstub/efi-stub-helper.c:13:
In file included from ./include/linux/efi.h:17:
In file included from ./include/linux/time.h:6:
In file included from ./include/linux/seqlock.h:36:
In file included from ./include/linux/spinlock.h:51:
In file included from ./include/linux/preempt.h:81:
In file included from ./arch/x86/include/asm/preempt.h:7:
In file included from ./include/linux/thread_info.h:38:
In file included from ./arch/x86/include/asm/thread_info.h:53:
In file included from ./arch/x86/include/asm/cpufeature.h:5:
./arch/x86/include/asm/processor.h:572:30: warning: taking address of packed member 'sp1' of class or structure 'x86_hw_tss' may result in an unaligned pointer value [-Waddress-of-packed-member]
        return this_cpu_read_stable(cpu_current_top_of_stack);
                                    ^~~~~~~~~~~~~~~~~~~~~~~~
./arch/x86/include/asm/processor.h:379:34: note: expanded from macro 'cpu_current_top_of_stack'
#define cpu_current_top_of_stack cpu_tss_rw.x86_tss.sp1
                                 ^~~~~~~~~~~~~~~~~~~~~~
./arch/x86/include/asm/percpu.h:392:59: note: expanded from macro 'this_cpu_read_stable'
#define this_cpu_read_stable(var)       percpu_stable_op("mov", var)
                                                                ^~~
./arch/x86/include/asm/percpu.h:219:16: note: expanded from macro 'percpu_stable_op'
                    : "p" (&(var)));                    \
                             ^~~
```

I found this patch [1] and not sure if this was fixed in the meantime:

"[PATCH 1/2] kbuild: clang: Disable 'address-of-packed-member' warning"

There is also no label "-Waddress-of-packed-member".

Thanks for any feedback.

[1] https://lore.kernel.org/lkml/CAK7LNASEnzDPQs2AY115sMx-i2NTUu9h9LHv5eN1ygvW81vtFw@mail.gmail.com/

**Comment by dileks** [comment] 2018-10-22 14:18
From a quick view into my build-log I suggest to do something similiar like in commit "x86/boot: Disable the address-of-packed-member compiler warning" Linux upstream:
```
[ drivers/firmware/efi/libstub/Makefile ]
KBUILD_CFLAGS += $(call cc-disable-warning, address-of-packed-member)
```
Not sure if this only affects x86/x86-64 or also arm/arm64.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=20c6c189045539d29f4854d92b7ea9c329e1edfc

**Comment by nathanchance** [comment] 2018-10-22 15:34
See if the patch I sent in #112 works for you.

**Comment by nickdesaulniers** [comment] 2018-10-22 23:46
dupe of #112.

**Closed by nickdesaulniers** 2018-10-22 23:46 UTC
Labels: -Waddress-of-packed-member
