### ISSUE TITLE
perf events fail to compile for i686

### ISSUE THREAD

**Issue by pefoley2** [ClangBuiltLinux/linux#1007] opened 2020-04-25 18:34 UTC
e.g.
In file included from ../arch/x86/events/amd/core.c:12:
../arch/x86/events/amd/../perf_event.h:853:21: error: invalid output size for constraint '=q'
        u64 disable_mask = __this_cpu_read(cpu_hw_events.perf_ctr_virt_mask);
                           ^
../include/linux/percpu-defs.h:446:2: note: expanded from macro '__this_cpu_read'
        raw_cpu_read(pcp);                                              \
        ^
../include/linux/percpu-defs.h:420:28: note: expanded from macro 'raw_cpu_read'
#define raw_cpu_read(pcp)               __pcpu_size_call_return(raw_cpu_read_, pcp)
                                        ^
../include/linux/percpu-defs.h:321:23: note: expanded from macro '__pcpu_size_call_return'
        case 1: pscr_ret__ = stem##1(variable); break;                  \
                             ^
<scratch space>:179:1: note: expanded from here
raw_cpu_read_1
^
../arch/x86/include/asm/percpu.h:394:30: note: expanded from macro 'raw_cpu_read_1'
#define raw_cpu_read_1(pcp)             percpu_from_op(, "mov", pcp)
                                        ^
../arch/x86/include/asm/percpu.h:189:15: note: expanded from macro 'percpu_from_op'
                    : "=q" (pfo_ret__)                  \
                            ^
In file included from ../arch/x86/events/amd/core.c:12:
../arch/x86/events/amd/../perf_event.h:853:21: error: invalid output size for constraint '=q'
../include/linux/percpu-defs.h:446:2: note: expanded from macro '__this_cpu_read'
        raw_cpu_read(pcp);                                              \
        ^
../include/linux/percpu-defs.h:420:28: note: expanded from macro 'raw_cpu_read'
#define raw_cpu_read(pcp)               __pcpu_size_call_return(raw_cpu_read_, pcp)
                                        ^
../include/linux/percpu-defs.h:322:23: note: expanded from macro '__pcpu_size_call_return'
        case 2: pscr_ret__ = stem##2(variable); break;                  \
                             ^
<scratch space>:188:1: note: expanded from here

**Comment by nathanchance** [comment] 2020-04-25 18:59
I think this is a dupe of #194 but can’t check very closely at the moment.

**Comment by tpimh** [comment] 2020-04-27 04:53
It is a duplicate. Please use one of these patches to resolve: https://github.com/ClangBuiltLinux/linux/issues/194#issuecomment-548710288

**Closed by tpimh** 2020-04-27 04:53 UTC
Labels: [ARCH] x86, [BUG] linux
