### ISSUE TITLE
error in backend: could not find corresponding %pcrel_hi

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1072] opened 2020-06-30 16:48 UTC
riscv mainline is crashing as of last night
https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/355728360
```
  CC      arch/riscv/kernel/cpu.o
fatal error: error in backend: could not find corresponding %pcrel_hi
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /usr/lib/llvm-11/bin/clang -Qunused-arguments -Wall -Wundef -Werror=strict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -fno-PIE -Werror=implicit-function-declaration -Werror=implicit-int -Wno-format-security -std=gnu89 --target=riscv64-linux-gnu --prefix=/usr/bin/ --gcc-toolchain=/usr -Werror=unknown-warning-option -mabi=lp64 -march=rv64imac -mno-save-restore -mcmodel=medany -fno-delete-null-pointer-checks -Wno-frame-address -Wno-address-of-packed-member -O2 -Wframe-larger-than=2048 -fno-stack-protector -Wno-format-invalid-specifier -Wno-gnu -mno-global-merge -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -Wdeclaration-after-statement -Wvla -Wno-pointer-sign -Wno-array-bounds -fno-strict-overflow -fno-merge-all-constants -fno-stack-check -Werror=date-time -Werror=incompatible-pointer-types -fmacro-prefix-map=./= -Wno-initializer-overrides -Wno-format -Wno-sign-compare -Wno-format-zero-length -Wno-pointer-to-enum-cast -Wno-tautological-constant-out-of-range-compare -Wno-implicit-fallthrough -nostdinc -isystem /usr/lib/llvm-11/lib/clang/11.0.0/include -I./arch/riscv/include -I./arch/riscv/include/generated -I./include -I./arch/riscv/include/uapi -I./arch/riscv/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -DCONFIG_PAGE_OFFSET=0xffffffe000000000 -DKBUILD_MODFILE="arch/riscv/kernel/cpu" -DKBUILD_BASENAME="cpu" -DKBUILD_MODNAME="cpu" -c -o arch/riscv/kernel/cpu.o arch/riscv/kernel/cpu.c 
1.	<eof> parser at end of file
2.	Code generation
 #0 0x00007fa592065bef llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/lib/x86_64-linux-gnu/libLLVM-11.so.1+0xa0abef)
 #1 0x00007fa592063f50 llvm::sys::RunSignalHandlers() (/lib/x86_64-linux-gnu/libLLVM-11.so.1+0xa08f50)
 #2 0x00007fa59206533d llvm::sys::CleanupOnSignal(unsigned long) (/lib/x86_64-linux-gnu/libLLVM-11.so.1+0xa0a33d)
 #3 0x00007fa591fadeda (/lib/x86_64-linux-gnu/libLLVM-11.so.1+0x952eda)
 #4 0x00007fa591fade7b (/lib/x86_64-linux-gnu/libLLVM-11.so.1+0x952e7b)
 #5 0x00007fa592060a1e (/lib/x86_64-linux-gnu/libLLVM-11.so.1+0xa05a1e)
 #6 0x00000000004128c2 (/usr/lib/llvm-11/bin/clang+0x4128c2)
 #7 0x00007fa591fb9fdf llvm::report_fatal_error(llvm::Twine const&, bool) (/lib/x86_64-linux-gnu/libLLVM-11.so.1+0x95efdf)
 #8 0x00007fa593107666 (/lib/x86_64-linux-gnu/libLLVM-11.so.1+0x1aac666)
 #9 0x00007fa593eb8b69 (/lib/x86_64-linux-gnu/libLLVM-11.so.1+0x285db69)
#10 0x00007fa5930fd057 llvm::MCAssembler::evaluateFixup(llvm::MCAsmLayout const&, llvm::MCFixup const&, llvm::MCFragment const*, llvm::MCValue&, unsigned long&, bool&) const (/lib/x86_64-linux-gnu/libLLVM-11.so.1+0x1aa2057)
#11 0x00007fa5930fe8be llvm::MCAssembler::handleFixup(llvm::MCAsmLayout const&, llvm::MCFragment&, llvm::MCFixup const&) (/lib/x86_64-linux-gnu/libLLVM-11.so.1+0x1aa38be)
#12 0x00007fa5930feec2 llvm::MCAssembler::layout(llvm::MCAsmLayout&) (/lib/x86_64-linux-gnu/libLLVM-11.so.1+0x1aa3ec2)
#13 0x00007fa5930ff1d8 llvm::MCAssembler::Finish() (/lib/x86_64-linux-gnu/libLLVM-11.so.1+0x1aa41d8)
#14 0x00007fa592721f07 llvm::AsmPrinter::doFinalization(llvm::Module&) (/lib/x86_64-linux-gnu/libLLVM-11.so.1+0x10c6f07)
#15 0x00007fa59217a6f1 llvm::FPPassManager::doFinalization(llvm::Module&) (/lib/x86_64-linux-gnu/libLLVM-11.so.1+0xb1f6f1)
#16 0x00007fa59217abd2 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/lib/x86_64-linux-gnu/libLLVM-11.so.1+0xb1fbd2)
#17 0x00007fa59772cf66 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x156df66)
#18 0x00007fa5979eaf8e (/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x182bf8e)
#19 0x00007fa596abfdf3 clang::ParseAST(clang::Sema&, bool, bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x900df3)
#20 0x00007fa59807a3e8 clang::FrontendAction::Execute() (/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x1ebb3e8)
#21 0x00007fa598031351 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x1e72351)
#22 0x00007fa5980df4d0 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x1f204d0)
#23 0x000000000041258c cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/lib/llvm-11/bin/clang+0x41258c)
#24 0x0000000000410a2e (/usr/lib/llvm-11/bin/clang+0x410a2e)
#25 0x00007fa597d693b2 (/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x1baa3b2)
#26 0x00007fa591fade5d llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/lib/x86_64-linux-gnu/libLLVM-11.so.1+0x952e5d)
#27 0x00007fa597d688ef clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x1ba98ef)
#28 0x00007fa597d407ef clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x1b817ef)
#29 0x00007fa597d40997 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x1b81997)
#30 0x00007fa597d5439c clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/lib/x86_64-linux-gnu/libclang-cpp.so.11+0x1b9539c)
#31 0x00000000004104cc main (/usr/lib/llvm-11/bin/clang+0x4104cc)
#32 0x00007fa5911430b3 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b3)
#33 0x000000000040dcce _start (/usr/lib/llvm-11/bin/clang+0x40dcce)
make[2]: *** [scripts/Makefile.build:281: arch/riscv/kernel/cpu.o] Error 1
make[1]: *** [scripts/Makefile.build:497: arch/riscv/kernel] Error 2
make: *** [Makefile:1756: arch/riscv] Error 2
make: *** Waiting for unfinished jobs....
```

**Comment by nathanchance** [comment] 2020-06-30 22:56
Caused by https://github.com/llvm/llvm-project/commit/2cb0644f90b7deda78fd5a4df4b74e25bd1db701 according to bisect.

```
$ git bisect log
# bad: [73377c45974855a00b13974cd515e875c5605556] [PowerPC][Power10] Add Vector Splat Imm/Permute/Blend/Shift Double Bit Imm Definitions and MC Tests
# good: [878a24d369ea4d627fb48f7af5edc28fd079a0c0] [X86] Add PR46461 test case
git bisect start 'master' 'master~282'
# bad: [4a80f1907860c9ebe55d0172d8e7d3ea95aa5d71] [mlir] [VectorOps] Extend vector reduction integration test with reassoc=true cases.
git bisect bad 4a80f1907860c9ebe55d0172d8e7d3ea95aa5d71
# good: [4822291da5b3a2db3b83d80a0876b26f7d6dd00a] [NFC] Introduce a helper in BasicTTIImpl.h to cast to T
git bisect good 4822291da5b3a2db3b83d80a0876b26f7d6dd00a
# bad: [fe0a555aa3c6f37a5b5d79942215b07587893efa] [analyzer][NFC] Add unittest for FalsePositiveRefutationBRVisitor
git bisect bad fe0a555aa3c6f37a5b5d79942215b07587893efa
# bad: [b6315aee5b420aa5a0be5f1ea86c3c963760a3f2] [VectorCombine] try to form vector compare and binop to eliminate scalar ops
git bisect bad b6315aee5b420aa5a0be5f1ea86c3c963760a3f2
# good: [d1df56023132914b877e34f6cf475758a96540f2] [Analyzer][StreamChecker] Use BugType instead of BuiltinBug (NFC) .
git bisect good d1df56023132914b877e34f6cf475758a96540f2
# bad: [0c332a7784c649038bd237a60fa18b45a3dea90d] [clang-format] Preserve whitespace in selected macros
git bisect bad 0c332a7784c649038bd237a60fa18b45a3dea90d
# bad: [876df18aecb6e7ce15b6c47684774bd33e169eb9] [gn build] Port 2cb0644f90b
git bisect bad 876df18aecb6e7ce15b6c47684774bd33e169eb9
# bad: [2cb0644f90b7deda78fd5a4df4b74e25bd1db701] [RISCV] Split the pseudo instruction splitting pass
git bisect bad 2cb0644f90b7deda78fd5a4df4b74e25bd1db701
# first bad commit: [2cb0644f90b7deda78fd5a4df4b74e25bd1db701] [RISCV] Split the pseudo instruction splitting pass
```

Compiling with assertions gives a more relevant error:

```
clang: /home/nathan/cbl/github/tc-build/llvm-project/llvm/lib/CodeGen/MachineBasicBlock.cpp:65: llvm::MCSymbol *llvm::MachineBasicBlock::getSymbol() const: Assertion `getNumber() >= 0 && "cannot get label for unreachable MBB"' failed.
```

I am going to do a reduction here in a bit and will post the results here and on Phabricator.

**Comment by nathanchance** [comment] 2020-06-30 23:28
https://reviews.llvm.org/D79635#2124242

**Comment by nathanchance** [comment] 2020-07-01 23:10
This is fixed with https://github.com/llvm/llvm-project/commit/b2aa546b0747418b0784b291b9104a4e3bf1e0c9.

**Closed** 2020-07-01 23:15 UTC
Labels: Reported upstream, [ARCH] risc-v, [BUG] llvm (master), compiler crash
