### ISSUE TITLE
-Wparentheses-equality in drivers/infiniband/hw/mlx4/mcg.c

### ISSUE THREAD

**Issue by shenki** [ClangBuiltLinux/linux#88] opened 2018-09-17 08:27 UTC
```
drivers/infiniband/hw/mlx4/mcg.c:676:16: warning: equality comparison with extraneous parentheses
      [-Wparentheses-equality]
                        if ((method == IB_MGMT_METHOD_GET_RESP)) {
                             ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/infiniband/hw/mlx4/mcg.c:676:16: note: remove extraneous parentheses around the comparison to
      silence this warning
                        if ((method == IB_MGMT_METHOD_GET_RESP)) {
                            ~       ^                         ~
drivers/infiniband/hw/mlx4/mcg.c:676:16: note: use '=' to turn this equality comparison into an assignment
                        if ((method == IB_MGMT_METHOD_GET_RESP)) {
                                    ^~
                                    =
```

**Comment by tpimh** [comment] 2018-09-18 12:34
Closed as duplicate of #65

**Closed by tpimh** 2018-09-18 12:34 UTC
Labels: duplicate
