### ISSUE TITLE
Warning: index register overlaps transfer register

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#838] opened 2020-01-09 17:30 UTC
arm32 defconfig + CONFIG_FORTIFY_SOURCE produces:

```
/tmp/core-80fb99.s:27935: Warning: index register overlaps transfer register
/tmp/fair-c9d1c4.s:993: Warning: index register overlaps transfer register
```

Which I'm guessing produced:
```
kernel/events/core.o
kernel/sched/fair.o
```

**Comment by ihalip** [comment] 2020-01-14 17:22
I see these with `kernel/events/core.c` and `kernel/events/ring_buffer.c`. Looking further.

**Comment by nathanchance** [comment] 2020-01-16 07:07
`CONFIG_FORTIFY_SOURCE` is not needed (a regular `multi_v7_defconfig` reproduces these warnings).

```
$ git bisect log
# bad: [5852475e2c049ce29dcb1f0da3ac33035f8c9156] Bump the trunk major version to 11
# good: [d2bb8c16e711602481c8b33d0e2ccc9994eb6641] [MC][TargetMachine] Delete MCTargetOptions::MCPIECopyRelocations
git bisect start 'llvmorg-11-init' 'HEAD'
# bad: [cd5da94d80b2b0f2bdb2d0157e24705a4cbd2a4e] [lldb/DWARF] Fix mixed v4+v5 location lists
git bisect bad cd5da94d80b2b0f2bdb2d0157e24705a4cbd2a4e
# good: [5173bfcbc4873fa12d14de0a0a4e6ac9ce960b5e] Add interface emitPrefix for MCCodeEmitter
git bisect good 5173bfcbc4873fa12d14de0a0a4e6ac9ce960b5e
# bad: [8edf759ca7e1ceadb8bd4c0701f08c48850c26e7] [PowerPC][Triple] Use elfv2 on freebsd>=13 and linux-musl
git bisect bad 8edf759ca7e1ceadb8bd4c0701f08c48850c26e7
# good: [5e0e0e3ff05f57b9495db57b6b205492d34cb5a8] [NFC] Fixes -Wrange-loop-analysis warnings
git bisect good 5e0e0e3ff05f57b9495db57b6b205492d34cb5a8
# bad: [60e0120c913dd1d4bfe33769e1f000a076249a42] [ARM] Improve codegen of volatile load/store of i64
git bisect bad 60e0120c913dd1d4bfe33769e1f000a076249a42
# good: [08de551f4f1087c4dd3220fee8ec328fa168168c] [APFloat] Fix fusedMultiplyAdd when `this` equals to `Addend`
git bisect good 08de551f4f1087c4dd3220fee8ec328fa168168c
# good: [bd1dc6a3eb801b0b6eadb569557a8bba6f7a4b9c] Fix "use of uninitialized variable" static analyzer warnings. NFCI.
git bisect good bd1dc6a3eb801b0b6eadb569557a8bba6f7a4b9c
# good: [c69ae835d0e0dc493eb09e75f0687a1390525440] [clangd] Add path mappings functionality
git bisect good c69ae835d0e0dc493eb09e75f0687a1390525440
# good: [14cd4a5b32478f76b9fa58825b7c92ba0dd5bc2b] [SystemZ] Extend fp-strict-alias test case
git bisect good 14cd4a5b32478f76b9fa58825b7c92ba0dd5bc2b
# good: [6ff1ea3244c543ad24fc99c7f4979db2f2078593] Fix "use of uninitialized variable" static analyzer warning. NFCI.
git bisect good 6ff1ea3244c543ad24fc99c7f4979db2f2078593
# first bad commit: [60e0120c913dd1d4bfe33769e1f000a076249a42] [ARM] Improve codegen of volatile load/store of i64

$ git show -s commit 60e0120c913dd1d4bfe33769e1f000a076249a42
Author: Victor Campos <Victor.Campos@arm.com>
Date:   Thu Jan 2 11:00:14 2020 +0000

    [ARM] Improve codegen of volatile load/store of i64
    
    Summary:
    Instead of generating two i32 instructions for each load or store of a volatile
    i64 value (two LDRs or STRs), now emit LDRD/STRD.
    
    These improvements cover architectures implementing ARMv5TE or Thumb-2.
    
    Reviewers: dmgreen, efriedma, john.brawn, nickdesaulniers
    
    Reviewed By: efriedma, nickdesaulniers
    
    Subscribers: nickdesaulniers, vvereschaka, kristof.beyls, hiraditya, llvm-commits
    
    Tags: #llvm
    
    Differential Revision: https://reviews.llvm.org/D70072
```

`creduce` reproducer:

```
struct g {
  long h;
  struct g *i;
  struct g *j
};
struct k {
  struct k *b
};
struct l {
  long m;
  int n
};
struct o {
} __attribute__((__aligned__(1 << 6)));
struct a {
  struct a *b, *c
} aj(ak) {
  *(volatile long long *)ak;
}
struct p {
  struct l a;
  long q;
  struct g r;
  struct a s;
  int t;
  long long u;
  long v;
  long long b;
  long w;
  struct o aa
};
struct {
  long d;
  void *e;
  int f;
  int b;
  int c;
  struct k x;
  int y;
  int z;
  long ab;
  int ac;
  int a;
  int ad;
  int t;
  int ae;
  int af;
  int ag;
  int ah;
  struct p ai
} a;
al() { aj(&a.ai.aa); }
```

Interestingness test and full preprocessed file available [here](https://github.com/nathanchance/creduce-files/tree/11d9a9dfd9861c87e9d15b1f3fcf0632b8276ba8/60e0120c913dd1d4bfe33769e1f000a076249a42).

**Comment by nickdesaulniers** [comment] 2020-01-16 19:07
Thanks for bisecting. I've pinged Victor again on https://reviews.llvm.org/D70072. The original version was reverted/fixed a few times, so there may be a little more work left to get it across the finish line.

**Comment by nathanchance** [comment] 2020-02-07 17:07
Reported on LLVM’s bug tracker since this is a clang-10 regression: https://llvm.org/pr44828

**Comment by vhscampos** [comment] 2020-02-08 13:26
The relevant patch has been reverted in the master branch. Please let me know if you want me to also revert it in 10.x

**Comment by nathanchance** [comment] 2020-02-08 13:33
@vhscampos yes, please have it reverted in 10.x so that we don’t get a regression there as well!

**Comment by vhscampos** [comment] 2020-02-08 13:40
Done!

**Comment by nathanchance** [comment] 2020-02-08 13:42
I’ll close this for now since we have the upstream bug. Thank you!

**Closed by nathanchance** 2020-02-08 13:42 UTC
Labels: Reported upstream, [ARCH] arm32, [BUG] llvm
