### ISSUE TITLE
enable -Wformat

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#378] opened 2019-02-25 18:56 UTC
[A previous attempt](https://patchwork.kernel.org/patch/10793767/) at re-enabling `-Wformat` showed that there were [LOTS](https://gist.github.com/443db156e56cd3c0f6b21d9d77728d80) of instances of this warning throughout the codebase.  Simply re-applying that patch and doing an arm64 defconfig, I experienced 236 unique instances of this warning.  Similar to @kees ' work enabling `-Wvla`, I'd like to find and fix all of these, then re-send the patch re-enabling the warning.

Assuming these aren't false positives, I think the only tricky cases we may encounter may come from config dependent types. ex.

```c
#ifdef CONFIG_FOO
int bar = 0;
#else 
float bar = 0;
#endif 
printk("bar: %d\n"); // warning: format specifies type 'int' but the argument has type 'float' [-Wformat]
```
which can be fixed via:
```diff
+prink("bar: "
+#ifdef CONFIG_FOO
+    "%d"
+#else
+    "%f"
+#endif
+    "\n");
-printk("bar: %d\n");
```
(or whatever maintainers prefer).  I don't expect many of those cases, but maybe I'm mistaken.

Also (meta), usually we file individual issues, but maybe it's better to use this one lone issue to track all the instances? (not sure; open to thoughts).

Also, let's find a way to split the work? And keep each other cc'ed when sending patches? (we should probably set up a mailing list to always cc for patches related to Clang Built Linux)

**Comment by nathanchance** [comment] 2019-02-25 19:08
> Also (meta), usually we file individual issues, but maybe it's better to use this one lone issue to track all the instances? (not sure; open to thoughts).

Given that some warnings might be easier fixed/received than others, it is still probably better to file individual issues and use the `-Wformat` label to link them all. We can either file issues as we deal with them or just take the list that I made above and file issues for all of them. I'd find the former easier to manage.

> we should probably set up a mailing list to always cc for patches related to Clang Built Linux

I've been thinking this for a bit. I usually CC you but I am sure there are others who would like to be kept in the loop as well.

**Comment by nickdesaulniers** [comment] 2019-02-25 21:15
https://groups.google.com/forum/#!forum/clang-built-linux

**Comment by nathanchance** [comment] 2019-02-25 22:44
So the email we'd CC is `clang-built-linux@googlegroups.com`?

**Comment by nickdesaulniers** [comment] 2019-02-25 22:49
it would be nice to get something on http://vger.kernel.org/vger-lists.html. I bet @arndb knows who to talk to about that.

**Comment by nathanchance** [comment] 2019-02-25 22:52
Maybe emailing postmaster@vger.kernel.org?

**Comment by arndb** [comment] 2019-02-26 19:16
On Mon, Feb 25, 2019 at 11:52 PM Nathan Chancellor <notifications@github.com>
wrote:

> Maybe emailing postmaster@vger.kernel.org?
>

Yes, that should be the right contact. Note that there is also a contact
for everything else on kernel.org,
but the mailing lists are handled by a separate team (David Miller is the
main person, not sure if
there are others).

       Arnd

**Comment by kragniz** [comment] 2019-02-26 23:53
I submitted a patch, tell me if I did something wrong: https://lore.kernel.org/r/20190226234853.20441-1-louis@kragniz.eu/

**Comment by jon-flatley** [comment] 2019-02-27 00:17
It looks good to me. In the future could you CC Nick and I on the patches? That will help us stay organized and will let us add a quick Reviewed-by if a patch needs some traction.

**Comment by jon-flatley** [comment] 2019-02-27 00:32
I reached out to the GCC community to try and better understand the difference for `-Wformat` in GCC vs Clang. It sounds like a big reason for the difference has to do with integer promotions. In GCC, any format specifier for a type that get promoted to an `int` checks the corresponding argument after it gets promoted, and just expects it to be an `int` after promotion. This means all types that get promoted to `int`, such as `short int` and `char`, are valid for any of each other's format specifiers in GCC. It appears that Clang checks these types pre-promotion, making Clang stricter. 

So a side effect of fixing these format specifiers is that they will no longer be converted to the size of their original "incorrect" type specifiers when they're formatted. I'm not sure if that could be problematic in places, but just something to keep in mind.

**Comment by kragniz** [comment] 2019-02-27 11:11
> I submitted a patch, tell me if I did something wrong: https://lore.kernel.org/r/20190226234853.20441-1-louis@kragniz.eu/

v2 of that patch: https://lore.kernel.org/r/20190227110720.27329-1-louis@kragniz.eu/

**Comment by nickdesaulniers** [comment] 2019-02-27 19:39
Some thoughts speaking more with @metti : 
* Documentation/core-api/printk-formats.rst is useful to cite in commit messages.
* lib/vsprintf.c#format_decode() implements most of the format flag decoding.
* `-Wformat-extra-args` is another case of `-Wformat` that looks serious.

**Comment by kragniz** [comment] 2019-02-27 20:25
Another patch: https://lore.kernel.org/r/20190227202202.21817-1-louis@kragniz.eu/

**Comment by kragniz** [comment] 2019-02-28 19:58
Some more patches:

https://lore.kernel.org/r/20190228122417.9318-1-louis@kragniz.eu/
https://lore.kernel.org/r/20190228194812.30929-1-louis@kragniz.eu/

**Comment by kragniz** [comment] 2019-03-02 14:34
https://lore.kernel.org/r/20190302141836.24638-1-louis@kragniz.eu/

**Comment by kragniz** [comment] 2019-03-03 13:10
https://lore.kernel.org/r/20190303123647.22020-1-louis@kragniz.eu/

**Comment by andy-shev** [comment] 2019-03-03 20:07
> https://lore.kernel.org/r/20190302141836.24638-1-louis@kragniz.eu/

This patch is wrong. We all know that IO port range is specified to be 0x0000-0xffff. You are trying to heal symptoms and not the issue.

**Comment by andy-shev** [comment] 2019-03-03 20:14
> Some more patches:
> 
> https://lore.kernel.org/r/20190228122417.9318-1-louis@kragniz.eu/

Not wrong, but better to use extended specifiers. I.e. here should be %16ph in use instead of all that old crap.

Joe did it in the right way.

> https://lore.kernel.org/r/20190228194812.30929-1-louis@kragniz.eu/

Again, healing the symptoms. We all know from PCI specification that mention values are 16-bit wide.

**Comment by andy-shev** [comment] 2019-03-03 20:22
> > I submitted a patch, tell me if I did something wrong: https://lore.kernel.org/r/20190226234853.20441-1-louis@kragniz.eu/
> 
> v2 of that patch: https://lore.kernel.org/r/20190227110720.27329-1-louis@kragniz.eu/

Healing the symptoms.

**Comment by nickdesaulniers** [comment] 2019-04-11 17:36
It might be more useful to tackle non-integer-widening `-Wformat` errors first:
https://llvm.org/pr41467
https://lore.kernel.org/r/CAHk-=wgoxnmsj8GEVFJSvTwdnWm8wVJthefNk2n6+4TC=20e0Q@mail.gmail.com/

**Comment by nickdesaulniers** [comment] 2019-07-18 20:42
Looking into this more, I think GCC does not warn in one case, and it should, and the kernel should be fixed, too: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91206

But let's wait and see what GCC devs think.

https://llvm.org/pr41467 is the LLVM bug report.

**Comment by jon-flatley** [comment] 2019-07-18 21:45
It seems like this is mostly a difference in philosophy, and there is
no clear answer for if the compiler should warn when passing integer
types with dissimilar lengths to their respective format specifier.

I had this conversation with some members in the gcc community and the
argument was that warning on "incorrect" length specifiers would imply
that it was against the c spec, but this behavior is defined in
7.19.6.1:

h
    Specifies that a following d, i, o, u, x, or X conversion specifier
    applies to a short int or unsigned short int argument (the argument
    will have been promoted according to the integer promotions, but
    its value shall be converted to short int or unsigned short int
    before printing); or that a following n conversion specifier applies
    to a pointer to a short int argument.
...
 If a conversion specification is invalid, the behavior is undefined.
If any argument is not the correct type for the corresponding
conversion specification, the behavior is undefined.


Now the answer to the question of whether or not the compiler should
warn in these situations lies in the interpretation of the language.
When asking if an argument "is not the correct type for the
corresponding conversion specification" is the spec referring to the
argument as it appears in the calling function, or as it is presented
to the called function? The language seems to indicate to me that the
correct type for the %hx format specifier for example would be
unsigned short int as it appears in the calling function, despite the
promotion to int within printf. This is up for debate, however.

**Comment by nickdesaulniers** [comment] 2019-08-14 17:32
@Nathan-Huckleberry has a patch to clang for the char -> short case: https://reviews.llvm.org/D66186

With that in, I think we can add a clang-version-specific check to scripts/Makefile.extrawarn that re-enables `-Wformat` for Clang if CONFIG_CLANG_VERSION >= 10.

**Comment by nickdesaulniers** [comment] 2019-08-23 18:11
In https://reviews.llvm.org/rL369791, Nathan made [unsigned] char -> [unsigned]short warn only for -Wformat-pedantic, not -Wformat.

So I think the final thing we can likely do to close this out is a modification to `scripts/Makefile.extrawarn` that does the equivalent:

```
if clang:
  if clang_version < 10:
    KBUILD_CFLAGS += -Wno-format
```
or maybe:
```
if clang:
  if clang_version >= 10:
    KBUILD_CFLAGS += -Wformat -Wno-format-pedantic
```

**Comment by andy-shev** [comment] 2019-08-26 13:03
> if clang:
>   if clang_version >= 10:

Doesn't option check macros work on CLang? As far as I understand you may simple check for option independently on compiler (in case there is no collision between compilers for the same option name).

**Comment by andy-shev** [comment] 2019-08-26 16:31
> @andy-shev the issue is we don’t want to enable `-Wformat` for builds of clang before r369791 because it will be extremely noisy. `-Wformat` has been around for a while so just doing `cc-option` won’t work.

I see.

> We could copy `arch/arm64/kernel/vdso/Makefile `:
> 
> `ifeq ($(shell test $(CONFIG_CLANG_VERSION) -lt 100000; echo $$?),0)`

Perhaps making it global for all code makes sense.

**Comment by nickdesaulniers** [comment] 2020-05-05 00:11
This is the patch I'd like to send for this:
```diff
diff --git a/scripts/Makefile.extrawarn b/scripts/Makefile.extrawarn
index 4aea7cf71d11..4b0c0664b838 100644
--- a/scripts/Makefile.extrawarn
+++ b/scripts/Makefile.extrawarn
@@ -45,7 +45,11 @@ else
 
 ifdef CONFIG_CC_IS_CLANG
 KBUILD_CFLAGS += -Wno-initializer-overrides
+# Clang < 10 was too strict about -Wformat. -Wformat-security is enabled by
+# setting -Wformat, but we only want to enable it via W=1.
+ifeq ($(shell test $(CONFIG_CLANG_VERSION) -lt 100000; echo $$?),0)
 KBUILD_CFLAGS += -Wno-format
+endif
 KBUILD_CFLAGS += -Wno-sign-compare
 KBUILD_CFLAGS += -Wno-format-zero-length
 KBUILD_CFLAGS += $(call cc-disable-warning, pointer-to-enum-cast)
```
unfortunately, this seems to dig up some other instances that GCC does not, so even with 
https://reviews.llvm.org/rL369791 we're still different. https://llvm.org/pr41467

x86_64 defconfig on linux-next has 11 instances of warnings via `-Wformat`.

**Comment by arndb** [comment] 2020-05-08 11:17
On Tue, May 5, 2020 at 2:11 AM Nick Desaulniers
<notifications@github.com> wrote:
>
> This is the patch I'd like to send for this:
>
> diff --git a/scripts/Makefile.extrawarn b/scripts/Makefile.extrawarn
> index 4aea7cf71d11..4b0c0664b838 100644
> --- a/scripts/Makefile.extrawarn
> +++ b/scripts/Makefile.extrawarn
> @@ -45,7 +45,11 @@ else
>
>  ifdef CONFIG_CC_IS_CLANG
>  KBUILD_CFLAGS += -Wno-initializer-overrides
> +# Clang < 10 was too strict about -Wformat. -Wformat-security is enabled by
> +# setting -Wformat, but we only want to enable it via W=1.
> +ifeq ($(shell test $(CONFIG_CLANG_VERSION) -lt 100000; echo $$?),0)
>  KBUILD_CFLAGS += -Wno-format
> +endif
>  KBUILD_CFLAGS += -Wno-sign-compare
>  KBUILD_CFLAGS += -Wno-format-zero-length
>  KBUILD_CFLAGS += $(call cc-disable-warning, pointer-to-enum-cast)
>
> unfortunately, this seems to dig up some other instances that GCC does not, so even with
> https://reviews.llvm.org/rL369791 we're still different. https://llvm.org/pr41467
>
> x86_64 defconfig on linux-next has 11 instances of warnings via -Wformat

I think number of files that show warnings in an allmodconfig build
would be more
important to list than the instances in defconfig.

I see 204 -Wformat warnings in 68 files on an x86 allmodconfig build with
clang-11, and they seem to all be the same kind of false positive, warning about
correct code:

      9  format specifies type 'char' but the argument has type 'int' [-Wformat]
      1  format specifies type 'char' but the argument has type 'u32'
(aka 'unsigned int') [-Wformat]
      3  format specifies type 'char' but the argument has type
'unsigned int' [-Wformat]
      2  format specifies type 'short' but the argument has type 'int'
[-Wformat]
      1  format specifies type 'unsigned char' but the argument has
type '__u16' (aka 'unsigned short') [-Wformat]
     20  format specifies type 'unsigned char' but the argument has
type 'int' [-Wformat]
      1  format specifies type 'unsigned char' but the argument has
type 's16' (aka 'short') [-Wformat]
      1  format specifies type 'unsigned char' but the argument has
type 's32' (aka 'int') [-Wformat]
     12  format specifies type 'unsigned char' but the argument has
type 'u16' (aka 'unsigned short') [-Wformat]
      4  format specifies type 'unsigned char' but the argument has
type 'u32' (aka 'unsigned int') [-Wformat]
      5  format specifies type 'unsigned char' but the argument has
type 'unsigned int' [-Wformat]
      1  format specifies type 'unsigned char' but the argument has
underlying type 'unsigned int' [-Wformat]
      2  format specifies type 'unsigned short' but the argument has
type '__u32' (aka 'unsigned int') [-Wformat]
     91  format specifies type 'unsigned short' but the argument has
type 'int' [-Wformat]
     27  format specifies type 'unsigned short' but the argument has
type 'u32' (aka 'unsigned int') [-Wformat]
     24  format specifies type 'unsigned short' but the argument has
type 'unsigned int' [-Wformat]

While it's possible to create a series of patches to fix them all up
(plus the ones that
are only seen in other configurations), I think a better workaround would be to
introduce a separate warning option in clang for the above that can be
turned off,
or just move them into -Wformat-pedantic like the subset from
https://llvm.org/pr41467

      Arnd

**Comment by nhukc** [comment] 2020-06-08 19:19
The warnings leftover look valid to me. They all truncate before printing which seems like unintended behavior. From here https://lore.kernel.org/r/CAHk-=wgoxnmsj8GEVFJSvTwdnWm8wVJthefNk2n6+4TC=20e0Q@mail.gmail.com/ it looks like Linus thinks that using "hh" specifiers on an int is bad style.

I filed https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95588

**Comment by nickdesaulniers** [comment] 2020-11-10 22:08
Discussion on the list is that we should do a treewide removal of `%h` and `%hh` format modifiers for print like functions.
https://lore.kernel.org/lkml/CAKwvOdku3o0nHhPppPOJzFXa3j1j_4r5ix3kbkduxY3YSpj9wg@mail.gmail.com/T/#m9795462050a04e8401a0ff4176760d189067316e

See also commit cbacb5ab0aa0 ("docs: printk-formats: Stop encouraging use of unnecessary %h[xudi] and %hh[xudi]").

**Comment by nickdesaulniers** [comment] 2020-12-02 22:40
Documentation in the kernel has been updated to reflect `%h` and `%hh` is frowned upon: https://lore.kernel.org/lkml/a68114afb134b8633905f5a25ae7c4e6799ce8f1.camel@perches.com/

Next up is separate efforts to add a warning to checkpatch.pl, and possibly leverage clang-tidy to help automate the removal of these format flags.

**Comment by nickdesaulniers** [comment] 2021-04-22 17:25
If I remove `KBUILD_CFLAGS += -Wno-format` from scripts/Makefile.extrawarn, I can repro, though for x86_64 defconfig, there's only 2 cases (net/ipv6/ah6.c:710, net/ipv6/esp6.c:1153)! But there are a lot more for ARCH=arm64 defconfig.

**Comment by nickdesaulniers** [comment] 2022-06-17 17:43
https://git.kernel.org/pub/scm/linux/kernel/git/akpm/mm.git/commit/?h=mm-nonmm-unstable&id=d30dfd490f7dc4cb6a7c11a647bd1ff7a22139e7 (accepted) will help with a bunch of calls to `ntohs` being passed to `printk`-like functions.

**Comment by nathanchance** [comment] 2022-08-10 19:41
Congratulations everyone!

https://git.kernel.org/linus/258fafcd0683d9ccfa524129d489948ab3ddc24c

**Comment by nickdesaulniers** [comment] 2022-08-11 16:57
Reverted by Linus: https://git.kernel.org/linus/21f9c8a13bb2a0c24d9c6b86bc0896542a28c197

Update: Shorten link (dileks)

**Comment by nickdesaulniers** [comment] 2022-08-19 23:29
https://github.com/llvm/llvm-project/issues/57102 is the upstream report.

I've also posted https://reviews.llvm.org/D132266 to discuss feasibility of moving these to `-Wformat-pedantic`.

Should that be accepted, I would first send https://lore.kernel.org/linux-kbuild/20220716084532.2324050-1-youngmin.nam@samsung.com/ in a series that then wrapped that in an `if clang version >= 16` check re-enabling `-Wformat` else at least enable `-Wformat-insufficient-args`.

**Comment by nathanchance** [comment] 2022-08-19 23:41
> Should that be accepted, I would first send https://lore.kernel.org/linux-kbuild/20220716084532.2324050-1-youngmin.nam@samsung.com/ in a series that then wrapped that in an `if clang version >= 16` check re-enabling `-Wformat` else at least enable `-Wformat-insufficient-args`.

Ah, that is a decent workaround. It might be interesting to see if we could enable all the other sub warnings of `-Wformat`.

**Comment by nickdesaulniers** [comment] 2022-08-24 22:59
https://reviews.llvm.org/D132568 is probably a better fix.

@nathanchance had question regarding which flags were in the `-Wformat` group.

https://github.com/llvm/llvm-project/blob/cff5bef948c91e4919de8a5fb9765e0edc13f3de/clang/include/clang/Basic/DiagnosticGroups.td#L934-L938 is the definition of the group.  Also, https://clang.llvm.org/docs/DiagnosticsReference.html#wformat which is generated from that source mentions:

Also controls `-Wformat-extra-args`, `-Wformat-insufficient-args`, `-Wformat-invalid-specifier`, `-Wformat-security`, `-Wformat-y2k`, `-Wformat-zero-length`, `-Wnonnull`.

The kernel already explicitly disables `-Wformat-security`, so that shouldn't be re-enabled.  https://clang.llvm.org/docs/DiagnosticsReference.html#wformat-y2k says that `-Wformat-y2k` does nothing in clang.

**Comment by inclyc** [comment] 2022-09-01 02:22
Thanks @nickdesaulniers ! I've landed https://reviews.llvm.org/D132568 in https://github.com/llvm/llvm-project/commit/e3bd67eddf65b20956513e91715b1f997dae2690 :)

**Comment by nickdesaulniers** [comment] 2022-09-01 17:48
Thanks @inclyc !

I'm working on a kernel patch for this.  Looks like `-Wformat-insufficient-args` is clang-12+...

**Comment by nickdesaulniers** [comment] 2022-09-01 18:01
Once more unto the breach! https://lore.kernel.org/lkml/20220901175913.2183047-1-ndesaulniers@google.com/

**Comment by nathanchance** [comment] 2022-09-04 23:46
https://git.kernel.org/linus/b0839b281c427e844143dba3893e25c83cdd6c17

Congrats everyone, round 2 ;)

**Closed** 2022-09-04 23:46 UTC
Labels: enhancement, [BUG] linux, [PATCH] Submitted, -Wformat, Reported upstream

**Comment by bwendling** [comment] 2022-10-11 08:44
Thank you! This was an annoying one I found.

-bw
