### ISSUE TITLE
-Wconstant-conversion in sound/i2c/cs8427.c

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#117] opened 2018-09-19 05:20 UTC
```
sound/i2c/cs8427.c:140:31: warning: implicit conversion from 'int' to 'char' changes value from 160 to -96 [-Wconstant-conversion]
        data[0] = CS8427_REG_AUTOINC | CS8427_REG_CORU_DATABUF;
                ~ ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

**Comment by nathanchance** [comment] 2018-10-18 17:14
Marking as duplicate of #227.

**Closed by nathanchance** 2018-10-18 17:14 UTC
Labels: -Wconstant-conversion, [BUG] linux, low priority

**Comment by bulwahn** [comment] 2018-10-18 17:19
Philipp Klocke provided this patch upstream:

https://lore.kernel.org/patchwork/patch/1001458/
