### ISSUE TITLE
Memory exhausted with integrated assembler

### ISSUE THREAD

**Issue by gwelymernans** [ClangBuiltLinux/linux#21] opened 2018-06-21 18:49 UTC
The following compilation:

```bash
$ clang-7 cc1as -triple x86_64-unknown-linux-gnu -filetype obj \
  -main-file-name aesni-intel_avx-x86_64.S -target-cpu x86-64 \
  -dwarf-version=4 -mrelocation-model static -debug-info-kind=limited \
  -dwarf-version=2 -o test.bc test.s
```

eventually runs out of memory. It seems like the `.rep` bits are being replicated over and over and over...

**Comment by gwelymernans** [comment] 2018-06-21 18:50
Erm, there doesn't seem to be a way to upload an example file. It's `aesni-intel_avx-x86_64.S` in the Linux source tree.

**Comment by nickdesaulniers** [comment] 2018-06-22 07:13
@niravhdave might be interested in this case.  Let me see if I can provide a preprocessed reproduction case.

**Comment by nickdesaulniers** [comment] 2018-07-17 23:42
I can confirm the infinite loop

1. in `arch/x86/Makefile` comment out the three lines checking `CC_HAVE_ASM_GOTO`
2. in `Makefile` comment out the two lines setting `-no-integrated-as`.

**Comment by niravhdave** [comment] 2018-07-18 16:23
This looks like a bug in the macro parsing code with using .rep in a macro body. I landed a fix upstream (r337398).

**Comment by nickdesaulniers** [comment] 2018-07-18 19:47
https://reviews.llvm.org/rL337398

ah nice thanks for a super fast fix, @niravhdave ! Will pull down and verify.

**Comment by nickdesaulniers** [comment] 2018-07-24 22:00
huh, I thought I could repro the loop.  With the latest build of clang-7, I see:

```sh
$ make CC=~/llvm/build/bin/clang-7 -j46 arch/x86/crypto/aesni-intel_avx-x86_64.o
...
  AS      arch/x86/crypto/aesni-intel_avx-x86_64.o
arch/x86/crypto/aesni-intel_avx-x86_64.S:126:1: warning: DWARF2 only supports one section per compilation unit
.section .rodata.cst16.POLY, "aM", @progbits, 16
^
arch/x86/crypto/aesni-intel_avx-x86_64.S:130:1: warning: DWARF2 only supports one section per compilation unit
.section .rodata.cst16.POLY2, "aM", @progbits, 16
^
arch/x86/crypto/aesni-intel_avx-x86_64.S:134:1: warning: DWARF2 only supports one section per compilation unit
.section .rodata.cst16.TWOONE, "aM", @progbits, 16
^
arch/x86/crypto/aesni-intel_avx-x86_64.S:138:1: warning: DWARF2 only supports one section per compilation unit
.section .rodata.cst16.SHUF_MASK, "aM", @progbits, 16
^
arch/x86/crypto/aesni-intel_avx-x86_64.S:142:1: warning: DWARF2 only supports one section per compilation unit
.section .rodata.cst16.ONE, "aM", @progbits, 16
^
arch/x86/crypto/aesni-intel_avx-x86_64.S:146:1: warning: DWARF2 only supports one section per compilation unit
.section .rodata.cst16.ONEf, "aM", @progbits, 16
^
arch/x86/crypto/aesni-intel_avx-x86_64.S:152:1: warning: DWARF2 only supports one section per compilation unit
.section .rodata, "a", @progbits
^
<unknown>:0: error: expression could not be evaluated
<unknown>:0: error: expression could not be evaluated
scripts/Makefile.build:417: recipe for target 'arch/x86/crypto/aesni-intel_avx-x86_64.o' failed
```

I suppose that error is coming from llvm/lib/MC/MCFragment.cpp#MCAsmLayout::getBaseSymbol() but it's odd that the line information is unknown.

**Comment by nickdesaulniers** [comment] 2018-07-24 22:46
printing the symbol names when unrecognized, it seems that `reg_i` and `reg_j` are problematic. `lib/MC/ELFObjectWriter.ccp#ELFWriter::isInSymtab()` has a fixme for the case `Symbol.isVariable() && Symbol.isUndefined()`.

**Comment by tpimh** [comment] 2018-09-19 07:07
Was it fixed? I can't reproduce it now.

**Comment by nickdesaulniers** [comment] 2018-09-23 23:05
Sorry, I haven't had time to try to repro.  Let's close for now and file a new bug if there's more issues with Clang's integrated assembler [IA] on x86_64.

**Closed by nickdesaulniers** 2018-09-23 23:05 UTC
Labels: [BUG] llvm, [PATCH] Exists, integrated-as
