### ISSUE TITLE
"fixup value out of range" with arm64 allmodconfig + ThinLTO with kCFI

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1730] opened 2022-10-04 20:10 UTC
With `ARCH=arm64 allmodconfig` + `CONFIG_LTO_CLANG_THIN=y`, I am seeing the following error:

```
$ echo 'CONFIG_GCOV_KERNEL=n
CONFIG_KASAN=n
CONFIG_KCSAN=n
CONFIG_LTO_CLANG_THIN=y' >allmod.config

$ make -skj"$(nproc)" ARCH=arm64 KCONFIG_ALLCONFIG=1 LLVM=1 mrproper allmodconfig all
ld.lld: error: <unknown>:0: fixup value out of range
```

CI sees it as well: https://builds.tuxbuild.com/2FfABo3KfBJufRjc1cSwHmRiBpd/build.log

As you can see, the error is pretty helpful :)

If I turn off `CONFIG_CFI_CLANG`, the build succeeds:

```
$ echo 'CONFIG_CFI_CLANG=y
CONFIG_GCOV_KERNEL=n
CONFIG_KASAN=n
CONFIG_KCSAN=n
CONFIG_LTO_CLANG_THIN=y' >allmod.config

$ make -skj"$(nproc)" ARCH=arm64 KCONFIG_ALLCONFIG=1 LLVM=1 mrproper allmodconfig all
```

cc @samitolvanen

**Comment by samitolvanen** [comment] 2022-10-04 20:15
Thanks for the report. It's in `drivers/misc/habanalabs/habanalabs.o`, it seems.

**Comment by nathanchance** [comment] 2022-10-04 20:18
It would pay to read my build logs fully :/ Indeed, this can just be reproduced with:

```
$ echo 'CONFIG_GCOV_KERNEL=n
CONFIG_KASAN=n
CONFIG_KCSAN=n
CONFIG_LTO_CLANG_THIN=y' >allmod.config

$ make -skj"$(nproc)" ARCH=arm64 KCONFIG_ALLCONFIG=1 LLVM=1 mrproper allmodconfig drivers/misc/habanalabs/habanalabs.o
ld.lld: error: <unknown>:0: fixup value out of range

make[4]: *** [scripts/Makefile.build:460: drivers/misc/habanalabs/habanalabs.o] Error 1
make[4]: Target '__build' not remade because of errors.
make[3]: *** [scripts/Makefile.build:525: drivers/misc/habanalabs] Error 2
make[3]: Target '__build' not remade because of errors.
make[2]: *** [scripts/Makefile.build:525: drivers/misc] Error 2
make[2]: Target '__build' not remade because of errors.
make[1]: *** [Makefile:1995: drivers] Error 2
make[1]: Target 'drivers/misc/habanalabs/habanalabs.o' not remade because of errors.
make: *** [Makefile:362: __build_one_by_one] Error 2
make: Target 'mrproper' not remade because of errors.
make: Target 'allmodconfig' not remade because of errors.
make: Target 'drivers/misc/habanalabs/habanalabs.o' not remade because of errors.
```

I can `cvise` something out.

**Comment by samitolvanen** [comment] 2022-10-04 20:26
Curiously the second attempt works for me, but if I delete `.thinlto-cache`, it fails again.
```
$ ld.lld -EL  -maarch64elf -z norelro --thinlto-cache-dir=.thinlto-cache -mllvm -import-instr-limit=5 -z noexecstack   -r -o drivers/misc/habanalabs/habanalabs.o @drivers/misc/habanalabs/habanalabs.mod
ld.lld: error: <unknown>:0: fixup value out of range

$ ld.lld -EL  -maarch64elf -z norelro --thinlto-cache-dir=.thinlto-cache -mllvm -import-instr-limit=5 -z noexecstack   -r -o drivers/misc/habanalabs/habanalabs.o @drivers/misc/habanalabs/habanalabs.mod
$ rm -rf .thinlto-cache/
$ ld.lld -EL  -maarch64elf -z norelro --thinlto-cache-dir=.thinlto-cache -mllvm -import-instr-limit=5 -z noexecstack   -r -o drivers/misc/habanalabs/habanalabs.o @drivers/misc/habanalabs/habanalabs.mod
ld.lld: error: <unknown>:0: fixup value out of range

```

**Comment by samitolvanen** [comment] 2022-10-04 21:06
Dropping `--thinlto-cache-dir=.thinlto-cache` allows me to reproduce this every time.

The error occurs while processing fixups for `gaudi_mmu_prepare`, which has 712 indirect calls as `gaudi_mmu_prepare_reg` is inlined and the `WREG32_*` macros each generate an indirect call to `hl_wreg`.

As a quick test, adding `noinline` to `gaudi_mmu_prepare_reg` fixes the issue, but probably isn't ideal. I'll have to take a closer look a bit later to see what exactly goes sideways here.

**Comment by nathanchance** [comment] 2022-10-05 01:56
Yup, that is exactly it. Here is the reproducer that `cvise` spat out for me:

https://gist.github.com/nathanchance/58b087f6b18ce44451382f24e1aa1d69

```
$ clang -flto=thin -fsanitize=kcfi -O2 --target=aarch64-linux-gnu -c -o gaudi.{o,i}

$ ld.lld -EL -maarch64elf -r -o /dev/null gaudi.o
ld.lld: error: <unknown>:0: fixup value out of range
```

**Comment by samitolvanen** [comment] 2022-10-05 22:29
> Yup, that is exactly it. Here is the reproducer that `cvise` spat out for me:

Thanks for reducing this! Using the reproducer I could also trigger the issue without LTO, which simplified debugging quite a bit. The problem is that we end up emitting a `tbnz` instruction that jumps to a label that's out of range (i.e. >32kB away).

Normally, out of range `tbnz` instructions should be fixed in the branch relaxation pass, but the `KCFI_CHECK` pseudo instruction was missing size information, so the relaxation pass thought it was only 4 bytes long instead of the actual 24 bytes, and therefore failed to notice the problem.

https://reviews.llvm.org/rG43f4c215a1a2 should fix this.

**Closed as completed by samitolvanen** 2022-10-05 22:29 UTC
Labels: [FEATURE] LTO, [FEATURE] CFI, [BUG] llvm (main), [FIXED][LLVM] main, [CONFIG] allmodconfig
