### ISSUE TITLE
-Wconstant-conversion in sound/i2c/cs8427

### ISSUE THREAD

**Issue by KillPinguin** [ClangBuiltLinux/linux#227] opened 2018-10-18 10:14 UTC
Compiling sound/i2c/cs8427.c with clang gives the following warning

```
sound/i2c/cs8427.c:141:31: warning: implicit conversion from 'int' to 'char' changes value from 160 to -96 [-Wconstant-conversion]
        data[0] = CS8427_REG_AUTOINC | CS8427_REG_CORU_DATABUF;
                ~ ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
```

where data is a `char data[32];` and `CS8427_REG_AUTOINC` defined as `0x80`=`128` and thus too big for a (signed) char.

I've sent in an RFC that supported my thoughts and a patch which was not addressed yet.

**Comment by nathanchance** [comment] 2018-10-18 17:13
Thanks for the issue! This is a duplicate of #117 but I'll close that one because this one has a little bit more info.

Patch just for reference: https://lore.kernel.org/lkml/20181018103303.30226-1-philipp97kl@gmail.com/

I'll link the accepted version when it shows up in Takashi's tree or -next (or you can, not trying to step on toes here), thanks for the contribution :)

**Comment by nathanchance** [comment] 2018-10-25 17:43
Merged into mainline: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=eb7ebfa3c1989aa8e59d5e68ab3cddd7df1bfb27

**Closed by nathanchance** 2018-10-25 17:43 UTC
Labels: -Wconstant-conversion, [BUG] linux, [PATCH] Accepted
