### ISSUE TITLE
Clang fails to build Linux for `ARCH=i386`: `error: invalid output size for constraint '=q'`

### ISSUE THREAD

**Issue by paulmenzel** [ClangBuiltLinux/linux#1075] opened 2020-07-04 10:26 UTC
Using Debian Sid/unstable with

    $ clang --version
    clang version 10.0.0-4 
    Target: x86_64-pc-linux-gnu
    Thread model: posix
    InstalledDir: /usr/bin

building Linux master (5.8-rc3+) fails with the error below.

```
$ make bindeb-pkg -j32 ARCH=i386 CC=clang-
[…]
In file included from arch/x86/events/amd/core.c:12:
arch/x86/events/amd/../perf_event.h:854:  AS      arch/x86/crypto/crc32-pclmul_asm.o
21: error: invalid output size for constraint '=q'
  AR      drivers/phy/samsung/built-in.a
        u64 disable_mask = __this_cpu_read(cpu_hw_events.perf_ctr_virt_mask);
                           ^
./include/linux/percpu-defs.h:446:2: note: expanded from macro '__this_cpu_read'
        raw_cpu_read(pcp);                                              \
        ^
./include/linux/percpu-defs.h:420:28: note: expanded from macro 'raw_cpu_read'
#define raw_cpu_read(pcp)               __pcpu_size_call_return(raw_cpu_read_, pcp)
                                        ^
./include/linux/percpu-defs.h:321:23: note: expanded from macro '__pcpu_size_call_return'
        case 1: pscr_ret__ = stem##1(variable); break;                  \
                             ^
<scratch space>:201:1: note: expanded from here
raw_cpu_read_1
^
./arch/x86/include/asm/percpu.h:394:30: note: expanded from macro 'raw_cpu_read_1'
#define raw_cpu_read_1(pcp)             percpu_from_op(, "mov", pcp)
                                        ^
./arch/x86/include/asm/percpu.h:189:15: note: expanded from macro 'percpu_from_op'
                    : "=q" (pfo_ret__)                  \
                            ^
```

**Comment by nathanchance** [comment] 2020-07-04 17:59
Dupe of #194 but thank you for reporting!

**Closed by nathanchance** 2020-07-04 17:59 UTC
