### ISSUE TITLE
error: hardware TLS register is not supported for the arm sub-architecture

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1502] opened 2021-11-11 17:23 UTC
[Linaro's CI reported](https://lore.kernel.org/r/814585495.6773.1636629846970@jenkins.jenkins/) an error after https://github.com/llvm/llvm-project/commit/24772720c54500714e2d48b9109bb62d5867ad95:

```
$ make -skj"$(nproc)" ARCH=arm LLVM=1 distclean defconfig arch/arm/kernel/iwmmxt.o
clang-14: error: hardware TLS register is not supported for the arm sub-architecture
```

I assume this is expected? A simplifier reproducer:

```
$ touch test.S

$ clang --target=arm-linux-gnueabi -mtp=cp15 -march=armv7-a -c -o /dev/null test.S

$ clang --target=arm-linux-gnueabi -mtp=cp15 -march=armv7-a -Wa,-mcpu=iwmmxt -c -o /dev/null test.S
clang-14: error: hardware TLS register is not supported for the arm sub-architecture
```

It looks like the `-mcpu` to the integrated assembler has implications for parsing the triple?

cc @ardbiesheuvel

**Comment by ardbiesheuvel** [comment] 2021-11-11 19:17
Does this help?
```
diff --git a/arch/arm/kernel/Makefile b/arch/arm/kernel/Makefile
index ae295a3bcfef..7d114078b36d 100644
--- a/arch/arm/kernel/Makefile
+++ b/arch/arm/kernel/Makefile
@@ -83,6 +83,7 @@ obj-$(CONFIG_PERF_EVENTS)     += perf_regs.o perf_callchain.o
 obj-$(CONFIG_HW_PERF_EVENTS)   += perf_event_xscale.o perf_event_v6.o \
                                   perf_event_v7.o
 AFLAGS_iwmmxt.o                        := -Wa,-mcpu=iwmmxt
+CFLAGS_REMOVE_iwmmxt.o         := -mtp=cp15
 obj-$(CONFIG_ARM_CPU_TOPOLOGY)  += topology.o
 obj-$(CONFIG_VDSO)             += vdso.o
 obj-$(CONFIG_EFI)              += efi.o
```

**Comment by nathanchance** [comment] 2021-11-11 19:28
I think that wants to be `AFLAGS_REMOVE_...` since it is a `.S` file but yes, that resolves this particular error.

Our CI reports an additional instance for `aspeed_g5_defconfig`: https://github.com/ClangBuiltLinux/continuous-integration2/runs/4178290190?check_suite_focus=true

```
$ make -skj"$(nproc)" ARCH=arm LLVM=1 distclean aspeed_g5_defconfig all
clang-14: error: hardware TLS register is not supported for the armv6k sub-architecture
clang-14: error: hardware TLS register is not supported for the armv6k sub-architecture
make[2]: *** [scripts/Makefile.build:121: scripts/mod/devicetable-offsets.s] Error 1
make[2]: *** [scripts/Makefile.build:287: scripts/mod/empty.o] Error 1
...
```

**Comment by ardbiesheuvel** [comment] 2021-11-11 19:52
> I think that wants to be `AFLAGS_REMOVE_...` since it is a `.S` file but yes, that resolves this particular error.
> 
> Our CI reports an additional instance for `aspeed_g5_defconfig`: https://github.com/ClangBuiltLinux/continuous-integration2/runs/4178290190?check_suite_focus=true
> 
> ```
> $ make -skj"$(nproc)" ARCH=arm LLVM=1 distclean aspeed_g5_defconfig all
> clang-14: error: hardware TLS register is not supported for the armv6k sub-architecture
> clang-14: error: hardware TLS register is not supported for the armv6k sub-architecture

Ouch. That one is a bit trickier. The ARM ARM claims that the TLS register is only implemented on v7 and later, but in reality, the kernel already assumes they are there (and uses them) for ARMv6k as well.

I am leaning towards simply reverting this commit in LLVM instead of playing whack-a-mole with corner cases like these. Any thoughts? @nickdesaulniers

**Comment by ardbiesheuvel** [comment] 2021-11-11 20:31
Actually, the ARM1176JZF-S TRM (which implements ARMv6 with the k extension) documents the TLS registers as well:

https://developer.arm.com/documentation/ddi0301/h/system-control-coprocessor/system-control-processor-registers/c13--thread-and-process-id-registers

I don't think other implementations of ARMv6k exist to begin with, so this is something we could consider fixing in the compiler. However, I don't think the diagnostic is that valuable anyway, so I'd still prefer to just revert it.

**Comment by nickdesaulniers** [comment] 2021-11-16 17:53
Is it just assembler sources producing this warning?  That flag _can't_ influence codegen of assembler sources.  I wonder if we can not omit the error for assembler sources?

**Comment by nathanchance** [comment] 2021-11-16 17:59
No, I believe that this warning happens in C source files as well (as you can tell from the `aspeed_g5_defconfig` build, `scripts/mod/empty.c` errors).

**Comment by nickdesaulniers** [comment] 2021-11-17 00:29
`aspeed_g5_defconfig` sets:
```                                                                                                                                           
 351 CONFIG_CPU_32v6=y                                                                                                                                                          
 352 CONFIG_CPU_32v6K=y                                                                                                                                                         
 353 CONFIG_CPU_32v7=y
```
arch/arm/Makefile uses those to add 
```
 64 arch-$(CONFIG_CPU_32v7)   =-D__LINUX_ARM_ARCH__=7 -march=armv7-a                                                                                                            
 65 arch-$(CONFIG_CPU_32v6)   =-D__LINUX_ARM_ARCH__=6 -march=armv6                                                                                                              
...                                                                                                                                             
 69 arch-$(CONFIG_CPU_32v6K)  =-D__LINUX_ARM_ARCH__=6 -march=armv6k
```
building with `make ... V=1`, I only see `-march=armv6k` being passed to clang (when building `scripts/mod/devicetable-offsets.s` and `scripts/mod/empty.o`).  I wonder why we're not passing `-march=armv7-a`, which should be avoiding the error from clang?

I guess KBUILD is re-assigning to `arch-y`, so `-march=armv7-a` is getting overwritten by `-march=armv6k`. I guess that means that configs like `CONFIG_CPU_32v6` and `CONFIG_CPU_32v7` aren't mutually exclusive? Hmm...reading 23688e999eda70f1ce1c61a68b865b996e3c6c4c the kconfig for `CPU_V7` selects `CPU_32v6K`; I guess `CPU_V7` then is always compiled as `-march=armv6k`. I wonder if that's intentional? Do we have configs that are `CONFIG_CPU_32v7=y` but `CONFIG_CPU_32v6K=n` (or unset)? ie. is `-march=armv7-a` ever used from the assignment in arch/arm/Makefile?

> I don't think other implementations of ARMv6k exist to begin with, so this is something we could consider fixing in the compiler.

Perhaps clang should support `-mtp=cp15` for `-march=armv6k` and up? Right now, it seems there's a slight mismatch between the Kconfig for CURRENT_POINTER_IN_TPIDRURO which supports armv6k and up, vs clang which supports armv7 and up (for `-mtp=cp15`). 

I think we just need to modify `llvm::ARM::parseArch(Triple.getArchName()) != llvm::ARM::ArchKind::ARMV6T2` into:

`(llvm::ARM::parseArch(Triple.getArchName()) != llvm::ARM::ArchKind::ARMV6T2 || llvm::ARM::parseArch(Triple.getArchName()) != llvm::ARM::ArchKind::ARMV6K))` (or wrapped in a smaller helper function)?

> instead of playing whack-a-mole with corner cases like these

:nods:

Looking at llvm/include/llvm/Support/ARMTargetParser.def, there's also `llvm::ARM::ArchKind::{ARMV6|ARMV6K|ARMV6T2|ARMV6KZ|ARMV6M}` for v6 sub-arches.  So there's 5 cases for v6 that clang knows about today.  I think at the least, it's not too much to tighten up clang to match Kconfig (ie. at least check for `ARMV6K`). I don't see v6kz or v6m used in the kernel at this time.

**Comment by ardbiesheuvel** [comment] 2021-11-17 11:21
ARMv6KZ == ARMv6K + TrustZone extensions, and this distinction is not really relevant for the kernel as it (usually) only runs in non-secure.

The problem is that permitting ARMv6K + Thumb (!= Thumb2) in the check permits the use of -mtp=cp15 with Thumb1 codegen, which will currently hit an assert in the backend. In the kernel, this never happens because we only support Thumb2 and only on v7+ CPUs, but in the general case.

**Comment by nickdesaulniers** [comment] 2021-11-17 19:36
https://reviews.llvm.org/D114116

EDIT: the above fixes aspeed_g5_defconfig. For iwmmxt.o, `-Wa,-mcpu` seems to be setting the sub arch version to something else.

EDIT2: `-Wa,-mcpu=iwmmxt` seems to be setting the sub arch version number to 0! oops! Even if it didn't, iwmmxt would be armv5te which would still be problematic.

EDIT3: https://reviews.llvm.org/D114124 disables the diagnostic for asm sources.

**Comment by nathanchance** [comment] 2021-12-03 21:26
The latest revision of D114116 resolves the `aspeed_g5_defconfig` breakage and does not introduce anything new, tested against [Ard's `arm-up-ti-in-task-v3` branch](https://git.kernel.org/pub/scm/linux/kernel/git/ardb/linux.git/log/?h=arm-up-ti-in-task-v3) (2cedab86cc9a797163eb2b1b828bbdc1f6b9c228). Ard's change to `arch/arm/kernel/Makefile` (`AFLAGS_REMOVE_iwmmxt.o := -mtp=cp15`) is still needed without D114124.

<details><summary>Build results</summary>
<p>

```
arm32 multi_v5_defconfig successful in 0:00:21

arm32 multi_v5_defconfig qemu boot successful

arm32 aspeed_g5_defconfig successful in 0:00:28

arm32 aspeed_g5_defconfig qemu boot successful

arm32 multi_v7_defconfig successful in 0:00:36

arm32 multi_v7_defconfig qemu boot successful

arm32 multi_v7_defconfig + CONFIG_THUMB2_KERNEL=y successful in 0:00:35

arm32 multi_v7_defconfig + CONFIG_THUMB2_KERNEL=y qemu boot successful

arm32 allmodconfig successful in 0:15:35

arm32 allnoconfig successful in 0:00:29

arm32 tinyconfig successful in 0:00:25

armv7 alpine config successful in 0:04:34

armv7 alpine config qemu boot successful

armv5 archlinux config successful in 0:03:48

armv7 archlinux config + CONFIG_EXTRA_FIRMWARE=n successful in 0:07:46

armv7 archlinux config qemu boot successful

arm32 debian config + CONFIG_SYSTEM_TRUSTED_KEYS=n successful in 0:12:05

arm32 debian config qemu boot successful

armv7hl fedora config + CONFIG_BPF_PRELOAD=n (https://github.com/ClangBuiltLinux/linux/issues/1433) successful in 0:15:31

armv7hl opensuse config successful in 0:10:33

armv7hl opensuse config qemu boot successful
```

</p>
</details>

**Comment by nathanchance** [comment] 2021-12-05 20:59
The latest revision of D114124 on top of LLVM @ https://github.com/llvm/llvm-project/commit/296ebeb808a71e44a64e0f805cffc6e3a3bf6182 resolves the error with `iwmmxt.o` and does not introduce any new failures against [Ard's `arm-up-ti-in-task-v4` branch](https://git.kernel.org/pub/scm/linux/kernel/git/ardb/linux.git/log/?h=arm-up-ti-in-task-v4) (0181a032905db85ea1f7a190af50e55e45a207b8).

<details><summary>Build results</summary>
<p>

```
arm32 multi_v5_defconfig successful in 0:01:28

arm32 multi_v5_defconfig qemu boot successful

arm32 aspeed_g5_defconfig successful in 0:01:21

arm32 aspeed_g5_defconfig qemu boot successful

arm32 multi_v7_defconfig successful in 0:03:27

arm32 multi_v7_defconfig qemu boot successful

arm32 multi_v7_defconfig + CONFIG_THUMB2_KERNEL=y successful in 0:03:26

arm32 multi_v7_defconfig + CONFIG_THUMB2_KERNEL=y qemu boot successful

arm32 allmodconfig + CONFIG_WERROR=n successful in 0:15:39

arm32 allnoconfig successful in 0:00:29

arm32 tinyconfig successful in 0:00:26

armv7 alpine config successful in 0:04:40

armv7 alpine config qemu boot successful

armv5 archlinux config successful in 0:03:53

armv7 archlinux config + CONFIG_EXTRA_FIRMWARE=n successful in 0:07:51

armv7 archlinux config qemu boot successful

arm32 debian config + CONFIG_SYSTEM_TRUSTED_KEYS=n successful in 0:08:24

arm32 debian config qemu boot successful

armv7hl fedora config + CONFIG_BPF_PRELOAD=n (https://github.com/ClangBuiltLinux/linux/issues/1433) successful in 0:09:08

armv7hl opensuse config successful in 0:10:30

armv7hl opensuse config qemu boot successful
```

</p>
</details>

**Comment by nathanchance** [comment] 2021-12-20 17:33
Our CI [just reported this error](https://github.com/ClangBuiltLinux/continuous-integration2/runs/4582653129?check_suite_focus=true) on `next-20211220` with a version of LLVM that definitely includes https://github.com/llvm/llvm-project/commit/73ee4e1cbd643028d63200f05199a128609aba5f. It appears to be related to `CROSS_COMPILE=arm-linux-gnueabihf-`, which `tuxmake` sets.

```
$ clang --version
Ubuntu clang version 14.0.0-++20211219032450+3a3fcd6a23ad-1~exp1~20211219152530.177
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin

$ make -skj"$(nproc)" ARCH=arm LLVM=1 distclean aspeed_g5_defconfig all
...

$ make -skj"$(nproc)" ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- LLVM=1 distclean aspeed_g5_defconfig all
clang: error: hardware TLS register is not supported for the armv6k sub-architecture
clang: error: hardware TLS register is not supported for the armv6k sub-architecture
clang: error: hardware TLS register is not supported for the armv6k sub-architecture
...
```

Is this expected?

**Comment by ardbiesheuvel** [comment] 2021-12-20 17:43
This is definitely not expected. The ARM v6k sub-architecture is the one that introduced the TLS registers to begin with, so the diagnostic is wrong by definition.

**Comment by nickdesaulniers** [comment] 2021-12-22 21:31
I wasn't able to reproduce this on mainline or next-20211222 with llvm @ 32e8b30d6e67352040ffef54fb0e4b3a69242a4a.

Could this be another out of tree patch that Debian is applying to llvm?

**Comment by nathanchance** [comment] 2021-12-22 21:48
This one looks suspicious, I will confirm in a bit.

https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/-/blob/snapshot/debian/patches/930008-arm.diff

Comes as a result of https://bugs.debian.org/930008.

However, we pass `-march=armv6k` so I am not that should impact it.

**Comment by nathanchance** [comment] 2021-12-22 22:30
Yes, that patch is the culprit. This diff on top of ToT LLVM reproduces the error with `next-20211222` (you need to use -next to see it, mainline does not have the `-mtp=cp15` flag in it yet).

```diff
diff --git a/clang/test/Driver/arm-mfpu.c b/clang/test/Driver/arm-mfpu.c
index c9bbe0aa1b3f..360cbf4573fe 100644
--- a/clang/test/Driver/arm-mfpu.c
+++ b/clang/test/Driver/arm-mfpu.c
@@ -347,14 +347,6 @@
 // CHECK-NO-FP-DAG: "-target-feature" "-sha2"
 // CHECK-NO-FP-DAG: "-target-feature" "-aes"

-// RUN: %clang -target arm-linux-gnueabihf %s -### 2>&1 \
-// RUN:   | FileCheck --check-prefix=CHECK-HF %s
-// RUN: %clang -target arm-linux-musleabihf %s -### 2>&1 \
-// RUN:   | FileCheck --check-prefix=CHECK-HF %s
-// CHECK-HF-NOT: "-target-feature" "+soft-float"
-// CHECK-HF-NOT: "-target-feature" "+soft-float-abi"
-// CHECK-HF-DAG: "-target-cpu" "arm1176jzf-s"
-
 // RUN: %clang -target armv7-apple-darwin -x assembler %s -### -c 2>&1 \
 // RUN:   | FileCheck --check-prefix=ASM %s
 // ASM-NOT: -target-feature
diff --git a/llvm/lib/Support/Triple.cpp b/llvm/lib/Support/Triple.cpp
index 2819dc0c139a..a4e39db795ce 100644
--- a/llvm/lib/Support/Triple.cpp
+++ b/llvm/lib/Support/Triple.cpp
@@ -1786,7 +1786,7 @@ StringRef Triple::getARMCPUForArch(StringRef MArch) const {
     case llvm::Triple::EABIHF:
     case llvm::Triple::GNUEABIHF:
     case llvm::Triple::MuslEABIHF:
-      return "arm1176jzf-s";
+      return "cortex-a7";
     default:
       return "arm7tdmi";
     }
```

I am not quite sure why that changes anything given that we pass in `-march=armv6k` but there must be some code path that I am not seeing.

**Comment by nathanchance** [comment] 2021-12-22 22:37
Something weird is going on though because adjusting the test from `// CHECK-HF-DAG: "-target-cpu" "arm1176jzf-s"` to `// CHECK-HF-DAG: "-target-cpu" "cortex-a7"` does not work like I thought it would. Prior to that patch:

```
$ clang -target arm-linux-gnueabihf clang/test/Driver/arm-mfpu.c -###
... "-triple" "armv6kz-unknown-linux-gnueabihf" ... "-target-cpu" "arm1176jzf-s" ...
```

But after:

```
$ build/stage1/bin/clang -target arm-linux-gnueabihf clang/test/Driver/arm-mfpu.c -###
... "-triple" "armv7-unknown-linux-gnueabihf" ... "-target-cpu" "generic" ...
```

**Comment by nathanchance** [comment] 2021-12-23 18:33
I ended up bisecting -next because I found it odd that there was no error on `next-20211217` but there was on `next-20211220` and I landed on commit [f05eb1d24eb5](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=f05eb1d24eb564488014d90b31824f71984d7ef5) ("ARM: stackprotector: prefer compiler for TLS based per-task protector"). I think I see what is going on here.

With Debian's LLVM, `CONFIG_STACKPROTECTOR_PER_TASK` gets enabled because the flags are tested without an `-march` option and `arm-linux-gnueabihf` means `armv7` now, instead of `armv6kz`:

```
$ rg CONFIG_STACKPROTECTOR .config
458:CONFIG_STACKPROTECTOR_PER_TASK=y
568:CONFIG_STACKPROTECTOR=y
569:CONFIG_STACKPROTECTOR_STRONG=y
```

Constrast with upstream LLVM:

```
$ rg CONFIG_STACKPROTECTOR .config
566:CONFIG_STACKPROTECTOR=y
567:CONFIG_STACKPROTECTOR_STRONG=y
```

When the build starts though, `-march=armv6k` gets added to the mix and everything explodes.

Debian's LLVM:

```
$ echo | clang --target=arm-linux-gnueabihf -mstack-protector-guard=tls -mstack-protector-guard-offset=1304 -x c -c -o /dev/null -

$ echo | clang --target=arm-linux-gnueabihf -march=armv6k -mstack-protector-guard=tls -mstack-protector-guard-offset=1304 -x c -c -o /dev/null -
clang: error: hardware TLS register is not supported for the armv6k sub-architecture
```

Upstream LLVM:

```
$ echo | clang --target=arm-linux-gnueabihf -mstack-protector-guard=tls -mstack-protector-guard-offset=1304 -x c -c -o /dev/null -
clang-14: error: hardware TLS register is not supported for the armv6kz sub-architecture

$ echo | clang --target=arm-linux-gnueabihf -march=armv6k -mstack-protector-guard=tls -mstack-protector-guard-offset=1304 -x c -c -o /dev/null -
clang: error: hardware TLS register is not supported for the armv6k sub-architecture
```

I think that Kconfig test needs to be refined because as it stands now, I don't think there is a way for `CONFIG_STACKPROTECTOR_PER_TASK` to be enabled for `clang` (it does not get enabled with `multi_v7_defconfig`), even though `clang-14` appears to support it:

```
$ echo | clang --target=arm-linux-gnueabihf -march=armv7 -mstack-protector-guard=tls -mstack-protector-guard-offset=1304 -x c -c -o /dev/null -
```

**Comment by nickdesaulniers** [comment] 2021-12-23 19:19
ah, the two places where `diag::err_target_unsupported_tp_hard` could be emitted got out of sync. We should be able to reuse the code here. Something like:
```diff
diff --git a/clang/lib/Driver/ToolChains/Clang.cpp b/clang/lib/Driver/ToolChains/Clang.cpp
index 2a3723975568..ae2a5a9d7fca 100644
--- a/clang/lib/Driver/ToolChains/Clang.cpp
+++ b/clang/lib/Driver/ToolChains/Clang.cpp
@@ -3217,9 +3217,7 @@ static void RenderSSPOptions(const Driver &D, const ToolChain &TC,
         return;
       }
       // Check whether the target subarch supports the hardware TLS register
-      if (arm::getARMSubArchVersionNumber(EffectiveTriple) < 7 &&
-          llvm::ARM::parseArch(EffectiveTriple.getArchName()) !=
-              llvm::ARM::ArchKind::ARMV6T2) {
+      if (!arm::isHardTPSupported(EffectiveTriple)) {
         D.Diag(diag::err_target_unsupported_tp_hard)
             << EffectiveTriple.getArchName();
         return;
```

**Comment by nickdesaulniers** [comment] 2021-12-23 20:16
@nathanchance can you please help test https://reviews.llvm.org/D116233 (with and w/o [debian's patch](https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/-/blob/snapshot/debian/patches/930008-arm.diff))?

**Comment by nathanchance** [comment] 2021-12-23 20:49
@nickdesaulniers Yes, my builds are running right now. The three defconfigs pass without any issues with `CROSS_COMPILE=arm-linux-gnueabihf`, with or without Debian's patch. I will report back if there are any breakages with `allmodconfig` or the distro configs.

**Comment by nathanchance** [comment] 2021-12-23 22:11
@nickdesaulniers All builds pass against `next-20211223`.

<details><summary>Without Debian's diff</summary>
<p>

```
arm32 multi_v5_defconfig successful in 0:01:27

arm32 multi_v5_defconfig qemu boot successful

arm32 aspeed_g5_defconfig successful in 0:01:20

arm32 aspeed_g5_defconfig qemu boot successful

arm32 multi_v7_defconfig successful in 0:03:27

arm32 multi_v7_defconfig qemu boot successful

arm32 allmodconfig + CONFIG_WERROR=n successful in 0:15:31

arm32 allnoconfig successful in 0:00:29

arm32 tinyconfig successful in 0:00:24

armv7 alpine config successful in 0:04:34

armv7 alpine config qemu boot successful

armv5 archlinux config successful in 0:03:48

armv7 archlinux config + CONFIG_EXTRA_FIRMWARE=n successful in 0:07:43

armv7 archlinux config qemu boot successful

arm32 debian config + CONFIG_SYSTEM_TRUSTED_KEYS=n successful in 0:08:19

arm32 debian config qemu boot successful

armv7hl fedora config + CONFIG_BPF_PRELOAD=n (https://github.com/ClangBuiltLinux/linux/issues/1433) successful in 0:09:01

armv7hl opensuse config successful in 0:10:20

armv7hl opensuse config qemu boot successful
```

</p>
</details>

<details><summary>With Debian's patch</summary>
<p>

```
arm32 multi_v5_defconfig successful in 0:00:17

arm32 multi_v5_defconfig qemu boot successful

arm32 aspeed_g5_defconfig successful in 0:00:25

arm32 aspeed_g5_defconfig qemu boot successful

arm32 multi_v7_defconfig successful in 0:00:29

arm32 multi_v7_defconfig qemu boot successful

arm32 allmodconfig + CONFIG_WERROR=n successful in 0:03:15

arm32 allnoconfig successful in 0:00:11

arm32 tinyconfig successful in 0:00:10

armv7 alpine config successful in 0:00:47

armv7 alpine config qemu boot successful

armv5 archlinux config successful in 0:00:26

armv7 archlinux config + CONFIG_EXTRA_FIRMWARE=n successful in 0:00:54

armv7 archlinux config qemu boot successful

arm32 debian config + CONFIG_SYSTEM_TRUSTED_KEYS=n successful in 0:01:19

arm32 debian config qemu boot successful

armv7hl fedora config + CONFIG_BPF_PRELOAD=n (https://github.com/ClangBuiltLinux/linux/issues/1433) successful in 0:01:31

armv7hl opensuse config successful in 0:02:22

armv7hl opensuse config qemu boot successful
```

</p>
</details>

I could also see `CONFIG_STACKPROTECTOR_PER_TASK=y` in configs where it was not present prior to your change.

**Closed as completed** 2021-12-28 21:28 UTC
Labels: [BUG] llvm (main), [Reported-by] Linaro TCWG CI, [FIXED][LLVM] 14
