### ISSUE TITLE
-Wunused-variable in drivers/video/fbdev/omap2/omapfb/dss/core.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#409] opened 2019-03-01 18:25 UTC
via KernelCI:
```
    1    drivers/video/fbdev/omap2/omapfb/dss/core.c:172:6: warning: unused variable 'r' [-Wunused-variable]
```
maybe leftover from https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/drivers/video/fbdev/omap2/omapfb/dss/core.c?id=60d2fa0dad0687b4d227aacc042ccdbea1782d87
cc @gregkh

**Comment by nathanchance** [comment] 2019-03-01 18:27
Dupe of #362.

**Closed by nathanchance** 2019-03-01 18:27 UTC
Labels: [BUG] linux-next, good first issue, low priority

**Comment by nickdesaulniers** [comment] 2019-03-01 18:30
gah! sorry (I miss bugzilla's feature that shows pre-existing bugs that look similar to the one you're filing).

**Comment by kragniz** [comment] 2019-03-01 18:33
@nickdesaulniers there's a beta feature for that I just enabled 
![2019-03-01-183121_761x242_scrot](https://user-images.githubusercontent.com/735008/53658354-6caf7880-3c50-11e9-9ab4-b21d28716ba0.png)

**Comment by tpimh** [comment] 2019-03-20 13:53
I don't think duplicate bugs should have warning labels.
