### ISSUE TITLE
Clang 18.0.0: Linux 6.1 and 6.6 giving unused-variable warnings despite used attribute

### ISSUE THREAD

**Issue by myxoid** [ClangBuiltLinux/linux#1977] opened 2024-01-10 19:20 UTC
These are actually Android Common Kernel branches, but I've no reason to suspect things will be different on other trees.

Switching from Clang 17 to 18 results in new, unexpected warnings and, with `-Werror`, builds fail.

6.1: https://android-review.googlesource.com/c/kernel/common/+/2875956
6.6: https://android-review.googlesource.com/c/kernel/common/+/2875957
mainline (https://android.googlesource.com/kernel/common/+/32f6c6538caedab053cfb60e0e7d0e6d7e8e6659): https://android-review.googlesource.com/c/kernel/common/+/2875955

The kernels are built in a variety of configurations (including for different architectures).

The failures have in common is the use of `__attribute__((__used__))` via `__used`.

A typical failure for x86_64 looks like (note that `__ADDRESSABLE` uses `__used`):

```
In file included from /mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/107/execroot/__main__/common/arch/x86/kernel/asm-offsets.c:9:
In file included from /mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/107/execroot/__main__/common/include/linux/crypto.h:15:
In file included from /mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/107/execroot/__main__/common/include/linux/completion.h:12:
In file included from /mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/107/execroot/__main__/common/include/linux/swait.h:7:
In file included from /mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/107/execroot/__main__/common/include/linux/spinlock.h:95:
In file included from /mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/107/execroot/__main__/common/arch/x86/include/asm/spinlock.h:10:
/mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/107/execroot/__main__/common/arch/x86/include/asm/paravirt.h:31:9: error: unused variable '__UNIQUE_ID___addressable___SCK__pv_sched_clock39' [-Werror,-Wunused-variable]
   31 |         return static_call(pv_sched_clock)();
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/107/execroot/__main__/common/include/linux/static_call_types.h:90:27: note: expanded from macro 'static_call'
   90 | #define static_call(name)       __static_call(name)
      |                                 ^~~~~~~~~~~~~~~~~~~
/mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/107/execroot/__main__/common/include/linux/static_call_types.h:57:2: note: expanded from macro '__static_call'
   57 |         __STATIC_CALL_ADDRESSABLE(name);                                \
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/107/execroot/__main__/common/include/linux/static_call_types.h:53:2: note: expanded from macro '__STATIC_CALL_ADDRESSABLE'
   53 |         __ADDRESSABLE(STATIC_CALL_KEY(name))
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 3 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/107/execroot/__main__/common/include/linux/compiler_types.h:84:22: note: expanded from macro '__PASTE'
   84 | #define __PASTE(a,b) ___PASTE(a,b)
      |                      ^~~~~~~~~~~~~
/mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/107/execroot/__main__/common/include/linux/compiler_types.h:83:23: note: expanded from macro '___PASTE'
   83 | #define ___PASTE(a,b) a##b
      |                       ^~~~
<scratch space>:159:1: note: expanded from here
  159 | __UNIQUE_ID___addressable___SCK__pv_sched_clock39
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Wheres for aarch64:

```
In file included from /mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/arch/arm64/kernel/asm-offsets.c:10:
In file included from /mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/include/linux/arm_sdei.h:8:
In file included from /mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/include/acpi/ghes.h:5:
In file included from /mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/include/acpi/apei.h:9:
In file included from /mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/include/linux/acpi.h:13:
In file included from /mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/include/linux/resource_ext.h:11:
In file included from /mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/include/linux/slab.h:16:
In file included from /mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/include/linux/gfp.h:7:
In file included from /mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/include/linux/mmzone.h:8:
In file included from /mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/include/linux/spinlock.h:59:
In file included from /mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/include/linux/irqflags.h:17:
In file included from /mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/arch/arm64/include/asm/irqflags.h:10:
In file included from /mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/arch/arm64/include/asm/ptrace.h:11:
In file included from /mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/arch/arm64/include/asm/cpufeature.h:26:
In file included from /mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/include/linux/cpumask.h:16:
/mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/include/linux/numa.h:34:2: warning: unused variable '_entry_ptr' [-Wunused-variable]
   34 |         pr_info_once("Unknown online node for memory at 0x%llx, assuming node 0\n",
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   35 |                         start);
      |                         ~~~~~~
/mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/include/linux/printk.h:617:2: note: expanded from macro 'pr_info_once'
  617 |         printk_once(KERN_INFO pr_fmt(fmt), ##__VA_ARGS__)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/include/linux/printk.h:594:15: note: expanded from macro 'printk_once'
  594 |         DO_ONCE_LITE(printk, fmt, ##__VA_ARGS__)
      |         ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/include/linux/once_lite.h:11:24: note: expanded from macro 'DO_ONCE_LITE'
   11 |         DO_ONCE_LITE_IF(true, func, ##__VA_ARGS__)
      |         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
note: (skipping 1 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/include/linux/printk.h:455:26: note: expanded from macro 'printk'
  455 | #define printk(fmt, ...) printk_index_wrap(_printk, fmt, ##__VA_ARGS__)
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/include/linux/printk.h:426:3: note: expanded from macro 'printk_index_wrap'
  426 |                 __printk_index_emit(_fmt, NULL, NULL);                  \
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/disks/build-disk/src/android/common-android-mainline/out/bazel/output_user_root/5eb738bf612d494239553bcc21fe7c03/sandbox/linux-sandbox/6/execroot/__main__/common/include/linux/printk.h:395:34: note: expanded from macro '__printk_index_emit'
  395 |                         static const struct pi_entry *_entry_ptr        \
      |                                                       ^~~~~~~~~~
```

**Comment by nathanchance** [comment] 2024-01-10 19:53
This is a duplicate of https://github.com/ClangBuiltLinux/linux/issues/1926.

It seems that Android's LLVM updated to a version that includes https://github.com/llvm/llvm-project/commit/92023b15099012a657da07ebf49dd7d94a260f84, which was reverted upstream in https://github.com/llvm/llvm-project/commit/f0f395e00e2ec3f1f20ca9021d1554fde73d56c9 for this reason (and as far as I can tell, it was never landed again?).

Android's LLVM team should be informed about this.

**Closed as not planned by nathanchance** 2024-01-10 19:53 UTC
Labels: duplicate

**Comment by myxoid** [comment] 2024-01-10 19:54
I'm trying to see if I can reproduce on a boring vanilla 6.7.

Just saw your update. I'm part of the team. I'll let Nick Desaulniers know.
