### ISSUE TITLE
[riscv] clang: error: unknown argument: '-mno-save-restore'

### ISSUE THREAD

**Issue by martell** [ClangBuiltLinux/linux#277] opened 2018-11-22 03:32 UTC
these flags are used in building of the linux kernel

```
  UPD     include/generated/utsrelease.h
  CC      kernel/bounds.s
  HOSTLD  scripts/dtc/dtc
clang: error: unknown argument: '-mno-save-restore'
make[1]: *** [Kbuild:21: kernel/bounds.s] Error 1
```
support needs to be added to clang?
https://github.com/riscv/riscv-toolchain-conventions#todo
the conventions seem incomplete?

Added @asb here to see if some context can be shared.
https://github.com/ClangBuiltLinux/continuous-integration/pull/70

**Comment by tpimh** [comment] 2018-11-23 05:59
Duplicate of #75. Is it submitted to LLVM bugzilla?

**Closed by tpimh** 2018-11-23 05:59 UTC
Labels: [ARCH] risc-v, [BUG] Untriaged
