### ISSUE TITLE
Modpost error with SND_SOC_CS35L45 and ThinLTO on 6.4.1 and LLVM-17-git

### ISSUE THREAD

**Issue by ms178** [ClangBuiltLinux/linux#1882] opened 2023-07-01 22:00 UTC
While [upgrading my Kernel to 6.4.1](https://github.com/ms178/archpkgbuilds/commit/fb61b79532f3cc8b5cca83eb3791d438a7fe76dd), I've seen a new Modpost error when compiling the Kernel with LLVM-17 (clang version 17.0.0 (c1dc914a8ca240650d7411d25c75ad7e2a5974e9) and my usual set of flags that used to work fine with 6.3.10 and an earlier llvm-git revision. I was also using a PGO-profile from an earlier Kernel.

Disabling the module below successfully worked around the issue. 

```
# CONFIG_SND_SOC_CS35L45 is not set
# CONFIG_SND_SOC_CS35L45_SPI is not set
# CONFIG_SND_SOC_CS35L45_I2C is not set
```

**Comment by nathanchance** [comment] 2023-07-03 15:45
What is the error?

Is it reproducible without PGO? Without your compiler flag additions?

**Comment by ms178** [comment] 2023-07-03 19:16
This is all the output I get in the console:
```
  AR      drivers/gpu/built-in.a
  AR      drivers/built-in.a
  AR      built-in.a
  AR      vmlinux.a
  GEN     .tmp_initcalls.lds
  LD      vmlinux.o
  OBJCOPY modules.builtin.modinfo
  GEN     modules.builtin
  MODPOST Module.symvers
ERROR: modpost: "devm_regmap_add_irq_chip" [sound/soc/codecs/snd-soc-cs35l45.ko] undefined!
ERROR: modpost: "regmap_irq_get_virq" [sound/soc/codecs/snd-soc-cs35l45.ko] undefined!
make[1]: *** [scripts/Makefile.modpost:136: Module.symvers] error 1
make: *** [Makefile:1979: modpost] error 2
```

And I've just reproduced it without any additional Cflags nor the PGO-profile.

Here is the config that fails: 
[config.txt](https://github.com/ClangBuiltLinux/linux/files/11940472/config.txt)

**Comment by nathanchance** [comment] 2023-07-03 20:00
Not a clang problem, I can reproduce it with GCC. I am getting ready to submit a patch, would you like me to include your name and email for a `Reported-by:` tag, so that you get propercredit for reporting this.? If so, please let me know what to put. Regardless, I will include a `Link:` back to this issue, so that it can get tracked somehow.

**Comment by ms178** [comment] 2023-07-03 21:12
Thanks for letting me know, here is the requested info for the credit: Marcus Seyfarth <m.seyfarth@gmail.com>

**Comment by nathanchance** [comment] 2023-07-03 21:45
Thanks a lot! I have sent https://lore.kernel.org/20230703-cs35l45-select-regmap_irq-v1-1-37d7e838b614@kernel.org/ just now. Since this is not a clang specific issue, I am going to close it up here. That patch should be picked up for 6.4 once it makes it into Linus's tree automatically.

**Closed as completed by nathanchance** 2023-07-03 21:45 UTC
