### ISSUE TITLE
-Wframe-larger-than in drivers/gpu/drm/amd/display/dc/dml/dcn314/display_mode_vba_314.c (only clang 16)

### ISSUE THREAD

**Issue by vadorovsky** [ClangBuiltLinux/linux#1917] opened 2023-08-16 07:52 UTC
I'm getting the following errors when both the latest stable kernel (6.4.10) and mainline:

```
drivers/gpu/drm/amd/amdgpu/../display/dc/dml/dcn31/display_mode_vba_31.c:3797:6: error: stack frame size (2536) exceeds limit (2048) in 'dml31_ModeSupportAndSystemConfigurationFull' [-Werror,-Wframe-larger-than]
void dml31_ModeSupportAndSystemConfigurationFull(struct display_mode_lib *mode_lib)
     ^
1369/2536 (53.98%) spills, 1167/2536 (46.02%) variables
```
```
drivers/gpu/drm/amd/amdgpu/../display/dc/dml/dcn314/display_mode_vba_314.c:3892:6: error: stack frame size (2536) exceeds limit (2048) in 'dml314_ModeSupportAndSystemConfigurationFull' [-Werror,-Wframe-larger-than]
void dml314_ModeSupportAndSystemConfigurationFull(struct display_mode_lib *mode_lib)
     ^
1352/2536 (53.31%) spills, 1184/2536 (46.69%) variables
```

It happens only with clang 16, the workaround for me was to use clang 15 instead.

(Happy to look at that and try to fix myself if nobody beats me up to it.)

**Comment by nathanchance** [comment] 2023-08-16 14:29
Thanks for the report, this is a duplicate of https://github.com/ClangBuiltLinux/linux/issues/1754, so let's continue over there. Could you comment in that issue with the configuration that triggers this (since I cannot get it to trigger with either LLVM 16.0.6 or 18.0.0 and the configurations that were listed in that thread) and see if applying [this series](https://lore.kernel.org/20230110154325.3350916-1-Rodrigo.Siqueira@amd.com/) helps? You can either use [`b4`](https://pypi.org/project/b4/)'s `am` or `shazam` command or you could use something like this `bash` one-liner:

```bash
for num in $(seq 2 10); do curl -LSs https://lore.kernel.org/all/20230110154325.3350916-"$num"-Rodrigo.Siqueira@amd.com/raw | git am || break; done
```

**Closed as not planned by nathanchance** 2023-08-16 14:29 UTC
Labels: duplicate

**Comment by vadorovsky** [comment] 2023-08-17 14:52
Sorry for opening a redundant issue and thanks for quick reply!

Actually I pulled the latest master (on Linus' tree) and it works, After brief look at git log I think that I got changes from [this series](https://lore.kernel.org/all/20230605183007.204399-1-hamza.mahfooz@amd.com/), which was mainlined.

I hope it gets included in the next stable release.

If I have any further problems, I will let you know in 1754 and include the config.
