### ISSUE TITLE
__lshrti3 after LLVM commit 273c299d5d649a0222fbde03c9a41e41913751b4

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/linux#1177] opened 2020-10-16 08:15 UTC
https://github.com/llvm/llvm-project/commit/273c299d5d649a0222fbde03c9a41e41913751b4

I discovered this while building my WSL2 kernel. Reduction below.

```
$ make -skj"$(nproc)" LLVM=1 distclean defconfig

$ scripts/config -e HYPERVISOR_GUEST -e PARAVIRT

$ make -skj"$(nproc)" LLVM=1 olddefconfig bzImage
...
ld.lld: error: undefined symbol: __lshrti3
>>> referenced by vmware.c
>>>               kernel/cpu/vmware.o:(vmware_cyc2ns_setup) in archive arch/x86/built-in.a
...
```

```
$ git bisect log
# bad: [1eb2c6d23f991a16afaaf898aeaf8f78e97be6fc] [SCEV][NFC] Split out type balancing in implication engine
# good: [400103f3d5f1f1d3e7dd02531f9db71a049ac507] [yaml2obj/obj2yaml] - Add support of 'Size' and 'Content' keys for all sections.
git bisect start '1eb2c6d23f991a16afaaf898aeaf8f78e97be6fc' '400103f3d5f1f1d3e7dd02531f9db71a049ac507'
# good: [6abc15ae3c245b6043f15d3cdedfad187888dfd5] [libc++] Reduce dependencies on <iostream> from <random>
git bisect good 6abc15ae3c245b6043f15d3cdedfad187888dfd5
# good: [1992e30c2d751f6f1f6ad5190f84e37dece04f7f] [WebAssembly] Prototype i8x16.popcnt
git bisect good 1992e30c2d751f6f1f6ad5190f84e37dece04f7f
# good: [609d765cd3b1a4f9558b654dbb1bc7c973f3408b] [AArch64][GlobalISel] NFC: Refactor emitIntegerCompare
git bisect good 609d765cd3b1a4f9558b654dbb1bc7c973f3408b
# bad: [6771b98c4e4d5c0bd0a78a876bd212a76ec80a24] [mlir][CAPI] Add mlirAttributeGetType function.
git bisect bad 6771b98c4e4d5c0bd0a78a876bd212a76ec80a24
# bad: [fc031d29bea856f2b91a250fd81c5f9fb79dbe07] Switch the default of VerifyIntegerConstantExpression from constant folding to not constant folding.
git bisect bad fc031d29bea856f2b91a250fd81c5f9fb79dbe07
# bad: [2bf423b0218c9583e3a372950a34facbf93e63d3] [mlir] RewriterGen NativeCodeCall matcher with ConstantOp matcher
git bisect bad 2bf423b0218c9583e3a372950a34facbf93e63d3
# bad: [273c299d5d649a0222fbde03c9a41e41913751b4] [PM/CC1] Add -f[no-]split-cold-code CC1 option to toggle splitting
git bisect bad 273c299d5d649a0222fbde03c9a41e41913751b4
# first bad commit: [273c299d5d649a0222fbde03c9a41e41913751b4] [PM/CC1] Add -f[no-]split-cold-code CC1 option to toggle splitting
```

cvise spits out with [this interestingness test](https://github.com/nathanchance/creduce-files/blob/8d7291ae9b0c6dedcc8f6022836ebd6c26ec5a35/D57265/test.sh):

```
int a, b, c;
__attribute__((__cold__)) void d() { c = (unsigned __int128)a >> b; }
```

The full preprocessed source can be viewed [here](https://github.com/nathanchance/creduce-files/tree/8d7291ae9b0c6dedcc8f6022836ebd6c26ec5a35/D57265).

No idea whose bug this is, this is just the initial information.

**Comment by nathanchance** [comment] 2020-10-18 02:12
Looks like this issue has been relevant before: https://lore.kernel.org/lkml/CAG5bF+S6OvBnsaR6UpMCqjDR9_hMo6qRMHGiW+iCaRYQW4C3YA@mail.gmail.com/

**Comment by davidbolvansky** [comment] 2020-10-19 08:06
This is trunk regression.
https://godbolt.org/z/ba3aqo

https://llvm.org/pr47897

**Comment by nickdesaulniers** [comment] 2020-10-19 17:38
@davidbolvansky I suspect this is bigger than just `__lshrti3`.  For example:
1. [our CI is pretty red for x86](https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/builds/190923127) but there's two reports of `__lshrti3` ([0](https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/401920242), [1](https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/401920244) but two reports of `__ashldi3` ([0](https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/401920201), [1](https://travis-ci.com/github/ClangBuiltLinux/continuous-integration/jobs/401920214)).
2. CrOS builds their kernels with AutoFDO, which can mark any function as cold.  If the CL in question regressed this is related to `cold` function attributes, then there may be a whole lot of breakage across the kernel for a major Linux distro's whose configuration we're not testing (because we don't have the AutoFDO profile data).

> https://godbolt.org/z/ba3aqo

If you change the clang-11 invocation to pass `-Oz` instead of `-O3`, you'll get the same result as trunk but `-Os` will not.  I think the upstream LLVM change should optimize cold code at `-Os`, not `-Oz`.

**Comment by nickdesaulniers** [comment] 2020-10-19 17:38
Looks like it was just reverted: https://reviews.llvm.org/D57265#2338207

**Comment by nickdesaulniers** [comment] 2020-10-19 18:05
Closing for now; it was reverted, and there's now three reports upstream (on the phab review) pointing to various problems.

**Closed by nickdesaulniers** 2020-10-19 18:05 UTC
Labels: Reported upstream, [BUG] llvm (master), [FIXED][LLVM] master

**Comment by nickdesaulniers** [comment] 2020-10-19 18:10
@m-gupta reports CrOS' 4.4 x86_64 is failing with `__lshrti3`, but in a different translation unit: `arch/x86/kvm/x86.c`. Might be due to a difference in configs, or from AFDO profiles.
