### ISSUE TITLE
-Wnon-literal-null-conversion in drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#314] opened 2019-01-17 21:27 UTC
```
drivers/gpu/drm/amd/amdgpu/../display/amdgpu_dm/amdgpu_dm.c:4535:3: warning: 
      expression which evaluates to zero treated as a null pointer constant of type
      'const enum color_transfer_func *' [-Wnon-literal-null-conversion]
                TRANSFER_FUNC_UNKNOWN,
                ^~~~~~~~~~~~~~~~~~~~~
```

mainline x86_64 allyesconfig.

**Comment by nathanchance** [comment] 2019-01-17 21:48
Dupe of #284.

**Closed by nathanchance** 2019-01-17 21:48 UTC
Labels: [ARCH] x86_64, [BUG] linux
