### ISSUE TITLE
-Wswitch in drivers/scsi/smartpqi/smartpqi_init.c

### ISSUE THREAD

**Issue by tpimh** [ClangBuiltLinux/linux#154] opened 2018-09-20 14:28 UTC
```
drivers/scsi/smartpqi/smartpqi_init.c:5610:7: warning: overflow converting case value
      to switch condition type (3227009547 to 18446744072641593867) [-Wswitch]
        case CCISS_PASSTHRU:
             ^
./include/uapi/linux/cciss_ioctl.h:78:27: note: expanded from macro 'CCISS_PASSTHRU'
#define CCISS_PASSTHRU     _IOWR(CCISS_IOC_MAGIC, 11, IOCTL_Command_struct)
                           ^
./include/uapi/asm-generic/ioctl.h:88:29: note: expanded from macro '_IOWR'
#define _IOWR(type,nr,size)     _IOC(_IOC_READ|_IOC_WRITE,(type),(nr),(_IOC_TYPECHECK(size)))
                                ^
./include/uapi/asm-generic/ioctl.h:70:2: note: expanded from macro '_IOC'
        (((dir)  << _IOC_DIRSHIFT) | \
        ^
drivers/scsi/smartpqi/smartpqi_init.c:5607:7: warning: overflow converting case value
      to switch condition type (2147762697 to 18446744071562347017) [-Wswitch]
        case CCISS_GETDRIVVER:
             ^
./include/uapi/linux/cciss_ioctl.h:76:28: note: expanded from macro 'CCISS_GETDRIVVER'
#define CCISS_GETDRIVVER   _IOR(CCISS_IOC_MAGIC, 9, DriverVer_type)
                           ^
./include/uapi/asm-generic/ioctl.h:86:28: note: expanded from macro '_IOR'
#define _IOR(type,nr,size)      _IOC(_IOC_READ,(type),(nr),(_IOC_TYPECHECK(size)))
                                ^
./include/uapi/asm-generic/ioctl.h:70:2: note: expanded from macro '_IOC'
        (((dir)  << _IOC_DIRSHIFT) | \
        ^
drivers/scsi/smartpqi/smartpqi_init.c:5604:7: warning: overflow converting case value
      to switch condition type (2148024833 to 18446744071562609153) [-Wswitch]
        case CCISS_GETPCIINFO:
             ^
./include/uapi/linux/cciss_ioctl.h:65:26: note: expanded from macro 'CCISS_GETPCIINFO'
#define CCISS_GETPCIINFO _IOR(CCISS_IOC_MAGIC, 1, cciss_pci_info_struct)
                         ^
./include/uapi/asm-generic/ioctl.h:86:28: note: expanded from macro '_IOR'
#define _IOR(type,nr,size)      _IOC(_IOC_READ,(type),(nr),(_IOC_TYPECHECK(size)))
                                ^
./include/uapi/asm-generic/ioctl.h:70:2: note: expanded from macro '_IOC'
        (((dir)  << _IOC_DIRSHIFT) | \
        ^
3 warnings generated.
```

**Comment by nickdesaulniers** [comment] 2018-10-03 08:16
[All](https://github.com/ClangBuiltLinux/linux/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A-Wswitch+) of our `-Wswitch` warnings go through `_IOC`.  Where there's smoke, there's fire.

**Comment by nathanchance** [comment] 2018-10-19 17:58
Patch sent: https://lore.kernel.org/lkml/20181019175714.444-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment] 2018-10-20 05:04
Patch v2: https://lore.kernel.org/lkml/20181020050143.589-1-natechancellor@gmail.com/

**Comment by nathanchance** [comment] 2019-01-14 05:07
Patch v3: https://lore.kernel.org/lkml/20190114044206.6351-1-natechancellor@gmail.com/

**Comment by nickdesaulniers** [comment] 2019-01-14 20:51
marking a dupe of #85 , since the same patch addresses both.

**Closed by nickdesaulniers** 2019-01-14 20:51 UTC
Labels: -Wswitch, [BUG] linux, [PATCH] Submitted, low priority
