### ISSUE TITLE
clang ias: failure in arch/arm/include/asm/futex.h

### ISSUE THREAD

**Issue by arndb** [ClangBuiltLinux/linux#1273] opened 2021-01-27 20:46 UTC
Not sure what causes this one yet:

/git/arm-soc/arch/arm/include/asm/futex.h:117:3: error: invalid instruction, did you mean: strt?
        "2:     " TUSER(streq) "        %4, [%2]\n"
         ^
<inline asm>:6:4: note: instantiated into assembly here
2:      streqt  r8, [r7]
        ^~~~~~
In file included from /git/arm-soc/kernel/futex.c:45:
/git/arm-soc/arch/arm/include/asm/futex.h:118:2: error: incorrect condition in IT block; got 'al', but expected 'eq'
        __futex_atomic_ex_table("%5")
        ^
/git/arm-soc/arch/arm/include/asm/futex.h:19:3: note: expanded from macro '__futex_atomic_ex_table'
        "4:     mov     %0, " err_reg "\n"                      \
         ^
<inline asm>:14:7: note: instantiated into assembly here
4:      mov     r4, r0
           ^

**Comment by arndb** [comment] 2021-01-27 20:47
Presumably this is caused by CONFIG_CPU_USE_DOMAINS

**Comment by arndb** [comment] 2021-01-28 08:01
I'll send this fix:

```diff
diff --git a/arch/arm/include/asm/futex.h b/arch/arm/include/asm/futex.h
index 7ec86418fcef..7766d89cea77 100644
--- a/arch/arm/include/asm/futex.h
+++ b/arch/arm/include/asm/futex.h
@@ -114,7 +114,7 @@ futex_atomic_cmpxchg_inatomic(u32 *uval, u32 __user *uaddr,
        "1:     " TUSER(ldr) "  %1, [%2]\n"
        "       teq     %1, %3\n"
        "       it      eq      @ explicit IT needed for the 2b label\n"
-       "2:     " TUSER(streq) "        %4, [%2]\n"
+       "2:     " TUSERCOND(str, eq) "  %4, [%2]\n"
        __futex_atomic_ex_table("%5")
        : "+&r" (ret), "=&r" (val), "+&r" (uaddr)
        : "r" (oldval), "r" (newval), "Ir" (-EFAULT)

```

**Comment by nickdesaulniers** [comment] 2021-02-22 23:58
> Presumably this is caused by CONFIG_CPU_USE_DOMAINS

That is selected by multi_v5_defconfig, but I wasn't able to reproduce the observed failure.  Though based on the error message, that looks like a UAL source issue, so the kernel patch is likely good to go.  Especially after reading a6c9e96bf86b8aa86d8696b7887e52c2e95bac0f.

**Comment by arndb** [comment] 2021-02-23 16:19
This is a configuration that reproduces the problem for me:

[0x29D50AD0_defconfig.gz](https://github.com/ClangBuiltLinux/linux/files/6030251/0x29D50AD0_defconfig.gz)

**Comment by nickdesaulniers** [comment] 2021-02-26 01:04
huh, if I fetch that config, I still can't repro (I get some other linker error).  Can you spot what I'm doing wrong?
```sh
$ cd linux
$ wget https://github.com/ClangBuiltLinux/linux/files/6030251/0x29D50AD0_defconfig.gz
$ gunzip 0x29D50AD0_defconfig.gz
$ cp 0x29D50AD0_defconfig .config
$ ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- make LLVM=1 LLVM_IAS=1 -j72 clean olddefconfig
$ ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- make LLVM=1 LLVM_IAS=1 -j72
...
  LD      vmlinux.o
ld.lld: warning: lld uses blx instruction, no object with architecture supporting feature detected
  MODPOST vmlinux.symvers
  MODINFO modules.builtin.modinfo
  GEN     modules.builtin
  LD      .tmp_vmlinux.kallsyms1
ld.lld: warning: lld uses blx instruction, no object with architecture supporting feature detected
ld.lld: warning: <internal>:(.ARM.exidx) is being placed in '.ARM.exidx'
ld.lld: error: section .rodata virtual address range overlaps with .data
>>> .rodata range is [0xBFF92000, 0xC089A5F4]
>>> .data range is [0xC0208000, 0xC0494003]

ld.lld: error: section .bss virtual address range overlaps with __param
>>> .bss range is [0xC04D1000, 0xC0C9553B]
>>> __param range is [0xC089A5F8, 0xC089EFCB]
```
```
$ diff -u 0x29D50AD0_defconfig .config
```
does show a number of changes. Perhaps `olddefconfig` is messing this up? But our compiler version strings don't precisely match, so that restarts the command line prompts for new configs if I don't do `olddefconfig`.  Am I misunderstanding how `olddefconfig` works, perhaps?

**Comment by nickdesaulniers** [comment] 2021-02-26 01:04
(either way, the kernel patch looks correct to me, and can probably be sent)

**Comment by nickdesaulniers** [comment] 2021-09-08 18:45
closing as unreproducible. Please reopen if you see this again.

**Closed as completed by nickdesaulniers** 2021-09-08 18:45 UTC
Labels: [BUG] linux, [PATCH] Exists, [TOOL] integrated-as, [ARCH] arm32, unreproducible
