### ISSUE TITLE
ASM: expression could not be evaluated

### ISSUE THREAD

**Issue by gwelymernans** [ClangBuiltLinux/linux#410] opened 2019-03-01 19:09 UTC
I'm getting the error `expression could not be evaluated` with this code:

```
i = 0

.macro BAR r n
reg_\r = %xmm\n
.endm

.macro FOO
.altmacro
BAR i %i
.noaltmacro
.endm

        FOO
```

This is the command line:

```
clang  -nostdinc -Qunused-arguments -Wno-unknown-warning-option   -D__ASSEMBLY__ -m64  -mfentry         -c -o x.o xz.s
```

It's due to x86 not implementing `evaluateAsRelocatableImpl` (the expression being `%xmm0`).

**Comment by nickdesaulniers** [comment] 2019-03-01 22:47
cc @niravhdave @rupprecht

**Comment by niravhdave** [comment] 2019-03-04 18:42
We can reproduce with just: 

reg_i = %xmm0

What's happening is that we have a layout check in the ELFObjectWriter that causes an error for ambiguous symbols if they are unreferenced and unused, because it doesn't exprect symbols to be registers. I have a simple patch written and will have it upstreamed in the next day.

**Comment by niravhdave** [comment] 2019-03-04 19:42
Landed upstream @ rL355325

**Comment by nickdesaulniers** [comment] 2019-03-05 00:17
Thanks @niravhdave ! @gwelymernans please reopen if you can repro post r355325.

**Closed by nickdesaulniers** 2019-03-05 00:17 UTC
Labels: [ARCH] x86_64, [BUG] llvm, [FIXED][CLANG] 9
