### ISSUE TITLE
test building LoongArch

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/linux#1787] opened 2023-01-12 18:24 UTC
https://discourse.llvm.org/t/rfc-promoting-the-loongarch-backend-from-experimental-to-official/67506 claims:

> LLVM/Clang-16 is able to build many large programs for LoongArch, e.g.
Gcc, Binutils, **Linux**, ...

So it would be interesting to try this and see how well supported this combo is, and whether anything is missing.

**Comment by SixWeining** [comment] 2023-01-13 05:41
@nickdesaulniers Thanks. The upstream Linux needs to be patched to be built by clang. The changes mainly include:
- Add '$' prefix to register names in inline asm. See discussion: https://reviews.llvm.org/D136436. These files need to be patched:
arch/loongarch/include/asm/cmpxchg.h
arch/loongarch/include/asm/futex.h
arch/loongarch/include/asm/vdso/gettimeofday.h
- Fix some builtin invocation in `arch/loongarch/include/asm/loongarch.h`  to avoid clang error: `error: argument to '__builtin_xxx' must be a constant integer`. GCC doesn't report such error in -O1 or above when callee is inlined while Clang does. But this is not arch specific.

I will discuss with GCC/Linux LoongArch port's maintainers @ChenghuaXu @chenhuacai to confirm whehter the changes could be upstreamed.

**Comment by nickdesaulniers** [comment] 2023-01-13 18:00
> GCC doesn't report such error in -O1 or above when callee is inlined while Clang does. But this is not arch specific.

Right, clang will perform semantic analysis before optimizations; this can result in source code compiler portability issues.  See:
commit 158807de5822 ("x86/uaccess: Make __get_user_size() Clang compliant on 32-bit")
as an example.

**Comment by xen0n** [comment] 2023-01-14 10:43
Thanks very much for the attention. This is going to be valuable for future LoongArch users (particularly some enterprise or distro-building use cases but there are more), and I'll work with the `arch/loongarch` maintainers to ensure any necessary changes end up in the mainline. (I'm a reviewer for `arch/loongarch` code and helped the port's initial upstreaming.)

**Comment by nickdesaulniers** [comment] 2023-04-20 18:43
Any progress here?

**Comment by xen0n** [comment] 2023-04-21 18:40
I suppose the earlier verification with Linux was done with an earlier in-house version, that didn't make use of as many new features as the current HEAD does. The LoongArch community co-developed Linux and Binutils/GCC so there are a few new toolchain features that got added for Linux's needs, but similar support in LLVM has lagged behind a bit.

Current missing pieces in LLVM/Clang:

* missing support for [`-mdirect-extern-access`](https://github.com/gcc-mirror/gcc/commit/7742b797b3fd7acea28a0a0bff9bbb06e7c2d0ea) (may not matter)
* missing support for [variable attribute `model`](https://github.com/gcc-mirror/gcc/commit/362749184c4fa67ea0b2135d4cae8f1a13208b9d) and [code model `extreme`](https://github.com/gcc-mirror/gcc/commit/69458145262e4cef76410f5d42fe0d12b7c395fb) which is needed by the LoongArch percpu mechanism

Aside from the missing Clang features, some kernel changes are also necessary:

* `-G0` is used to disable emission of small-data sections, but currently not wired up for LoongArch in Clang (leading to unused argument error on `-G 0`; not including the argument in case of Clang is enough)
* `-msoft-float` takes precedence over `-mabi=lp64s` (leading to unused argument error on `-mabi=lp64s`; omitting `-mabi` in case of Clang is enough)
* `-mexplicit-relocs` is not needed (Clang behaves as expected from the very beginning)
* all `asm("xx")` need to become `asm("$xx")` due to not having [D136436](https://reviews.llvm.org/D136436) (as explained by @SixWeining earlier)
* CSR, IOCSR and CPUCFG helpers need slight tweaks (done, will be part of the Clang enablement patches; also covered earlier)

**Comment by xen0n** [comment] 2023-05-16 07:42
Some progress update:

* https://reviews.llvm.org/D136436 already merged
* https://reviews.llvm.org/D150417 for LP64S ABI support
* https://reviews.llvm.org/D150537 for correct output `e_flags` for assembly inputs
* https://reviews.llvm.org/D150522 one step closer to code model override support for percpu variables

**Comment by heiher** [comment] 2023-06-08 14:10
- Need to prevent optimization from eliminating `CSR`/`IOCSR` builtin ops without any data-dependency.

**Comment by xry111** [comment] 2023-06-17 09:48
> * Need to prevent optimization from eliminating `CSR`/`IOCSR` builtin ops without any data-dependency.

Done with https://reviews.llvm.org/D153120.

**Comment by xen0n** [comment] 2023-06-23 06:53
* `llvm-objcopy` needs adaptation: https://reviews.llvm.org/D153609
* The lld port (currently under review) needs to ignore `e_flags` of files that doesn't contain code, similar to what BFD does, to be able to link `vmlinuz.efi.elf`

With these LLVM bits patched and [this tree](https://github.com/xen0n/linux/commits/loong-clang), a build without `CONFIG_RELOCATABLE` and `CONFIG_MODULE` now works!

Remaining:

* `__attribute__((model("extreme")))` support in Clang for `CONFIG_MODULE`
* Investigate LLD's behavior difference in pre-populating the GOT to unbreak `CONFIG_RELOCATABLE`

**Comment by xen0n** [comment] 2023-06-24 18:52
[v2](https://lore.kernel.org/loongarch/20230624184055.3000636-1-kernel@xen0n.name/) of the enablement patches is sent. For minimal Linux-side modifications two more LLVM patches are needed:

* https://reviews.llvm.org/D150196 for allowing FP insns in `-msoft-float` translation units
* https://reviews.llvm.org/D153707 for silencing the "unused arguments" error when both `-mabi` and `-msoft-float` is present

**Comment by nathanchance** [comment] 2023-06-26 21:41
v3: https://lore.kernel.org/20230625095644.3156349-1-kernel@xen0n.name/

I can confirm that `ARCH=loongarch LLVM=1 defconfig` + `CONFIG_MODULES=n` + `CONFIG_RELOCATABLE=n` builds with that series on top of `next-20230626` using https://github.com/llvm/llvm-project/commit/7827beeebb5948c9edaedd679d9d2c9ff30df6ed + [D138135](https://reviews.llvm.org/D138135), although I did need the following diff to avoid erroring out in the vDSO (#1859):

```
clang: error: unsupported option '-mabi=' for target 'x86_64-pc-linux-gnu'
make[4]: *** [.../scripts/Makefile.build:370: arch/loongarch/vdso/vdso.lds] Error 1
```

```diff
diff --git a/arch/loongarch/vdso/Makefile b/arch/loongarch/vdso/Makefile
index ee4abcf5642e..19f6ea4b3fb4 100644
--- a/arch/loongarch/vdso/Makefile
+++ b/arch/loongarch/vdso/Makefile
@@ -16,11 +16,8 @@ ccflags-vdso := \
        $(filter -E%,$(KBUILD_CFLAGS)) \
        $(filter -march=%,$(KBUILD_CFLAGS)) \
        $(filter -m%-float,$(KBUILD_CFLAGS)) \
-       -D__VDSO__
-
-ifeq ($(cc-name),clang)
-ccflags-vdso += $(filter --target=%,$(KBUILD_CFLAGS))
-endif
+       -D__VDSO__ \
+       $(CLANG_FLAGS)

 cflags-vdso := $(ccflags-vdso) \
        -isystem $(shell $(CC) -print-file-name=include) \
```

which is basically applying [76d7fff22be3](https://git.kernel.org/linus/76d7fff22be3e4185ee5f9da2eecbd8188e76b2c) ("MIPS: VDSO: Use CLANG_FLAGS instead of filtering out '--target='") to `arch/loongarch` from `arch/mips`. Additionally, a variant of [08f6554ff90e](https://git.kernel.org/masahiroy/linux-kbuild/c/08f6554ff90ef189e6b8f0303e57005bddfdd6a7) ("mips: Include KBUILD_CPPFLAGS in CHECKFLAGS invocation") will be needed for `arch/loongarch` to avoid the same error after [feb843a469fb](https://git.kernel.org/masahiroy/linux-kbuild/c/feb843a469fb0ab00d2d23cfb9bcc379791011bb) ("kbuild: add $(CLANG_FLAGS) to KBUILD_CPPFLAGS") is merged into mainline.

**Comment by chenhuacai** [comment] 2023-06-27 04:02
Hi, Nathan,

On Tue, Jun 27, 2023 at 5:41 AM Nathan Chancellor ***@***.***>
wrote:

> v3: ***@***.***/
>
> I can confirm that ARCH=loongarch LLVM=1 defconfig + CONFIG_MODULES=n +
> CONFIG_RELOCATABLE=n builds with that series on top of next-20230626
> using ***@***.***
> <https://github.com/llvm/llvm-project/commit/7827beeebb5948c9edaedd679d9d2c9ff30df6ed>
> + D138135 <https://reviews.llvm.org/D138135>, although I did need the
> following diff to avoid erroring out in the vDSO (#1859
> <https://github.com/ClangBuiltLinux/linux/issues/1859>):
>
> clang: error: unsupported option '-mabi=' for target 'x86_64-pc-linux-gnu'
> make[4]: *** [.../scripts/Makefile.build:370: arch/loongarch/vdso/vdso.lds] Error 1
>
> diff --git a/arch/loongarch/vdso/Makefile b/arch/loongarch/vdso/Makefile
> index ee4abcf5642e..19f6ea4b3fb4 100644--- a/arch/loongarch/vdso/Makefile+++ b/arch/loongarch/vdso/Makefile@@ -16,11 +16,8 @@ ccflags-vdso := \
>         $(filter -E%,$(KBUILD_CFLAGS)) \
>         $(filter -march=%,$(KBUILD_CFLAGS)) \
>         $(filter -m%-float,$(KBUILD_CFLAGS)) \-       -D__VDSO__--ifeq ($(cc-name),clang)-ccflags-vdso += $(filter --target=%,$(KBUILD_CFLAGS))-endif+       -D__VDSO__ \+       $(CLANG_FLAGS)
>
>  cflags-vdso := $(ccflags-vdso) \
>         -isystem $(shell $(CC) -print-file-name=include) \
>
> which is basically applying 76d7fff22be3
> <https://git.kernel.org/linus/76d7fff22be3e4185ee5f9da2eecbd8188e76b2c>
> ("MIPS: VDSO: Use CLANG_FLAGS instead of filtering out '--target='") to
> arch/loongarch from arch/mips. Additionally, a variant of 08f6554ff90e
> <https://git.kernel.org/masahiroy/linux-kbuild/c/08f6554ff90ef189e6b8f0303e57005bddfdd6a7>
> ("mips: Include KBUILD_CPPFLAGS in CHECKFLAGS invocation") will be needed
> for arch/loongarch to avoid the same error after feb843a469fb
> <https://git.kernel.org/masahiroy/linux-kbuild/c/feb843a469fb0ab00d2d23cfb9bcc379791011bb>
> ("kbuild: add $(CLANG_FLAGS) to KBUILD_CPPFLAGS") is merged into mainline.
>
Can the modification of  08f6554ff90e
<https://git.kernel.org/masahiroy/linux-kbuild/c/08f6554ff90ef189e6b8f0303e57005bddfdd6a7>
be
added before  feb843a469fb
<https://git.kernel.org/masahiroy/linux-kbuild/c/feb843a469fb0ab00d2d23cfb9bcc379791011bb>?
Thanks.

Huacai

**Comment by nathanchance** [comment] 2023-06-27 04:35
> Can the modification of  08f6554ff90e
> 
> <https://git.kernel.org/masahiroy/linux-kbuild/c/08f6554ff90ef189e6b8f0303e57005bddfdd6a7>
> 
> be
> 
> added before  feb843a469fb
> 
> <https://git.kernel.org/masahiroy/linux-kbuild/c/feb843a469fb0ab00d2d23cfb9bcc379791011bb>?

Yes, it should be fine. I can send  a small series with those two changes on top of loongarch-next, since I see v3 has been applied. I can do it tomorrow.

**Comment by xen0n** [comment] 2023-06-27 04:46
> > Can the modification of  [08f6554](https://github.com/ClangBuiltLinux/linux/commit/08f6554ff90ef189e6b8f0303e57005bddfdd6a7)
> > https://git.kernel.org/masahiroy/linux-kbuild/c/08f6554ff90ef189e6b8f0303e57005bddfdd6a7
> > be
> > added before  [feb843a](https://github.com/ClangBuiltLinux/linux/commit/feb843a469fb0ab00d2d23cfb9bcc379791011bb)
> > https://git.kernel.org/masahiroy/linux-kbuild/c/feb843a469fb0ab00d2d23cfb9bcc379791011bb?
> 
> Yes, it should be fine. I can send a small series with those two changes on top of loongarch-next, since I see v3 has been applied. I can do it tomorrow.

Thanks! But I guess it would probably be more convenient for Huacai if we (Huacai and/or I) craft the series instead, because he seems to have to go through in-house integrations before updating `loongarch-next`, so how about we do it right away in UTC+8 working time so you could wake up to see everything integrated?

**Comment by nathanchance** [comment] 2023-06-27 04:49
> Thanks! But I guess it would probably be more convenient for Huacai if we (Huacai and/or I) craft the series instead, because he seems to have to go through in-house integrations before updating `loongarch-next`, so how about we do it right away in UTC+8 working time so you could wake up to see everything integrated?

Sure thing, I will never complain about having to do less work :) I’ll review whatever is sent my way.

**Comment by heiher** [comment] 2023-06-27 15:00
After [`jump-label`](https://lore.kernel.org/loongarch/1684118574-7572-1-git-send-email-tangyouling@loongson.cn/) is added to LoongArch, two more LLVM patches are needed:

- https://reviews.llvm.org/D153872 for generates valid relocation of jump-label
- https://reviews.llvm.org/D138135 supports new `R_LARCH_64_PCREL` relocation

**Comment by nathanchance** [comment] 2023-06-30 18:42
The initial LoongArch clang build support has been merged into mainline: https://git.kernel.org/linus/112e7e21519422b6f2bb0fa8061f5685e9757170

Should we mark this as resolved and open more specific tracking issues for:
- Getting this turned on in continuous integration (need `tuxmake` to support LoongArch first, I can look into this in next week)
- Implementing `__attribute__((model("extreme")))` for `CONFIG_MODULES=y`
- Getting `ld.lld` support merged
- Investigating what breaks `CONFIG_RELOCATABLE=y` with `ld.lld`

Am I missing anything?

**Comment by xry111** [comment] 2023-07-05 12:46
If it's difficult to implement `model` attribute, should we consider loading the main kernel image into XKVRANGE instead of XKPRANGE?  If we can load the main kernel image into XKVRANGE we can make the main kernel image and the modules altogether in a 2GB range, thus the "normal" code model will be sufficient.

And we are already building the kernel image as a PIE so I guess it might be not so difficult...

**Comment by xen0n** [comment] 2023-07-06 10:42
For the record, I [started a discussion](https://discourse.llvm.org/t/how-to-best-implement-code-model-overriding-for-certain-values/71816/) on how to best implement the `model` attribute over at the LLVM forums. Hairier than I originally expected but still kinda feasible, but of course any simplification of the picture would be appreciated.

**Comment by xen0n** [comment] 2023-07-06 10:49
> The initial LoongArch clang build support has been merged into mainline: https://git.kernel.org/linus/112e7e21519422b6f2bb0fa8061f5685e9757170
> 
> Should we mark this as resolved and open more specific tracking issues for:
> 
> * Getting this turned on in continuous integration (need `tuxmake` to support LoongArch first, I can look into this in next week)
> * Implementing `__attribute__((model("extreme")))` for `CONFIG_MODULES=y`
> * Getting `ld.lld` support merged
> * Investigating what breaks `CONFIG_RELOCATABLE=y` with `ld.lld`
> 
> Am I missing anything?

Seems that's a pretty complete picture! I'd be fine with closing this issue and tracking the follow-up work separately.

**Comment by nickdesaulniers** [comment] 2023-07-07 23:52
> I'd be fine with closing this issue and tracking the follow-up work separately.

As a member of @clangbuiltlinux, please feel empowered to do so. Make sure to use the loongarch label on relevant github issues, and consider linking to each individual issue. I prefer distinct issues filed to track each work item, if it makes sense to do so.

**Comment by nickdesaulniers** [comment] 2023-07-07 23:53
> need tuxmake to support LoongArch first, I can look into this in next week

I meant to do that [file an issue on tuxmake's gitlab] today, but gitlab was having an outtage this morning...

**Comment by xen0n** [comment] 2023-07-10 13:28
Hmm I just discovered I don't have issue triage permissions. Not in a hurry though, I created the follow-up issues anyway and I'll fix the labels / close this issue whenever the permissions are sorted out.

**Comment by xen0n** [comment] 2023-07-10 13:34
Regarding the review process of the `ld.lld` port: review activity has resumed, and all review comments are again addressed, so I still expect it to get merged before the LLVM 17 branch. I'll coordinate anyway should anything happen.

**Comment by nathanchance** [comment] 2023-07-10 16:51
> Hmm I just discovered I don't have issue triage permissions.

And I don't see how to give them to you :/ in the Organization settings, I see "Triage" as one of the pre-defined roles in the "Repository roles" section but I do not see it in the "Base permissions" drop down under the "Member privileges" section...

> I'll fix the labels / close this issue whenever the permissions are sorted out.

Looks like Nick already added labels. I opened https://github.com/ClangBuiltLinux/continuous-integration2/issues/599 for adding LoongArch to our continuous integration. I will close this up since all action items should have their own issue now.

**Closed as completed by nathanchance** 2023-07-10 16:51 UTC
Labels: good first issue, [ARCH] loongarch
