### ISSUE TITLE
Building big endian fails

### ISSUE THREAD

**Issue by agners** [ClangBuiltLinux/linux#57] opened 2018-09-13 06:53 UTC
Compiling using CPU_BIG_ENDIAN=y fails with:

    arm-linux-gnueabihf-ld: init/.tmp_main.o: compiled for a little endian system and target is big endian                                                                                                             
    arm-linux-gnueabihf-ld: failed to merge target specific data of file init/.tmp_main.o

**Comment by nickdesaulniers** [comment] 2018-09-13 18:00
I suspect this is a duplicate of #36 and specific to arm regardless of word size.

**Comment by agners** [comment] 2018-09-13 20:14
Not really duplicate, but very much related. After all, arm/arm64 have separate Kconfig/Makefiles, and `CONFIG_CPU_BIG_ENDIAN` handling looks slight different. I guess in the end we probably have to have a separate patch anyway for the two arches.

**Comment by nickdesaulniers** [comment] 2018-09-13 20:37
`init/.tmp_main.o` seems to be `init/main.c`.  `scripts/Makefile.build` seems to create thes `.tmp_<file>.o` files.  I wonder if the `CONFIG_CPU_BIG_ENDIAN` handling in `arch/arm[64]/Makefile` is happening after building `init/main.o`?  I know the sub arch makefiles have been getting shuffled around in the top level `Makefile` recently.

**Comment by nickdesaulniers** [comment] 2018-09-13 20:42
I'm quite certain that `-mbig-endian` is not being passed along correctly.

```sh
$ clang -target arm-linux-gnueabifh hello.c -c
$ llvm-objdump -D hello.o | grep ELF
hello.o:	file format ELF32-arm-little

$ clang -target arm-linux-gnueabifh hello.c -c -mbig-endian
$ llvm-objdump -D hello.o | grep ELF
```

What is a `KBUILD_CPPFLAGS`? CPP as in C preprocessor? I would think it should be `KBUILD_CFLAGS` but maybe they're the same and it was my earlier hypothesis about sub arch Makefile include order.

**Comment by nathanchance** [comment] 2018-09-14 05:32
`init/main.o` compiles fine with `allyesconfig` on both arm and arm64:
* `make ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- allyesconfig init/main.o`
* `make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- allyesconfig init/main.o`

Compiling with `V=1` shows that `-mbig-endian` is getting passed along for both GCC and Clang:

```bash
arm-linux-gnueabi-gcc -Wp,-MD,init/.main.o.d  -nostdinc -isystem /home/nathan/toolchains/btg-gcc-8.2.1-arm/bin/../lib/gcc/arm-linux-gnueabi/8.2.1/include -I./arch/arm/include -I./arch/arm/include/generated  -I./include -I./arch/arm/include/uapi -I./arch/arm/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -mbig-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -DCC_HAVE_ASM_GOTO -fno-dwarf2-cfi-asm -fno-omit-frame-pointer -fno-ipa-sra -mabi=aapcs-linux -mfpu=vfp -funwind-tables -marm -Wa,-mno-warn-deprecated -D__LINUX_ARM_ARCH__=6 -march=armv6k -mtune=arm1136j-s -msoft-float -Uarm -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-int-in-bool-context -O2 --param=allow-store-data-races=0 -fplugin=./scripts/gcc-plugins/latent_entropy_plugin.so -fplugin=./scripts/gcc-plugins/structleak_plugin.so -fplugin=./scripts/gcc-plugins/randomize_layout_plugin.so -DLATENT_ENTROPY_PLUGIN -DSTRUCTLEAK_PLUGIN -DRANDSTRUCT_PLUGIN -fno-reorder-blocks -fno-ipa-cp-clone -fno-partial-inlining -Wframe-larger-than=2048 -fstack-protector-strong -Wno-unused-but-set-variable -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -fno-inline-functions-called-once -Wdeclaration-after-statement -Wno-pointer-sign -Wno-stringop-truncation -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -fmacro-prefix-map=./= -Wno-packed-not-aligned -fno-function-sections -fno-data-sections    -fsanitize-coverage=trace-pc -fsanitize-coverage=trace-cmp    -DKBUILD_BASENAME='"main"' -DKBUILD_MODNAME='"main"' -c -o init/.tmp_main.o init/main.c
```

```bash
clang -Wp,-MD,init/.main.o.d  -nostdinc -isystem /home/nathan/toolchains/flash-clang-8.x/lib/clang/8.0.341764/include -I./arch/arm/include -I./arch/arm/include/generated  -I./include -I./arch/arm/include/uapi -I./arch/arm/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -mbig-endian -Qunused-arguments -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 --target=arm-linux-gnueabi --gcc-toolchain=/home/nathan/toolchains/btg-gcc-8.2.1-arm -no-integrated-as -fno-PIE -fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mabi=aapcs-linux -mfpu=vfp -funwind-tables -marm -Wa,-mno-warn-deprecated -D__LINUX_ARM_ARCH__=6 -march=armv5t -Wa,-march=armv6k -mtune=arm1136j-s -msoft-float -Uarm -fno-delete-null-pointer-checks -O2 -Wframe-larger-than=1024 -fstack-protector-strong -Wno-format-invalid-specifier -Wno-gnu -Wno-address-of-packed-member -Wno-tautological-compare -mno-global-merge -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -pg -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-merge-all-constants -fno-stack-check -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Wno-initializer-overrides -Wno-unused-value -Wno-format -Wno-sign-compare -Wno-format-zero-length -Wno-uninitialized -fno-function-sections -fno-data-sections    -fsanitize-coverage=trace-pc -fsanitize-coverage=trace-cmp    -DKBUILD_BASENAME='"main"' -DKBUILD_MODNAME='"main"' -c -o init/.tmp_main.o init/main.c
```

```bash
$ arm-linux-gnueabi-objdump -D init/main.o | rg arm
init/main.o:     file format elf32-bigarm
```

**Comment by agners** [comment] 2018-09-18 03:46
I don't quite get it, so what you are saying it works for you without changes to Linux (e.g. vanilla v4.19-rc4?). At least `ARCH=arm` with allyesconfig `-CONFIG_FTRACE` and `-CONFIG_ARCH_MULTI_V6` fails for me with:

      CC      init/main.o
    arm-linux-gnueabihf-ld: init/.tmp_main.o: compiled for a little endian system and target is big endian
    arm-linux-gnueabihf-ld: failed to merge target specific data of file init/.tmp_main.o
    make[1]: *** [scripts/Makefile.build:306: init/main.o] Error 1

    $ file init/.tmp_main.o
    init/.tmp_main.o: ELF 32-bit LSB relocatable, ARM, EABI5 version 1 (SYSV), not stripped

**Comment by nickdesaulniers** [comment] 2018-09-24 01:32
What did you set `CROSS_COMPILE` to? Can you try `CROSS_COMPILE=aarch64_be-linux-gnu-`?
https://github.com/ClangBuiltLinux/linux/issues/36#issuecomment-423862623

**Comment by nickdesaulniers** [comment] 2018-10-10 18:18
https://llvm.org/pr38770
https://reviews.llvm.org/D52784

**Comment by nickdesaulniers** [comment] 2018-10-16 22:54
https://reviews.llvm.org/rC344597

**Comment by nickdesaulniers** [comment] 2018-10-16 22:55
Closing this as fixed. @agners please confirm and reopen if this is still an issue for armv7.

**Closed** 2018-10-16 22:57 UTC
Labels: [ARCH] arm32, [BUG] llvm, [FIXED][CLANG] 8, low priority
