### ISSUE TITLE
LLVM build of RISCV kernel fails with `relocation R_RISCV_PCREL_HI20 out of range`

### ISSUE THREAD

**Issue by compnerd** [ClangBuiltLinux/linux#1409] opened 2021-06-24 22:32 UTC
See https://github.com/ClangBuiltLinux/continuous-integration2/runs/2900446779?check_suite_focus=true for the CI run.  I've also found this issue in a local build.

**Comment by compnerd** [comment] 2021-06-24 22:33
CC: @nathanchance

**Comment by compnerd** [comment] 2021-06-24 22:34
It appears to be due to `CONFIG_MAXPHYSMEM_128GB=y`.  Switching to `CONFIG_MAXPHYSMEM_2GB=y` avoids the issue.  This obviously makes sense since the HI/LO relocation is range limited, and enabling a large address space means that it is possible to overflow that relocation.  This would require using linker relaxation to rewrite the site to a different form allowing the full addressability, but unfortunately, lld does not support linker relaxation at the moment.

**Comment by nathanchance** [comment] 2021-06-24 23:51
It seems like this was tangentially fixed by https://git.kernel.org/linus/2bfc6cd81bd17e4306e24ee47b9554c967bcb499, according to my reverse bisect. v5.13-rc1 with https://git.kernel.org/linus/ec3a5cb61146c91f0f7dcec8b7e7157a4879a9ee is fine, v5.12 with the same patch is not.

**Comment by compnerd** [comment] 2021-06-30 23:09
It's actually the `CMODEL_MEDANY=y` which generates a PC-relative addressing for the VDSO symbol (`__rt_sigaction`), which is expected to be relaxed by the linker.  Discussing with @MaskRay about how to address the linker relaxation, he suggested that we consider rewriting the `VDSO_SYMBOL` macro.  Digging through GCC, I found that there is the internal `S` constraint (https://github.com/riscv/riscv-gcc/blob/riscv-gcc-10.2.0/gcc/config/riscv/constraints.md#L69-L72).  @MaskRay has filed a request to make it public and to document it: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=101275.

```diff
diff --git a/arch/riscv/include/asm/vdso.h b/arch/riscv/include/asm/vdso.h
index 8454f746bbfd..9c19bccf9441 100644
--- a/arch/riscv/include/asm/vdso.h
+++ b/arch/riscv/include/asm/vdso.h
@@ -26,7 +26,11 @@ struct vdso_data {
 #define VDSO_SYMBOL(base, name)                                                        \
 ({                                                                             \
        extern const char __vdso_##name[];                                      \
-       (void __user *)((unsigned long)(base) + __vdso_##name);                 \
+       void __user *addr;                                                      \
+       __asm__ __volatile__("lui %0, %%hi(%1)\n\t"                             \
+                               "addi %0, %0, %%lo(%1)\n\t"                     \
+                               : "=r"(addr) : "S"(&__vdso_##name));            \
+       addr;                                                                   \
 })

 asmlinkage long sys_riscv_flush_icache(uintptr_t, uintptr_t, uintptr_t);
```
Seems to work for generating the right thing with gcc, I can create a patch for clang/IAS if GCC decides to make the `S` constraint public & documented.  Otherwise, I think that we should implement the linker relaxation.

**Comment by MaskRay** [comment] 2021-06-30 23:11
@jrtc27 @kito-cheng

(I am trying to emulate https://reviews.llvm.org/D46745 for llvm-project's RISCV target.)

**Comment by jrtc27** [comment] 2021-06-30 23:13
Given it's documented as a "call address" this seems wrong, unless GCC's self-documentation is inaccurate.

**Comment by compnerd** [comment] 2021-06-30 23:15
@MaskRay - I do have a local patch for that already, the question is whether this correct or not.

**Comment by jrtc27** [comment] 2021-06-30 23:18
I've also seen cases like this before where you have symbols that are known to not be in range, either because they're absolute symbols like this or because they're things like a foo_size symbol generated in a linker script. I think the real fix is to have a symbol attribute that causes the compiler to use a non-PC-relative addressing mode. Itanium has `__attribute__((model(small)))` (to force GP-relative (`@gprel`) rather than indirect (`@ltoff`, i.e. via the GOT)), I think we just want `__attribute__((model(medlow)))` etc to be supported for RISC-V. This nicely mirrors the `tls_model` attribute. Forcing people to write inline assembly for something like that is just unnecessarily annoying.

**Comment by MaskRay** [comment] 2021-07-01 00:08
`__attribute__((model(medlow)))` is not sufficient, if he code is ever compiled with `-fpie/-fpic` (grep fpic/fPIC in the kernel, it is not impossible elsewhere) for riscv.

The code is making assumption that link-time address = runtime address. This works with absolute relocations and GOT-generating relocations but not with PC-relative relocations. Making the intention explicit in inline asm is the right approach, or via some variable attribute. I don't want to go with a variable attribute because I am not sure how much usage it will have. I don't want a function/variable attribute which will not get many uses. Regarding `__attribute__((model(...)))`, it will definitely have some implementation complexity in llvm-project (the regular inlining consideration and a bunch of `TargetMachine::getCodeModel` call sites need to change). Well, it is not insurmountable but I do not know the additional complexity justifies.

I pretty strongly object to implement an ld.lld instruction rewriting for correctness. It feels to me "linker instruction rewriting as a workaround for the kernel source code issue". (If we implement linker relaxation, the discussion will be different. If you can demonstrate non-negligible performance, the discussion can be different) If my memory serves me well, x86 kernel has encountered problems due to instructions being (unexpectedly) rewritten to absolute address form, the converse of the riscv problem. Moreover, does instruction rewriting happen in `--no-relax` mode? I think it can be argued that it is intuitive to do so.

Another less fragile approach is pointer difference (`&a - &base`) in code. It assumes that the accesses to the two symbols will use the same access model but generally this property holds. I haven't built the code myself so I am guessing, but you may pick `__ehdr_start` as the image base symbol.

**Comment by compnerd** [comment] 2021-07-01 16:18
I do like the idea of using the symbolic difference.  However, experimentation shows that it doesn't actually work:
Changing `VDSO_SYMBOL` to:
```c
(void __user *)((uintptr_t)(base) + ((uintptr_t)&__vdso_##name - (uintptr_t)&_start));
```
Still gives: `ld.lld: error: signal.c:(function do_notify_resume: .text+0x492): relocation R_RISCV_PCREL_HI20 out of range: 33553919 is not in [-524288, 524287]; references __vdso_rt_sigreturn`

Looking at signal.o:
```
000000000000048a <.LBB1_53>:
 48a:   00000597                auipc   a1,0x0
                        48a: R_RISCV_PCREL_HI20 _start
 48e:   00058593                mv      a1,a1
                        48e: R_RISCV_PCREL_LO12_I       .LBB1_53

0000000000000492 <.LBB1_54>:
 492:   00000617                auipc   a2,0x0
                        492: R_RISCV_PCREL_HI20 __vdso_rt_sigreturn
 496:   00060613                mv      a2,a2
                        496: R_RISCV_PCREL_LO12_I       .LBB1_54
 49a:   40b605b3                sub     a1,a2,a1
```

My understanding is that this is because `__vdso_rt_sigreturn` is meant to be a weak undefined symbol.  The kernel is expecting that the VDSO is mapped in at a specific location in its address space, and that the linker actually relaxes the `auipc;mv` with `lui;addi` as it is known that the value is known to be 0 (as it is a weak undefined symbol).

**Comment by jrtc27** [comment] 2021-07-01 16:25
Weak undef symbols for medany code is a known issue with the current spec; see https://github.com/riscv/riscv-elf-psabi-doc/issues/126. I would like to make those be indirected so it works reliably, as is done on AArch64, but there was previously resistance to that...

**Comment by compnerd** [comment] 2021-07-01 16:29
Ah, thanks @jrtc27, I need to read through that thread.  But, this is rather interesting.  It seems that this happens to work just because the kernel is built non-PIE and thus can take advantage of a linker relaxation in the binutils linker.  I think that the proper thing would be to resolve the PS ABI issue (not that I'm aware of what the issue is yet), but in the mean time, it really does seem that the linker relaxation for this is likely the right thing.

**Comment by compnerd** [comment] 2021-07-01 17:48
Turns out that I was wrong (the symbol is generated via scripts and `git grep` failed me as a result).  The value of `__vdso_rt_sigaction` is a constant value that is computed and known to the linker at the link time.  This is a case of the value being close to zero, which binutils will treat as being relative to `zero`, which lld does not.  If the psABI states that an address close to zero is valid in medany, then this is definitely something that lld should respect, otherwise, an argument could be made that the Linux kernel should do something else.

**Comment by nickdesaulniers** [comment] 2021-07-01 20:33
https://patchwork.kernel.org/project/linux-riscv/patch/20210701200547.355742-1-abdulras@google.com/

**Comment by jrtc27** [comment] 2021-07-01 20:41
As discussed with @MaskRay on IRC, the RISC-V kernel port should just copy what arm64 does and generate a bunch of `#define`s with the offsets; it's both more efficient and more reliable. The above patch is just a bit of a kludge that makes it even less efficient, albeit as reliable as the arm64 approach.

**Comment by compnerd** [comment] 2021-07-01 21:06
@jrtc27 I agree with you that the change isnt' the greatest.  However, as you said, its as reliable as the arm64 approach.  I'd like to get the build repaired and then work through the changes to clean this up using the header as that is cleaner.

**Comment by compnerd** [comment] 2021-07-07 18:54
https://patchwork.kernel.org/project/linux-riscv/patch/20210707185105.1180526-1-abdulras@google.com/

This new version actually generates an offsets header much like ARM64.

**Comment by nickdesaulniers** [comment] 2021-07-08 01:07
I can repro this on stable linux-5.10.y.  It looks like this was masked by a commit that came in between 5.12 and 5.13-rc1. (ec3a5cb61146c91f0f7dcec8b7e7157a4879a9ee needs to be cherry-picked #1020 ).  Looks like 2bfc6cd81bd17e4306e24ee47b9554c967bcb499 is the culprit. No comment on it's viability for inclusion into stable linux-5.10.y. Perhaps a revert of 2bfc6cd81bd17e4306e24ee47b9554c967bcb499 on mailine/linux-next can more reliably reproduce the originally reported error.

**Comment by nathanchance** [comment] 2021-07-28 00:41
With @compnerd 's [patch](https://lore.kernel.org/r/20210707185105.1180526-1-abdulras@google.com/) fixed up according to my comments, I still see the following errors on 5.10.53:

```
$ make -skj"$(nproc)" ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- LLVM=1 LLVM_IAS=1 O=build/riscv distclean defconfig all
ld.lld: error: kallsyms.c:(function kallsyms_lookup_name: .text+0x2A): relocation R_RISCV_PCREL_HI20 out of range: 33553783 is not in [-524288, 524287]; references kallsyms_num_syms
>>> defined in kernel/built-in.a(kallsyms.o)

ld.lld: error: kallsyms.c:(function kallsyms_lookup_name: .text+0x44): relocation R_RISCV_PCREL_HI20 out of range: 33553783 is not in [-524288, 524287]; references kallsyms_names
>>> defined in kernel/built-in.a(kallsyms.o)

ld.lld: error: kallsyms.c:(function kallsyms_lookup_name: .text+0x4C): relocation R_RISCV_PCREL_HI20 out of range: 33553783 is not in [-524288, 524287]; references kallsyms_token_index
>>> defined in kernel/built-in.a(kallsyms.o)

ld.lld: error: kallsyms.c:(function kallsyms_lookup_name: .text+0x54): relocation R_RISCV_PCREL_HI20 out of range: 33553783 is not in [-524288, 524287]; references kallsyms_token_table
>>> defined in kernel/built-in.a(kallsyms.o)

ld.lld: error: kallsyms.c:(function kallsyms_lookup_name: .text+0xF2): relocation R_RISCV_PCREL_HI20 out of range: 33553783 is not in [-524288, 524287]; references kallsyms_relative_base
>>> defined in kernel/built-in.a(kallsyms.o)

ld.lld: error: btf.c:(function btf_parse_vmlinux: .text+0x8E6): relocation R_RISCV_PCREL_HI20 out of range: 33553722 is not in [-524288, 524287]; references __start_BTF
>>> defined in kernel/built-in.a(bpf/btf.o)

ld.lld: error: kallsyms.c:(function kallsyms_lookup_name: .text+0x102): relocation R_RISCV_PCREL_HI20 out of range: 33553783 is not in [-524288, 524287]; references kallsyms_offsets
>>> defined in kernel/built-in.a(kallsyms.o)

ld.lld: error: btf.c:(function btf_parse_vmlinux: .text+0x8F2): relocation R_RISCV_PCREL_HI20 out of range: 33553722 is not in [-524288, 524287]; references __stop_BTF
>>> defined in kernel/built-in.a(bpf/btf.o)

ld.lld: error: kallsyms.c:(function kallsyms_on_each_symbol: .text+0x170): relocation R_RISCV_PCREL_HI20 out of range: 33553783 is not in [-524288, 524287]; references kallsyms_num_syms
>>> defined in kernel/built-in.a(kallsyms.o)

ld.lld: error: kallsyms.c:(function kallsyms_on_each_symbol: .text+0x190): relocation R_RISCV_PCREL_HI20 out of range: 33553783 is not in [-524288, 524287]; references kallsyms_relative_base
>>> defined in kernel/built-in.a(kallsyms.o)
...
```

**Comment by compnerd** [comment] 2021-07-28 16:01
@nathanchance am I mistaken or are the symbols actually different?  That is, the source fo these out-of-range relocations is different than the VDSO issue.  Seems like there is another source of these to chase down.

**Comment by jrtc27** [comment] 2021-07-28 16:05
These would all be fixed by a compiler that implements https://github.com/riscv/riscv-elf-psabi-doc/pull/201; all those symbols are using `__weak` presumably to avoid PC-relative addressing due to things like this also being a concern on other architectures like amd64 and aarch64.

**Comment by MaskRay** [comment] 2021-07-28 17:17
I wonder whether clang should diverge from GCC for <https://github.com/riscv/riscv-elf-psabi-doc/pull/201>.
An undefined-behavior style (which users can't even notice) thing somehow gets some support from GCC+binutils.

**Comment by jrtc27** [comment] 2021-07-28 17:19
I'm of the view LLVM should just go ahead an implement that, yes. Ideally we'd cherry-pick it to the new 13.x branch so FreeBSD can stop using -fPIE for its kernel on RISC-V. I have zero concerns about increasing binary size for newlib binaries by 10 or 12 bytes...

**Comment by jrtc27** [comment] 2021-08-04 02:34
https://reviews.llvm.org/D107280

**Comment by nathanchance** [comment] 2021-08-04 18:00
I can confirm that D107280 and its prerequisites with https://lore.kernel.org/r/20210802210016.642262-1-abdulras@google.com/ on top of 5.10.55 and v5.14-rc4 has no build errors and boots fine in QEMU.

**Comment by nickdesaulniers** [comment] 2021-08-05 18:32
v3 of kernel patch: https://lore.kernel.org/lkml/20210804173214.1027994-1-abdulras@google.com/

**Comment by nickdesaulniers** [comment] 2021-08-25 20:51
accepted: https://git.kernel.org/pub/scm/linux/kernel/git/riscv/linux.git/commit/?h=for-next&id=fde9c59aebafb91caeed816cc510b56f14aa63ae

**Comment by nickdesaulniers** [comment] 2021-09-07 22:40
fde9c59aebafb91caeed816cc510b56f14aa63ae

**Comment by nickdesaulniers** [comment] 2021-09-07 22:41
We might need to reopen this for a 5.10 backport.

**Closed as completed by nickdesaulniers** 2021-09-07 22:40 UTC
Labels: [ARCH] risc-v, [BUG] linux-stable, [FIXED][LINUX] 5.15
