### ISSUE TITLE
unreachable instruction in arch/x86/events/intel/core.o

### ISSUE THREAD

**Issue by ms178** [ClangBuiltLinux/linux#549] opened 2019-06-20 11:07 UTC
Makefile and config are the same as uploaded here: https://github.com/ClangBuiltLinux/linux/issues/548

With a vanilla clang version 9.0.0 (363704) and Kernel 5.2-rc5 (Suse), I get the following objtool error: 
arch/x86/events/intel/core.o: warning: objtool: intel_pmu_nhm_workaround()+0xb1: unreachable instruction

**Comment by nickdesaulniers** [comment] 2019-07-02 21:20
The fix for #551 fixes this for me, so closing this as a dupe of that.

**Closed by nickdesaulniers** 2019-07-02 21:20 UTC
Labels: [ARCH] x86_64, objtool
